import {normalizePath} from '../filesystem/paths.ts';
export type ServerLanguage='python'|'rust';
export interface LanguageEvent{sessionId:string;workspaceId:string;type:'diagnostics'|'stopped';params?:{uri:string;version?:number;diagnostics:unknown[]}}
export interface LanguageBridge{invoke<T>(command:string,args:Record<string,unknown>):Promise<T>;listen(listener:(event:LanguageEvent)=>void):Promise<()=>void>}
export interface LanguageSource{path:string;content:string;savedContent?:string}
export interface LanguageState{status:'idle'|'starting'|'ready'|'stopping'|'failed';language:ServerLanguage|null;error:string;limited:boolean}
export interface TextRange{start:{line:number;character:number};end:{line:number;character:number}}
export interface RenameEdit{path:string;range:TextRange;newText:string;expected:string}
export function languagePath(path:string,language:ServerLanguage){const normalized=normalizePath(path);if(normalized!==path||path.split('/').some(part=>/^\.env(?:\.|$)/i.test(part)||/^(?:credentials|id_rsa|id_ed25519)(?:\.|$)/i.test(part)||['.git','node_modules','target'].includes(part))||!(language==='rust'?/\.rs$/i:/\.pyi?$/i).test(path))throw Error('Language path escapes this Project.');return path;}
export function serverUri(root:string,path:string,language:ServerLanguage){languagePath(path,language);const base=root.replace(/\/$/,'')+'/';return new URL(path.split('/').map(encodeURIComponent).join('/'),base).href;}
export function serverPath(root:string,value:string,language:ServerLanguage){const base=new URL(root.replace(/\/$/,'')+'/'),url=new URL(value);if(url.protocol!=='file:'||url.host!==base.host||url.search||url.hash||!(/^\/[a-z]:\//i.test(base.pathname)?url.pathname.toLowerCase().startsWith(base.pathname.toLowerCase()):url.pathname.startsWith(base.pathname)))throw Error('Language path escapes this Project.');return languagePath(decodeURIComponent(url.pathname.slice(base.pathname.length)),language);}
export function languageError(value:unknown){if(value instanceof Error)return value;const code=value&&typeof value==='object'&&'code'in value?String(value.code):'';const messages:Record<string,string>={'language-content-modified':'Language index changed. Retry this action.','language-tool':'Choose a trusted language server with an absolute path.','language-timeout':'Language server timed out. Stop and restart it.','language-response':'Language server could not complete this request.','language-limit':'Language server request limit reached.','path':'Language path escapes this Project.','access':'Connect a workspace folder first.'};return Error(messages[code]??'Language server could not complete this request.');}
function range(value:unknown):TextRange{const v=value as TextRange;for(const p of [v?.start,v?.end])if(!p||!Number.isSafeInteger(p.line)||p.line<0||p.line>1000000||!Number.isSafeInteger(p.character)||p.character<0||p.character>2000000)throw Error('Invalid language range.');if(v.start.line>v.end.line||v.start.line===v.end.line&&v.start.character>v.end.character)throw Error('Invalid language range.');return v;}
export class LanguageService{
 private bridge:LanguageBridge;private workspace:string;private listeners=new Set<()=>void>();private state:LanguageState={status:'idle',language:null,error:'',limited:false};private session='';private root='';private off?:()=>void;private epoch=0;private serial:Promise<unknown>=Promise.resolve();private sources=new Map<string,{content:string;savedContent:string;version:number}>();private diagnostics=new Map<string,{version?:number;diagnostics:unknown[]}>();
 constructor(bridge:LanguageBridge,workspace:string){this.bridge=bridge;this.workspace=workspace;}
 snapshot=()=>this.state;subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};private update(value:Partial<LanguageState>){this.state={...this.state,...value};this.listeners.forEach(fn=>fn());}diagnosticRows=()=>new Map(this.diagnostics);
 async start(language:ServerLanguage,toolPath:string,nodePath:string,initial:readonly LanguageSource[],limited=false){if(this.state.status!=='idle'&&this.state.status!=='failed')throw Error('Stop the current language server first.');const epoch=++this.epoch,session=crypto.randomUUID();this.session=session;this.sources.clear();this.diagnostics.clear();this.update({status:'starting',language,error:'',limited});try{const off=await this.bridge.listen(event=>{if(event.sessionId!==this.session||event.workspaceId!==this.workspace||this.epoch!==epoch)return;if(event.type==='stopped'){this.diagnostics.clear();void this.bridge.invoke('language_stop',{sessionId:session,workspaceId:this.workspace}).catch(()=>{});this.update({status:'failed',error:'Language server stopped.'});return;}if(!event.params||!this.root)return;try{const path=serverPath(this.root,event.params.uri,language),source=this.sources.get(path);if(source&&event.params.version!==undefined&&event.params.version!==source.version)return;const diagnostics=event.params.diagnostics;if(!Array.isArray(diagnostics)||diagnostics.length>1000)return;this.diagnostics.set(path,{version:event.params.version,diagnostics});this.update({});}catch{}});if(epoch!==this.epoch){off();return;}this.off=off;const result=await this.bridge.invoke<{rootUri:string}>('language_start',{request:{sessionId:session,workspaceId:this.workspace,language,toolPath,nodePath:language==='python'?nodePath:null}});if(epoch!==this.epoch)return;if(new URL(result.rootUri).protocol!=='file:')throw Error('Invalid language root.');this.root=result.rootUri;this.update({status:'ready'});await this.sync(initial);}catch(error){if(epoch===this.epoch){this.update({status:'failed',error:languageError(error).message});this.off?.();this.off=undefined;await this.bridge.invoke('language_stop',{sessionId:session,workspaceId:this.workspace}).catch(()=>{});throw languageError(error);}}}
 private call(method:string,params:unknown){const session=this.session,epoch=this.epoch;if(this.state.status!=='ready')return Promise.reject(Error('Language server is not ready.'));const result=this.serial.then(async()=>{if(epoch!==this.epoch||this.state.status!=='ready')throw Error('Language session changed.');return this.bridge.invoke<unknown>('language_call',{request:{sessionId:session,workspaceId:this.workspace,method,params}}).catch(error=>{throw languageError(error);});});this.serial=result.catch(()=>{});return result;}
 async sync(documents:readonly LanguageSource[]){const language=this.state.language;if(!language||this.state.status!=='ready')return;for(const doc of documents){try{languagePath(doc.path,language);}catch{continue;}if(doc.content.length>2*1024*1024||doc.content.includes('\0'))continue;const existing=this.sources.get(doc.path);if(!existing){if(this.sources.size>=256){this.update({limited:true});continue;}const source={content:doc.content,savedContent:doc.savedContent??doc.content,version:1};this.sources.set(doc.path,source);await this.call('textDocument/didOpen',{textDocument:{uri:serverUri(this.root,doc.path,language),languageId:language,version:1,text:doc.content}});}else if(existing.content!==doc.content){existing.content=doc.content;existing.savedContent=doc.savedContent??existing.savedContent;existing.version++;this.diagnostics.delete(doc.path);await this.call('textDocument/didChange',{textDocument:{uri:serverUri(this.root,doc.path,language),version:existing.version},contentChanges:[{text:doc.content}]});}else if(doc.savedContent!==undefined)existing.savedContent=doc.savedContent;}}
 async syncEditors(documents:readonly LanguageSource[]){const paths=new Set(documents.map(doc=>doc.path));const restored=[...this.sources].filter(([path,source])=>!paths.has(path)&&source.content!==source.savedContent).map(([path,source])=>({path,content:source.savedContent,savedContent:source.savedContent}));await this.sync([...restored,...documents]);}
 async query(method:'definition'|'references'|'hover'|'completion',path:string,position:{line:number;character:number}){const language=this.state.language!,epoch=this.epoch,source=this.sources.get(path),version=source?.version;if(!source)throw Error('Language document is not indexed.');if(!Number.isSafeInteger(position.line)||position.line<0||!Number.isSafeInteger(position.character)||position.character<0)throw Error('Invalid language position.');const result=await this.call('textDocument/'+method,{textDocument:{uri:serverUri(this.root,path,language)},position,...(method==='references'?{context:{includeDeclaration:true}}:{})});if(epoch!==this.epoch||this.state.status!=='ready')throw Error('Language session changed.');if(this.sources.get(path)?.version!==version)throw Error('Language index changed. Retry this action.');return result;}
 locations(value:unknown){const language=this.state.language!;const list=value===null?[]:Array.isArray(value)?value:[value];if(list.length>1000)throw Error('Language result limit reached.');return list.flatMap(item=>{const row=item as {uri?:string;range?:TextRange;targetUri?:string;targetSelectionRange?:TextRange};try{const path=serverPath(this.root,row.uri??row.targetUri!,language);return[{path,range:range(row.range??row.targetSelectionRange)}];}catch{return[];}});}
 async rename(path:string,position:{line:number;character:number},name:string):Promise<RenameEdit[]>{if(!/^[\p{L}_][\p{L}\p{N}_]{0,99}$/u.test(name))throw Error('Invalid symbol name.');const language=this.state.language!,epoch=this.epoch,baseline=new Map([...this.sources].map(([path,source])=>[path,{...source}]));const result=await this.call('textDocument/rename',{textDocument:{uri:serverUri(this.root,path,language)},position,newName:name}) as {changes?:Record<string,unknown[]>;documentChanges?:{textDocument?:{uri:string;version?:number|null};edits?:unknown[];kind?:string}[]}|null;if(!result)return[];if(epoch!==this.epoch)throw Error('Language session changed.');const edits:RenameEdit[]=[];const add=(uri:string,rows:unknown[],version?:number|null)=>{const path=serverPath(this.root,uri,language),source=baseline.get(path);if(!source||this.sources.get(path)?.content!==source.content||version!==undefined&&version!==null&&source.version!==version)throw Error('Language rename base changed.');if(!Array.isArray(rows)||rows.length>1000)throw Error('Language result limit reached.');for(const value of rows){const edit=value as {range:unknown;newText:string};if(typeof edit.newText!=='string'||edit.newText.length>10000)throw Error('Invalid language edit.');edits.push({path,range:range(edit.range),newText:edit.newText,expected:source.content});}};if(result.changes)for(const [uri,rows]of Object.entries(result.changes))add(uri,rows);if(result.documentChanges)for(const change of result.documentChanges){if(change.kind||!change.textDocument||!change.edits)throw Error('Language file operations are not allowed.');add(change.textDocument.uri,change.edits,change.textDocument.version);}if(edits.length>1000||new Set(edits.map(edit=>edit.path)).size>64)throw Error('Language result limit reached.');return edits;}
 expectedSaved(path:string){return this.sources.get(path)?.savedContent;}
 async stop(){const session=this.session;++this.epoch;this.session='';this.off?.();this.off=undefined;this.update({status:'stopping'});this.sources.clear();this.diagnostics.clear();try{if(session)await this.bridge.invoke('language_stop',{sessionId:session,workspaceId:this.workspace});}finally{this.serial=Promise.resolve();this.update({status:'idle',language:null,error:'',limited:false});}}
}
