import {languageCompletions} from './language-completion';
import type * as Monaco from 'monaco-editor';import type {LanguageService} from './language-service';import type {Documents} from './documents';import type {WorkspaceFileService} from '../filesystem/file-service';import {uriWorkspacePath,workspaceUri} from './language-workspace';
export function connectLanguageProviders(monaco:typeof Monaco,service:LanguageService,workspace:string,documents:Documents,files:WorkspaceFileService){const disposables:Monaco.IDisposable[]=[];let disposed=false;const position=(value:Monaco.Position)=>({line:value.lineNumber-1,character:value.column-1});const range=(value:{start:{line:number;character:number};end:{line:number;character:number}})=>new monaco.Range(value.start.line+1,value.start.character+1,value.end.line+1,value.end.character+1);const path=(model:Monaco.editor.ITextModel)=>uriWorkspacePath(model.uri,workspace);const allowed=(model:Monaco.editor.ITextModel)=>!disposed&&service.snapshot().status==='ready'&&model.getLanguageId()===service.snapshot().language;const locations=async(model:Monaco.editor.ITextModel,p:Monaco.Position,kind:'definition'|'references',token:Monaco.CancellationToken)=>{if(!allowed(model)||!path(model))return[];await service.syncEditors(documents.snapshot().openEditors);const result=await service.query(kind,path(model)!,position(p));if(disposed||token.isCancellationRequested)return[];return service.locations(result).map(row=>({uri:workspaceUri(monaco,workspace,row.path),range:range(row.range)}));};
for(const language of ['python','rust']){disposables.push(monaco.languages.registerCompletionItemProvider(language,{
 triggerCharacters:['.'],
 async provideCompletionItems(model,p,_context,token){
  if(!allowed(model)||!path(model))return {suggestions:[]};
  const version=model.getVersionId();
  await service.syncEditors(documents.snapshot().openEditors);
  const response=await service.query('completion',path(model)!,position(p));
  if(disposed||token.isCancellationRequested||model.isDisposed()||version!==model.getVersionId())return {suggestions:[]};
  const result=languageCompletions(response),word=model.getWordUntilPosition(p);
  const kinds=[monaco.languages.CompletionItemKind.Text,monaco.languages.CompletionItemKind.Method,monaco.languages.CompletionItemKind.Function,monaco.languages.CompletionItemKind.Constructor,monaco.languages.CompletionItemKind.Field,monaco.languages.CompletionItemKind.Variable,monaco.languages.CompletionItemKind.Class,monaco.languages.CompletionItemKind.Interface,monaco.languages.CompletionItemKind.Module,monaco.languages.CompletionItemKind.Property,monaco.languages.CompletionItemKind.Unit,monaco.languages.CompletionItemKind.Value,monaco.languages.CompletionItemKind.Enum,monaco.languages.CompletionItemKind.Keyword,monaco.languages.CompletionItemKind.Snippet,monaco.languages.CompletionItemKind.Color,monaco.languages.CompletionItemKind.File,monaco.languages.CompletionItemKind.Reference,monaco.languages.CompletionItemKind.Folder,monaco.languages.CompletionItemKind.EnumMember,monaco.languages.CompletionItemKind.Constant,monaco.languages.CompletionItemKind.Struct,monaco.languages.CompletionItemKind.Event,monaco.languages.CompletionItemKind.Operator,monaco.languages.CompletionItemKind.TypeParameter];
  return {incomplete:result.incomplete,suggestions:result.items.flatMap(item=>{
   const editRange=item.range?range(item.range):new monaco.Range(p.lineNumber,word.startColumn,p.lineNumber,word.endColumn);
   if(!model.validateRange(editRange).equalsRange(editRange)||!editRange.containsPosition(p))return [];
   return [{label:item.label,kind:kinds[item.kind-1],insertText:item.insertText,range:editRange,...(item.snippet?{insertTextRules:monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet}:{}),detail:item.detail,sortText:item.sortText,filterText:item.filterText,...(item.documentation?{documentation:{value:item.documentation,isTrusted:false,supportHtml:false}}:{})}];
  })};
 }
}),monaco.languages.registerDefinitionProvider(language,{provideDefinition:(model,p,token)=>locations(model,p,'definition',token)}),monaco.languages.registerReferenceProvider(language,{provideReferences:(model,p,_context,token)=>locations(model,p,'references',token)}),monaco.languages.registerRenameProvider(language,{async provideRenameEdits(model,p,newName,token){if(!allowed(model)||!path(model))return {edits:[],rejectReason:'Language server is not ready.'};await service.syncEditors(documents.snapshot().openEditors);const edits=await service.rename(path(model)!,position(p),newName);if(disposed||token.isCancellationRequested)return{edits:[]};const targets=[...new Set(edits.map(edit=>edit.path))];for(const target of targets){const doc=documents.snapshot().openEditors.find(doc=>doc.path===target),expected=edits.find(edit=>edit.path===target)!.expected;if(doc){if(doc.content!==expected)throw Error('Language rename base changed.');}else if((await files.read(target)).content!==service.expectedSaved(target))throw Error('Language rename disk state changed.');}for(const target of targets)if(!documents.snapshot().openEditors.some(doc=>doc.path===target))await documents.open(target);if(disposed||token.isCancellationRequested)return{edits:[]};for(const edit of edits){const doc=documents.snapshot().openEditors.find(doc=>doc.path===edit.path);if(!doc||doc.content!==edit.expected)throw Error('Language rename base changed.');const target=monaco.editor.getModel(workspaceUri(monaco,workspace,edit.path));if(!target||target.getValue(undefined,true)!==edit.expected)throw Error('Language rename editor changed.');}return {edits:edits.map(edit=>{const resource=workspaceUri(monaco,workspace,edit.path),target=monaco.editor.getModel(resource)!;return{resource,versionId:target.getVersionId(),textEdit:{range:range(edit.range),text:edit.newText}};})};}}),monaco.languages.registerHoverProvider(language,{async provideHover(model,p,token){if(!allowed(model)||!path(model))return null;const version=model.getVersionId();await service.syncEditors(documents.snapshot().openEditors);const value=await service.query('hover',path(model)!,position(p)) as {contents?:unknown;range?:Parameters<typeof range>[0]}|null;if(!value||disposed||token.isCancellationRequested||model.isDisposed()||version!==model.getVersionId())return null;const contents=(Array.isArray(value.contents)?value.contents:[value.contents]).flatMap(item=>typeof item==='string'?[{value:item,isTrusted:false,supportHtml:false}]:item&&typeof item==='object'&&'value'in item&&typeof item.value==='string'?[{value:item.value,isTrusted:false,supportHtml:false}]:[]);return{contents,...(value.range?{range:range(value.range)}:{})};}}));}
const update=()=>{const rows=service.diagnosticRows();for(const model of monaco.editor.getModels()){const current=path(model);if(!current)continue;const diagnostics=rows.get(current)?.diagnostics??[];const markers=diagnostics.flatMap(value=>{const row=value as {range:Parameters<typeof range>[0];message:string;severity?:number;code?:string|number};try{const r=range(row.range);if(typeof row.message!=='string'||row.message.length>16000||r.startLineNumber>model.getLineCount()||r.endLineNumber>model.getLineCount())return[];return[{...r,message:row.message,severity:row.severity===1?monaco.MarkerSeverity.Error:row.severity===2?monaco.MarkerSeverity.Warning:monaco.MarkerSeverity.Info,source:'Language server',...(typeof row.code==='string'||typeof row.code==='number'?{code:String(row.code)}:{})}];}catch{return[];}});monaco.editor.setModelMarkers(model,'studio-language',markers);}};const off=service.subscribe(update);update();return()=>{disposed=true;off();disposables.forEach(disposable=>disposable.dispose());for(const model of monaco.editor.getModels())if(path(model))monaco.editor.setModelMarkers(model,'studio-language',[]);};}
