import type {Language} from './core.ts';
const locales:Language[]=['ko','de','es','fr','it','pt','ja','zh','zh-hant'];
const rows=`Proposal|제안|Vorschlag|Propuesta|Proposition|Proposta|Proposta|提案|提案|提案
File|파일|Datei|Archivo|Fichier|File|Arquivo|ファイル|文件|檔案
AI review center|AI 검토|AI-Prüfung|Revisión IA|Revue IA|Revisione IA|Revisão IA|AIレビュー|AI审查|AI審核
Compare attempts and your edits. Writes and tests keep separate approvals.|시도와 사용자 변경을 비교합니다. 수정·테스트는 별도로 승인합니다.|Versuche und eigene Änderungen vergleichen. Schreiben und Tests benötigen eigene Freigaben.|Compare intentos y cambios. Escrituras y pruebas requieren aprobación aparte.|Comparez tentatives et modifications. Écriture et tests exigent des accords distincts.|Confronta tentativi e modifiche. Scritture e test richiedono approvazioni separate.|Compare tentativas e alterações. Escrita e testes exigem aprovações separadas.|試行と編集を比較。変更とテストは個別に承認します。|比较尝试与编辑，写入和测试分别批准。|比較嘗試與編輯，寫入與測試分別核准。
Analysis budget|분석 예산|Analysebudget|Presupuesto de análisis|Budget d’analyse|Budget analisi|Orçamento de análise|分析予算|分析预算|分析預算
Analysis timeout (ms)|분석 제한 시간(ms)|Analysezeitlimit (ms)|Tiempo límite (ms)|Délai d’analyse (ms)|Tempo limite (ms)|Tempo limite (ms)|分析時間制限(ms)|分析超时(ms)|分析逾時(ms)
Maximum provider requests|최대 Provider 요청|Maximale Provider-Anfragen|Máximo de solicitudes|Requêtes maximales|Richieste massime|Máximo de solicitações|最大リクエスト数|最大请求数|最大請求數
Maximum input tokens|최대 입력 token|Maximale Eingabetokens|Tokens de entrada máximos|Tokens entrants maximaux|Token input massimi|Tokens de entrada máximos|最大入力トークン|最大输入token|最大輸入token
Maximum output tokens|최대 출력 token|Maximale Ausgabetokens|Tokens de salida máximos|Tokens sortants maximaux|Token output massimi|Tokens de saída máximos|最大出力トークン|最大输出token|最大輸出token
Maximum fix attempts|최대 수정 시도|Maximale Fixversuche|Máximo de intentos|Tentatives maximales|Tentativi massimi|Máximo de tentativas|最大修正試行|最大修复次数|最大修復次數
Save budget|예산 저장|Budget speichern|Guardar presupuesto|Enregistrer budget|Salva budget|Salvar orçamento|予算を保存|保存预算|儲存預算
Budget saved. Each new proposal still requires approval.|예산 저장됨. 새 제안은 각각 승인이 필요합니다.|Budget gespeichert. Jeder neue Vorschlag braucht Freigabe.|Guardado. Cada propuesta nueva requiere aprobación.|Enregistré. Chaque proposition exige un accord.|Salvato. Ogni nuova proposta richiede approvazione.|Salvo. Cada nova proposta exige aprovação.|保存済み。新しい提案には承認が必要です。|已保存，每个新提案仍需批准。|已儲存，每個新提案仍需核准。
Invalid budget or analysis is active.|예산이 잘못됐거나 분석 중입니다.|Ungültiges Budget oder Analyse aktiv.|Presupuesto inválido o análisis activo.|Budget invalide ou analyse active.|Budget non valido o analisi attiva.|Orçamento inválido ou análise ativa.|予算が無効または分析中です。|预算无效或正在分析。|預算無效或正在分析。
Token limits use reported usage after each request. Missing usage and monetary cost are not estimated.|Token 한도는 요청 후 보고된 사용량을 기준으로 합니다. 누락된 사용량·요금은 추정하지 않습니다.|Tokenlimits nutzen gemeldeten Verbrauch nach jeder Anfrage. Fehlende Werte und Kosten werden nicht geschätzt.|Límites según uso informado tras cada solicitud. No se estima uso faltante ni costo.|Limites selon usage déclaré après requête. Usage absent et coût non estimés.|Limiti sull’uso riportato dopo ogni richiesta. Uso mancante e costo non stimati.|Limites pelo uso informado após cada pedido. Uso ausente e custo não estimados.|各要求後の使用量で制限。未報告の使用量と料金は推定しません。|根据每次请求后报告的用量限制，不估算缺失用量和费用。|依每次請求後回報的用量限制，不估算缺失用量與費用。
Earlier attempt|이전 시도|Früherer Versuch|Intento anterior|Tentative antérieure|Tentativo precedente|Tentativa anterior|前の試行|之前尝试|先前嘗試
Later attempt|다음 시도|Späterer Versuch|Intento posterior|Tentative suivante|Tentativo successivo|Tentativa posterior|後の試行|之后尝试|後續嘗試
Select attempt|시도 선택|Versuch wählen|Elegir intento|Choisir tentative|Scegli tentativo|Escolher tentativa|試行を選択|选择尝试|選擇嘗試
Select attempts from the same original failure.|같은 원본 실패의 시도를 선택하세요.|Versuche desselben Fehlers wählen.|Elija intentos del mismo fallo.|Choisissez le même échec initial.|Scegli tentativi dello stesso errore.|Escolha tentativas da mesma falha.|同じ元の失敗を選択してください。|选择同一初始失败的尝试。|選擇同一初始失敗的嘗試。
Compare with current editor / disk|현재 편집기·디스크와 비교|Mit Editor / Disk vergleichen|Comparar con editor / disco|Comparer avec éditeur / disque|Confronta editor / disco|Comparar editor / disco|現在の編集／ディスクと比較|比较当前编辑器／磁盘|比較目前編輯器／磁碟
Review test result|테스트 결과 검토|Testergebnis prüfen|Revisar resultado|Revoir le résultat|Esamina risultato|Revisar resultado|テスト結果を確認|审查测试结果|審核測試結果
Review Git changes|Git 변경 검토|Git-Änderungen prüfen|Revisar cambios Git|Revoir changements Git|Esamina modifiche Git|Revisar alterações Git|Git変更を確認|审查Git更改|審核Git變更
AI result → current editor / disk|AI 결과 → 현재 편집기·디스크|AI-Ergebnis → Editor / Disk|Resultado IA → editor / disco|Résultat IA → éditeur / disque|Risultato IA → editor / disco|Resultado IA → editor / disco|AI結果 → 現在の編集／ディスク|AI结果 → 当前编辑器／磁盘|AI結果 → 目前編輯器／磁碟
Earlier result → later result|이전 결과 → 다음 결과|Früheres → späteres Ergebnis|Resultado anterior → posterior|Résultat précédent → suivant|Risultato precedente → successivo|Resultado anterior → posterior|前の結果 → 後の結果|之前结果 → 之后结果|先前結果 → 後續結果
No fix attempts yet. Analyze a failed Run and review its proposal.|수정 시도가 없습니다. 실패 Run을 분석하고 제안을 검토하세요.|Noch keine Fixversuche. Fehler analysieren und Vorschlag prüfen.|Sin intentos. Analice un Run fallido y revise la propuesta.|Aucune tentative. Analysez un Run échoué et sa proposition.|Nessun tentativo. Analizza un Run fallito e la proposta.|Sem tentativas. Analise um Run com falha e a proposta.|失敗Runを分析して提案を確認してください。|尚无修复尝试，请分析失败Run并审查提案。|尚無修復嘗試，請分析失敗Run並審核提案。
Review data unavailable. Reconnect and retry.|검토 데이터를 불러오지 못했습니다. 재연결 후 다시 시도하세요.|Prüfdaten fehlen. Neu verbinden.|Datos no disponibles. Reconecte.|Données indisponibles. Reconnectez.|Dati non disponibili. Riconnetti.|Dados indisponíveis. Reconecte.|データを取得できません。再接続してください。|审查数据不可用，请重连。|審核資料無法取得，請重新連線。
Usage unavailable|사용량 미보고|Verbrauch nicht verfügbar|Uso no disponible|Usage indisponible|Uso non disponibile|Uso indisponível|使用量未報告|用量不可用|用量無法取得
Timing unavailable|시간 미기록|Zeit nicht verfügbar|Tiempo no disponible|Durée indisponible|Tempo non disponibile|Tempo indisponível|時間未記録|时间未记录|時間未記錄`;
export const aiReviewMessages:Partial<Record<Language,Record<string,string>>>=Object.fromEntries(locales.map((locale,index)=>[locale,Object.fromEntries(rows.split('\n').map(row=>{const parts=row.split('|');return[parts[0],parts[index+1]];}))]));
