import type {Language} from './core.ts';
const locales:Language[]=['ko','de','es','fr','it','pt','ja','zh','zh-hant'];
const rows=`Agent execution issues · recent 100 terminal Runs|Agent 실행 문제 · 최근 종료 Run 100건|Agent-Ausführungsprobleme · letzte 100 abgeschlossene Läufe|Problemas Agent · últimas 100 ejecuciones terminadas|Problèmes Agent · 100 dernières exécutions terminées|Problemi Agent · ultime 100 esecuzioni concluse|Problemas Agent · últimas 100 execuções concluídas|Agent実行問題・直近100完了Run|Agent执行问题·最近100个结束运行|Agent執行問題·最近100個結束執行
Compare Runs|실행 비교|Läufe vergleichen|Comparar ejecuciones|Comparer les exécutions|Confronta esecuzioni|Comparar execuções|実行を比較|比较运行|比較執行
Source identity|소스 식별 정보|Quellidentität|Identidad de fuente|Identité source|Identità sorgente|Identidade da fonte|ソース識別情報|源码身份|原始碼身分
Test definition|테스트 정의|Testdefinition|Definición de prueba|Définition du test|Definizione test|Definição do teste|テスト定義|测试定义|測試定義
Reported environment|보고된 환경|Gemeldete Umgebung|Entorno informado|Environnement déclaré|Ambiente dichiarato|Ambiente informado|報告環境|报告环境|回報環境
Comparable|비교 가능|Vergleichbar|Comparable|Comparable|Confrontabile|Comparável|比較可能|可比较|可比較
Different / unknown|다름 / 미확인|Abweichend / unbekannt|Distinto / desconocido|Différent / inconnu|Diverso / sconosciuto|Diferente / desconhecido|相違／不明|不同／未知|不同／未知
Slowdown candidate|실행 지연 후보|Verlangsamungskandidat|Posible ralentización|Ralentissement possible|Possibile rallentamento|Possível lentidão|遅延候補|变慢候选|變慢候選
Flaky candidate|불안정 테스트 후보|Instabiler Testkandidat|Posible prueba inestable|Test instable possible|Possibile test instabile|Possível teste instável|不安定テスト候補|不稳定测试候选|不穩定測試候選
Candidates require matching source, saved test definition and reported Agent environment. They are not confirmed defects.|후보 판단에는 동일 소스·저장된 테스트 정의·보고된 Agent 환경이 필요합니다. 확정된 결함은 아닙니다.|Kandidaten benötigen gleiche Quelle, Testdefinition und gemeldete Agent-Umgebung. Keine bestätigten Fehler.|Los candidatos requieren fuente, prueba guardada y entorno Agent iguales. No son defectos confirmados.|Les candidats exigent source, test enregistré et environnement Agent identiques. Défauts non confirmés.|I candidati richiedono sorgente, test salvato e ambiente Agent uguali. Difetti non confermati.|Candidatos exigem fonte, teste salvo e ambiente Agent iguais. Não são defeitos confirmados.|同じソース・保存テスト定義・報告Agent環境が必要。確定不具合ではありません。|候选需相同源码、保存的测试定义和报告的Agent环境，非确定缺陷。|候選需相同原始碼、儲存的測試定義與回報的Agent環境，非確定缺陷。
Estimate cost|비용 추정|Kosten schätzen|Estimar coste|Estimer le coût|Stima costo|Estimar custo|費用を推定|估算费用|估算費用
Model|모델|Modell|Modelo|Modèle|Modello|Modelo|モデル|模型|模型
Input USD / million tokens|입력 백만 토큰당 USD|Eingabe USD / Million Tokens|Entrada USD / millón de tokens|Entrée USD / million de jetons|Input USD / milione di token|Entrada USD / milhão de tokens|入力百万トークンあたりUSD|输入每百万token的USD|輸入每百萬token的USD
Output USD / million tokens|출력 백만 토큰당 USD|Ausgabe USD / Million Tokens|Salida USD / millón de tokens|Sortie USD / million de jetons|Output USD / milione di token|Saída USD / milhão de tokens|出力百万トークンあたりUSD|输出每百万token的USD|輸出每百萬token的USD
Maximum estimated USD|최대 추정 USD|Maximale geschätzte USD|USD estimados máximos|USD estimés maximum|USD stimati massimi|USD estimados máximos|推定USD上限|估算USD上限|估算USD上限
Cost estimate USD|추정 비용 USD|Geschätzte Kosten USD|Coste estimado USD|Coût estimé USD|Costo stimato USD|Custo estimado USD|推定費用USD|估算费用USD|估算費用USD
Estimates use configured rates after each reply. This is not a billing cap. Unknown usage or model stops cost-limited analysis.|응답 후 설정 단가로 추정합니다. 실제 청구 한도가 아닙니다. 사용량·모델 미확인 시 비용 제한 분석을 중단합니다.|Schätzung nach Antwort mit eigenen Tarifen, kein Rechnungslimit. Unbekannter Verbrauch oder Modell stoppt die Analyse.|Estimación tras respuesta con tarifas configuradas, no límite de facturación. Uso o modelo desconocido detiene el análisis.|Estimation après réponse avec tarifs configurés, sans plafond de facturation. Usage ou modèle inconnu arrête l’analyse.|Stima dopo risposta con tariffe configurate, non tetto di fatturazione. Uso o modello ignoto ferma l’analisi.|Estimativa após resposta com tarifas configuradas, não limite de cobrança. Uso ou modelo desconhecido interrompe análise.|応答後に設定単価で推定。請求上限ではありません。使用量やモデル不明で分析停止。|回复后按配置单价估算，并非账单上限。用量或模型未知时停止分析。|回覆後依設定單價估算，非帳單上限。用量或模型未知時停止分析。
Proposal|제안|Vorschlag|Propuesta|Proposition|Proposta|Proposta|提案|提案|提案
File|파일|Datei|Archivo|Fichier|File|Arquivo|ファイル|文件|檔案
AI review center|AI 검토|AI-Prüfung|Revisión IA|Revue IA|Revisione IA|Revisão IA|AIレビュー|AI审查|AI審核
Compare attempts and your edits. Writes and tests keep separate approvals.|시도와 사용자 변경을 비교합니다. 수정·테스트는 별도로 승인합니다.|Versuche und eigene Änderungen vergleichen. Schreiben und Tests benötigen eigene Freigaben.|Compare intentos y cambios. Escrituras y pruebas requieren aprobación aparte.|Comparez tentatives et modifications. Écriture et tests exigent des accords distincts.|Confronta tentativi e modifiche. Scritture e test richiedono approvazioni separate.|Compare tentativas e alterações. Escrita e testes exigem aprovações separadas.|試行と編集を比較。変更とテストは個別に承認します。|比较尝试与编辑，写入和测试分别批准。|比較嘗試與編輯，寫入與測試分別核准。
Analysis budget|분석 예산|Analysebudget|Presupuesto de análisis|Budget d’analyse|Budget analisi|Orçamento de análise|分析予算|分析预算|分析預算
Analysis timeout (ms)|분석 제한 시간(ms)|Analysezeitlimit (ms)|Tiempo límite (ms)|Délai d’analyse (ms)|Tempo limite (ms)|Tempo limite (ms)|分析時間制限(ms)|分析超时(ms)|分析逾時(ms)
Maximum provider requests|최대 Provider 요청|Maximale Provider-Anfragen|Máximo de solicitudes|Requêtes maximales|Richieste massime|Máximo de solicitações|最大リクエスト数|最大请求数|最大請求數
Maximum input tokens|최대 입력 token|Maximale Eingabetokens|Tokens de entrada máximos|Tokens entrants maximaux|Token input massimi|Tokens de entrada máximos|最大入力トークン|最大输入token|最大輸入token
Maximum output tokens|최대 출력 token|Maximale Ausgabetokens|Tokens de salida máximos|Tokens sortants maximaux|Token output massimi|Tokens de saída máximos|最大出力トークン|最大输出token|最大輸出token
Maximum fix attempts|최대 수정 시도|Maximale Fixversuche|Máximo de intentos|Tentatives maximales|Tentativi massimi|Máximo de tentativas|最大修正試行|最大修复次数|最大修復次數
Save budget|예산 저장|Budget speichern|Guardar presupuesto|Enregistrer budget|Salva budget|Salvar orçamento|予算を保存|保存预算|儲存預算
Budget saved. Each new proposal still requires approval.|예산 저장됨. 새 제안은 각각 승인이 필요합니다.|Budget gespeichert. Jeder neue Vorschlag braucht Freigabe.|Guardado. Cada propuesta nueva requiere aprobación.|Enregistré. Chaque proposition exige un accord.|Salvato. Ogni nuova proposta richiede approvazione.|Salvo. Cada nova proposta exige aprovação.|保存済み。新しい提案には承認が必要です。|已保存，每个新提案仍需批准。|已儲存，每個新提案仍需核准。
Invalid budget or analysis is active.|예산이 잘못됐거나 분석 중입니다.|Ungültiges Budget oder Analyse aktiv.|Presupuesto inválido o análisis activo.|Budget invalide ou analyse active.|Budget non valido o analisi attiva.|Orçamento inválido ou análise ativa.|予算が無効または分析中です。|预算无效或正在分析。|預算無效或正在分析。
Token limits use reported usage after each request. Missing usage and monetary cost are not estimated.|Token 한도는 요청 후 보고된 사용량을 기준으로 합니다. 누락된 사용량·요금은 추정하지 않습니다.|Tokenlimits nutzen gemeldeten Verbrauch nach jeder Anfrage. Fehlende Werte und Kosten werden nicht geschätzt.|Límites según uso informado tras cada solicitud. No se estima uso faltante ni costo.|Limites selon usage déclaré après requête. Usage absent et coût non estimés.|Limiti sull’uso riportato dopo ogni richiesta. Uso mancante e costo non stimati.|Limites pelo uso informado após cada pedido. Uso ausente e custo não estimados.|各要求後の使用量で制限。未報告の使用量と料金は推定しません。|根据每次请求后报告的用量限制，不估算缺失用量和费用。|依每次請求後回報的用量限制，不估算缺失用量與費用。
Earlier attempt|이전 시도|Früherer Versuch|Intento anterior|Tentative antérieure|Tentativo precedente|Tentativa anterior|前の試行|之前尝试|先前嘗試
Later attempt|다음 시도|Späterer Versuch|Intento posterior|Tentative suivante|Tentativo successivo|Tentativa posterior|後の試行|之后尝试|後續嘗試
Select attempt|시도 선택|Versuch wählen|Elegir intento|Choisir tentative|Scegli tentativo|Escolher tentativa|試行を選択|选择尝试|選擇嘗試
Select attempts from the same original failure.|같은 원본 실패의 시도를 선택하세요.|Versuche desselben Fehlers wählen.|Elija intentos del mismo fallo.|Choisissez le même échec initial.|Scegli tentativi dello stesso errore.|Escolha tentativas da mesma falha.|同じ元の失敗を選択してください。|选择同一初始失败的尝试。|選擇同一初始失敗的嘗試。
Compare with current editor / disk|현재 편집기·디스크와 비교|Mit Editor / Disk vergleichen|Comparar con editor / disco|Comparer avec éditeur / disque|Confronta editor / disco|Comparar editor / disco|現在の編集／ディスクと比較|比较当前编辑器／磁盘|比較目前編輯器／磁碟
Review test result|테스트 결과 검토|Testergebnis prüfen|Revisar resultado|Revoir le résultat|Esamina risultato|Revisar resultado|テスト結果を確認|审查测试结果|審核測試結果
Review Git changes|Git 변경 검토|Git-Änderungen prüfen|Revisar cambios Git|Revoir changements Git|Esamina modifiche Git|Revisar alterações Git|Git変更を確認|审查Git更改|審核Git變更
AI result → current editor / disk|AI 결과 → 현재 편집기·디스크|AI-Ergebnis → Editor / Disk|Resultado IA → editor / disco|Résultat IA → éditeur / disque|Risultato IA → editor / disco|Resultado IA → editor / disco|AI結果 → 現在の編集／ディスク|AI结果 → 当前编辑器／磁盘|AI結果 → 目前編輯器／磁碟
Earlier result → later result|이전 결과 → 다음 결과|Früheres → späteres Ergebnis|Resultado anterior → posterior|Résultat précédent → suivant|Risultato precedente → successivo|Resultado anterior → posterior|前の結果 → 後の結果|之前结果 → 之后结果|先前結果 → 後續結果
No fix attempts yet. Analyze a failed Run and review its proposal.|수정 시도가 없습니다. 실패 Run을 분석하고 제안을 검토하세요.|Noch keine Fixversuche. Fehler analysieren und Vorschlag prüfen.|Sin intentos. Analice un Run fallido y revise la propuesta.|Aucune tentative. Analysez un Run échoué et sa proposition.|Nessun tentativo. Analizza un Run fallito e la proposta.|Sem tentativas. Analise um Run com falha e a proposta.|失敗Runを分析して提案を確認してください。|尚无修复尝试，请分析失败Run并审查提案。|尚無修復嘗試，請分析失敗Run並審核提案。
Review data unavailable. Reconnect and retry.|검토 데이터를 불러오지 못했습니다. 재연결 후 다시 시도하세요.|Prüfdaten fehlen. Neu verbinden.|Datos no disponibles. Reconecte.|Données indisponibles. Reconnectez.|Dati non disponibili. Riconnetti.|Dados indisponíveis. Reconecte.|データを取得できません。再接続してください。|审查数据不可用，请重连。|審核資料無法取得，請重新連線。
Usage unavailable|사용량 미보고|Verbrauch nicht verfügbar|Uso no disponible|Usage indisponible|Uso non disponibile|Uso indisponível|使用量未報告|用量不可用|用量無法取得
Recommended validation|추천 검증|Empfohlene Validierung|Validación recomendada|Validation recommandée|Validazione consigliata|Validação recomendada|推奨検証|建议验证|建議驗證
Tests matched configured affected files.|설정된 영향 파일에 맞는 테스트입니다.|Tests entsprechen betroffenen Dateien.|Pruebas para archivos afectados.|Tests des fichiers concernés.|Test per file interessati.|Testes para arquivos afetados.|影響ファイルに対応するテストです。|测试匹配受影响文件。|測試符合受影響檔案。
Shared configuration changed; review all Protocol tests.|공통 설정이 변경되어 모든 Protocol 테스트를 검토합니다.|Gemeinsame Konfiguration geändert; alle Tests prüfen.|Configuración común cambiada; revise todas las pruebas.|Configuration commune modifiée ; vérifiez tous les tests.|Configurazione comune cambiata; verifica tutti i test.|Configuração comum alterada; revise todos os testes.|共通設定変更のため全テストを確認してください。|公共配置已更改，请检查全部测试。|共用設定已變更，請檢查所有測試。
Some files have no affected-test mapping; review all Protocol tests.|일부 파일에 테스트 연결이 없어 모든 Protocol 테스트를 검토합니다.|Dateien ohne Testzuordnung; alle Tests prüfen.|Hay archivos sin pruebas asignadas; revise todas.|Certains fichiers sans tests associés ; vérifiez tous les tests.|File senza test associati; verifica tutti i test.|Arquivos sem testes associados; revise todos.|未対応ファイルがあるため全テストを確認してください。|部分文件未映射测试，请检查全部测试。|部分檔案未對應測試，請檢查所有測試。
Selection prepares the existing approval action. Nothing runs automatically.|선택 후 기존 승인 절차를 따릅니다. 자동으로 실행하지 않습니다.|Auswahl bereitet die Genehmigung vor. Kein automatischer Start.|La selección prepara la aprobación. Nada se ejecuta automáticamente.|La sélection prépare l'approbation. Aucun lancement automatique.|La selezione prepara l'approvazione. Nessuna esecuzione automatica.|A seleção prepara a aprovação. Nada executa automaticamente.|選択後に承認します。自動実行はありません。|选择后仍需批准，不会自动运行。|選取後仍需核准，不會自動執行。
No saved Protocol validation is available.|저장된 Protocol 검증이 없습니다.|Keine gespeicherte Validierung.|No hay validación guardada.|Aucune validation enregistrée.|Nessuna validazione salvata.|Nenhuma validação salva.|保存済み検証がありません。|没有已保存的验证。|沒有已儲存的驗證。
Unmapped files|연결되지 않은 파일|Nicht zugeordnete Dateien|Archivos sin asignar|Fichiers non associés|File non associati|Arquivos sem associação|未対応ファイル|未映射文件|未對應檔案
Suggestions without a saved Protocol reference are not executable.|저장된 Protocol 참조가 없는 제안은 실행할 수 없습니다.|Vorschläge ohne gespeicherten Bezug sind nicht ausführbar.|Sugerencias sin referencia guardada no son ejecutables.|Suggestions sans référence enregistrée non exécutables.|Proposte senza riferimento salvato non eseguibili.|Sugestões sem referência salva não executáveis.|保存済み参照のない提案は実行できません。|无已保存引用的建议不可执行。|無已儲存參照的建議無法執行。
Affected files|영향 파일|Betroffene Dateien|Archivos afectados|Fichiers concernés|File interessati|Arquivos afetados|影響ファイル|受影响文件|受影響檔案
Optional relative file patterns, one per line. Use * for file names or ** for directories.|상대 파일 패턴을 한 줄씩 선택 입력합니다. 파일명은 *, 디렉터리는 **를 사용합니다.|Optionale relative Muster, je Zeile. * für Namen, ** für Verzeichnisse.|Patrones relativos opcionales por línea. * para nombres, ** para carpetas.|Motifs relatifs facultatifs par ligne. * pour noms, ** pour dossiers.|Modelli relativi opzionali per riga. * per nomi, ** per cartelle.|Padrões relativos opcionais por linha. * para nomes, ** para pastas.|相対パターンを1行ずつ入力。名前は*、ディレクトリは**。|可选相对模式每行一个，名称用*，目录用**。|選填相對模式每行一個，名稱用*，目錄用**。
standard-validation|기본 검증|Standardprüfung|Validación estándar|Validation standard|Validazione standard|Validação padrão|標準検証|标准验证|標準驗證
affected-files|영향 파일|Betroffene Dateien|Archivos afectados|Fichiers concernés|File interessati|Arquivos afetados|影響ファイル|受影响文件|受影響檔案
original-failure|원래 실패|Ursprünglicher Fehler|Fallo original|Échec initial|Errore originale|Falha original|元の失敗|原始失败|原始失敗
global-change|공통 변경|Gemeinsame Änderung|Cambio común|Modification commune|Modifica comune|Alteração comum|共通変更|公共更改|共用變更
unmapped-change|연결 없는 변경|Nicht zugeordnete Änderung|Cambio sin asignar|Modification non associée|Modifica non associata|Alteração sem associação|未対応変更|未映射更改|未對應變更
ai-protocol-reference|AI Protocol 참조|AI-Protokollbezug|Referencia IA Protocol|Référence IA Protocol|Riferimento AI Protocol|Referência IA Protocol|AI Protocol参照|AI Protocol引用|AI Protocol參照
Refresh state before retrying. Do not repeat a submitted action blindly.|재시도 전 상태를 새로 확인하세요. 요청을 무작정 반복하지 마세요.|Vor Wiederholung Zustand aktualisieren. Gesendete Aktionen nicht blind wiederholen.|Actualice el estado antes de reintentar. No repita acciones a ciegas.|Actualisez l'état avant de réessayer. Ne répétez pas aveuglément.|Aggiorna lo stato prima di riprovare. Non ripetere alla cieca.|Atualize o estado antes de tentar. Não repita ações cegamente.|再試行前に状態を更新し、送信済み操作を無条件に繰り返さないでください。|重试前刷新状态，不要盲目重复已提交操作。|重試前重新整理狀態，不要盲目重複已提交操作。
Stop Core before upgrade. Diagnose, back up, then restore into a new directory if recovery is required.|업그레이드 전 Core를 중지하고 진단·백업하세요. 복구 시 새 폴더로 복원하세요.|Core vor Upgrade stoppen, prüfen und sichern. In neues Verzeichnis wiederherstellen.|Detenga Core antes de actualizar, diagnostique y respalde. Restaure en carpeta nueva.|Arrêtez Core avant mise à niveau, diagnostiquez et sauvegardez. Restaurez dans un nouveau dossier.|Arresta Core prima di aggiornare, diagnostica e salva. Ripristina in nuova cartella.|Pare Core antes de atualizar, diagnostique e faça backup. Restaure em pasta nova.|更新前にCoreを停止し診断・バックアップ。復旧は新規フォルダーへ。|升级前停止Core并诊断备份，恢复到新目录。|升級前停止Core並診斷備份，還原至新目錄。
No history matches these filters. Change filters and load again.|조건에 맞는 이력이 없습니다. 조건을 바꿔 다시 조회하세요.|Keine passenden Einträge. Filter ändern und erneut laden.|No hay resultados. Cambie filtros y cargue otra vez.|Aucun résultat. Modifiez les filtres puis rechargez.|Nessun risultato. Cambia filtri e ricarica.|Nenhum resultado. Altere filtros e carregue novamente.|一致する履歴がありません。条件を変更して再読込してください。|没有匹配历史，请调整筛选后重载。|沒有符合歷程，請調整篩選後重新載入。
Previous page|이전 페이지|Vorherige Seite|Página anterior|Page précédente|Pagina precedente|Página anterior|前のページ|上一页|上一頁
Source transfer|소스 전송|Quellübertragung|Transferencia de fuente|Transfert source|Trasferimento sorgente|Transferência de fonte|ソース転送|源码传输|原始碼傳輸
reused files|재사용 파일|wiederverwendete Dateien|archivos reutilizados|fichiers réutilisés|file riutilizzati|arquivos reutilizados|再利用ファイル|复用文件|重用檔案
History display request cancelled. Server work is unchanged.|이력 표시 요청을 취소했습니다. 서버 작업은 그대로입니다.|Anzeige abgebrochen. Serverarbeit unverändert.|Visualización cancelada. Trabajo servidor sin cambios.|Affichage annulé. Travail serveur inchangé.|Visualizzazione annullata. Lavoro server invariato.|Exibição cancelada. Trabalho servidor inalterado.|履歴表示を中止。サーバー作業は継続します。|历史显示已取消，服务器工作不变。|歷程顯示已取消，伺服器工作不變。
Review the proposed diff before approving.|승인 전 수정안을 검토하세요.|Diff vor Genehmigung prüfen.|Revise diff antes de aprobar.|Vérifiez le diff avant approbation.|Rivedi diff prima di approvare.|Revise diff antes de aprovar.|承認前に差分を確認してください。|批准前审查差异。|核准前檢查差異。
Approval recorded. Apply the reviewed patch.|승인이 기록됐습니다. 검토한 수정안을 적용하세요.|Genehmigung gespeichert. Geprüften Patch anwenden.|Aprobación registrada. Aplique parche revisado.|Approbation enregistrée. Appliquez le patch vérifié.|Approvazione registrata. Applica patch verificato.|Aprovação registrada. Aplique patch revisado.|承認済みです。確認した修正を適用してください。|批准已记录，请应用已审查补丁。|核准已記錄，請套用已檢查修補。
Review disk changes and select a saved validation.|디스크 변경을 확인하고 저장된 검증을 선택하세요.|Diskänderungen prüfen und gespeicherte Validierung wählen.|Revise cambios y elija validación guardada.|Vérifiez les changements et choisissez une validation.|Verifica modifiche e scegli validazione salvata.|Revise alterações e escolha validação salva.|ディスク変更を確認し保存済み検証を選択。|检查磁盘更改并选择已保存验证。|檢查磁碟變更並選擇已儲存驗證。
Validation is running. Wait for the recorded result.|검증 중입니다. 기록된 결과를 기다리세요.|Validierung läuft. Ergebnis abwarten.|Validación en curso. Espere resultado.|Validation en cours. Attendez le résultat.|Validazione in corso. Attendi risultato.|Validação em andamento. Aguarde resultado.|検証中です。結果を待ってください。|正在验证，请等待记录结果。|正在驗證，請等待記錄結果。
Remote retest is queued or running. Source transfer alone is not a test pass.|원격 재시험 대기 또는 실행 중입니다. 소스 전송만으로 합격하지 않습니다.|Retest wartet oder läuft. Übertragung bedeutet keinen Testpass.|Reprueba pendiente o activa. Transferir fuente no implica éxito.|Retest en attente ou actif. Transfert seul ne valide pas le test.|Retest in attesa o attivo. Trasferimento non significa test riuscito.|Reteste pendente ou ativo. Transferir fonte não significa aprovação.|再試験待機・実行中。ソース転送だけでは合格ではありません。|重测排队或运行中，源码传输不等于测试通过。|重測排隊或執行中，原始碼傳輸不等於測試通過。
Fix verified by the recorded test result.|기록된 테스트 결과로 수정이 검증됐습니다.|Fix durch Testergebnis bestätigt.|Corrección verificada por resultado de prueba.|Correction vérifiée par résultat du test.|Correzione verificata dal risultato test.|Correção verificada pelo resultado do teste.|テスト結果で修正を検証しました。|修复已由记录测试结果验证。|修復已由記錄測試結果驗證。
Inspect the new failure evidence, then reanalyze or revert.|새 실패 근거를 확인하고 재분석하거나 되돌리세요.|Neue Fehlerbelege prüfen, neu analysieren oder zurücksetzen.|Revise evidencia nueva, reanalice o revierta.|Vérifiez les nouveaux indices, réanalysez ou annulez.|Verifica nuove prove, rianalizza o ripristina.|Revise novas evidências, reanalise ou reverta.|新たな失敗証拠を確認して再分析・復元してください。|检查新失败证据，然后重新分析或回退。|檢查新失敗證據，再重新分析或還原。
AI changes were reverted. Review the current workspace.|AI 변경을 되돌렸습니다. 현재 작업 공간을 확인하세요.|AI-Änderungen zurückgesetzt. Workspace prüfen.|Cambios IA revertidos. Revise workspace.|Modifications IA annulées. Vérifiez workspace.|Modifiche AI ripristinate. Verifica workspace.|Alterações IA revertidas. Revise workspace.|AI変更を復元しました。作業領域を確認。|AI更改已回退，请检查工作区。|AI變更已還原，請檢查工作區。
Cancellation recorded. Review source and run state before continuing.|취소가 기록됐습니다. 계속하기 전 소스와 실행 상태를 확인하세요.|Abbruch gespeichert. Quelle und Lauf prüfen.|Cancelación registrada. Revise fuente y ejecución.|Annulation enregistrée. Vérifiez source et exécution.|Annullamento registrato. Verifica sorgente ed esecuzione.|Cancelamento registrado. Revise fonte e execução.|中止記録済み。継続前にソースと実行状態を確認。|取消已记录，继续前检查源码和运行状态。|取消已記錄，繼續前檢查原始碼及執行狀態。
Proposal rejected. Source was not changed.|제안을 거부했습니다. 소스 변경은 없습니다.|Vorschlag abgelehnt. Quelle unverändert.|Propuesta rechazada. Fuente sin cambios.|Proposition rejetée. Source inchangée.|Proposta respinta. Sorgente invariata.|Proposta rejeitada. Fonte inalterada.|提案を拒否。ソースは未変更。|提案已拒绝，源码未更改。|提案已拒絕，原始碼未變更。
Recovery requires reviewing the patch conflict before further writes.|추가 수정 전 패치 충돌을 검토해야 합니다.|Patchkonflikt vor weiteren Änderungen prüfen.|Revise conflicto antes de más escrituras.|Vérifiez le conflit avant nouvelle modification.|Verifica conflitto prima di nuove scritture.|Revise conflito antes de novas alterações.|追加変更前に修正の競合を確認してください。|进一步写入前审查补丁冲突。|進一步寫入前檢查修補衝突。
Open the retest Run to verify the recorded result.|재시험 Run을 열어 기록된 결과를 확인하세요.|Retest-Lauf öffnen und Ergebnis prüfen.|Abra Run de reprueba y verifique resultado.|Ouvrez le Run de retest et vérifiez le résultat.|Apri Run retest e verifica risultato.|Abra Run do reteste e verifique resultado.|再試験Runを開いて記録結果を確認。|打开重测Run以验证记录结果。|開啟重測Run以驗證記錄結果。
Timing unavailable|시간 미기록|Zeit nicht verfügbar|Tiempo no disponible|Durée indisponible|Tempo non disponibile|Tempo indisponível|時間未記録|时间未记录|時間未記錄`;
export const aiReviewMessages:Partial<Record<Language,Record<string,string>>>=Object.fromEntries(locales.map((locale,index)=>[locale,Object.fromEntries(rows.split('\n').map(row=>{const parts=row.split('|');return[parts[0],parts[index+1]];}))]));
