import {additionalLanguages} from './international.ts';
const rows=`Ask about the connected project or inspect a failed Run. Only selected context and requested read-only tool results are sent to the provider.|Fragen zum verbundenen Projekt oder fehlgeschlagenen Lauf stellen. Nur ausgewählter Kontext und angeforderte Leseergebnisse werden gesendet.|Pregunta sobre el proyecto o una ejecución fallida. Solo se envían contexto seleccionado y resultados de herramientas de lectura.|Posez une question sur le projet ou une exécution échouée. Seuls le contexte sélectionné et les résultats de lecture demandés sont envoyés.|Chiedi del progetto o di un'esecuzione fallita. Si inviano solo contesto selezionato e risultati di lettura richiesti.|Pergunte sobre o projeto ou uma execução falha. Apenas contexto selecionado e resultados de leitura são enviados.|接続したプロジェクトについて質問、または失敗した実行を調べます。選択したコンテキストと要求された読み取り結果だけを送信します。|询问已连接项目或检查失败运行。仅发送选定上下文及请求的只读工具结果。|詢問已連接專案或檢查失敗執行。僅傳送選定內容脈絡及要求的唯讀工具結果。
Read source, explain code and investigate failed tests.|Quellcode lesen, erklären und fehlgeschlagene Tests untersuchen.|Lee código, explícalo e investiga pruebas fallidas.|Lisez le code, expliquez-le et étudiez les tests échoués.|Leggi e spiega codice, indaga test falliti.|Leia e explique código e investigue testes falhos.|ソースの読み取り、コード説明、失敗テストの調査を行います。|读取源代码、解释代码并调查失败测试。|讀取原始碼、解釋程式碼並調查失敗測試。
Read + analyze + propose. Source changes require explicit proposal approval.|Lesen, analysieren, vorschlagen. Quelländerungen erfordern ausdrückliche Freigabe.|Leer, analizar y proponer. Cambiar código requiere aprobación explícita.|Lire, analyser et proposer. Toute modification nécessite une approbation explicite.|Leggi, analizza e proponi. Le modifiche richiedono approvazione esplicita.|Leia, analise e proponha. Alterações exigem aprovação explícita.|読み取り・分析・提案を行います。ソース変更には提案への明示的な承認が必要です。|读取、分析和提案。源代码更改需明确批准提案。|讀取、分析與提案。原始碼變更需明確核准提案。
Connect to Core in Agents. AI credentials and model are configured on Core; existing IDE features remain available.|In Agents Core verbinden. KI-Zugangsdaten und Modell werden in Core konfiguriert; IDE-Funktionen bleiben verfügbar.|Conecta Core en Agentes. Credenciales y modelo IA se configuran en Core; el IDE sigue disponible.|Connectez Core dans Agents. Identifiants et modèle IA sont configurés sur Core ; l'IDE reste disponible.|Collega Core in Agenti. Credenziali e modello IA si configurano su Core; l'IDE resta disponibile.|Conecte Core em Agentes. Credenciais e modelo IA são configurados no Core; o IDE permanece disponível.|エージェントで Core に接続してください。AI 認証とモデルは Core で設定します。既存 IDE 機能は利用できます。|在代理页面连接 Core。AI 凭据与模型在 Core 配置，现有 IDE 功能仍可用。|在代理程式頁面連接 Core。AI 認證與模型在 Core 設定，現有 IDE 功能仍可使用。
No analysis in this workspace session.|Keine Analyse in dieser Sitzung.|Sin análisis en esta sesión.|Aucune analyse dans cette session.|Nessuna analisi in questa sessione.|Sem análise nesta sessão.|このセッションに分析はありません。|此工作区会话暂无分析。|此工作區工作階段尚無分析。
No context sent yet.|Noch kein Kontext gesendet.|Aún no se envió contexto.|Aucun contexte envoyé.|Nessun contesto inviato.|Nenhum contexto enviado.|コンテキストはまだ送信されていません。|尚未发送上下文。|尚未傳送內容脈絡。
No related source analysis supplied.|Keine zugehörige Quellanalyse vorhanden.|No se proporcionó análisis de código relacionado.|Aucune analyse de source liée fournie.|Nessuna analisi sorgente correlata.|Sem análise de código relacionado.|関連ソースの分析はありません。|未提供相关源代码分析。|未提供相關原始碼分析。
No additional uncertainty reported; verify all suggestions before use.|Keine weitere Unsicherheit gemeldet; Vorschläge vor Nutzung prüfen.|Sin incertidumbre adicional; verifica todas las sugerencias antes de usarlas.|Aucune incertitude supplémentaire ; vérifiez les suggestions avant usage.|Nessuna ulteriore incertezza; verifica i suggerimenti prima dell'uso.|Sem incerteza adicional; verifique sugestões antes de usar.|追加の不確実性は報告されていません。提案は使用前に確認してください。|未报告额外不确定性；使用前请验证所有建议。|未回報額外不確定性；使用前請驗證所有建議。
Inspecting project context…|Projektkontext wird geprüft…|Inspeccionando contexto del proyecto…|Inspection du contexte du projet…|Esame del contesto del progetto…|Inspecionando contexto do projeto…|プロジェクトのコンテキストを確認中…|正在检查项目上下文…|正在檢查專案內容脈絡…
Review this proposal. Applying requires explicit approval.|Vorschlag prüfen. Anwenden erfordert ausdrückliche Freigabe.|Revisa la propuesta. Aplicar requiere aprobación explícita.|Relisez la proposition. L'application nécessite une approbation explicite.|Rivedi la proposta. Applicarla richiede approvazione esplicita.|Revise a proposta. Aplicar exige aprovação explícita.|提案を確認してください。適用には明示的な承認が必要です。|请审核提案。应用需要明确批准。|請審核提案。套用需要明確核准。
Drafts stay in TASTEDEV. GitHub creation requires review and explicit approval.|Entwürfe bleiben in TASTEDEV. GitHub-Erstellung erfordert Prüfung und Freigabe.|Borradores permanecen en TASTEDEV. Crear en GitHub requiere revisión y aprobación.|Les brouillons restent dans TASTEDEV. La création GitHub exige relecture et approbation.|Le bozze restano in TASTEDEV. Creare su GitHub richiede revisione e approvazione.|Rascunhos ficam no TASTEDEV. Criar no GitHub exige revisão e aprovação.|下書きは TASTEDEV に保存。GitHub 作成には確認と明示的承認が必要です。|草稿保留在 TASTEDEV。GitHub 创建需审核和明确批准。|草稿保留在 TASTEDEV。GitHub 建立需審核與明確核准。
Connect to Core in Agents. IDE, AI and tests remain available without GitHub.|In Agents Core verbinden. IDE, KI und Tests bleiben ohne GitHub verfügbar.|Conecta Core en Agentes. IDE, IA y pruebas funcionan sin GitHub.|Connectez Core dans Agents. IDE, IA et tests restent disponibles sans GitHub.|Collega Core in Agenti. IDE, IA e test restano disponibili senza GitHub.|Conecte Core em Agentes. IDE, IA e testes funcionam sem GitHub.|エージェントで Core に接続してください。GitHub がなくても IDE・AI・テストは利用できます。|在代理页面连接 Core。无需 GitHub 仍可使用 IDE、AI 和测试。|在代理程式頁面連接 Core。無需 GitHub 仍可使用 IDE、AI 與測試。
No candidates. Select a failed Run to prepare a draft.|Keine Kandidaten. Fehlgeschlagenen Lauf für Entwurf wählen.|Sin candidatos. Selecciona ejecución fallida para preparar borrador.|Aucun candidat. Sélectionnez une exécution échouée pour un brouillon.|Nessun candidato. Scegli esecuzione fallita per una bozza.|Sem candidatos. Selecione execução falha para criar rascunho.|候補がありません。失敗した実行を選択して下書きを作成してください。|无候选。选择失败运行以准备草稿。|無候選。選取失敗執行以準備草稿。
No linked external issues.|Keine externen Issues verknüpft.|Sin incidencias externas vinculadas.|Aucun ticket externe lié.|Nessuna issue esterna collegata.|Sem issues externas vinculadas.|リンクした外部 Issue はありません。|无关联外部问题。|無連結外部議題。
Select a completed Run|Abgeschlossenen Lauf wählen|Seleccionar ejecución finalizada|Sélectionner une exécution terminée|Seleziona esecuzione completata|Selecionar execução concluída|完了した実行を選択|选择已完成运行|選取已完成執行
Select an Issue Candidate or Linked Issue. Failure never creates a GitHub issue automatically.|Issue-Kandidaten oder verknüpftes Issue wählen. Fehler erstellen niemals automatisch GitHub-Issues.|Selecciona candidato o incidencia vinculada. Los fallos nunca crean incidencias GitHub automáticamente.|Sélectionnez un candidat ou ticket lié. Un échec ne crée jamais automatiquement un ticket GitHub.|Scegli candidato o issue collegata. Un errore non crea mai automaticamente issue GitHub.|Selecione candidata ou issue vinculada. Falhas nunca criam issues GitHub automaticamente.|Issue 候補またはリンク済み Issue を選択してください。失敗による GitHub 自動作成は行いません。|选择候选问题或关联问题。失败不会自动创建 GitHub 问题。|選取候選議題或連結議題。失敗不會自動建立 GitHub 議題。
These are suggestions. Choose an existing Issue or explicitly approve a new Issue.|Dies sind Vorschläge. Bestehendes Issue wählen oder neues ausdrücklich freigeben.|Son sugerencias. Elige incidencia existente o aprueba una nueva explícitamente.|Ce sont des suggestions. Choisissez un ticket existant ou approuvez explicitement un nouveau.|Sono suggerimenti. Scegli issue esistente o approva esplicitamente una nuova.|São sugestões. Escolha issue existente ou aprove explicitamente uma nova.|これは候補です。既存の Issue を選択するか、新規 Issue を明示的に承認してください。|这些是建议。请选择现有问题或明确批准新问题。|這些是建議。請選擇現有議題或明確核准新議題。
No duplicate candidates returned.|Keine Duplikatkandidaten gefunden.|Sin candidatos duplicados.|Aucun doublon candidat retourné.|Nessun candidato duplicato.|Nenhuma candidata duplicada.|重複の候補はありません。|无重复候选。|無重複候選。
Schedules run in Core. AI analysis is off; patches and GitHub writes still need approval.|Zeitpläne laufen in Core. KI-Analyse ist aus; Patches und GitHub-Schreiben brauchen Freigabe.|Las programaciones se ejecutan en Core. IA desactivada; parches y escritura GitHub requieren aprobación.|Les planifications s'exécutent dans Core. Analyse IA désactivée ; correctifs et écritures GitHub exigent approbation.|Le pianificazioni girano in Core. Analisi IA disattivata; patch e scritture GitHub richiedono approvazione.|Agendamentos executam no Core. IA desativada; patches e gravações GitHub exigem aprovação.|スケジュールは Core で実行。AI 分析は無効で、パッチと GitHub 書き込みには承認が必要です。|计划在 Core 运行。AI 分析关闭；补丁和 GitHub 写入仍需批准。|排程在 Core 執行。AI 分析關閉；修補與 GitHub 寫入仍需核准。
No schedules. Sync a saved Protocol to choose a Test.|Keine Zeitpläne. Gespeichertes Protocol synchronisieren, um Test zu wählen.|Sin programaciones. Sincroniza el protocolo guardado para elegir prueba.|Aucune planification. Synchronisez un protocole enregistré pour choisir un test.|Nessuna pianificazione. Sincronizza protocollo salvato per scegliere test.|Sem agendamentos. Sincronize protocolo salvo para escolher teste.|スケジュールがありません。保存した Protocol を同期してテストを選択してください。|无计划。请同步已保存协议以选择测试。|無排程。請同步已儲存協定以選取測試。
Select a Schedule or create one after syncing the project's saved Protocol.|Zeitplan wählen oder nach Protocol-Synchronisierung erstellen.|Selecciona programación o crea una tras sincronizar el protocolo del proyecto.|Sélectionnez une planification ou créez-en une après synchronisation du protocole.|Scegli pianificazione o creane una dopo aver sincronizzato il protocollo.|Selecione agendamento ou crie após sincronizar protocolo do projeto.|スケジュールを選択、または保存した Protocol を同期して作成してください。|选择计划，或同步项目已保存协议后创建。|選取排程，或同步專案已儲存協定後建立。
No trigger history yet.|Noch kein Auslöserverlauf.|Aún no hay historial de activación.|Aucun historique de déclenchement.|Nessuna cronologia attivazioni.|Sem histórico de gatilhos.|トリガー履歴はまだありません。|尚无触发历史。|尚無觸發歷程。
Enabled — allow automatic Protocol Test execution|Aktiviert — automatische Protocol-Tests erlauben|Activado — permitir pruebas automáticas del protocolo|Activé — autoriser les tests automatiques du protocole|Abilitato — consenti test automatici del protocollo|Ativado — permitir testes automáticos do protocolo|有効 — Protocol テストの自動実行を許可|启用—允许自动执行协议测试|啟用—允許自動執行協定測試
Manual, disabled or waiting for Protocol|Manuell, deaktiviert oder wartet auf Protocol|Manual, desactivado o esperando protocolo|Manuel, désactivé ou en attente du protocole|Manuale, disabilitato o in attesa del protocollo|Manual, desativado ou aguardando protocolo|手動・無効・Protocol 待機|手动、已禁用或等待协议|手動、已停用或等待協定
Missed executions are skipped. An overlapping Project/Test is skipped, including queued tests. Minimum interval:60s.|Verpasste Läufe werden übersprungen. Überlappende Projekt-/Tests einschließlich wartender Tests werden übersprungen. Mindestintervall: 60 s.|Se omiten ejecuciones perdidas y pruebas superpuestas, incluidas las en cola. Intervalo mínimo: 60 s.|Les exécutions manquées et tests de projet qui se chevauchent, y compris en file, sont ignorés. Intervalle minimal : 60 s.|Si saltano esecuzioni perse e test sovrapposti, inclusi quelli in coda. Intervallo minimo: 60 s.|Execuções perdidas e testes sobrepostos, incluindo na fila, são ignorados. Intervalo mínimo: 60 s.|未実行と重複したプロジェクト／テストはキュー内も含めてスキップします。最小間隔は 60 秒です。|错过的执行和重叠项目/测试（含队列中）将跳过。最小间隔：60 秒。|錯過的執行及重疊專案/測試（含佇列中）將略過。最小間隔：60 秒。
Closing Studio leaves schedules running while Core is alive. Core restart restores definitions and requires Protocol sync before execution. History is kept for the current Core session. Git, dependency and OS event adapters are foundation only.|Zeitpläne laufen bei aktivem Core auch ohne Studio. Core-Neustart stellt Definitionen wieder her; vor Ausführung Protocol synchronisieren. Verlauf gilt für die Core-Sitzung. Git-, Abhängigkeits- und OS-Adapter sind nur Grundlagen.|Las programaciones siguen con Core activo aunque cierres Studio. Reiniciar Core restaura definiciones y exige sincronizar protocolo antes de ejecutar. Historial por sesión Core. Adaptadores Git, dependencias y SO son solo base.|Les planifications continuent tant que Core reste actif. Un redémarrage restaure les définitions et exige une synchronisation du protocole avant exécution. Historique par session Core. Adaptateurs Git, dépendances et OS : fondations uniquement.|Le pianificazioni continuano con Core attivo anche chiudendo Studio. Riavviare Core ripristina definizioni e richiede sincronizzazione protocollo. Cronologia per sessione Core. Adattatori Git, dipendenze e OS sono solo fondamenta.|Agendamentos continuam com Core ativo mesmo fechando Studio. Reiniciar Core restaura definições e exige sincronizar protocolo. Histórico por sessão Core. Adaptadores Git, dependências e SO são apenas base.|Studio を閉じても Core 稼働中はスケジュールを継続します。Core 再起動で定義を復元し、実行前に Protocol 同期が必要です。履歴は Core セッション内のみ。Git・依存関係・OS イベントは基盤のみです。|关闭 Studio 后，只要 Core 运行计划就继续。Core 重启恢复定义，执行前需同步协议。历史仅保留当前 Core 会话。Git、依赖和系统事件适配器仅为基础。|關閉 Studio 後，只要 Core 執行排程就繼續。Core 重啟復原定義，執行前需同步協定。歷程僅保留目前 Core 工作階段。Git、相依性及系統事件配接器僅為基礎。
No artifact metadata for this Run. Logs are included when available.|Keine Artefaktmetadaten. Verfügbare Protokolle werden einbezogen.|Sin metadatos de artefactos. Se incluyen registros disponibles.|Aucune métadonnée d'artefact. Les journaux disponibles sont inclus.|Nessun metadato artefatto. Si includono i log disponibili.|Sem metadados de artefatos. Logs disponíveis são incluídos.|この実行の成果物情報はありません。利用可能なログを含めます。|此运行无产物元数据。可用时包含日志。|此執行無產物中繼資料。可用時包含日誌。
No artifact metadata recorded.|Keine Artefaktmetadaten aufgezeichnet.|Sin metadatos de artefactos registrados.|Aucune métadonnée d'artefact enregistrée.|Nessun metadato artefatto registrato.|Sem metadados de artefatos registrados.|成果物情報は記録されていません。|未记录产物元数据。|未紀錄產物中繼資料。
No evidence available. Artifacts appear after verified transfer; an interrupted run may have partial evidence.|Keine Nachweise. Artefakte erscheinen nach verifiziertem Transfer; unterbrochene Läufe können Teilnachweise haben.|Sin evidencias. Los artefactos aparecen tras transferencia verificada; ejecuciones interrumpidas pueden tener evidencia parcial.|Aucune preuve. Les artefacts apparaissent après transfert vérifié ; une exécution interrompue peut avoir des preuves partielles.|Nessuna prova. Gli artefatti compaiono dopo trasferimento verificato; esecuzioni interrotte possono avere prove parziali.|Sem evidências. Artefatos aparecem após transferência verificada; execuções interrompidas podem ter evidência parcial.|証跡がありません。成果物は転送検証後に表示します。中断した実行には部分的な証跡がある場合があります。|无可用证据。产物在验证传输后显示；中断运行可能有部分证据。|無可用證據。產物在驗證傳輸後顯示；中斷執行可能有部分證據。
Select an artifact to preview or export. Files are loaded on demand.|Artefakt zum Vorschauen oder Exportieren wählen. Dateien werden bei Bedarf geladen.|Selecciona artefacto para ver o exportar. Los archivos se cargan bajo demanda.|Sélectionnez un artefact à prévisualiser ou exporter. Chargement à la demande.|Seleziona artefatto per anteprima o esportazione. File caricati su richiesta.|Selecione artefato para visualizar ou exportar. Arquivos carregados sob demanda.|成果物を選択してプレビューまたはエクスポートしてください。必要時にファイルを読み込みます。|选择产物以预览或导出。文件按需加载。|選取產物以預覽或匯出。檔案依需求載入。
Export the trace, then open it locally with Playwright show-trace. Source files and response bodies are excluded; visual content may contain sensitive information.|Trace exportieren und lokal mit Playwright show-trace öffnen. Quelldateien und Antwortinhalte sind ausgeschlossen; Bilder können sensible Daten enthalten.|Exporta la traza y ábrela localmente con Playwright show-trace. Se excluyen fuentes y cuerpos de respuesta; imágenes pueden contener datos sensibles.|Exportez la trace puis ouvrez-la localement avec Playwright show-trace. Sources et corps de réponse exclus ; les images peuvent contenir des données sensibles.|Esporta la traccia e aprila localmente con Playwright show-trace. Sorgenti e risposte escluse; le immagini possono contenere dati sensibili.|Exporte o trace e abra localmente com Playwright show-trace. Fontes e respostas excluídas; imagens podem conter informações sensíveis.|トレースをエクスポートし、ローカルで Playwright show-trace を使用してください。ソースとレスポンス本文は除外します。画像には機密情報が含まれる場合があります。|导出跟踪后用 Playwright show-trace 本地打开。源文件和响应正文被排除；视觉内容可能含敏感信息。|匯出追蹤後用 Playwright show-trace 本機開啟。原始檔與回應本文已排除；視覺內容可能含敏感資訊。
No network failures recorded.|Keine Netzwerkfehler aufgezeichnet.|Sin fallos de red registrados.|Aucun échec réseau enregistré.|Nessun errore di rete registrato.|Sem falhas de rede registradas.|ネットワーク障害の記録はありません。|未记录网络失败。|未紀錄網路失敗。`;
export const analysisGuidance=Object.fromEntries(additionalLanguages.map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const cells=row.split('|');if(cells.length!==9)throw new Error('Invalid analysis translation: '+cells[0]);return[cells[0],cells[index+1]];}))]));
