import {additionalLanguages} from './international.ts';
const rows=String.raw`Approve source changes|Quelländerungen genehmigen|Aprobar cambios de código|Approuver les modifications du code|Approva modifiche sorgente|Aprovar alterações no código|ソース変更を承認|批准源代码更改|核准原始碼變更
Approve and Apply|Genehmigen und anwenden|Aprobar y aplicar|Approuver et appliquer|Approva e applica|Aprovar e aplicar|承認して適用|批准并应用|核准並套用
Proposal {proposal}\nFiles: {files}\nApply exactly the reviewed change? Test execution requires a separate action.|Vorschlag {proposal}\nDateien: {files}\nGenau die geprüfte Änderung anwenden? Tests erfordern eine separate Aktion.|Propuesta {proposal}\nArchivos: {files}\n¿Aplicar exactamente el cambio revisado? Las pruebas requieren otra acción.|Proposition {proposal}\nFichiers : {files}\nAppliquer exactement la modification relue ? Les tests exigent une action séparée.|Proposta {proposal}\nFile: {files}\nApplicare esattamente la modifica rivista? I test richiedono un'azione separata.|Proposta {proposal}\nArquivos: {files}\nAplicar exatamente a alteração revisada? Testes exigem ação separada.|提案 {proposal}\nファイル：{files}\n確認した変更を適用しますか？テスト実行は別の操作が必要です。|提案 {proposal}\n文件：{files}\n应用已审核的确切更改？测试执行需单独操作。|提案 {proposal}\n檔案：{files}\n套用已審核的確切變更？測試執行需另行操作。
Approve local validation|Lokale Prüfung genehmigen|Aprobar validación local|Approuver la validation locale|Approva convalida locale|Aprovar validação local|ローカル検証を承認|批准本地验证|核准本機驗證
Approve Validation|Prüfung genehmigen|Aprobar validación|Approuver la validation|Approva convalida|Aprovar validação|検証を承認|批准验证|核准驗證
Protocol Task {task}: {command}\nRun this saved Protocol task in the connected workspace?|Protocol-Aufgabe {task}: {command}\nGespeicherte Aufgabe im verbundenen Arbeitsbereich ausführen?|Tarea del protocolo {task}: {command}\n¿Ejecutar esta tarea guardada en el espacio conectado?|Tâche du protocole {task} : {command}\nExécuter cette tâche enregistrée dans l'espace connecté ?|Attività protocollo {task}: {command}\nEseguire l'attività salvata nell'area collegata?|Tarefa do protocolo {task}: {command}\nExecutar tarefa salva no espaço conectado?|Protocol タスク {task}：{command}\n保存したタスクを接続中の領域で実行しますか？|协议任务 {task}：{command}\n在已连接工作区运行此保存的协议任务？|協定工作 {task}：{command}\n在已連接工作區執行此儲存的協定工作？
Approve validation and remote retest|Prüfung und Remote-Retest genehmigen|Aprobar validación y prueba remota|Approuver validation et nouveau test distant|Approva convalida e nuovo test remoto|Aprovar validação e novo teste remoto|検証とリモート再テストを承認|批准验证和远程重新测试|核准驗證及遠端重新測試
Approve Retest|Retest genehmigen|Aprobar repetición|Approuver le nouveau test|Approva nuovo test|Aprovar novo teste|再テストを承認|批准重新测试|核准重新測試
Run Protocol Test {test} on an eligible Agent using a secret-filtered saved workspace snapshot?|Protocol-Test {test} auf geeignetem Agent mit geheimnisgefiltertem Snapshot ausführen?|¿Ejecutar prueba {test} en agente compatible usando instantánea guardada sin secretos?|Exécuter le test {test} sur un agent admissible avec instantané enregistré filtré des secrets ?|Eseguire test {test} su agente idoneo usando snapshot salvato filtrato dai segreti?|Executar teste {test} em agente elegível com snapshot salvo filtrado de segredos?|シークレットを除外した保存済みスナップショットで、対応エージェントに Protocol テスト {test} を実行しますか？|使用过滤秘密的已保存工作区快照，在合适代理上运行协议测试 {test}？|使用過濾祕密的已儲存工作區快照，在適合代理程式上執行協定測試 {test}？
Repository: {repository}\nTitle: {title}\n{count} possible duplicate(s). Create exactly this reviewed title/body/labels? This approval covers this candidate only. Internal evidence is not public.|Repository: {repository}\nTitel: {title}\n{count} mögliche Duplikate. Geprüften Titel/Inhalt/Labels erstellen? Freigabe gilt nur für diesen Kandidaten. Interne Nachweise sind nicht öffentlich.|Repositorio: {repository}\nTítulo: {title}\n{count} posibles duplicados. ¿Crear este título/cuerpo/etiquetas revisados? Aprobación solo para este candidato. La evidencia interna no es pública.|Dépôt : {repository}\nTitre : {title}\n{count} doublons possibles. Créer ces titre/corps/étiquettes relus ? Approbation pour ce candidat uniquement. Preuves internes non publiques.|Repository: {repository}\nTitolo: {title}\n{count} possibili duplicati. Creare titolo/testo/etichette rivisti? Approvazione solo per questo candidato. Prove interne non pubbliche.|Repositório: {repository}\nTítulo: {title}\n{count} possíveis duplicatas. Criar título/corpo/rótulos revisados? Aprovação só desta candidata. Evidências internas não são públicas.|リポジトリ：{repository}\nタイトル：{title}\n重複候補 {count} 件。確認したタイトル・本文・ラベルで作成しますか？承認はこの候補のみ。内部証跡は公開されません。|仓库：{repository}\n标题：{title}\n{count} 个可能重复项。创建已审核标题/正文/标签？批准仅限此候选。内部证据不公开。|儲存庫：{repository}\n標題：{title}\n{count} 個可能重複項目。建立已審核標題/本文/標籤？核准僅限此候選。內部證據不公開。`;
export const approval=Object.fromEntries(additionalLanguages.map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const cells=row.split('|').map(v=>v.replaceAll('\\n','\n'));if(cells.length!==9)throw new Error('Invalid approval translation: '+cells[0]);return[cells[0],cells[index+1]];}))]));
/** These application-owned templates are matched only at feedback/dialog boundaries. */
export const feedbackTemplates=[
 'Create in {path}.',
 'Delete “{name}” from disk? This cannot be undone in Studio. {open} open editor(s) will close; {dirty} unsaved document(s) will be discarded.',
 'Delete “{name}” and all its contents from disk? This cannot be undone in Studio. {open} open editor(s) will close; {dirty} unsaved document(s) will be discarded.',
 'Folder received: {name}. Connecting workspace…','Opening {name}…','{name} added to Recent Projects. No folders or source files were created.',
 '“{name}” has unsaved changes.','Discard unsaved changes in “{name}” and load its current disk content?',
 'Proposal {proposal}\nFiles: {files}\nApply exactly the reviewed change? Test execution requires a separate action.',
 'Protocol Task {task}: {command}\nRun this saved Protocol task in the connected workspace?',
 'Run Protocol Test {test} on an eligible Agent using a secret-filtered saved workspace snapshot?',
 'Repository: {repository}\nTitle: {title}\n{count} possible duplicate(s). Create exactly this reviewed title/body/labels? This approval covers this candidate only. Internal evidence is not public.',
];
export function matchFeedback(message:string){for(const template of feedbackTemplates){const names:string[]=[];const parts=template.split(/(\{[a-z]+\})/);const pattern=parts.map(part=>{const m=part.match(/^\{([a-z]+)\}$/);if(m){names.push(m[1]);return '([\\s\\S]*?)';}return part.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}).join('');const match=message.match(new RegExp('^'+pattern+'$'));if(match)return{key:template,values:Object.fromEntries(names.map((name,i)=>[name,match[i+1]]))};}return null;}
