import type {Language} from './core.ts';
const locales:Language[]=['ko','de','es','fr','it','pt','ja','zh','zh-hant'];
const rows=`Could not load folder.|폴더를 불러오지 못했습니다.|Ordner konnte nicht geladen werden.|No se pudo cargar la carpeta.|Impossible de charger le dossier.|Impossibile caricare la cartella.|Não foi possível carregar a pasta.|フォルダーを読み込めませんでした。|无法加载文件夹。|無法載入資料夾。
No active runs.|실행 중인 작업이 없습니다.|Keine aktiven Läufe.|No hay ejecuciones activas.|Aucune exécution active.|Nessuna esecuzione attiva.|Nenhuma execução ativa.|実行中のジョブはありません。|没有正在执行的任务。|沒有正在執行的工作。
Review required|확인 필요|Prüfung erforderlich|Revisión necesaria|Vérification requise|Verifica necessaria|Revisão necessária|確認が必要|需要检查|需要檢查
Language index notice|언어 색인 안내|Sprachindex-Hinweis|Aviso del índice de lenguaje|Avis d’indexation linguistique|Avviso indice linguistico|Aviso de índice de linguagem|言語索引のお知らせ|语言索引提示|語言索引提示
Language indexing limit reached. Open additional files directly.|언어 색인 한도에 도달했습니다. 필요한 파일을 직접 열어주세요.|Sprachindexlimit erreicht. Öffnen Sie weitere Dateien direkt.|Límite de indexación alcanzado. Abra otros archivos directamente.|Limite d’indexation atteinte. Ouvrez les autres fichiers directement.|Limite di indicizzazione raggiunto. Apri direttamente altri file.|Limite de indexação atingido. Abra outros arquivos diretamente.|言語索引の上限に達しました。必要なファイルを直接開いてください。|已达语言索引上限。请直接打开其他文件。|已達語言索引上限。請直接開啟其他檔案。
Folder|폴더|Ordner|Carpeta|Dossier|Cartella|Pasta|フォルダー|文件夹|資料夾
Connection settings|연결 설정|Verbindungseinstellungen|Configuración de conexión|Paramètres de connexion|Impostazioni di connessione|Configurações de conexão|接続設定|连接设置|連線設定
Core disconnected|Core 연결 끊김|Core getrennt|Core desconectado|Core déconnecté|Core disconnesso|Core desconectado|Core 未接続|Core 已断开|Core 已中斷
Reconnecting to Core…|Core 재연결 중…|Core wird erneut verbunden…|Reconectando a Core…|Reconnexion à Core…|Riconnessione a Core…|Reconectando ao Core…|Core に再接続中…|正在重新连接 Core…|正在重新連線 Core…
Connection profiles|연결 프로필|Verbindungsprofile|Perfiles de conexión|Profils de connexion|Profili di connessione|Perfis de conexão|接続プロファイル|连接配置|連線設定
Profiles save addresses only. Tokens must be entered for each connection.|주소만 저장합니다. 연결할 때 token을 입력하세요.|Nur Adressen werden gespeichert. Token bei jeder Verbindung eingeben.|Solo se guardan direcciones. Introduzca el token en cada conexión.|Seules les adresses sont enregistrées. Saisissez le jeton à chaque connexion.|Si salvano solo gli indirizzi. Inserisci il token per ogni connessione.|Somente endereços são salvos. Informe o token a cada conexão.|アドレスのみ保存します。接続ごとにトークンを入力してください。|仅保存地址，每次连接需输入令牌。|僅儲存位址，每次連線需輸入權杖。
Load profiles|프로필 불러오기|Profile laden|Cargar perfiles|Charger les profils|Carica profili|Carregar perfis|プロファイルを読み込む|加载配置|載入設定
Saved profile|저장된 프로필|Gespeichertes Profil|Perfil guardado|Profil enregistré|Profilo salvato|Perfil salvo|保存済みプロファイル|已保存配置|已儲存設定
New profile|새 프로필|Neues Profil|Nuevo perfil|Nouveau profil|Nuovo profilo|Novo perfil|新しいプロファイル|新配置|新設定
Profile name|프로필 이름|Profilname|Nombre del perfil|Nom du profil|Nome profilo|Nome do perfil|プロファイル名|配置名称|設定名稱
Save profile|프로필 저장|Profil speichern|Guardar perfil|Enregistrer le profil|Salva profilo|Salvar perfil|プロファイルを保存|保存配置|儲存設定
Delete profile|프로필 삭제|Profil löschen|Eliminar perfil|Supprimer le profil|Elimina profilo|Excluir perfil|プロファイルを削除|删除配置|刪除設定
Secure remote setup and recovery|안전한 원격 연결·복구|Sichere Fernverbindung und Wiederherstellung|Conexión remota segura y recuperación|Connexion distante sécurisée et restauration|Connessione remota sicura e ripristino|Conexão remota segura e recuperação|安全なリモート接続と復元|安全远程连接与恢复|安全遠端連線與復原
Use wss:// for remote Core with a trusted TLS certificate. Only local loopback accepts ws://.|원격 Core는 신뢰된 TLS 인증서와 wss://를 사용하세요. ws://는 로컬 loopback만 허용합니다.|Remote Core benötigt wss:// und ein vertrauenswürdiges TLS-Zertifikat. ws:// nur lokal.|Core remoto requiere wss:// y certificado TLS fiable. ws:// solo en bucle local.|Core distant requiert wss:// et un certificat TLS fiable. ws:// uniquement en local.|Core remoto richiede wss:// e certificato TLS attendibile. ws:// solo locale.|Core remoto exige wss:// e certificado TLS confiável. ws:// apenas local.|リモートCoreには信頼されたTLS証明書とwss://が必要です。ws://はローカルのみです。|远程Core使用受信TLS证书和wss://，ws://仅限本地环回。|遠端Core使用受信TLS憑證與wss://，ws://僅限本機迴路。
Keep Core behind the TLS proxy and restrict origins. Obtain a scoped, expiring Studio session from the Owner. Tokens are never saved in profiles.|TLS proxy와 허용 origin을 설정하고 Owner에게 범위·만료가 있는 세션을 받으세요. 프로필에 token은 저장하지 않습니다.|Core hinter TLS-Proxy betreiben und Origins beschränken. Begrenzte Sitzung vom Owner beziehen. Profile speichern keine Token.|Use proxy TLS y orígenes restringidos. Solicite sesión limitada y con vencimiento al Owner. Los perfiles no guardan tokens.|Utilisez un proxy TLS et limitez les origines. Demandez une session limitée au Owner. Aucun jeton dans les profils.|Usa proxy TLS e origini limitate. Richiedi sessione limitata al Owner. Nessun token nei profili.|Use proxy TLS e origens restritas. Solicite sessão limitada ao Owner. Perfis não salvam tokens.|TLSプロキシと許可originを設定し、Ownerから範囲と期限付きセッションを取得してください。トークンは保存しません。|使用TLS代理并限制来源，向Owner申请有范围和期限的会话。配置不保存令牌。|使用TLS代理並限制來源，向Owner申請具範圍與期限的工作階段。設定不儲存權杖。
Backup and restore are administrator operations. Stop Core, back up to a new directory, and restore only into a new directory. Keep the protected storage key with the backup.|백업·복원은 관리자 작업입니다. Core를 중지하고 새 디렉터리에 백업·복원하세요. 보호된 storage key도 함께 보관하세요.|Backup und Restore sind Administratoraufgaben. Core stoppen; neue Verzeichnisse verwenden. Geschützten Schlüssel mit Backup aufbewahren.|Copias y restauración son tareas de administrador. Detenga Core y use directorios nuevos. Conserve la clave protegida.|Sauvegarde et restauration sont administratives. Arrêtez Core et utilisez des dossiers nouveaux. Conservez la clé protégée.|Backup e ripristino sono operazioni amministrative. Arresta Core e usa nuove cartelle. Conserva la chiave protetta.|Backup e restauração são operações administrativas. Pare Core e use novos diretórios. Guarde a chave protegida.|バックアップと復元は管理者操作です。Coreを停止し、新しいディレクトリを使用してください。保護されたキーも保管します。|备份和恢复由管理员操作。停止Core并使用新目录，保留受保护的存储密钥。|備份與復原由管理員操作。停止Core並使用新目錄，保留受保護的儲存金鑰。
Agent access|Agent 접근 권한|Agent-Zugriff|Acceso de Agent|Accès Agent|Accesso Agent|Acesso Agent|Agentアクセス|Agent权限|Agent權限
Use the existing Agent ID from agent-id.json in its workspace. Grant an assigned project group and provide a dedicated Agent token. Only its hash is sent to Core.|workspace의 agent-id.json에 있는 기존 ID를 사용하세요. 프로젝트 그룹과 전용 token을 지정하며 hash만 Core로 전송합니다.|Vorhandene ID aus agent-id.json verwenden. Projektgruppe und eigenes Token angeben. Nur Hash geht an Core.|Use ID existente de agent-id.json, grupo del proyecto y token dedicado. Solo se envía el hash.|Utilisez l’ID existant de agent-id.json, un groupe du projet et un jeton dédié. Seul le hash est envoyé.|Usa ID esistente in agent-id.json, gruppo progetto e token dedicato. Si invia solo l’hash.|Use ID existente de agent-id.json, grupo do projeto e token dedicado. Apenas o hash é enviado.|agent-id.jsonの既存IDを使い、プロジェクトグループと専用トークンを指定します。ハッシュのみ送信します。|使用agent-id.json中的现有ID，指定项目组和专用令牌，仅发送哈希。|使用agent-id.json中的現有ID，指定專案群組與專用權杖，僅傳送雜湊。
Refresh Agent access|Agent 권한 새로고침|Agent-Zugriff aktualisieren|Actualizar acceso Agent|Actualiser l’accès Agent|Aggiorna accesso Agent|Atualizar acesso Agent|Agentアクセスを更新|刷新Agent权限|重新整理Agent權限
Revoked|철회됨|Widerrufen|Revocado|Révoqué|Revocato|Revogado|取り消し済み|已撤销|已撤銷
Active|활성|Aktiv|Activo|Actif|Attivo|Ativo|有効|有效|有效
Revoke this Agent for all projects using it? Active cancellation is requested and the connection is closed.|이 Agent를 사용하는 모든 프로젝트의 권한을 철회할까요? 작업 취소를 요청하고 연결을 종료합니다.|Agent für alle Projekte sperren? Abbruch wird angefordert und Verbindung geschlossen.|¿Revocar Agent para todos los proyectos? Se solicita cancelación y se cierra la conexión.|Révoquer cet Agent pour tous les projets ? Annulation demandée et connexion fermée.|Revocare Agent per tutti i progetti? Si richiede annullamento e si chiude la connessione.|Revogar Agent para todos os projetos? Cancelamento solicitado e conexão fechada.|全プロジェクトでAgentを取り消しますか？キャンセルを要求し接続を閉じます。|撤销此Agent在所有项目的权限？将请求取消并关闭连接。|撤銷此Agent於所有專案的權限？將要求取消並關閉連線。
Revoke Agent|Agent 권한 철회|Agent sperren|Revocar Agent|Révoquer Agent|Revoca Agent|Revogar Agent|Agentを取り消す|撤销Agent|撤銷Agent
Agent token|Agent token|Agent-Token|Token de Agent|Jeton Agent|Token Agent|Token Agent|Agentトークン|Agent令牌|Agent權杖
Agent group|Agent 그룹|Agent-Gruppe|Grupo de Agent|Groupe Agent|Gruppo Agent|Grupo Agent|Agentグループ|Agent组|Agent群組
Grant Agent access|Agent 권한 부여|Agent-Zugriff gewähren|Conceder acceso Agent|Autoriser Agent|Concedi accesso Agent|Conceder acesso Agent|Agentアクセスを許可|授予Agent权限|授予Agent權限
Session expires|세션 만료|Sitzung läuft ab|Vencimiento de sesión|Expiration de session|Scadenza sessione|Expiração da sessão|セッション期限|会话到期|工作階段到期`;
export const connectionManagementMessages:Partial<Record<Language,Record<string,string>>>=Object.fromEntries(locales.map((locale,index)=>[locale,Object.fromEntries(rows.split('\n').map(row=>{const parts=row.split('|');return [parts[0],parts[index+1]];}))]));
