import type {Language} from './core.ts';
const languages:Language[]=['ko','de','es','fr','it','pt','ja','zh','zh-hant'];
const rows=`Review change blocks|변경 블록 검토|Änderungsblöcke prüfen|Revisar bloques de cambios|Examiner les blocs de modifications|Rivedi blocchi di modifiche|Revisar blocos de alterações|変更ブロックを確認|审查更改块|檢閱變更區塊
Stage this change block|이 변경 블록 Stage|Diesen Änderungsblock vormerken|Preparar este bloque de cambios|Indexer ce bloc de modifications|Prepara questo blocco di modifiche|Preparar este bloco de alterações|この変更ブロックをステージ|暂存此更改块|暫存此變更區塊
Use ours in editor|편집기에 현재 내용 반영|Unsere Version im Editor verwenden|Usar nuestra versión en el editor|Utiliser notre version dans l’éditeur|Usa la nostra versione nell’editor|Usar nossa versão no editor|エディターに現在の内容を反映|在编辑器中使用我们的版本|在編輯器中使用我們的版本
Use theirs in editor|편집기에 상대 내용 반영|Andere Version im Editor verwenden|Usar su versión en el editor|Utiliser leur version dans l’éditeur|Usa la loro versione nell’editor|Usar a versão deles no editor|エディターに相手の内容を反映|在编辑器中使用对方的版本|在編輯器中使用對方的版本
Conflict resolution is unsaved. Review and save it before marking resolved.|충돌 해결 내용이 저장되지 않았습니다. 검토·저장 후 해결로 표시하세요.|Die Konfliktlösung ist nicht gespeichert. Vor dem Markieren prüfen und speichern.|La resolución no está guardada. Revísala y guárdala antes de marcarla como resuelta.|La résolution n’est pas enregistrée. Vérifiez et enregistrez avant de marquer comme résolu.|La risoluzione non è salvata. Rivedila e salvala prima di segnarla come risolta.|A resolução não foi salva. Revise e salve antes de marcar como resolvido.|競合の解決内容は未保存です。確認して保存した後、解決済みにしてください。|冲突解决内容尚未保存。请审查并保存后再标记为已解决。|衝突解決內容尚未儲存。請檢閱並儲存後再標記為已解決。`;
export const gitAdvancedMessages=Object.fromEntries(languages.map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const values=row.split('|');return [values[0],values[index+1]];}))])) as Record<Language,Record<string,string>>;
const pullRows=`Pull requests|Pull Request|Pull Requests|Solicitudes de incorporación|Pull requests|Pull request|Pull requests|プルリクエスト|拉取请求|提取請求
Review pull request|PR 검토|Pull Request prüfen|Revisar solicitud|Examiner la pull request|Rivedi pull request|Revisar pull request|プルリクエストを確認|审查拉取请求|檢閱提取請求
Approve and create pull request|승인하고 PR 생성|Bestätigen und Pull Request erstellen|Aprobar y crear solicitud|Approuver et créer la pull request|Approva e crea pull request|Aprovar e criar pull request|承認してプルリクエストを作成|批准并创建拉取请求|核准並建立提取請求
Refresh pull request and CI|PR·CI 새로고침|Pull Request und CI aktualisieren|Actualizar solicitud y CI|Actualiser la pull request et la CI|Aggiorna pull request e CI|Atualizar pull request e CI|プルリクエストとCIを更新|刷新拉取请求和 CI|重新整理提取請求與 CI
CI checks|CI 검사|CI-Prüfungen|Comprobaciones de CI|Vérifications CI|Controlli CI|Verificações CI|CIチェック|CI 检查|CI 檢查
Showing the first 100 results.|처음 100개 결과 표시 중.|Die ersten 100 Ergebnisse werden angezeigt.|Se muestran los primeros 100 resultados.|Les 100 premiers résultats sont affichés.|Visualizzati i primi 100 risultati.|Mostrando os primeiros 100 resultados.|最初の100件を表示しています。|显示前 100 个结果。|顯示前 100 個結果。
Connect to Core to manage pull requests.|Core에 연결하여 PR을 관리하세요.|Mit Core verbinden, um Pull Requests zu verwalten.|Conéctate a Core para gestionar solicitudes.|Connectez-vous à Core pour gérer les pull requests.|Connettiti a Core per gestire le pull request.|Conecte ao Core para gerenciar pull requests.|Coreに接続してプルリクエストを管理してください。|连接 Core 以管理拉取请求。|連線至 Core 以管理提取請求。
Pull request operation failed. Inspect state before retrying.|PR 작업이 실패했습니다. 재시도 전에 상태를 확인하세요.|PR-Vorgang fehlgeschlagen. Status vor erneutem Versuch prüfen.|La operación falló. Revisa el estado antes de reintentar.|L’opération a échoué. Vérifiez l’état avant de réessayer.|Operazione fallita. Verifica lo stato prima di riprovare.|A operação falhou. Verifique o estado antes de tentar novamente.|操作に失敗しました。再試行の前に状態を確認してください。|操作失败。重试前请检查状态。|操作失敗。重試前請檢查狀態。
Refresh Git before preparing a pull request.|PR 검토 전에 Git을 새로고침하세요.|Git vor der PR-Vorbereitung aktualisieren.|Actualiza Git antes de preparar la solicitud.|Actualisez Git avant de préparer la pull request.|Aggiorna Git prima di preparare la pull request.|Atualize o Git antes de preparar a pull request.|準備前にGitを更新してください。|准备拉取请求前请刷新 Git。|準備提取請求前請重新整理 Git。
Project repository does not match the selected Git remote.|프로젝트 저장소와 선택한 Git 원격이 다릅니다.|Projekt-Repository entspricht nicht dem gewählten Git-Remote.|El repositorio no coincide con el remoto seleccionado.|Le dépôt ne correspond pas au remote choisi.|Il repository non corrisponde al remoto selezionato.|O repositório não corresponde ao remoto selecionado.|リポジトリが選択したGitリモートと一致しません。|项目仓库与所选 Git 远程不匹配。|專案儲存庫與所選 Git 遠端不相符。
Pull request source changed after review. Inspect the current revision.|검토 후 PR 소스가 변경됐습니다. 현재 리비전을 확인하세요.|PR-Quelle nach Prüfung geändert. Aktuelle Revision prüfen.|El origen cambió tras la revisión. Comprueba la revisión actual.|La source a changé. Vérifiez la révision actuelle.|La sorgente è cambiata. Verifica la revisione attuale.|A fonte mudou. Verifique a revisão atual.|確認後にソースが変更されました。現在のリビジョンを確認してください。|审查后源码已更改。请检查当前修订。|檢閱後原始碼已變更。請檢查目前修訂。
GitHub credentials stay on Core. Review the exact repository, branches, revision and masked body before creating.|GitHub 인증정보는 Core에 유지됩니다. 생성 전에 저장소·브랜치·리비전·마스킹된 본문을 검토하세요.|GitHub-Zugangsdaten bleiben auf Core. Repository, Zweige, Revision und maskierten Text vor Erstellung prüfen.|Las credenciales permanecen en Core. Revisa repositorio, ramas, revisión y texto enmascarado antes de crear.|Les identifiants restent sur Core. Vérifiez dépôt, branches, révision et texte masqué avant de créer.|Le credenziali restano su Core. Rivedi repository, rami, revisione e testo mascherato prima di creare.|As credenciais ficam no Core. Revise repositório, branches, revisão e texto mascarado antes de criar.|認証情報はCoreに保持されます。作成前にリポジトリ・ブランチ・リビジョン・マスク済み本文を確認してください。|GitHub 凭据保留在 Core。创建前请审查仓库、分支、修订和已遮蔽的正文。|GitHub 憑證保留在 Core。建立前請檢閱儲存庫、分支、修訂和已遮蔽的本文。`;
for(const row of pullRows.split('\n')){const [key,...values]=row.split('|');languages.forEach((language,index)=>{gitAdvancedMessages[language][key]=values[index];});}
