import {additionalLanguages} from './international.ts';
const rows=`Register a project in this browser. This saves metadata; it does not create folders or source files.|Projekt in diesem Browser registrieren. Nur Metadaten werden gespeichert, keine Ordner oder Quelldateien erstellt.|Registra un proyecto en este navegador. Guarda metadatos; no crea carpetas ni archivos.|Enregistrez un projet dans ce navigateur. Seules les métadonnées sont sauvegardées, sans créer de dossiers ni de fichiers.|Registra un progetto in questo browser. Salva metadati, senza creare cartelle o file.|Registre um projeto neste navegador. Salva metadados, sem criar pastas ou arquivos.|このブラウザーにプロジェクト情報を登録します。フォルダーやソースファイルは作成しません。|在此浏览器注册项目，仅保存元数据，不创建文件夹或源文件。|在此瀏覽器註冊專案，僅儲存中繼資料，不建立資料夾或原始檔。
Enter a repository and destination. Cloning requires native Git in the future desktop runtime.|Repository und Ziel eingeben. Klonen erfordert natives Git in der Desktop-Laufzeit.|Introduce repositorio y destino. La clonación requiere Git nativo en el entorno de escritorio.|Saisissez un dépôt et une destination. Le clonage nécessite Git natif dans l'environnement de bureau.|Inserisci repository e destinazione. La clonazione richiede Git nativo nel runtime desktop.|Informe repositório e destino. A clonagem exige Git nativo no runtime desktop.|リポジトリと保存先を入力してください。クローンにはデスクトップ環境のネイティブ Git が必要です。|输入仓库和目标路径。克隆需要桌面运行时中的原生 Git。|輸入儲存庫與目的地。複製需要桌面執行環境中的原生 Git。
Use an absolute Windows, macOS, or Linux path. Folder existence is not checked in the browser.|Absoluten Windows-, macOS- oder Linux-Pfad verwenden. Der Browser prüft nicht, ob der Ordner existiert.|Usa una ruta absoluta de Windows, macOS o Linux. El navegador no comprueba si existe la carpeta.|Utilisez un chemin absolu Windows, macOS ou Linux. Le navigateur ne vérifie pas l'existence du dossier.|Usa un percorso assoluto Windows, macOS o Linux. Il browser non verifica l'esistenza della cartella.|Use um caminho absoluto Windows, macOS ou Linux. O navegador não verifica se a pasta existe.|Windows、macOS、Linux の絶対パスを指定してください。ブラウザーではフォルダーの存在を確認しません。|使用 Windows、macOS 或 Linux 绝对路径。浏览器不检查文件夹是否存在。|使用 Windows、macOS 或 Linux 絕對路徑。瀏覽器不檢查資料夾是否存在。
Browser folder · absolute path unavailable|Browserordner · absoluter Pfad nicht verfügbar|Carpeta del navegador · ruta absoluta no disponible|Dossier navigateur · chemin absolu indisponible|Cartella browser · percorso assoluto non disponibile|Pasta do navegador · caminho absoluto indisponível|ブラウザーフォルダー・絶対パス取得不可|浏览器文件夹·绝对路径不可用|瀏覽器資料夾·絕對路徑無法取得
Choose a local folder to browse and edit its files.|Wählen Sie einen lokalen Ordner zum Durchsuchen und Bearbeiten.|Elige una carpeta local para explorar y editar archivos.|Choisissez un dossier local pour parcourir et modifier ses fichiers.|Scegli una cartella locale per esplorare e modificare i file.|Escolha uma pasta local para navegar e editar arquivos.|ローカルフォルダーを選んでファイルを参照・編集してください。|选择本地文件夹以浏览和编辑文件。|選取本機資料夾以瀏覽和編輯檔案。
Chrome and Edge can connect a local folder with your permission. Metadata and folder handles stay in this browser. Git cloning is not connected.|Chrome und Edge verbinden lokale Ordner mit Ihrer Erlaubnis. Metadaten und Ordnerzugriff bleiben im Browser. Git-Klonen ist nicht angebunden.|Chrome y Edge pueden conectar carpetas con tu permiso. Los metadatos y accesos permanecen en el navegador. La clonación Git no está conectada.|Chrome et Edge peuvent connecter un dossier avec votre autorisation. Métadonnées et accès restent dans ce navigateur. Le clonage Git n'est pas connecté.|Chrome ed Edge collegano cartelle con il tuo permesso. Metadati e accessi restano nel browser. La clonazione Git non è collegata.|Chrome e Edge conectam pastas com sua permissão. Metadados e acessos ficam neste navegador. A clonagem Git não está conectada.|Chrome と Edge は許可されたフォルダーに接続できます。情報とアクセス権はこのブラウザーに保存されます。Git クローンは未接続です。|Chrome 和 Edge 经许可可连接本地文件夹。元数据和文件夹句柄保留在浏览器中。Git 克隆尚未连接。|Chrome 和 Edge 經許可可連接本機資料夾。中繼資料與資料夾控制代碼保留在瀏覽器中。Git 複製尚未連接。
Connect a local folder to edit files, use the terminal and manage Git changes. Projects stay on this computer. Git cloning is not connected.|Lokalen Ordner verbinden, um Dateien, Terminal und Git zu nutzen. Projekte bleiben auf diesem Computer. Git-Klonen ist nicht angebunden.|Conecta una carpeta para editar, usar terminal y gestionar Git. Los proyectos permanecen en este equipo. La clonación Git no está conectada.|Connectez un dossier pour modifier les fichiers, utiliser le terminal et Git. Les projets restent sur cet ordinateur. Le clonage Git n'est pas connecté.|Collega una cartella per modificare file, usare terminale e Git. I progetti restano sul computer. La clonazione Git non è collegata.|Conecte uma pasta para editar arquivos, usar terminal e Git. Os projetos ficam neste computador. A clonagem Git não está conectada.|ローカルフォルダーを接続して編集・ターミナル・Git を使用できます。プロジェクトはこのコンピューターに保存されます。Git クローンは未接続です。|连接本地文件夹以编辑文件、使用终端和管理 Git。项目保留在此计算机。Git 克隆尚未连接。|連接本機資料夾以編輯檔案、使用終端機及管理 Git。專案保留在此電腦。Git 複製尚未連接。
UTF-8 text files up to 2 MiB. Changes are saved only when you choose Save.|UTF-8-Textdateien bis 2 MiB. Änderungen werden nur mit Speichern gesichert.|Archivos UTF-8 de hasta 2 MiB. Los cambios solo se guardan al elegir Guardar.|Fichiers texte UTF-8 jusqu'à 2 Mio. Les modifications sont enregistrées uniquement via Enregistrer.|File UTF-8 fino a 2 MiB. Le modifiche vengono salvate solo scegliendo Salva.|Arquivos UTF-8 de até 2 MiB. As alterações só são salvas ao escolher Salvar.|2 MiB 以下の UTF-8 テキストに対応。保存を選択したときだけ変更を保存します。|支持最大 2 MiB 的 UTF-8 文本文件。仅选择保存后才保存更改。|支援最大 2 MiB 的 UTF-8 文字檔。僅選擇儲存後才儲存變更。
Permission was denied. Request access or reconnect the folder.|Zugriff verweigert. Zugriff anfordern oder Ordner erneut verbinden.|Permiso denegado. Solicita acceso o reconecta la carpeta.|Accès refusé. Demandez l'accès ou reconnectez le dossier.|Permesso negato. Richiedi accesso o ricollega la cartella.|Permissão negada. Solicite acesso ou reconecte a pasta.|アクセスが拒否されました。許可を要求するかフォルダーを再接続してください。|权限被拒绝。请请求访问权限或重新连接文件夹。|權限遭拒。請要求存取權限或重新連接資料夾。
Requires File System Access API in desktop Chrome or Edge.|Erfordert File System Access API in Desktop-Chrome oder Edge.|Requiere File System Access API en Chrome o Edge de escritorio.|Nécessite File System Access API sur Chrome ou Edge pour ordinateur.|Richiede File System Access API in Chrome o Edge desktop.|Exige File System Access API no Chrome ou Edge desktop.|デスクトップ版 Chrome または Edge の File System Access API が必要です。|需要桌面 Chrome 或 Edge 的 File System Access API。|需要桌面 Chrome 或 Edge 的 File System Access API。
Select the project folder on your computer to reconnect.|Projektordner auf Ihrem Computer zum erneuten Verbinden wählen.|Selecciona la carpeta del proyecto para reconectar.|Sélectionnez le dossier du projet pour le reconnecter.|Seleziona la cartella del progetto per ricollegarla.|Selecione a pasta do projeto para reconectar.|再接続するプロジェクトフォルダーを選択してください。|请选择计算机上的项目文件夹以重新连接。|請選取電腦上的專案資料夾以重新連接。
No workspace folder is connected.|Kein Arbeitsbereichsordner verbunden.|Ninguna carpeta de trabajo conectada.|Aucun dossier de travail connecté.|Nessuna cartella di lavoro collegata.|Nenhuma pasta de trabalho conectada.|ワークスペースのフォルダーが未接続です。|未连接工作区文件夹。|未連接工作區資料夾。
Theme is shared across the application. Layout is saved separately for each project in this browser.|Das Design gilt für die gesamte Anwendung. Das Layout wird pro Projekt in diesem Browser gespeichert.|El tema se comparte en la aplicación. El diseño se guarda por proyecto en este navegador.|Le thème est partagé dans l'application. La disposition est enregistrée par projet dans ce navigateur.|Il tema è condiviso nell'app. Il layout è salvato per progetto nel browser.|O tema é compartilhado no aplicativo. O layout é salvo por projeto neste navegador.|テーマはアプリ全体で共有されます。レイアウトはこのブラウザーでプロジェクトごとに保存されます。|主题在应用内共享。布局在此浏览器中按项目保存。|主題在應用程式內共用。版面配置在此瀏覽器中依專案儲存。
File content search will be available after filesystem integration.|Inhaltssuche wird nach Dateisystemintegration verfügbar.|La búsqueda de contenido estará disponible tras integrar el sistema de archivos.|La recherche de contenu sera disponible après l'intégration du système de fichiers.|La ricerca nei file sarà disponibile dopo l'integrazione del file system.|A pesquisa de conteúdo estará disponível após integração do sistema de arquivos.|ファイル内容検索はファイルシステム統合後に利用できます。|文件内容搜索将在文件系统集成后可用。|檔案內容搜尋將在檔案系統整合後可用。
No files have been indexed.|Keine Dateien indiziert.|No se han indexado archivos.|Aucun fichier indexé.|Nessun file indicizzato.|Nenhum arquivo indexado.|ファイルはまだ索引化されていません。|尚未索引任何文件。|尚未建立任何檔案索引。
Search this workspace|Diesen Arbeitsbereich durchsuchen|Buscar en este espacio de trabajo|Rechercher dans cet espace de travail|Cerca in questa area di lavoro|Pesquisar neste espaço de trabalho|ワークスペースを検索|搜索此工作区|搜尋此工作區
Loading workspace layout…|Arbeitsbereichslayout wird geladen…|Cargando diseño del espacio de trabajo…|Chargement de la disposition…|Caricamento layout area di lavoro…|Carregando layout do espaço de trabalho…|ワークスペースのレイアウトを読み込み中…|正在加载工作区布局…|正在載入工作區版面配置…
Select a project from the Project Manager.|Projekt in der Projektverwaltung wählen.|Selecciona un proyecto en el gestor de proyectos.|Sélectionnez un projet dans le gestionnaire.|Seleziona un progetto dal gestore progetti.|Selecione um projeto no gerenciador.|プロジェクト管理でプロジェクトを選択してください。|从项目管理器选择项目。|從專案管理員選取專案。
The application could not be displayed. Retry to recover.|Anwendung konnte nicht angezeigt werden. Erneut versuchen.|No se pudo mostrar la aplicación. Reintenta para recuperar.|Impossible d'afficher l'application. Réessayez pour récupérer.|Impossibile mostrare l'applicazione. Riprova per recuperare.|Não foi possível exibir o aplicativo. Tente novamente.|アプリを表示できませんでした。再試行してください。|无法显示应用，请重试以恢复。|無法顯示應用程式，請重試以復原。
The page could not be displayed. Retry to load your projects again.|Seite konnte nicht angezeigt werden. Projekte erneut laden.|No se pudo mostrar la página. Reintenta cargar los proyectos.|Impossible d'afficher la page. Réessayez de charger vos projets.|Impossibile mostrare la pagina. Riprova a caricare i progetti.|Não foi possível exibir a página. Tente carregar os projetos novamente.|ページを表示できませんでした。プロジェクトを再読み込みしてください。|无法显示页面。请重试加载项目。|無法顯示頁面。請重試載入專案。
Commit becomes available in the desktop runtime.|Commit ist in der Desktop-Laufzeit verfügbar.|El commit está disponible en el entorno de escritorio.|Le commit est disponible dans l'environnement de bureau.|Il commit è disponibile nel runtime desktop.|O commit está disponível no runtime desktop.|コミットはデスクトップ環境で利用できます。|提交功能在桌面运行时中可用。|提交功能在桌面執行環境中可用。
Save the file to update Git changes. Git compares saved disk content; unsaved edits are preserved.|Datei speichern, um Git zu aktualisieren. Git vergleicht gespeicherte Inhalte; ungespeicherte Änderungen bleiben erhalten.|Guarda para actualizar Git. Git compara el contenido del disco y conserva cambios sin guardar.|Enregistrez pour actualiser Git. Git compare le contenu du disque ; les modifications non enregistrées sont préservées.|Salva per aggiornare Git. Git confronta il contenuto su disco; le modifiche non salvate restano.|Salve para atualizar Git. Git compara conteúdo do disco; alterações não salvas são preservadas.|Git の変更を更新するには保存してください。Git はディスク内容を比較し、未保存の編集は保持します。|保存文件以更新 Git 更改。Git 比较磁盘内容，未保存的编辑会保留。|儲存檔案以更新 Git 變更。Git 比較磁碟內容，未儲存的編輯會保留。
Status is out of date. Refresh before changing Git data.|Status ist veraltet. Vor Git-Änderungen aktualisieren.|Estado desactualizado. Actualiza antes de cambiar datos de Git.|État obsolète. Actualisez avant de modifier Git.|Stato obsoleto. Aggiorna prima di modificare Git.|Status desatualizado. Atualize antes de alterar Git.|状態が古くなっています。Git 操作の前に更新してください。|状态已过期。请先刷新再更改 Git 数据。|狀態已過期。請先重新整理再變更 Git 資料。
Original ↔ Modified · Read only · Saved repository content|Original ↔ Geändert · Schreibgeschützt · Gespeicherter Repository-Inhalt|Original ↔ Modificado · Solo lectura · Contenido guardado del repositorio|Original ↔ Modifié · Lecture seule · Contenu enregistré du dépôt|Originale ↔ Modificato · Sola lettura · Contenuto salvato del repository|Original ↔ Modificado · Somente leitura · Conteúdo salvo do repositório|元の内容 ↔ 変更後・読み取り専用・保存済みリポジトリ内容|原始 ↔ 修改后·只读·已保存仓库内容|原始 ↔ 修改後·唯讀·已儲存儲存庫內容
 · Unsaved editor changes are not included.| · Ungespeicherte Editoränderungen sind nicht enthalten.| · No incluye cambios sin guardar del editor.| · Les modifications non enregistrées sont exclues.| · Le modifiche non salvate sono escluse.| · Alterações não salvas do editor são excluídas.|・エディターの未保存変更は含まれません。|·不包含编辑器未保存更改。|·不含編輯器未儲存變更。
No configurations yet. Add an executable and its arguments to prepare a run.|Keine Konfigurationen. Programm und Argumente hinzufügen.|Sin configuraciones. Añade un ejecutable y argumentos para ejecutar.|Aucune configuration. Ajoutez un exécutable et ses arguments.|Nessuna configurazione. Aggiungi eseguibile e argomenti.|Sem configurações. Adicione executável e argumentos.|構成がありません。実行ファイルと引数を追加してください。|暂无配置。请添加可执行文件及其参数以准备运行。|尚無設定。請新增執行檔與引數以準備執行。
Select a configuration to begin.|Konfiguration zum Starten wählen.|Selecciona una configuración para empezar.|Sélectionnez une configuration pour commencer.|Seleziona una configurazione per iniziare.|Selecione uma configuração para começar.|構成を選択して開始してください。|选择配置以开始。|選取設定以開始。
Each array item is one argument. No shell command is assembled.|Jedes Array-Element ist ein Argument. Kein Shell-Befehl wird zusammengesetzt.|Cada elemento es un argumento. No se construyen comandos de shell.|Chaque élément est un argument. Aucune commande shell n'est assemblée.|Ogni elemento è un argomento. Non si compongono comandi shell.|Cada item é um argumento. Nenhum comando shell é montado.|配列の各要素は一つの引数です。シェルコマンドは組み立てません。|数组每项为一个参数。不会拼接 Shell 命令。|陣列每項為一個引數。不會組合 Shell 命令。
Relative to the connected workspace. “.” uses its root.|Relativ zum Arbeitsbereich. „.“ verwendet dessen Root.|Relativo al espacio de trabajo. “.” usa su raíz.|Relatif à l'espace de travail. « . » utilise sa racine.|Relativo all'area di lavoro. “.” usa la radice.|Relativo ao espaço de trabalho. “.” usa a raiz.|接続したワークスペースからの相対パス。「.」はルートを使用します。|相对于已连接工作区。“.” 使用根目录。|相對於已連接工作區。「.」使用根目錄。
Stored locally with the configuration. This is not a secret vault.|Lokal mit der Konfiguration gespeichert. Kein Geheimnisspeicher.|Guardado localmente con la configuración. No es una bóveda de secretos.|Enregistré localement avec la configuration. Ce n'est pas un coffre de secrets.|Salvato localmente con la configurazione. Non è un archivio segreti.|Salvo localmente com a configuração. Não é um cofre de segredos.|構成とともにローカル保存します。シークレット保管庫ではありません。|随配置保存在本地。这不是密钥保险库。|隨設定儲存在本機。這不是祕密保管庫。
No task output. Studio run messages and non-interactive task output appear here.|Keine Aufgabenausgabe. Studio-Meldungen und nicht interaktive Ausgabe erscheinen hier.|Sin salida de tareas. Aquí aparecen mensajes de Studio y salida no interactiva.|Aucune sortie de tâche. Les messages Studio et sorties non interactives apparaissent ici.|Nessun output. Qui compaiono messaggi Studio e output non interattivi.|Sem saída. Mensagens Studio e saída não interativa aparecem aqui.|タスク出力がありません。Studio の実行メッセージと非対話タスク出力を表示します。|无任务输出。Studio 运行信息和非交互任务输出将显示在此。|無工作輸出。Studio 執行訊息與非互動工作輸出將顯示於此。
Older output discarded at the retention limit.|Ältere Ausgabe am Aufbewahrungslimit verworfen.|Salida antigua descartada por límite de retención.|Anciennes sorties supprimées à la limite de rétention.|Output precedente scartato al limite di conservazione.|Saída antiga descartada no limite de retenção.|保持上限に達した古い出力は破棄されました。|旧输出已因保留上限被丢弃。|舊輸出已因保留上限被捨棄。
No output received.|Keine Ausgabe empfangen.|No se recibió salida.|Aucune sortie reçue.|Nessun output ricevuto.|Nenhuma saída recebida.|出力はまだありません。|未收到输出。|未收到輸出。
No output for this step.|Keine Ausgabe für diesen Schritt.|Sin salida para este paso.|Aucune sortie pour cette étape.|Nessun output per questo passaggio.|Sem saída nesta etapa.|このステップの出力はありません。|此步骤无输出。|此步驟無輸出。
Connect the project folder to inspect .tastedev.|Projektordner verbinden, um .tastedev zu prüfen.|Conecta la carpeta del proyecto para inspeccionar .tastedev.|Connectez le dossier du projet pour inspecter .tastedev.|Collega la cartella del progetto per esaminare .tastedev.|Conecte a pasta do projeto para inspecionar .tastedev.|.tastedev を確認するにはプロジェクトフォルダーを接続してください。|连接项目文件夹以检查 .tastedev。|連接專案資料夾以檢查 .tastedev。
This project has no .tastedev/project.yml. Local IDE features remain available.|Kein .tastedev/project.yml vorhanden. Lokale IDE-Funktionen bleiben verfügbar.|No existe .tastedev/project.yml. Las funciones IDE locales siguen disponibles.|Aucun .tastedev/project.yml. Les fonctions IDE locales restent disponibles.|Manca .tastedev/project.yml. Le funzioni IDE locali restano disponibili.|Não há .tastedev/project.yml. Os recursos IDE locais permanecem disponíveis.|.tastedev/project.yml がありません。ローカル IDE 機能は利用できます。|此项目没有 .tastedev/project.yml。本地 IDE 功能仍可用。|此專案沒有 .tastedev/project.yml。本機 IDE 功能仍可使用。
Creates a definition without executable tasks.|Erstellt eine Definition ohne ausführbare Aufgaben.|Crea una definición sin tareas ejecutables.|Crée une définition sans tâches exécutables.|Crea una definizione senza attività eseguibili.|Cria definição sem tarefas executáveis.|実行タスクを含まない定義を作成します。|创建不含可执行任务的定义。|建立不含可執行工作的定義。
Optional files can be created in Explorer.|Optionale Dateien können im Explorer erstellt werden.|Los archivos opcionales pueden crearse en el explorador.|Les fichiers facultatifs peuvent être créés dans l'explorateur.|I file facoltativi possono essere creati in Esplora file.|Arquivos opcionais podem ser criados no explorador.|任意のファイルはエクスプローラーで作成できます。|可在资源管理器创建可选文件。|可在檔案總管建立選填檔案。
Fix the definition, save, then reload.|Definition korrigieren, speichern und neu laden.|Corrige la definición, guarda y recarga.|Corrigez la définition, enregistrez puis rechargez.|Correggi la definizione, salva e ricarica.|Corrija a definição, salve e recarregue.|定義を修正して保存し、再読み込みしてください。|修复定义、保存后重新加载。|修正定義、儲存後重新載入。
Save Protocol edits before queuing. The view reflects saved files.|Protocol vor dem Einreihen speichern. Die Ansicht zeigt gespeicherte Dateien.|Guarda el protocolo antes de encolar. La vista refleja archivos guardados.|Enregistrez le protocole avant la mise en file. La vue reflète les fichiers enregistrés.|Salva il protocollo prima di accodare. La vista riflette i file salvati.|Salve o protocolo antes de enfileirar. A visualização reflete arquivos salvos.|キューに追加する前に Protocol を保存してください。保存済み内容を表示しています。|入队前请保存协议编辑。视图反映已保存文件。|加入佇列前請儲存協定編輯。檢視反映已儲存檔案。
No source provider declared. Tasks run in an empty Agent workspace.|Kein Quellanbieter definiert. Aufgaben laufen in leerem Agent-Arbeitsbereich.|Sin proveedor de código declarado. Las tareas usan un espacio de agente vacío.|Aucun fournisseur de source déclaré. Les tâches utilisent un espace agent vide.|Nessun provider sorgente. Le attività usano un'area agente vuota.|Sem provedor de código declarado. Tarefas usam espaço de agente vazio.|ソースプロバイダー未設定。タスクは空のエージェント領域で実行します。|未声明源代码提供者。任务在空代理工作区运行。|未宣告原始碼提供者。工作在空白代理程式工作區執行。
Inspect registered execution environments and their capabilities.|Registrierte Umgebungen und Fähigkeiten prüfen.|Inspecciona entornos registrados y capacidades.|Inspectez les environnements enregistrés et leurs capacités.|Esamina ambienti registrati e capacità.|Inspecione ambientes registrados e recursos.|登録された実行環境と機能を確認します。|查看注册的执行环境及其能力。|檢視已註冊執行環境與功能。
Inspect run attempts, ordered steps and recorded results.|Versuche, geordnete Schritte und Ergebnisse prüfen.|Inspecciona intentos, pasos ordenados y resultados.|Inspectez les tentatives, étapes et résultats enregistrés.|Esamina tentativi, passaggi e risultati registrati.|Inspecione tentativas, etapas e resultados registrados.|試行・実行ステップ・記録済み結果を確認します。|查看运行尝试、有序步骤及记录结果。|檢視執行嘗試、有序步驟及紀錄結果。
Create and inspect work requests for this project.|Arbeitsanfragen für dieses Projekt erstellen und prüfen.|Crea e inspecciona solicitudes de trabajo del proyecto.|Créez et inspectez les demandes de travail du projet.|Crea ed esamina richieste di lavoro del progetto.|Crie e inspecione solicitações de trabalho do projeto.|このプロジェクトの作業リクエストを作成・確認します。|创建和查看此项目的工作请求。|建立與檢視此專案的工作要求。
Record an execution environment. Declared capabilities are unverified until an agent connects.|Umgebung registrieren. Fähigkeiten bleiben bis zur Agent-Verbindung ungeprüft.|Registra un entorno. Las capacidades no se verifican hasta conectar un agente.|Enregistrez un environnement. Les capacités restent non vérifiées avant connexion d'un agent.|Registra un ambiente. Le capacità restano non verificate finché l'agente non si collega.|Registre um ambiente. Os recursos não são verificados até o agente conectar.|実行環境を登録します。機能はエージェント接続まで未検証です。|注册执行环境。代理连接前，声明能力未经验证。|註冊執行環境。代理程式連接前，宣告功能未經驗證。
Status and last seen are reported by Core. Capability probes describe the connected agent.|Status und letzter Kontakt kommen von Core. Fähigkeiten beschreiben den verbundenen Agent.|Core informa estado y último contacto. Las capacidades describen el agente conectado.|Core indique l'état et le dernier contact. Les capacités décrivent l'agent connecté.|Core riporta stato e ultimo contatto. Le capacità descrivono l'agente collegato.|Core informa status e último contato. Os recursos descrevem o agente conectado.|状態と最終接続は Core が報告します。機能確認は接続中のエージェントの情報です。|状态和最后在线由 Core 报告。能力探测描述已连接代理。|狀態與最後上線由 Core 回報。功能探測描述已連接代理程式。
Connect to Core in Agents. Local IDE features remain available.|In Agents mit Core verbinden. Lokale IDE-Funktionen bleiben verfügbar.|Conecta Core en Agentes. Las funciones IDE locales siguen disponibles.|Connectez Core dans Agents. Les fonctions IDE locales restent disponibles.|Collega Core in Agenti. Le funzioni IDE locali restano disponibili.|Conecte Core em Agentes. Recursos IDE locais permanecem disponíveis.|エージェント画面で Core に接続してください。ローカル IDE 機能は利用できます。|在代理页面连接 Core。本地 IDE 功能仍可用。|在代理程式頁面連接 Core。本機 IDE 功能仍可使用。
Connect to Core in Agents to queue a task.|In Agents mit Core verbinden, um Aufgaben einzureihen.|Conecta Core en Agentes para encolar tareas.|Connectez Core dans Agents pour mettre une tâche en file.|Collega Core in Agenti per accodare attività.|Conecte Core em Agentes para enfileirar tarefas.|タスクをキューに追加するにはエージェント画面で Core に接続してください。|在代理页面连接 Core 以将任务入队。|在代理程式頁面連接 Core 以將工作加入佇列。
Core retains state while its server process runs. Reconnect after reloading Studio.|Core hält Zustand solange der Server läuft. Nach Studio-Neuladen erneut verbinden.|Core mantiene el estado mientras funciona el servidor. Reconecta tras recargar Studio.|Core conserve l'état tant que le serveur fonctionne. Reconnectez après rechargement de Studio.|Core conserva lo stato mentre il server è attivo. Ricollega dopo il reload di Studio.|Core mantém estado enquanto o servidor funciona. Reconecte após recarregar Studio.|Core の状態はサーバー稼働中保持されます。Studio を再読み込みしたら再接続してください。|Core 在服务器运行期间保留状态。重新加载 Studio 后请重新连接。|Core 在伺服器運行期間保留狀態。重新載入 Studio 後請重新連接。
Local Core state resets on reload. Connect to Core for actual Agent execution.|Lokaler Core-Zustand wird beim Neuladen zurückgesetzt. Für echte Agent-Ausführung Core verbinden.|El estado Core local se reinicia al recargar. Conecta Core para ejecución real de agentes.|L'état Core local est réinitialisé au rechargement. Connectez Core pour exécuter un agent réel.|Lo stato Core locale si resetta al reload. Collega Core per eseguire agenti reali.|O estado Core local reinicia ao recarregar. Conecte Core para execução real de agentes.|ローカル Core の状態は再読み込みでリセットされます。実際のエージェント実行には Core 接続が必要です。|本地 Core 状态在重新加载时重置。连接 Core 以进行实际代理执行。|本機 Core 狀態在重新載入時重設。連接 Core 以進行實際代理程式執行。
No agents registered.|Keine Agents registriert.|No hay agentes registrados.|Aucun agent enregistré.|Nessun agente registrato.|Nenhum agente registrado.|登録されたエージェントはありません。|未注册代理。|未註冊代理程式。
No jobs queued.|Keine Jobs eingereiht.|Sin trabajos en cola.|Aucun travail en file.|Nessuna attività in coda.|Nenhum trabalho na fila.|キューにジョブはありません。|队列中无作业。|佇列中無作業。
No runs recorded.|Keine Ausführungen aufgezeichnet.|Sin ejecuciones registradas.|Aucune exécution enregistrée.|Nessuna esecuzione registrata.|Nenhuma execução registrada.|実行記録はありません。|无运行记录。|無執行紀錄。
No compatible agent available.|Kein kompatibler Agent verfügbar.|No hay agente compatible.|Aucun agent compatible disponible.|Nessun agente compatibile.|Nenhum agente compatível.|互換性のあるエージェントがありません。|无可用兼容代理。|無可用相容代理程式。
Select an agent to view its details.|Agent für Details wählen.|Selecciona un agente para ver detalles.|Sélectionnez un agent pour ses détails.|Seleziona un agente per i dettagli.|Selecione um agente para ver detalhes.|エージェントを選択して詳細を表示してください。|选择代理以查看详情。|選取代理程式以檢視詳細資料。
Select a job to inspect its requirements.|Job zum Prüfen der Anforderungen wählen.|Selecciona un trabajo para ver requisitos.|Sélectionnez un travail pour ses exigences.|Seleziona un'attività per i requisiti.|Selecione um trabalho para ver requisitos.|ジョブを選択して要件を確認してください。|选择作业以查看要求。|選取作業以檢視需求。
Select a run to inspect its steps and result.|Ausführung für Schritte und Ergebnis wählen.|Selecciona una ejecución para ver pasos y resultado.|Sélectionnez une exécution pour ses étapes et résultats.|Seleziona un'esecuzione per passaggi e risultato.|Selecione uma execução para etapas e resultado.|実行を選択してステップと結果を確認してください。|选择运行以查看步骤和结果。|選取執行以檢視步驟與結果。
Assign the queued job to a compatible Agent to execute it.|Eingereihten Job einem kompatiblen Agent zur Ausführung zuweisen.|Asigna el trabajo a un agente compatible para ejecutarlo.|Affectez le travail en file à un agent compatible.|Assegna l'attività a un agente compatibile per eseguirla.|Atribua o trabalho a um agente compatível para executar.|キューのジョブを互換エージェントに割り当てて実行してください。|将队列作业分配给兼容代理以执行。|將佇列作業指派給相容代理程式以執行。
Compatible agent connected. Assignment sends this command for execution.|Kompatibler Agent verbunden. Zuweisung sendet den Befehl zur Ausführung.|Agente compatible conectado. La asignación envía el comando para ejecutar.|Agent compatible connecté. L'affectation envoie la commande pour exécution.|Agente compatibile collegato. L'assegnazione invia il comando per eseguirlo.|Agente compatível conectado. A atribuição envia o comando para execução.|互換エージェントが接続中です。割り当てるとコマンドを送信して実行します。|兼容代理已连接。分配将发送命令以执行。|相容代理程式已連接。指派將傳送命令以執行。
Compatible registration available. Assignment does not start execution.|Kompatible Registrierung vorhanden. Zuweisung startet keine Ausführung.|Registro compatible disponible. Asignar no inicia ejecución.|Enregistrement compatible disponible. L'affectation ne lance pas l'exécution.|Registrazione compatibile disponibile. L'assegnazione non avvia esecuzione.|Registro compatível disponível. Atribuir não inicia execução.|互換登録があります。割り当てだけでは実行を開始しません。|存在兼容注册。分配不会开始执行。|存在相容註冊。指派不會開始執行。
Remote agent transport is not connected. Registration does not establish a connection.|Remote-Agent-Transport nicht verbunden. Registrierung stellt keine Verbindung her.|Transporte remoto no conectado. Registrar no establece conexión.|Transport agent distant non connecté. L'enregistrement n'établit pas de connexion.|Trasporto agente remoto non collegato. Registrare non crea connessione.|Transporte remoto não conectado. Registrar não estabelece conexão.|リモートエージェントの通信は未接続です。登録では接続されません。|远程代理传输未连接。注册不会建立连接。|遠端代理程式傳輸未連接。註冊不會建立連接。
No remote transport is connected.|Kein Remote-Transport verbunden.|Ningún transporte remoto conectado.|Aucun transport distant connecté.|Nessun trasporto remoto collegato.|Nenhum transporte remoto conectado.|リモート通信は未接続です。|未连接远程传输。|未連接遠端傳輸。
Live Core execution records.|Live-Core-Ausführungsaufzeichnungen.|Registros de ejecución Core en vivo.|Enregistrements d'exécution Core en direct.|Registri esecuzione Core dal vivo.|Registros de execução Core ao vivo.|Core のライブ実行記録。|实时 Core 执行记录。|即時 Core 執行紀錄。
Execution history is saved by Core. Connection credentials stay in memory.|Core speichert den Ausführungsverlauf. Verbindungsdaten bleiben im Speicher.|Core guarda el historial de ejecución. Las credenciales de conexión permanecen en memoria.|Core conserve l’historique d’exécution. Les identifiants de connexion restent en mémoire.|Core salva la cronologia di esecuzione. Le credenziali di connessione restano in memoria.|O Core salva o histórico de execução. As credenciais de conexão ficam na memória.|Core は実行履歴を保存します。接続認証情報はメモリ内に保持します。|Core 保存执行历史。连接凭据保留在内存中。|Core 儲存執行歷程。連線認證資料保留在記憶體中。
This connection is temporary. Reconnect after reloading.|Diese Verbindung ist temporär. Nach Neuladen erneut verbinden.|Conexión temporal. Reconecta tras recargar.|Connexion temporaire. Reconnectez après rechargement.|Connessione temporanea. Ricollega dopo il reload.|Conexão temporária. Reconecte após recarregar.|一時的な接続です。再読み込み後に再接続してください。|此连接为临时连接。重新加载后请重新连接。|此連接為暫時連接。重新載入後請重新連接。
No result reported yet.|Noch kein Ergebnis gemeldet.|Aún no se informa resultado.|Aucun résultat signalé.|Nessun risultato riportato.|Nenhum resultado informado.|結果はまだ報告されていません。|尚未报告结果。|尚未回報結果。`;
export const guidance=Object.fromEntries(additionalLanguages.map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const cells=row.split('|');if(cells.length!==9)throw new Error('Invalid guidance translation: '+cells[0]);return[cells[0],cells[index+1]];}))]));
