import {languages} from './core.ts';
// English IDs followed by ko/de/es/fr/it/pt/ja/zh/zh-hant; external data is not translated.
const rows=`Enter the configured Studio token.|Core 설정의 Studio 토큰을 입력하세요.|Geben Sie das Studio-Token aus der Core-Konfiguration ein.|Introduzca el token de Studio de la configuración de Core.|Saisissez le jeton Studio configuré dans Core.|Inserisci il token Studio configurato in Core.|Insira o token Studio configurado no Core.|Core 設定の Studio トークンを入力してください。|请输入 Core 配置中的 Studio 令牌。|請輸入 Core 設定中的 Studio 權杖。
Back|이전|Zurück|Atrás|Retour|Indietro|Voltar|戻る|上一步|上一步
Next|다음|Weiter|Siguiente|Suivant|Avanti|Próximo|次へ|下一步|下一步
Source changed since the proposal. Review your changes and reconcile the file before retrying. Your content is preserved.|제안 이후 소스가 변경되었습니다. 기존 변경을 검토하고 파일을 조정한 뒤 재시도하세요. 내용은 보존됩니다.|Quelltext seit dem Vorschlag geändert. Änderungen prüfen und Datei vor erneutem Versuch abgleichen. Ihr Inhalt bleibt erhalten.|El código cambió desde la propuesta. Revise sus cambios y concilie el archivo antes de reintentar. Su contenido se conserva.|Le code a changé depuis la proposition. Vérifiez vos modifications et réconciliez le fichier avant de réessayer. Votre contenu est conservé.|Il codice è cambiato dopo la proposta. Controlla le modifiche e riconcilia il file prima di riprovare. Il contenuto è preservato.|O código mudou após a proposta. Revise suas alterações e reconcilie o arquivo antes de tentar novamente. Seu conteúdo é preservado.|提案後にソースが変更されました。変更を確認してファイルを調整してから再試行してください。内容は保持されています。|提案后源代码已更改。请检查并协调文件后重试。您的内容已保留。|提案後原始碼已變更。請檢查並協調檔案後重試。您的內容已保留。
Save or close your unsaved editor changes before retrying. Your editor content is preserved.|편집기의 미저장 변경을 저장하거나 닫은 뒤 재시도하세요. 편집 내용은 보존됩니다.|Ungespeicherte Änderungen vor erneutem Versuch speichern oder schließen. Ihr Editorinhalt bleibt erhalten.|Guarde o cierre los cambios sin guardar antes de reintentar. El contenido del editor se conserva.|Enregistrez ou fermez les modifications non enregistrées avant de réessayer. Votre contenu est conservé.|Salva o chiudi le modifiche non salvate prima di riprovare. Il contenuto dell’editor è preservato.|Salve ou feche as alterações não salvas antes de tentar novamente. O conteúdo do editor é preservado.|未保存の編集を保存するか閉じてから再試行してください。編集内容は保持されています。|请保存或关闭未保存的编辑后重试。编辑内容已保留。|請儲存或關閉未儲存的編輯後重試。編輯內容已保留。
recovery-required|복구 필요|Wiederherstellung erforderlich|Recuperación necesaria|Récupération requise|Ripristino necessario|Recuperação necessária|復旧が必要|需要恢复|需要復原
Not connected|연결되지 않음|Nicht verbunden|Sin conexión|Non connecté|Non connesso|Desconectado|未接続|未连接|未連線
Connecting to Core…|Core에 연결 중…|Verbindung mit Core…|Conectando a Core…|Connexion à Core…|Connessione a Core…|Conectando ao Core…|Core に接続中…|正在连接 Core…|正在連線 Core…
Connected to Core|Core에 연결됨|Mit Core verbunden|Conectado a Core|Connecté à Core|Connesso a Core|Conectado ao Core|Core に接続済み|已连接 Core|已連線 Core
Core unavailable. Retrying…|Core에 접근할 수 없습니다. 재시도 중…|Core nicht verfügbar. Erneuter Versuch…|Core no disponible. Reintentando…|Core indisponible. Nouvelle tentative…|Core non disponibile. Nuovo tentativo…|Core indisponível. Tentando novamente…|Core を利用できません。再試行中…|Core 不可用。正在重试…|Core 無法使用。正在重試…
Core disconnected. Retrying…|Core 연결이 끊어졌습니다. 재시도 중…|Core getrennt. Erneuter Versuch…|Core desconectado. Reintentando…|Core déconnecté. Nouvelle tentative…|Core disconnesso. Nuovo tentativo…|Core desconectado. Tentando novamente…|Core が切断されました。再試行中…|Core 已断开。正在重试…|Core 已中斷。正在重試…
Authentication failed.|인증에 실패했습니다.|Authentifizierung fehlgeschlagen.|La autenticación falló.|Échec de l’authentification.|Autenticazione non riuscita.|Falha na autenticação.|認証に失敗しました。|身份验证失败。|驗證失敗。
Core protocol mismatch.|Core 프로토콜이 일치하지 않습니다.|Core-Protokoll stimmt nicht überein.|El protocolo Core no coincide.|Le protocole Core ne correspond pas.|Il protocollo Core non corrisponde.|O protocolo Core não corresponde.|Core のプロトコルが一致しません。|Core 协议不匹配。|Core 通訊協定不符。
Invalid Core response. Reconnect to retry.|Core 응답이 잘못되었습니다. 다시 연결하세요.|Ungültige Core-Antwort. Erneut verbinden.|Respuesta Core inválida. Vuelva a conectar.|Réponse Core invalide. Reconnectez-vous.|Risposta Core non valida. Riconnetti.|Resposta Core inválida. Reconecte.|Core の応答が無効です。再接続してください。|Core 响应无效。请重新连接。|Core 回應無效。請重新連線。
Core rejected the connection.|Core가 연결을 거부했습니다.|Core hat die Verbindung abgelehnt.|Core rechazó la conexión.|Core a refusé la connexion.|Core ha rifiutato la connessione.|Core recusou a conexão.|Core が接続を拒否しました。|Core 拒绝了连接。|Core 拒絕了連線。
Core response exceeds limit.|Core 응답이 한도를 초과했습니다.|Core-Antwort überschreitet das Limit.|La respuesta Core supera el límite.|La réponse Core dépasse la limite.|La risposta Core supera il limite.|A resposta Core excede o limite.|Core の応答が上限を超えています。|Core 响应超过限制。|Core 回應超過限制。
Invalid Core snapshot.|Core 상태 정보가 잘못되었습니다.|Ungültiger Core-Zustand.|Estado Core inválido.|État Core invalide.|Stato Core non valido.|Estado Core inválido.|Core の状態情報が無効です。|Core 状态信息无效。|Core 狀態資訊無效。
Core disconnected; refresh state before retrying.|Core 연결이 끊어졌습니다. 상태를 새로 확인한 뒤 재시도하세요.|Core getrennt; vor erneutem Versuch Zustand aktualisieren.|Core desconectado; actualice el estado antes de reintentar.|Core déconnecté ; actualisez l’état avant de réessayer.|Core disconnesso; aggiorna lo stato prima di riprovare.|Core desconectado; atualize o estado antes de tentar novamente.|Core が切断されました。状態を更新してから再試行してください。|Core 已断开；重试前请刷新状态。|Core 已中斷；重試前請重新整理狀態。
Core request timed out. Inspect state before retrying.|Core 요청 시간이 초과되었습니다. 상태를 확인한 뒤 재시도하세요.|Core-Anfrage abgelaufen. Vor erneutem Versuch Zustand prüfen.|La solicitud Core expiró. Consulte el estado antes de reintentar.|La demande Core a expiré. Vérifiez l’état avant de réessayer.|Richiesta Core scaduta. Controlla lo stato prima di riprovare.|A solicitação Core expirou. Verifique o estado antes de tentar novamente.|Core の要求がタイムアウトしました。状態を確認してから再試行してください。|Core 请求超时。重试前请检查状态。|Core 要求逾時。重試前請檢查狀態。
File editor|파일 편집기|Dateieditor|Editor de archivos|Éditeur de fichiers|Editor di file|Editor de arquivos|ファイルエディター|文件编辑器|檔案編輯器
Inspect previous request|이전 요청 확인|Vorherige Anfrage prüfen|Consultar solicitud anterior|Inspecter la demande précédente|Controlla richiesta precedente|Verificar solicitação anterior|前のリクエストを確認|检查先前请求|檢查先前要求
Inspect the refreshed Queue, then retry the same request.|새로 받은 대기열을 확인한 뒤 같은 요청을 재시도하세요.|Aktualisierte Warteschlange prüfen und dieselbe Anfrage erneut versuchen.|Revise la cola actualizada y reintente la misma solicitud.|Vérifiez la file actualisée puis réessayez la même demande.|Controlla la coda aggiornata e riprova la stessa richiesta.|Verifique a fila atualizada e tente a mesma solicitação novamente.|更新されたキューを確認し、同じリクエストを再試行してください。|请检查刷新后的队列，然后重试同一请求。|請檢查更新後的佇列，再重試同一要求。
Workflow timeline|작업 타임라인|Workflow-Zeitleiste|Cronología del flujo|Chronologie du flux|Cronologia del flusso|Linha do tempo do fluxo|作業タイムライン|工作流程时间线|工作流程時間軸
Older history has no complete event timeline.|이전 이력에는 전체 이벤트 기록이 없습니다.|Ältere Historie enthält keine vollständige Ereignisfolge.|El historial anterior no tiene una cronología completa.|L’ancien historique n’a pas de chronologie complète.|La cronologia precedente non contiene tutti gli eventi.|O histórico anterior não contém todos os eventos.|以前の履歴には完全なイベント記録がありません。|旧历史记录没有完整的事件时间线。|舊歷史紀錄沒有完整的事件時間軸。
Original Run|원본 Run|Ursprünglicher Run|Run original|Run d’origine|Run originale|Run original|元の Run|原始 Run|原始 Run
Original failure|원본 실패|Ursprünglicher Fehler|Fallo original|Échec initial|Errore originale|Falha original|元の失敗|原始失败|原始失敗
Approval|승인|Genehmigung|Aprobación|Approbation|Approvazione|Aprovação|承認|批准|核准
Patch|패치|Patch|Parche|Correctif|Patch|Patch|パッチ|补丁|修補
Validation|검증|Validierung|Validación|Validation|Convalida|Validação|検証|验证|驗證
Retest|재테스트|Erneuter Test|Reprueba|Nouveau test|Nuovo test|Novo teste|再テスト|重新测试|重新測試
Recovery|복구|Wiederherstellung|Recuperación|Récupération|Ripristino|Recuperação|復旧|恢复|復原
Connection guide|연결 안내|Verbindungsanleitung|Guía de conexión|Guide de connexion|Guida alla connessione|Guia de conexão|接続ガイド|连接指南|連線指南
Connection mode|연결 방식|Verbindungsmodus|Modo de conexión|Mode de connexion|Modalità di connessione|Modo de conexão|接続モード|连接模式|連線模式
Local Core|로컬 Core|Lokaler Core|Core local|Core local|Core locale|Core local|ローカル Core|本地 Core|本機 Core
Team Core|팀 Core|Team-Core|Core del equipo|Core de l’équipe|Core del team|Core da equipe|チーム Core|团队 Core|團隊 Core
Retry connection|연결 재시도|Verbindung erneut versuchen|Reintentar conexión|Réessayer la connexion|Riprova connessione|Tentar conexão novamente|接続を再試行|重试连接|重試連線
Agent capabilities|Agent 실행 기능|Agent-Fähigkeiten|Capacidades del Agent|Capacités de l’Agent|Funzionalità dell’Agent|Recursos do Agent|Agent の実行機能|Agent 执行能力|Agent 執行能力
Check the Studio token.|Studio 토큰을 확인하세요.|Studio-Token prüfen.|Compruebe el token de Studio.|Vérifiez le jeton Studio.|Controlla il token Studio.|Verifique o token do Studio.|Studio トークンを確認してください。|请检查 Studio 令牌。|請檢查 Studio 權杖。
Check the Core protocol version.|Core 프로토콜 버전을 확인하세요.|Core-Protokollversion prüfen.|Compruebe la versión del protocolo Core.|Vérifiez la version du protocole Core.|Controlla la versione del protocollo Core.|Verifique a versão do protocolo Core.|Core プロトコルのバージョンを確認してください。|请检查 Core 协议版本。|請檢查 Core 通訊協定版本。
Connected Agent capabilities are reported.|연결된 Agent의 실행 기능이 보고되었습니다.|Fähigkeiten des verbundenen Agents wurden gemeldet.|Se informaron las capacidades del Agent conectado.|Les capacités de l’Agent connecté sont disponibles.|Le funzionalità dell’Agent connesso sono disponibili.|Os recursos do Agent conectado foram informados.|接続された Agent の実行機能が報告されています。|已报告连接的 Agent 执行能力。|已回報連線 Agent 的執行能力。
Start an Agent connected to this Core.|이 Core에 연결할 Agent를 시작하세요.|Einen mit diesem Core verbundenen Agent starten.|Inicie un Agent conectado a este Core.|Démarrez un Agent connecté à ce Core.|Avvia un Agent connesso a questo Core.|Inicie um Agent conectado a este Core.|この Core に接続する Agent を起動してください。|请启动连接此 Core 的 Agent。|請啟動連線至此 Core 的 Agent。
Loading project definition…|프로젝트 정의를 읽는 중…|Projektdefinition wird geladen…|Cargando definición del proyecto…|Chargement de la définition du projet…|Caricamento della definizione del progetto…|Carregando definição do projeto…|プロジェクト定義を読み込み中…|正在加载项目定义…|正在載入專案定義…
Open the project definition and resolve its reported issues.|프로젝트 정의를 열고 표시된 문제를 해결하세요.|Projektdefinition öffnen und gemeldete Probleme beheben.|Abra la definición del proyecto y resuelva los problemas indicados.|Ouvrez la définition du projet et corrigez les problèmes signalés.|Apri la definizione del progetto e risolvi i problemi segnalati.|Abra a definição do projeto e resolva os problemas informados.|プロジェクト定義を開いて報告された問題を解決してください。|请打开项目定义并解决报告的问题。|請開啟專案定義並解決回報的問題。
Reload project definition|프로젝트 정의 다시 읽기|Projektdefinition neu laden|Recargar definición del proyecto|Recharger la définition du projet|Ricarica definizione del progetto|Recarregar definição do projeto|プロジェクト定義を再読み込み|重新加载项目定义|重新載入專案定義
Start Core locally, then connect an Agent to the same Core.|로컬에서 Core를 시작한 뒤 Agent를 같은 Core에 연결하세요.|Core lokal starten und einen Agent mit demselben Core verbinden.|Inicie Core localmente y conecte un Agent al mismo Core.|Démarrez Core localement puis connectez un Agent au même Core.|Avvia Core localmente e collega un Agent allo stesso Core.|Inicie o Core localmente e conecte um Agent ao mesmo Core.|ローカルで Core を起動し、Agent を同じ Core に接続してください。|请在本地启动 Core，然后将 Agent 连接到同一 Core。|請在本機啟動 Core，再將 Agent 連線至同一 Core。
Enter the address and Studio token supplied by your team administrator.|팀 관리자가 제공한 주소와 Studio 토큰을 입력하세요.|Adresse und Studio-Token vom Teamadministrator eingeben.|Introduzca la dirección y el token de Studio de su administrador.|Saisissez l’adresse et le jeton Studio fournis par votre administrateur.|Inserisci l’indirizzo e il token Studio forniti dall’amministratore.|Informe o endereço e o token do Studio fornecidos pelo administrador.|チーム管理者から提供されたアドレスと Studio トークンを入力してください。|请输入团队管理员提供的地址和 Studio 令牌。|請輸入團隊管理員提供的位址與 Studio 權杖。
Desktop supports local processes and native file access.|Desktop은 로컬 프로세스와 네이티브 파일 접근을 지원합니다.|Desktop unterstützt lokale Prozesse und nativen Dateizugriff.|Desktop permite procesos locales y acceso nativo a archivos.|Desktop prend en charge les processus locaux et l’accès natif aux fichiers.|Desktop supporta processi locali e accesso nativo ai file.|Desktop permite processos locais e acesso nativo a arquivos.|Desktop はローカルプロセスとネイティブファイルアクセスに対応しています。|Desktop 支持本地进程和原生文件访问。|Desktop 支援本機程序與原生檔案存取。
Web keeps remote Agent execution available; local processes and native Git require Desktop.|Web에서 원격 Agent 실행을 사용할 수 있습니다. 로컬 프로세스와 네이티브 Git은 Desktop이 필요합니다.|Web unterstützt entfernte Agents; lokale Prozesse und natives Git benötigen Desktop.|Web permite Agents remotos; los procesos locales y Git nativo requieren Desktop.|Web permet les Agents distants ; les processus locaux et Git natif nécessitent Desktop.|Web permette Agent remoti; processi locali e Git nativo richiedono Desktop.|Web permite Agents remotos; processos locais e Git nativo precisam do Desktop.|Web でリモート Agent を実行できます。ローカルプロセスとネイティブ Git には Desktop が必要です。|Web 支持远程 Agent 执行；本地进程和原生 Git 需要 Desktop。|Web 支援遠端 Agent 執行；本機程序與原生 Git 需要 Desktop。
After reloading, enter your token again. Saved addresses do not contain credentials.|새로고침 후 토큰을 다시 입력하세요. 저장된 주소에는 인증 정보가 없습니다.|Nach dem Neuladen Token erneut eingeben. Gespeicherte Adressen enthalten keine Zugangsdaten.|Tras recargar, introduzca de nuevo el token. Las direcciones guardadas no contienen credenciales.|Après rechargement, saisissez à nouveau le jeton. Les adresses enregistrées ne contiennent pas d’identifiants.|Dopo il ricaricamento, inserisci di nuovo il token. Gli indirizzi salvati non contengono credenziali.|Após recarregar, informe o token novamente. Endereços salvos não contêm credenciais.|再読み込み後、トークンを再入力してください。保存されたアドレスに認証情報は含まれません。|重新加载后请再次输入令牌。保存的地址不含凭据。|重新載入後請再次輸入權杖。儲存的位址不含憑證。
Drafts could not be saved.|입력 상태를 저장할 수 없습니다.|Eingaben konnten nicht gespeichert werden.|No se pudieron guardar los datos.|Impossible d’enregistrer les saisies.|Impossibile salvare i dati inseriti.|Não foi possível salvar os dados.|入力内容を保存できませんでした。|无法保存输入状态。|無法儲存輸入狀態。
ready|준비됨|Bereit|Listo|Prêt|Pronto|Pronto|準備完了|就绪|就緒
loading|확인 중|Wird geprüft|Comprobando|Vérification|Verifica in corso|Verificando|確認中|检查中|檢查中
empty|설정 없음|Nicht eingerichtet|Sin configurar|Non configuré|Non configurato|Não configurado|未設定|未配置|未設定
unavailable|사용할 수 없음|Nicht verfügbar|No disponible|Indisponible|Non disponibile|Indisponível|利用不可|不可用|無法使用
error|오류|Fehler|Error|Erreur|Errore|Erro|エラー|错误|錯誤
recovering|복구 중|Wird wiederhergestellt|Recuperando|Récupération|Ripristino in corso|Recuperando|復旧中|恢复中|復原中
Proposed files:|제안 대상 파일:|Vorgeschlagene Dateien:|Archivos propuestos:|Fichiers proposés :|File proposti:|Arquivos propostos:|提案対象ファイル：|建议文件：|建議檔案：
Core history could not be restored. Source changes are paused; reconnect to retry.|Core 이력을 복원하지 못했습니다. 소스 변경은 중지되었습니다. 다시 연결해 재시도하세요.|Der Core-Verlauf konnte nicht wiederhergestellt werden. Quelländerungen sind pausiert; verbinden Sie sich erneut.|No se pudo restaurar el historial de Core. Los cambios están pausados; vuelva a conectarse.|Impossible de restaurer l’historique Core. Les modifications sont suspendues ; reconnectez-vous.|Impossibile ripristinare la cronologia Core. Le modifiche sono sospese; riconnettersi.|Não foi possível restaurar o histórico Core. As alterações estão pausadas; reconecte-se.|Core の履歴を復元できませんでした。ソース変更は停止中です。再接続して再試行してください。|无法恢复 Core 历史记录。源代码更改已暂停，请重新连接重试。|無法復原 Core 歷史記錄。原始碼變更已暫停，請重新連線重試。
Proposal rejected. No source changed.|제안을 거부했습니다. 소스는 변경되지 않았습니다.|Vorschlag abgelehnt. Der Quellcode wurde nicht geändert.|Propuesta rechazada. No se modificó el código.|Proposition rejetée. Aucun code source modifié.|Proposta rifiutata. Nessun codice modificato.|Proposta rejeitada. Nenhum código alterado.|提案を却下しました。ソースは変更されていません。|建议已拒绝。源代码未更改。|建議已拒絕。原始碼未變更。`;
export const onboardingMessages=Object.fromEntries(languages.filter(l=>l!=='en').map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const cells=row.split('|');if(cells.length!==10)throw Error('Invalid onboarding translation: '+cells[0]);return[cells[0],cells[index+1]];}))]));
