import type { Language } from './core.ts';
const locales: Language[] = ['ko', 'de', 'es', 'fr', 'it', 'pt', 'ja', 'zh', 'zh-hant'];
const rows = `Project setup|프로젝트 준비|Projekteinrichtung|Configuración del proyecto|Configuration du projet|Configurazione progetto|Configuração do projeto|プロジェクト設定|项目设置|專案設定
Register existing folder|기존 폴더 등록|Vorhandenen Ordner registrieren|Registrar carpeta existente|Enregistrer un dossier existant|Registra cartella esistente|Registrar pasta existente|既存フォルダーを登録|注册现有文件夹|註冊現有資料夾
Create new folder|새 폴더 생성|Neuen Ordner erstellen|Crear carpeta nueva|Créer un dossier|Crea nuova cartella|Criar nova pasta|新しいフォルダーを作成|创建新文件夹|建立新資料夾
Template|템플릿|Vorlage|Plantilla|Modèle|Modello|Modelo|テンプレート|模板|範本
Node starter with smoke test|Node 기본 프로젝트와 테스트|Node-Projekt mit Smoke-Test|Proyecto Node con prueba básica|Projet Node avec test de base|Progetto Node con test di base|Projeto Node com teste básico|Node 基本プロジェクトとテスト|Node 基础项目和测试|Node 基礎專案與測試
Empty folder|빈 폴더|Leerer Ordner|Carpeta vacía|Dossier vide|Cartella vuota|Pasta vazia|空のフォルダー|空文件夹|空資料夾
Choose parent folder|상위 폴더 선택|Übergeordneten Ordner wählen|Elegir carpeta principal|Choisir le dossier parent|Scegli cartella superiore|Escolher pasta pai|親フォルダーを選択|选择父文件夹|選擇上層資料夾
Check local tools|로컬 도구 확인|Lokale Werkzeuge prüfen|Comprobar herramientas locales|Vérifier les outils locaux|Verifica strumenti locali|Verificar ferramentas locais|ローカルツールを確認|检查本地工具|檢查本機工具
Next: open the project, connect Core and an Agent, then run the smoke test in Tests.|다음: 프로젝트를 열고 Core·Agent를 연결한 뒤 Tests에서 smoke 테스트를 실행하세요.|Projekt öffnen, Core und Agent verbinden, dann Smoke-Test unter Tests starten.|Abra el proyecto, conecte Core y un Agent y ejecute smoke en Tests.|Ouvrez le projet, connectez Core et un Agent, puis lancez smoke dans Tests.|Apri il progetto, collega Core e un Agent ed esegui smoke in Tests.|Abra o projeto, conecte Core e um Agent e execute smoke em Tests.|プロジェクトを開き、Core と Agent を接続して Tests で smoke を実行してください。|打开项目，连接 Core 和 Agent，然后在 Tests 中运行 smoke 测试。|開啟專案，連接 Core 與 Agent，然後在 Tests 中執行 smoke 測試。
Project ready. Open it from Recent Projects.|프로젝트가 준비되었습니다. 최근 프로젝트에서 여세요.|Projekt bereit. Unter Letzte Projekte öffnen.|Proyecto listo. Ábralo desde Proyectos recientes.|Projet prêt. Ouvrez-le depuis les projets récents.|Progetto pronto. Aprilo dai progetti recenti.|Projeto pronto. Abra em projetos recentes.|プロジェクトの準備ができました。最近のプロジェクトから開いてください。|项目已准备就绪。请从最近项目中打开。|專案已準備就緒。請從最近專案中開啟。
Project creation and Git Clone require the desktop app.|프로젝트 생성과 Git Clone은 데스크톱 앱에서 사용할 수 있습니다.|Projekterstellung und Git Clone benötigen die Desktop-App.|Crear proyectos y clonar Git requiere la app de escritorio.|La création et Git Clone nécessitent l’application de bureau.|Creazione e Git Clone richiedono l’app desktop.|Criação e Git Clone exigem o aplicativo desktop.|プロジェクト作成と Git Clone にはデスクトップアプリが必要です。|创建项目和 Git Clone 需要桌面应用。|建立專案與 Git Clone 需要桌面應用程式。
Clone into a new folder. Existing folders are never replaced. HTTPS repositories only.|새 폴더로 Clone합니다. 기존 폴더는 바꾸지 않습니다. HTTPS 저장소만 지원합니다.|In neuen Ordner klonen. Vorhandene Ordner bleiben erhalten. Nur HTTPS.|Clonar en carpeta nueva. No reemplaza carpetas existentes. Solo HTTPS.|Cloner dans un nouveau dossier. Aucun remplacement. Dépôts HTTPS uniquement.|Clona in una nuova cartella. Nessuna sostituzione. Solo HTTPS.|Clonar em nova pasta. Pastas existentes são preservadas. Somente HTTPS.|新しいフォルダーに Clone します。既存フォルダーは置換しません。HTTPS のみ。|克隆到新文件夹。不会替换现有文件夹。仅支持 HTTPS 仓库。|複製至新資料夾。不會取代現有資料夾。僅支援 HTTPS 儲存庫。
Create a new folder and the selected template. Existing folders are never replaced.|새 폴더와 선택한 템플릿을 생성합니다. 기존 폴더는 바꾸지 않습니다.|Neuen Ordner mit Vorlage erstellen. Kein Ersetzen vorhandener Ordner.|Crear carpeta y plantilla. No reemplaza carpetas existentes.|Créer le dossier et le modèle. Aucun remplacement de dossier.|Crea cartella e modello. Nessuna sostituzione delle cartelle esistenti.|Criar pasta e modelo. Não substitui pastas existentes.|新しいフォルダーとテンプレートを作成します。既存フォルダーは置換しません。|创建新文件夹和所选模板。不会替换现有文件夹。|建立新資料夾與所選範本。不會取代現有資料夾。
Without a Git source, tests use an approved, secret-filtered snapshot of saved workspace files.|Git Source가 없으면 승인 후 민감 정보를 제외한 저장된 작업 파일 스냅샷으로 테스트합니다.|Ohne Git-Quelle verwenden Tests einen genehmigten, geheimnisgefilterten Snapshot gespeicherter Dateien.|Sin fuente Git, las pruebas usan una instantánea aprobada de archivos guardados sin secretos.|Sans source Git, les tests utilisent un snapshot approuvé des fichiers enregistrés sans secrets.|Senza sorgente Git, i test usano uno snapshot approvato dei file salvati senza segreti.|Sem fonte Git, os testes usam snapshot aprovado de arquivos salvos sem segredos.|Git ソースがない場合、承認済みの保存ファイルから秘密を除外したスナップショットを使用します。|没有 Git 源时，测试使用经批准且已过滤机密的已保存文件快照。|沒有 Git 來源時，測試使用經核准且已過濾機密的已儲存檔案快照。`;
export const projectSetupMessages: Partial<Record<Language, Record<string, string>>> = Object.fromEntries(locales.map(language => [language, {}]));
for (const row of rows.split('\n')) { const [key, ...values] = row.split('|'); if (values.length !== locales.length) throw Error('Invalid project setup translation'); locales.forEach((language, index) => { projectSetupMessages[language]![key] = values[index]; }); }
