import {languages} from './core.ts';
// English IDs, followed by ko/de/es/fr/it/pt/ja/zh/zh-hant.
const rows=`Execution result:|실행 결과:|Ausführungsergebnis:|Resultado de ejecución:|Résultat d’exécution :|Risultato esecuzione:|Resultado da execução:|実行結果：|执行结果：|執行結果：
Passed|통과|Bestanden|Aprobado|Réussi|Superato|Aprovado|成功|通过|通過
Test failed|테스트 실패|Test fehlgeschlagen|Prueba fallida|Test échoué|Test fallito|Teste falhou|テスト失敗|测试失败|測試失敗
Could not execute the task|작업을 실행할 수 없습니다|Aufgabe konnte nicht ausgeführt werden|No se pudo ejecutar la tarea|Impossible d’exécuter la tâche|Impossibile eseguire l’attività|Não foi possível executar a tarefa|タスクを実行できませんでした|无法执行任务|無法執行工作
Execution timed out|실행 시간 초과|Zeitüberschreitung bei der Ausführung|Tiempo de ejecución agotado|Délai d’exécution dépassé|Tempo di esecuzione scaduto|Tempo de execução esgotado|実行がタイムアウトしました|执行超时|執行逾時
Cancelled|취소됨|Abgebrochen|Cancelado|Annulé|Annullato|Cancelado|キャンセル済み|已取消|已取消
Connection to Core was lost|Core 연결이 끊어졌습니다|Verbindung zu Core verloren|Se perdió la conexión con Core|Connexion à Core perdue|Connessione a Core persa|Conexão com Core perdida|Core との接続が切れました|与 Core 的连接已断开|與 Core 的連線已中斷
Agent was stopped|Agent가 중지되었습니다|Agent wurde gestoppt|El agente se detuvo|L’agent a été arrêté|Agent arrestato|O agente foi interrompido|エージェントが停止しました|代理已停止|代理程式已停止
Agent restarted during execution|실행 중 Agent가 재시작되었습니다|Agent während der Ausführung neu gestartet|El agente se reinició durante la ejecución|L’agent a redémarré pendant l’exécution|Agent riavviato durante l’esecuzione|O agente reiniciou durante a execução|実行中にエージェントが再起動しました|代理在执行期间重启|代理程式在執行期間重新啟動
Required tools are unavailable or changed|필수 도구를 사용할 수 없거나 변경되었습니다|Erforderliche Werkzeuge fehlen oder wurden geändert|Las herramientas necesarias no están disponibles o han cambiado|Les outils requis sont indisponibles ou ont changé|Gli strumenti richiesti non sono disponibili o sono cambiati|As ferramentas necessárias estão indisponíveis ou mudaram|必要なツールが利用できないか変更されました|所需工具不可用或已更改|必要工具無法使用或已變更
Some live output was omitted because the log limit or transfer queue was full.|로그 한도 또는 전송 대기열 초과로 일부 실시간 출력이 생략되었습니다.|Ein Teil der Live-Ausgabe wurde wegen des Protokolllimits oder einer vollen Übertragungswarteschlange ausgelassen.|Se omitió parte de la salida por el límite de registros o una cola de transferencia llena.|Une partie de la sortie a été omise en raison de la limite des journaux ou d’une file de transfert pleine.|Parte dell’output è stata omessa per il limite dei log o la coda di trasferimento piena.|Parte da saída foi omitida devido ao limite de logs ou à fila de transferência cheia.|ログ上限または転送キューの満杯により、一部の出力が省略されました。|由于日志上限或传输队列已满，部分实时输出已省略。|由於日誌上限或傳輸佇列已滿，部分即時輸出已省略。
chunks omitted.|개 청크 생략됨.|Blöcke ausgelassen.|bloques omitidos.|blocs omis.|blocchi omessi.|blocos omitidos.|チャンク省略。|个块已省略。|個區塊已省略。`;
export const reliabilityMessages=Object.fromEntries(languages.filter(language=>language!=='en').map((language,index)=>[language,Object.fromEntries(rows.split('\n').map(row=>{const cells=row.split('|');if(cells.length!==10)throw new Error('Invalid reliability translation: '+cells[0]);return[cells[0],cells[index+1]];}))]));
