import type { Language } from './core.ts';
const locales: Language[] = ['ko', 'de', 'es', 'fr', 'it', 'pt', 'ja', 'zh', 'zh-hant'];
const rows = `The update service is unavailable. Reinstall the latest desktop package.|업데이트 서비스에 연결할 수 없습니다. 최신 데스크톱 패키지를 다시 설치하세요.|Der Update-Dienst ist nicht verfügbar. Installieren Sie das neueste Desktop-Paket erneut.|El servicio de actualización no está disponible. Reinstala el paquete de escritorio más reciente.|Le service de mise à jour est indisponible. Réinstallez le dernier paquet de bureau.|Il servizio di aggiornamento non è disponibile. Reinstalla il pacchetto desktop più recente.|O serviço de atualização está indisponível. Reinstale o pacote desktop mais recente.|更新サービスを利用できません。最新のデスクトップパッケージを再インストールしてください。|更新服务不可用。请重新安装最新桌面软件包。|更新服務無法使用。請重新安裝最新桌面套件。
Could not reach the update server. Check your connection and try again.|업데이트 서버에 연결하지 못했습니다. 네트워크 연결을 확인하고 다시 시도하세요.|Update-Server nicht erreichbar. Prüfen Sie die Verbindung und versuchen Sie es erneut.|No se pudo conectar al servidor. Comprueba la conexión e inténtalo de nuevo.|Serveur de mise à jour inaccessible. Vérifiez la connexion et réessayez.|Server di aggiornamento non raggiungibile. Controlla la connessione e riprova.|Não foi possível acessar o servidor. Verifique a conexão e tente novamente.|更新サーバーに接続できません。接続を確認して再試行してください。|无法连接更新服务器。请检查网络并重试。|無法連接更新伺服器。請檢查網路後重試。
Updates|업데이트|Updates|Actualizaciones|Mises à jour|Aggiornamenti|Atualizações|更新|更新|更新
Current version|현재 버전|Aktuelle Version|Versión actual|Version actuelle|Versione attuale|Versão atual|現在のバージョン|当前版本|目前版本
Check for updates when the app starts|앱 시작 시 업데이트 확인|Beim Start nach Updates suchen|Buscar actualizaciones al iniciar|Rechercher au démarrage|Cerca aggiornamenti all’avvio|Verificar ao iniciar|起動時に更新を確認|启动时检查更新|啟動時檢查更新
Check for updates|업데이트 확인|Nach Updates suchen|Buscar actualizaciones|Rechercher des mises à jour|Cerca aggiornamenti|Verificar atualizações|更新を確認|检查更新|檢查更新
Checking for updates…|업데이트 확인 중…|Suche nach Updates…|Buscando actualizaciones…|Recherche en cours…|Ricerca in corso…|Verificando atualizações…|更新を確認中…|正在检查更新…|正在檢查更新…
You are up to date.|최신 버전입니다.|Sie sind auf dem neuesten Stand.|Está actualizado.|Vous êtes à jour.|La versione è aggiornata.|Você está atualizado.|最新バージョンです。|已是最新版本。|已是最新版本。
A new version is available.|새 버전이 있습니다.|Eine neue Version ist verfügbar.|Hay una nueva versión.|Une nouvelle version est disponible.|È disponibile una nuova versione.|Há uma nova versão.|新しいバージョンがあります。|有新版本可用。|有新版本可用。
Downloading and verifying…|다운로드 및 검증 중…|Download und Prüfung…|Descargando y verificando…|Téléchargement et vérification…|Download e verifica…|Baixando e verificando…|ダウンロード・検証中…|正在下载并验证…|正在下載並驗證…
Update verified. Ready to install.|검증 완료. 설치할 수 있습니다.|Update geprüft. Bereit zur Installation.|Actualización verificada. Lista para instalar.|Mise à jour vérifiée. Prête à installer.|Aggiornamento verificato. Pronto da installare.|Atualização verificada. Pronta para instalar.|検証完了。インストールできます。|更新已验证，可以安装。|更新已驗證，可以安裝。
Installing update…|업데이트 설치 중…|Update wird installiert…|Instalando actualización…|Installation en cours…|Installazione in corso…|Instalando atualização…|更新をインストール中…|正在安装更新…|正在安裝更新…
Update cancelled.|업데이트를 취소했습니다.|Update abgebrochen.|Actualización cancelada.|Mise à jour annulée.|Aggiornamento annullato.|Atualização cancelada.|更新をキャンセルしました。|更新已取消。|更新已取消。
Update failed. Your current installation is unchanged. Try again.|업데이트에 실패했습니다. 현재 설치는 변경되지 않았습니다. 다시 시도하세요.|Update fehlgeschlagen. Die aktuelle Installation bleibt unverändert. Erneut versuchen.|La actualización falló. La instalación actual no cambió. Inténtelo de nuevo.|Échec de la mise à jour. L’installation actuelle reste inchangée. Réessayez.|Aggiornamento non riuscito. L’installazione attuale è invariata. Riprova.|Falha na atualização. A instalação atual não foi alterada. Tente novamente.|更新に失敗しました。現在のインストールは変更されていません。再試行してください。|更新失败。当前安装未更改，请重试。|更新失敗。目前安裝未變更，請重試。
Save your files and finish active tasks before installing.|파일을 저장하고 실행 중인 작업을 마친 후 설치하세요.|Dateien speichern und aktive Aufgaben vor der Installation beenden.|Guarde los archivos y termine las tareas antes de instalar.|Enregistrez les fichiers et terminez les tâches avant l’installation.|Salva i file e termina le attività prima di installare.|Salve os arquivos e conclua as tarefas antes de instalar.|ファイルを保存し、実行中の作業を終了してからインストールしてください。|请保存文件并结束正在运行的任务后安装。|請儲存檔案並結束執行中的工作後安裝。
Automatic updates are available in the desktop app.|자동 업데이트는 데스크톱 앱에서 사용할 수 있습니다.|Automatische Updates sind in der Desktop-App verfügbar.|Las actualizaciones automáticas están en la aplicación de escritorio.|Les mises à jour automatiques sont disponibles dans l’application de bureau.|Gli aggiornamenti automatici sono disponibili nell’app desktop.|Atualizações automáticas estão disponíveis no aplicativo desktop.|自動更新はデスクトップアプリで利用できます。|自动更新适用于桌面应用。|自動更新適用於桌面應用程式。
This installation needs a manual update. Open the release page.|이 설치 방식은 수동 업데이트가 필요합니다. 릴리스 페이지를 여세요.|Diese Installation muss manuell aktualisiert werden. Release-Seite öffnen.|Esta instalación requiere actualización manual. Abra la página de versiones.|Cette installation nécessite une mise à jour manuelle. Ouvrez la page de version.|Questa installazione richiede un aggiornamento manuale. Apri la pagina della versione.|Esta instalação requer atualização manual. Abra a página da versão.|このインストールは手動更新が必要です。リリースページを開いてください。|此安装需要手动更新，请打开发布页面。|此安裝需要手動更新，請開啟發佈頁面。
Release notes and downloads|릴리스 노트 및 다운로드|Versionshinweise und Downloads|Notas y descargas|Notes et téléchargements|Note e download|Notas e downloads|リリースノートとダウンロード|发布说明与下载|版本說明與下載
Installation restarts the app. Save your files and finish active tasks first.|설치 후 앱이 다시 시작됩니다. 먼저 파일을 저장하고 실행 중인 작업을 마치세요.|Die Installation startet die App neu. Zuerst Dateien speichern und aktive Aufgaben beenden.|La instalación reinicia la aplicación. Primero guarde los archivos y termine las tareas.|L’installation redémarre l’application. Enregistrez les fichiers et terminez les tâches.|L’installazione riavvia l’app. Prima salva i file e termina le attività.|A instalação reinicia o aplicativo. Salve os arquivos e conclua as tarefas primeiro.|インストール後にアプリが再起動します。先にファイルを保存し、作業を終了してください。|安装将重启应用，请先保存文件并结束任务。|安裝將重新啟動應用程式，請先儲存檔案並結束工作。
Download update|업데이트 다운로드|Update herunterladen|Descargar actualización|Télécharger la mise à jour|Scarica aggiornamento|Baixar atualização|更新をダウンロード|下载更新|下載更新
Install and restart|설치 후 재시작|Installieren und neu starten|Instalar y reiniciar|Installer et redémarrer|Installa e riavvia|Instalar e reiniciar|インストールして再起動|安装并重启|安裝並重新啟動
Later|나중에|Später|Más tarde|Plus tard|Più tardi|Mais tarde|後で|稍后|稍後
The previous update was installed.|이전 업데이트가 설치되었습니다.|Das vorherige Update wurde installiert.|Se instaló la actualización anterior.|La mise à jour précédente a été installée.|L’aggiornamento precedente è stato installato.|A atualização anterior foi instalada.|前回の更新がインストールされました。|上次更新已安装。|上次更新已安裝。
The previous update could not be installed.|이전 업데이트를 설치하지 못했습니다.|Das vorherige Update konnte nicht installiert werden.|No se pudo instalar la actualización anterior.|La mise à jour précédente n’a pas pu être installée.|Impossibile installare l’aggiornamento precedente.|Não foi possível instalar a atualização anterior.|前回の更新をインストールできませんでした。|无法安装上次更新。|無法安裝上次更新。`;
export const updateMessages: Partial<Record<Language, Record<string, string>>> = Object.fromEntries(locales.map(language => [language, {}]));
for (const row of rows.split('\n')) { const [key, ...values] = row.split('|'); if (values.length !== locales.length) throw Error('Invalid update translation row'); locales.forEach((language, index) => { updateMessages[language]![key] = values[index]; }); }
