import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {immutableRunSource} from '../src/features/ai/run-source.ts';
import {projectManifest,projectManifestRecord,type ProjectSnapshot} from '../src/features/ai/project-snapshot.ts';
import {contentHash} from '../src/features/ai/fix-service.ts';
async function fixture(){const project=randomUUID(),runId=randomUUID(),content='export const value = false;',checksum=await contentHash(content);const snapshot:ProjectSnapshot={schemaVersion:2,provider:'snapshot',snapshotId:randomUUID(),projectId:project,proposalId:randomUUID(),attempt:1,baseRevision:'base',changedFiles:['src/service.ts'],files:[{path:'src/service.ts',content,encoding:'utf8',size:content.length,checksum}],checksum:''};snapshot.checksum=await contentHash(projectManifest(snapshot));let requests=0;const request=async(path:string)=>{requests++;return path.endsWith('/manifest')?projectManifestRecord(snapshot):{path:'src/service.ts',content,checksum};};return{project,runId,snapshot,request,calls:()=>requests};}
test('immutable source verifies manifest and bytes, lists directories and caches bounded text reads',async()=>{const f=await fixture(),source=await immutableRunSource(f.project,f.runId,f.request,new AbortController().signal);assert.equal((await source.files.list('',true))[0].kind,'directory');assert.equal((await source.files.list('src',true))[0].path,'src/service.ts');assert.equal((await source.files.read('src/service.ts')).content,f.snapshot.files[0].content);await source.files.read('src/service.ts');assert.equal(f.calls(),2);assert.equal(source.identity.snapshotId,f.snapshot.snapshotId);});
test('unknown file, project escape and excluded source cannot be read',async()=>{const f=await fixture(),s=await immutableRunSource(f.project,f.runId,f.request,new AbortController().signal);for(const path of ['src/missing.ts','../escape','.env','C:/file'])await assert.rejects(s.files.read(path));assert.equal(f.calls(),1);});
test('corrupt manifest, foreign project and file content mismatch fail closed',async()=>{const f=await fixture();await assert.rejects(immutableRunSource(randomUUID(),f.runId,f.request,new AbortController().signal));await assert.rejects(immutableRunSource(f.project,f.runId,async()=>({...projectManifestRecord(f.snapshot),checksum:'a'.repeat(64)}),new AbortController().signal));const s=await immutableRunSource(f.project,f.runId,async(path)=>path.endsWith('/manifest')?projectManifestRecord(f.snapshot):{path:'src/service.ts',content:'mutated',checksum:f.snapshot.files[0].checksum},new AbortController().signal);await assert.rejects(s.files.read('src/service.ts'));});
test('snapshot pin survives caller mutation; abort stops cached and new reads',async()=>{const f=await fixture(),abort=new AbortController(),s=await immutableRunSource(f.project,f.runId,f.request,abort.signal);f.snapshot.files[0].path='another.ts';assert.equal((await s.files.list('src',true))[0].path,'src/service.ts');await s.files.read('src/service.ts');abort.abort();await assert.rejects(s.files.read('src/service.ts'));await assert.rejects(s.files.list('',true));});

test('identical bytes at two manifest paths remain readable by checksum',async()=>{const f=await fixture();f.snapshot.files.push({...f.snapshot.files[0],path:'src/copy.ts'});f.snapshot.checksum=await contentHash(projectManifest(f.snapshot));const s=await immutableRunSource(f.project,f.runId,f.request,new AbortController().signal);assert.equal((await s.files.read('src/copy.ts')).content,f.snapshot.files[0].content);});
