import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {SourceReview,type SourceReviewState} from '../src/features/ai/source-review.ts';
import type {immutableRunSource} from '../src/features/ai/run-source.ts';
type Source=Awaited<ReturnType<typeof immutableRunSource>>;
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
function fixture(){const identity={runId:randomUUID(),snapshotId:randomUUID(),checksum:'a'.repeat(64)},reads:string[]=[],source:Source={identity,paths:['a.ts','b.ts'],files:{list:async()=>[],read:async path=>{reads.push(path);return{content:path+' snapshot',size:13,modified:0};}}};const states:SourceReviewState[]=[];let current=true;const review=new SourceReview(async()=>source,()=>current,s=>states.push(s));return{identity,source,reads,review,states,invalidate:()=>{current=false;}};}
test('review opens exact Snapshot file and line; selection is read-only and clears comparison',async()=>{const f=fixture();await f.review.open({identity:f.identity,path:'b.ts',line:8});assert.equal(f.review.state.path,'b.ts');assert.equal(f.review.state.line,8);assert.equal(f.review.state.text,'b.ts snapshot');assert.deepEqual(f.review.state.identity,f.identity);await f.review.compare(async()=>({content:'dirty content',kind:'dirty-editor'}),()=>true);await f.review.select('a.ts');assert.equal(f.review.state.comparison,undefined);assert.equal(f.review.state.text,'a.ts snapshot');assert.deepEqual(f.reads,['b.ts','a.ts']);});
test('foreign Snapshot and missing requested path fail without reading a different file',async()=>{const f=fixture();await f.review.open({identity:{...f.identity,snapshotId:randomUUID()}});assert.equal(f.review.state.status,'error');assert.equal(f.reads.length,0);await f.review.open({identity:f.identity,path:'missing.ts'});assert.equal(f.review.state.status,'error');assert.equal(f.reads.length,0);await f.review.select('b.ts');assert.equal(f.review.state.status,'ready');});
test('unapproved paths cannot be read and displayed text masks credentials',async()=>{const f=fixture();f.source.files.read=async()=>({content:'token=dummy-review-secret',size:25,modified:0});await f.review.open({identity:f.identity});assert(!f.review.state.text.includes('dummy-review-secret'));for(const path of ['../escape','.env','missing.ts'])await f.review.select(path);assert.equal(f.review.state.path,'a.ts');});
test('late file reply cannot replace a newer selection',async()=>{const f=fixture();await f.review.open({identity:f.identity});const late=deferred<{content:string;size:number;modified:number}>();f.source.files.read=async path=>path==='a.ts'?late.promise:{content:'latest b',size:8,modified:0};const old=f.review.select('a.ts');await f.review.select('b.ts');late.resolve({content:'old a',size:5,modified:0});await old;assert.equal(f.review.state.path,'b.ts');assert.equal(f.review.state.text,'latest b');});
test('closing aborts pending Source session and ignores its reply',async()=>{const f=fixture(),late=deferred<Source>();let signal:AbortSignal|undefined;const review=new SourceReview(async(_id,s)=>{signal=s;return late.promise;},()=>true,()=>{});const pending=review.open({identity:f.identity});review.close();assert(signal?.aborted);late.resolve(f.source);await pending;assert.equal(review.state.status,'closed');assert.equal(review.state.text,'');});
test('changed Core session prevents late results; review target is pinned before async loading',async()=>{const f=fixture();await f.review.open({identity:f.identity});const late=deferred<{content:string;size:number;modified:number}>();f.source.files.read=async()=>late.promise;const pending=f.review.select('b.ts');f.invalidate();late.resolve({content:'stale',size:5,modified:0});await pending;assert.notEqual(f.review.state.text,'stale');const loader=deferred<Source>(),review=new SourceReview(()=>loader.promise,()=>true,()=>{}),target={identity:structuredClone(f.identity),path:'a.ts'};f.source.files.read=async()=>({content:'pinned',size:6,modified:0});const opening=review.open(target);target.identity.snapshotId=randomUUID();loader.resolve(f.source);await opening;assert.equal(review.state.status,'ready');assert.equal(review.state.identity?.snapshotId,f.identity.snapshotId);});
test('dirty comparison preserves Snapshot and rejects editor changes or late comparison',async()=>{const f=fixture();await f.review.open({identity:f.identity});const snapshot=f.review.state.text;await f.review.compare(async()=>({content:'token=dummy-local',kind:'dirty-editor'}),()=>true);assert.equal(f.review.state.comparison?.kind,'dirty-editor');assert(!f.review.state.comparison?.content.includes('dummy-local'));assert.equal(f.review.state.text,snapshot);await f.review.compare(async()=>({content:'new edit',kind:'disk'}),()=>false);assert.equal(f.review.state.comparison,undefined);const late=deferred<{content:string;kind:'disk'}>(),comparison=f.review.compare(()=>late.promise,()=>true);await f.review.select('b.ts');late.resolve({content:'old edit',kind:'disk'});await comparison;assert.equal(f.review.state.comparison,undefined);assert.equal(f.review.state.path,'b.ts');});
test('comparison failure preserves verified Source, unavailable Snapshot never uses current workspace',async()=>{const f=fixture();await f.review.open({identity:f.identity});const text=f.review.state.text;await f.review.compare(async()=>{throw Error('Missing current file');},()=>true);assert.equal(f.review.state.status,'ready');assert.equal(f.review.state.text,text);assert.match(f.review.state.error!,/comparison unavailable/);const review=new SourceReview(async()=>{throw Error('Snapshot removed');},()=>true,()=>{});await review.open({identity:f.identity});assert.equal(review.state.status,'error');assert.equal(review.state.text,'');});
