import test from 'node:test';
import assert from 'node:assert/strict';
import { CoreService } from '../src/features/core/service.ts';
import { InMemoryCoreRepository } from '../src/features/core/repository.ts';
import { matchAgent } from '../src/features/core/matcher.ts';
import { transition, jobTransitions, type Agent, type AgentCapability, type JobRequirement } from '../src/features/core/domain.ts';
import type { Project } from '../src/features/projects/types/project.ts';
const capabilities:AgentCapability={cpuCores:8,memoryMiB:8192,docker:true,gpu:false,pty:true,runtimes:{node:'24.11.1',python:'3.13',java:'21',rust:'1.98'},browsers:['chromium']};
const agentInput={name:'Test Agent',platform:'linux' as const,architecture:'x86_64' as const,capabilities};
const input={name:'Build',requirements:{platform:'linux' as const,runtimes:{node:'>=24'}},payload:{task:'build',steps:[{name:'Install',executable:'node',args:['install.mjs'],cwd:'.'},{name:'Build',executable:'node',args:['build.mjs'],cwd:'.'}]}};
function fixture(){let id=0,time=0;const repository=new InMemoryCoreRepository();const project={id:'A',name:'Project A'} as Project;const core=new CoreService(repository,{async get(id){return ['A','B'].includes(id)?{...project,id}:null;}},{id:()=>`id-${String(++id).padStart(4,'0')}`,now:()=>new Date(1790700000000+time++).toISOString()});return {core,repository};}
function available(core:CoreService,name='Test Agent',status:'idle'|'online'='idle'){const a=core.registerAgent({...agentInput,name});return core.updateAgentStatus(a.id,status);}
async function running(core:CoreService,project='A'){const job=await core.createJob(project,input);if(!core.listAgents().length)available(core);const assigned=core.dispatch(project)!;core.startRun(project,assigned.run.id);return {job,run:assigned.run};}

test('registry register/get/list starts offline with no fabricated last seen and rejects duplicate',()=>{const {core}=fixture();const a=core.registerAgent(agentInput);assert.equal(a.status,'offline');assert.equal(a.lastSeenAt,null);assert.equal(core.getAgent(a.id)?.name,agentInput.name);assert.equal(core.listAgents().length,1);assert.throws(()=>core.registerAgent({...agentInput,name:'TEST AGENT'}),/already/);});
test('registry update/status/capability/remove and returned objects are detached',()=>{const {core}=fixture();const a=core.registerAgent(agentInput);core.updateAgent(a.id,{...agentInput,name:'Renamed'});core.updateCapabilities(a.id,{...capabilities,gpu:true});assert.equal(core.getAgent(a.id)?.capabilities.gpu,true);assert.ok(core.updateAgentStatus(a.id,'online').lastSeenAt);a.capabilities.runtimes.node='1';assert.equal(core.getAgent(a.id)?.capabilities.runtimes.node,'24.11.1');core.removeAgent(a.id);assert.equal(core.listAgents().length,0);});
const matchCases:[string,JobRequirement,boolean,string?][]=[['OS matches',{platform:'linux'},true],['OS differs',{platform:'windows'},false,'OS'],['architecture',{architecture:'arm64'},false,'Architecture'],['runtime matches',{runtimes:{node:'>=24.11.1'}},true],['runtime insufficient',{runtimes:{node:'>=25'}},false,'node'],['browser',{browser:'firefox'},false,'Browser'],['Docker',{docker:'required'},true],['GPU required',{gpu:'required'},false,'gpu'],['GPU optional',{gpu:'optional'},true],['CPU',{cpuCores:16},false,'cpuCores'],['memory',{memoryMiB:16000},false,'memoryMiB'],['PTY',{pty:'required'},true],['combined',{platform:'linux',architecture:'x86_64',runtimes:{node:'>=24',python:'>=3.13'},browser:'chromium',docker:'required'},true]];
for(const [name,requirements,expected,reason] of matchCases)test(`matcher ${name}`,()=>{const {core}=fixture();const agent=available(core);const m=matchAgent(agent,requirements);assert.equal(m.matches,expected);if(reason)assert.ok(m.reasons.some(r=>r.includes(reason)));});
test('matcher rejects absent runtimes, Docker and PTY',()=>{const {core}=fixture();const agent=available(core);agent.capabilities={...capabilities,runtimes:{},docker:false,pty:false};const m=matchAgent(agent,{runtimes:{node:'>=24'},docker:'required',pty:'required'});assert.equal(m.reasons.length,3);});
test('job validation rejects missing project, invalid priority/ranges and unstructured payload',async()=>{const {core}=fixture();await assert.rejects(core.createJob('missing',input),/Project/);await assert.rejects(core.createJob('A',{...input,priority:101}),/Priority/);await assert.rejects(core.createJob('A',{...input,requirements:{runtimes:{node:'^24'}}}),/Invalid requirements/);await assert.rejects(core.createJob('A',{...input,payload:{task:'bad',steps:[{name:'bad',executable:'node',args:[],cwd:'../outside'}]}}),/relative/);assert.equal(core.snapshot('A').jobs.length,0);});
test('queue priority then oldest; enqueue is idempotent and queued cancellation is final',async()=>{const {core}=fixture();const first=await core.createJob('A',input),second=await core.createJob('A',{...input,priority:10}),third=await core.createJob('A',{...input,priority:10});assert.deepEqual(core.queue('A').map(j=>j.id),[second.id,third.id,first.id]);assert.equal(core.dequeueCandidate('A')?.id,second.id);core.enqueue('A',second.id);core.cancelJob('A',second.id);assert.equal(core.dequeueCandidate('A')?.id,third.id);assert.throws(()=>core.enqueue('A',second.id),/queued/);assert.throws(()=>transition('cancelled','running',jobTransitions),/Cannot/);});
test('dispatch no agents or incompatible agents leaves queued without runs',async()=>{const {core}=fixture();await core.createJob('A',input);assert.equal(core.dispatch(),null);const a=core.registerAgent({...agentInput,platform:'windows'});core.updateAgentStatus(a.id,'idle');assert.equal(core.dispatch(),null);assert.equal(core.queue().length,1);assert.equal(core.snapshot('A').runs.length,0);});
test('dispatch prefers idle, reserves exactly once and excludes busy agents',async()=>{const {core}=fixture();available(core,'Online','online');const idle=available(core,'Idle');await core.createJob('A',input);await core.createJob('A',input);const a=core.dispatch()!;assert.equal(a.agent.id,idle.id);assert.equal(a.job.status,'assigned');assert.equal(a.run.status,'pending');assert.equal(a.run.startedAt,null);const b=core.dispatch()!;assert.notEqual(a.agent.id,b.agent.id);assert.equal(core.dispatch(),null);assert.throws(()=>core.updateAgentStatus(idle.id,'idle'),/reserved/);assert.throws(()=>core.removeAgent(idle.id),/reserved/);assert.throws(()=>core.updateCapabilities(idle.id,capabilities),/reserved/);});
test('busy agent cannot match; lower priority compatible job is not starved by incompatible first job',async()=>{const {core}=fixture();const a=available(core);core.updateAgentStatus(a.id,'busy');await core.createJob('A',input);assert.equal(core.dispatch(),null);core.updateAgentStatus(a.id,'idle');await core.createJob('A',{...input,priority:100,requirements:{gpu:'required'}});assert.equal(core.dispatch()!.job.priority,0);});
test('integration Project -> Job -> Queue -> Match -> Assignment -> Run -> Steps -> Pass -> Success',async()=>{const {core}=fixture();const {job,run}=await running(core);const steps=core.snapshot('A').steps;for(const step of steps){core.changeStep('A',run.id,step.id,'running');core.changeStep('A',run.id,step.id,'passed',0);}const result=core.finishRun('A',run.id,'passed',0,'All steps passed.');assert.equal(result.status,'passed');assert.ok(result.startedAt&&result.finishedAt);assert.equal(core.snapshot('A').jobs.find(j=>j.id===job.id)?.status,'succeeded');assert.equal(core.getAgent(run.agentId)?.status,'idle');assert.throws(()=>core.startRun('A',run.id),/Cannot/);assert.ok(core.snapshot('A').events.some(e=>e.type==='run.completed'));});
test('step ordering and false passing are rejected atomically',async()=>{const {core,repository}=fixture();const {run}=await running(core);const steps=core.snapshot('A').steps;const before=repository.read();assert.throws(()=>core.changeStep('A',run.id,steps[1].id,'running'),/earlier/);assert.throws(()=>core.finishRun('A',run.id,'passed',0,'Fake success'),/Passing/);assert.deepEqual(repository.read(),before);core.changeStep('A',run.id,steps[0].id,'running');assert.throws(()=>core.changeStep('A',run.id,steps[0].id,'passed',1),/exit code 0/);});
test('integration step fail -> Run failed -> Job failed; retry preserves history and prevents duplicate attempts',async()=>{const {core}=fixture();const {job,run}=await running(core);core.changeStep('A',run.id,core.snapshot('A').steps[0].id,'running');core.changeStep('A',run.id,core.snapshot('A').steps[0].id,'failed',2);assert.equal(core.snapshot('A').runs[0].status,'failed');assert.equal(core.snapshot('A').jobs[0].status,'failed');assert.equal(core.snapshot('A').steps[1].status,'cancelled');const retry=core.retryJob('A',job.id);assert.equal(retry.sourceJobId,job.id);assert.equal(retry.attempt,2);assert.equal(retry.status,'queued');assert.throws(()=>core.retryJob('A',job.id),/already exists/);assert.equal(core.snapshot('A').runs[0].status,'failed');});
test('assigned cancellation waits for acknowledgement and prevents start',async()=>{const {core}=fixture();available(core);const job=await core.createJob('A',input);const {run}=core.dispatch()!;const requested=core.cancelJob('A',job.id);assert.equal(requested.status,'assigned');assert.ok(requested.cancellationRequestedAt);assert.throws(()=>core.startRun('A',run.id),/acknowledgement/);core.finishRun('A',run.id,'cancelled',null,'Cancellation acknowledged.');assert.equal(core.snapshot('A').jobs[0].status,'cancelled');assert.equal(core.getAgent(run.agentId)?.status,'idle');});
test('running cancel request does not claim a killed process; timeout closes run and prevents resume',async()=>{const {core}=fixture();const {job,run}=await running(core);core.cancelJob('A',job.id);assert.equal(core.snapshot('A').runs[0].status,'running');core.finishRun('A',run.id,'timeout',null,'Execution timed out.');assert.equal(core.snapshot('A').jobs[0].status,'failed');assert.throws(()=>core.startRun('A',run.id),/acknowledgement|Cannot/);});
test('retry limit enforced',async()=>{const {core}=fixture();available(core);const job=await core.createJob('A',{...input,maxAttempts:1});const {run}=core.dispatch()!;core.startRun('A',run.id);core.finishRun('A',run.id,'failed',1,'Failed.');assert.throws(()=>core.retryJob('A',job.id),/attempts/);});
test('project isolation applies to jobs, runs, steps, mutations and artifact references',async()=>{const {core}=fixture();const a=await running(core,'A');available(core,'Second');const b=await running(core,'B');assert.equal(core.snapshot('A').jobs.length,1);assert.equal(core.snapshot('B').runs.length,1);assert.throws(()=>core.cancelJob('B',a.job.id),/another project/);assert.throws(()=>core.startRun('B',a.run.id),/another project/);assert.throws(()=>core.changeStep('A',a.run.id,core.snapshot('B').steps[0].id,'running'),/another run/);assert.throws(()=>core.addArtifact('A',{runId:a.run.id,runStepId:core.snapshot('B').steps[0].id,type:'log',name:'log',location:'logs/result.txt',size:10}),/another run/);assert.notEqual(a.run.id,b.run.id);});
test('artifact metadata has safe references, no upload, and events contain no command arguments',async()=>{const {core}=fixture();const {run}=await running(core);const artifact=core.addArtifact('A',{runId:run.id,runStepId:null,type:'report',name:'Report',location:'reports/result.json',size:120});assert.equal(core.snapshot('A').artifacts[0].id,artifact.id);assert.throws(()=>core.addArtifact('A',{...artifact,location:'javascript:bad'}),/Unsupported/);assert.doesNotMatch(JSON.stringify(core.snapshot('A').events),/install.mjs|build.mjs/);});
test('repository rollback, detached reads and observer failures preserve committed state',()=>{const {core,repository}=fixture();const before=repository.read();assert.throws(()=>repository.transaction(tx=>{tx.agents.save({id:'broken'} as Agent);throw new Error('rollback');}));assert.deepEqual(repository.read(),before);repository.subscribe(()=>{throw new Error('observer');});core.registerAgent(agentInput);const read=repository.read();read.agents[0].name='outside mutation';assert.equal(core.listAgents()[0].name,agentInput.name);});
test('equal timestamps retain queue insertion order rather than random ID order',async()=>{const repo=new InMemoryCoreRepository();let id=0;const core=new CoreService(repo,{async get(id){return {id} as Project;}},{now:()=> '2026-09-30T00:00:00Z',id:()=>String(1000-id++)});const first=await core.createJob('A',input),second=await core.createJob('A',input);assert.deepEqual(core.queue().map(j=>j.id),[first.id,second.id]);});
