import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {runtimeConfig} from '../transport/runtime-config.ts';
import {RuntimeLog} from '../transport/runtime-log.ts';
import {startCoreServer} from '../transport/server.ts';
const root=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/advancement-2/unit/',import.meta.url));
fs.mkdirSync(root,{recursive:true});
const tokens={CORE_AGENT_TOKEN:'dummy-agent-runtime-2026',CORE_STUDIO_TOKEN:'dummy-studio-runtime-2026'};
const temp=()=>fs.mkdtempSync(path.join(root,'case-'));
test('runtime config: env overrides strict file and OS defaults; no file credential',()=>{
 const dir=temp();try{const filename=path.join(dir,'config.json');fs.writeFileSync(filename,JSON.stringify({port:4450,dataDir:dir}));const c=runtimeConfig({...tokens,CORE_CONFIG:filename,CORE_PORT:'4451'},'win32');assert.equal(c.port,4451);assert.equal(c.dataDir,dir);assert.ok(c.storagePath.startsWith(dir));assert.equal(c.host,'127.0.0.1');assert.equal(runtimeConfig(tokens,'linux').dataDir,'/var/lib/tastestudio-core');fs.writeFileSync(filename,JSON.stringify({studioToken:'no'}));assert.throws(()=>runtimeConfig({...tokens,CORE_CONFIG:filename}),/CONFIG_UNKNOWN_FIELD/);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
for(const [key,value] of [['CORE_PORT','NaN'],['CORE_PORT','0'],['CORE_ALLOW_LAN','yes'],['CORE_STORAGE_PATH','relative'],['CORE_ORIGINS','https://user:password@example.com'],['CORE_SHUTDOWN_TIMEOUT_MS','-1']])test(`runtime invalid ${key} rejects without echoing input`,()=>{assert.throws(()=>runtimeConfig({...tokens,[key]:value}),/^Error: CONFIG_/);});
test('remote binding requires explicit proxy TLS and HTTPS Artifact URL; distinct tokens',()=>{assert.throws(()=>runtimeConfig({...tokens,CORE_HOST:'0.0.0.0'}),/REMOTE_REQUIRES/);assert.throws(()=>runtimeConfig({...tokens,CORE_HOST:'0.0.0.0',CORE_ALLOW_LAN:'1',CORE_TLS_PROXY:'1'}),/REMOTE_HTTPS/);assert.equal(runtimeConfig({...tokens,CORE_HOST:'0.0.0.0',CORE_ALLOW_LAN:'1',CORE_TLS_PROXY:'1',CORE_ARTIFACT_BASE_URL:'https://core.example.com'}).allowLan,true);assert.throws(()=>runtimeConfig({...tokens,CORE_AGENT_TOKEN:tokens.CORE_STUDIO_TOKEN}),/DISTINCT/);});
test('structured runtime logs mask values and rotate with bounded retention',()=>{const dir=temp();try{const output:string[]=[];const secret='dummy-secret-log-2026';const log=new RuntimeLog(dir,4096,3,[secret],line=>output.push(line));for(let i=0;i<60;i++)log.write('info','case',{i,token:secret,body:'x'.repeat(300),authorization:'Bearer dummy'});const names=fs.readdirSync(dir);assert.equal(names.length,3);for(const name of names){const body=fs.readFileSync(path.join(dir,name),'utf8');assert.equal(body.includes(secret),false);assert.equal(body.includes('Bearer dummy'),false);for(const line of body.trim().split('\n'))assert.ok(JSON.parse(line).timestamp);}assert.equal(output.join('').includes(secret),false);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('readiness/version, unauthorized stop, drain rejects assignment and preserves queued work',async()=>{
 const dir=temp(),opts={port:0,agentToken:tokens.CORE_AGENT_TOKEN,studioToken:tokens.CORE_STUDIO_TOKEN,storagePath:path.join(dir,'core.sqlite'),storageKey:Buffer.alloc(32,7),artifactRoot:path.join(dir,'artifacts'),version:'fixture'};let s=await startCoreServer(opts);const ws=new WebSocket(`ws://127.0.0.1:${s.port}/studio`);const messages:Record<string,unknown>[]=[];ws.on('message',data=>messages.push(JSON.parse(data.toString())));const project={id:'runtime-project',name:'Runtime',workspacePath:null};
 try{const url=`http://127.0.0.1:${s.port}`;assert.equal((await (await fetch(url+'/health/ready')).json()).ready,true);assert.equal((await (await fetch(url+'/runtime')).json()).protocolVersion,1);assert.equal((await fetch(url+'/runtime/stop',{method:'POST'})).status,403);if(ws.readyState!==WebSocket.OPEN)await once(ws,'open');ws.send(JSON.stringify({protocolVersion:1,type:'subscribe',token:tokens.CORE_STUDIO_TOKEN,project}));while(!messages.some(m=>m.type==='snapshot'))await new Promise(r=>setTimeout(r,10));const job=await s.service.createJob(project.id,{name:'queued',requirements:{},payload:{task:'q',steps:[{name:'q',executable:'node',args:['-v'],cwd:'.'}]}});const stopping=s.stop(100);assert.equal(s.health().ready,false);ws.send(JSON.stringify({protocolVersion:1,type:'rpc',requestId:'blocked',method:'dispatch',args:[job.id]}));await stopping;s=await startCoreServer(opts);assert.equal(s.service.queue(project.id)[0].id,job.id);assert.equal(s.service.snapshot(project.id).runs.length,0);}finally{ws.terminate();await s.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('repeated listener lifecycle releases port and single-writer database',async()=>{const dir=temp();try{let port=0;for(let i=0;i<4;i++){const s=await startCoreServer({port,agentToken:tokens.CORE_AGENT_TOKEN,studioToken:tokens.CORE_STUDIO_TOKEN,storagePath:path.join(dir,'core.sqlite'),storageKey:Buffer.alloc(32,8),artifactRoot:path.join(dir,'artifacts')});port=s.port;const same=s.stop(100);assert.equal(s.stop(100),same);await same;}}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('drain timeout retains unresolved execution identity and reports not-ready while live',async()=>{
 const dir=temp(),opts={port:0,agentToken:tokens.CORE_AGENT_TOKEN,studioToken:tokens.CORE_STUDIO_TOKEN,storagePath:path.join(dir,'core.sqlite'),storageKey:Buffer.alloc(32,9),artifactRoot:path.join(dir,'artifacts')};let s=await startCoreServer(opts);const ws=new WebSocket(`ws://127.0.0.1:${s.port}/studio`);const messages:Record<string,unknown>[]=[];ws.on('message',data=>messages.push(JSON.parse(data.toString())));
 try{await once(ws,'open');const project={id:'timeout-runtime-project',name:'Controlled timeout'};ws.send(JSON.stringify({protocolVersion:1,type:'subscribe',token:tokens.CORE_STUDIO_TOKEN,project}));while(!messages.some(m=>m.type==='snapshot'))await new Promise(r=>setTimeout(r,10));const controlled=s.service.registerAgent({name:'Controlled unresponsive Agent',platform:'windows',architecture:'x86_64',capabilities:{cpuCores:1,memoryMiB:1024,docker:false,gpu:false,pty:false,runtimes:{},browsers:[]}});s.service.updateAgentStatus(controlled.id,'idle');const job=await s.service.createJob(project.id,{name:'pending identity',requirements:{},payload:{task:'pending',steps:[{name:'pending',executable:'node',args:['-v'],cwd:'.'}]}});const assigned=s.service.dispatch(project.id,job.id)!;assert.ok(assigned);const stopping=s.stop(1500);assert.equal((await fetch(`http://127.0.0.1:${s.port}/health/ready`)).status,503);assert.equal((await(await fetch(`http://127.0.0.1:${s.port}/health/live`)).json()).live,true);assert.equal((await stopping).timedOut,true);s=await startCoreServer(opts);assert.equal(s.service.snapshot(project.id).runs[0].id,assigned.run.id);assert.ok(s.service.snapshot(project.id).jobs[0].cancellationRequestedAt);}finally{ws.terminate();await s.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('oversized runtime record omitted and every rotated file remains within byte cap',()=>{const dir=temp();try{const log=new RuntimeLog(dir,4096,2,[],()=>{});log.write('info','oversized',{data:'가'.repeat(10000)});const filename=path.join(dir,'core.jsonl');assert.ok(fs.statSync(filename).size<=4096);assert.equal(JSON.parse(fs.readFileSync(filename,'utf8')).fields.omitted,'record size limit');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('legacy DB prevents silent switch to empty OS default and remains untouched',()=>{const dir=temp();try{const legacy=path.join(dir,'legacy.sqlite');fs.writeFileSync(legacy,'controlled existing bytes');assert.throws(()=>runtimeConfig(tokens,process.platform,true,legacy),/LEGACY_STORAGE_REQUIRES_EXPLICIT_PATH/);assert.equal(runtimeConfig({...tokens,CORE_STORAGE_PATH:legacy},process.platform,true,legacy).storagePath,legacy);assert.equal(fs.readFileSync(legacy,'utf8'),'controlled existing bytes');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
