import test from 'node:test';
import assert from 'node:assert/strict';
import {FixService,type FixAttempt} from '../src/features/ai/fix-service.ts';
import {buildSnapshot} from '../src/features/ai/snapshot.ts';
import {HistoryStore} from '../transport/history.ts';
import {CoreStore} from '../transport/storage.ts';
import type {AnalysisRecord} from '../src/features/ai/domain.ts';
async function fixture(){
 const projectId=crypto.randomUUID(),store=new CoreStore(':memory:',Buffer.alloc(32,9)),history=new HistoryStore(store);
 const disk=new Map([['a.ts','user baseline'],['.env','TOKEN=dummy-snapshot-secret']]);
 const files={list:async()=>[...disk].map(([path])=>({path,name:path,kind:'file' as const})),read:async(path:string)=>({path,content:disk.get(path)!,modified:0,size:10}),write:async(path:string,value:string,expected:string)=>{assert.equal(disk.get(path),expected);disk.set(path,value);}};
 const record:AnalysisRecord={id:crypto.randomUUID(),projectId,conversationId:crypto.randomUUID(),runId:crypto.randomUUID(),model:'controlled',createdAt:new Date().toISOString(),context:[],originals:{'a.ts':'user baseline'},result:{summary:'controlled',observedFailure:'',candidates:[],evidence:[],uncertainty:'',relatedFiles:[],proposal:[{path:'a.ts',proposed:'AI result',rationale:'controlled',impact:'controlled',tests:['unit']}]}};
 const open=()=>{const fix=new FixService(projectId,files);fix.restore(history.list(projectId,'attempt').map(v=>history.get(projectId,'attempt',v.id)!.value as FixAttempt));fix.setPersistence({save:async a=>{await history.put(projectId,'attempt',a.id,history.get(projectId,'attempt',a.id)?.version??0,a);}});return fix;};
 const fix=open(),a=await fix.propose(record);await fix.approve(a.id,['a.ts']);await fix.apply(a.id);
 const snapshot=async()=>buildSnapshot(files as never,{projectId,proposalId:a.proposalId,attempt:a.attempt,baseRevision:'controlled',changedFiles:['a.ts']});
 return{store,history,disk,fix,open,a,record,snapshot,projectId};
}
test('execution approval survives reopen and stale task definitions cannot execute',async()=>{const f=await fixture();try{const task={executable:'node',args:['unit.cjs'],env:{DUMMY_SECRET:'dummy-execution-secret'}};await assert.rejects(f.fix.beginApprovedValidation(f.a.id,crypto.randomUUID(),task),/VALIDATION_APPROVAL_REQUIRED/);const approval=await f.fix.approveExecution(f.a.id,'local-task','unit',task);const reopened=f.open();assert.equal(reopened.get(f.a.id).executionApprovals?.[0].id,approval.id);await assert.rejects(reopened.beginApprovedValidation(f.a.id,approval.id,{...task,args:['other.cjs']}),/VALIDATION_APPROVAL_REQUIRED/);assert.equal(reopened.get(f.a.id).status,'applied');await reopened.beginApprovedValidation(f.a.id,approval.id,task);assert.equal(reopened.get(f.a.id).status,'validating');assert(!JSON.stringify(reopened.get(f.a.id).executionApprovals).includes('dummy-execution-secret'));}finally{f.store.close();}});
test('remote retest requires matching approval plus immutable persisted Snapshot identity',async()=>{const f=await fixture();try{const plan={test:'unit',steps:[{executable:'node',args:['unit.cjs']}]};const approval=await f.fix.approveExecution(f.a.id,'remote-test','unit',plan);await assert.rejects(f.fix.beginApprovedRetest(f.a.id,approval.id,plan),/INVALID_SNAPSHOT/);const {snapshot,excluded}=await f.snapshot();assert(excluded.includes('.env'));await f.fix.recordSnapshot(f.a.id,snapshot);await f.fix.beginApprovedRetest(f.a.id,approval.id,plan);const reopened=f.open().get(f.a.id);assert.equal(reopened.status,'retesting');assert.equal(reopened.snapshot?.snapshotId,snapshot.snapshotId);assert.equal(reopened.snapshot?.checksum,snapshot.checksum);assert(!JSON.stringify(reopened.snapshot).includes('dummy-snapshot-secret'));assert(!Object.hasOwn(reopened.snapshot!.files[0],'content'));}finally{f.store.close();}});
test('changed patched Source cannot silently become a different fix retest',async()=>{const f=await fixture();try{f.disk.set('a.ts','later user change');const {snapshot}=await f.snapshot();await assert.rejects(f.fix.recordSnapshot(f.a.id,snapshot),/PATCH_CONFLICT/);assert.equal(f.fix.get(f.a.id).snapshot,undefined);assert.equal(f.disk.get('a.ts'),'later user change');}finally{f.store.close();}});
test('old execution approval cannot authorize a new proposal',async()=>{const f=await fixture();try{const task={executable:'node',args:[]};const approval=await f.fix.approveExecution(f.a.id,'local-task','unit',task);const next=await f.fix.propose(f.record);await assert.rejects(f.fix.beginApprovedValidation(next.id,approval.id,task),/VALIDATION_APPROVAL_REQUIRED/);assert.equal(f.fix.get(next.id).status,'proposed');}finally{f.store.close();}});
test('durable audit approvals cannot be edited or removed by a later CAS writer',async()=>{const f=await fixture();try{await f.fix.approveExecution(f.a.id,'local-task','unit',{executable:'node',args:[]});const row=f.history.get(f.projectId,'attempt',f.a.id)!;const changed=structuredClone(row.value) as FixAttempt;changed.executionApprovals![0].name='other-task';await assert.rejects(f.history.put(f.projectId,'attempt',f.a.id,row.version,changed),/Reviewed proposal is immutable/);delete changed.executionApprovals;await assert.rejects(f.history.put(f.projectId,'attempt',f.a.id,row.version,changed),/Reviewed proposal is immutable/);}finally{f.store.close();}});
