import test from 'node:test';
import assert from 'node:assert/strict';
import {FixService,applyEdits,structuredEdit} from '../src/features/ai/fix-service.ts';
import {Documents} from '../src/features/editor/documents.ts';
import type {AnalysisRecord} from '../src/features/ai/domain.ts';
const projectId='11111111-1111-4111-8111-111111111111';
function setup(){const disk=new Map([['a.ts','user baseline'],['b.ts','second baseline']]);let fail='';const files={read:async(path:string)=>{if(!disk.has(path))throw Error('missing');return{path,content:disk.get(path)!,modified:0,size:disk.get(path)!.length};},write:async(path:string,content:string,expected:string)=>{if(path===fail)throw Error('write failed');if(disk.get(path)!==expected)throw Error('conflict');disk.set(path,content);}};const docs=new Documents(files as never);const service=new FixService(projectId,files,docs);const record:AnalysisRecord={id:crypto.randomUUID(),projectId,conversationId:'session',runId:'failure',model:'test',createdAt:'',context:[],originals:Object.fromEntries(disk),result:{summary:'test',observedFailure:'',candidates:[],evidence:[],uncertainty:'test',relatedFiles:[],proposal:[{path:'a.ts',proposed:'user baseline fixed',rationale:'fix',impact:'test',tests:['unit']},{path:'b.ts',proposed:'second baseline fixed',rationale:'fix',impact:'test',tests:['unit']}]}};return{disk,files,docs,service,record,setFail:(path:string)=>{fail=path;}};}
test('structured edit preserves prefix and suffix and rejects invalid preconditions',()=>{const edits=structuredEdit('abc old xyz','abc new xyz');assert.equal(edits[0].remove,'old');assert.equal(applyEdits('abc old xyz',edits),'abc new xyz');assert.throws(()=>applyEdits('abc user xyz',edits));});
test('approval required before writes and exact proposal scope',async()=>{const {service,record,disk}=setup();const a=await service.propose(record);await assert.rejects(service.apply(a.id),/APPROVAL_REQUIRED/);assert.equal(disk.get('a.ts'),'user baseline');await assert.rejects(service.approve(a.id,['outside.ts']),/APPROVAL_SCOPE/);await service.approve(a.id,['a.ts','b.ts']);await service.apply(a.id);assert.equal(disk.get('a.ts'),'user baseline fixed');});
test('reject and cancel never write',async()=>{const {service,record,disk}=setup();const a=await service.propose(record,[0]);service.reject(a.id);await assert.rejects(service.apply(a.id));const b=await service.propose(record,[0]);service.cancel(b.id);await assert.rejects(service.apply(b.id));assert.equal(disk.get('a.ts'),'user baseline');});
test('stale base preserves user modifications',async()=>{const {service,record,disk}=setup();const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);disk.set('a.ts','user later');await assert.rejects(service.apply(a.id),/PATCH_CONFLICT/);assert.equal(disk.get('a.ts'),'user later');});
test('dirty editor preserved before apply',async()=>{const {service,record,docs,disk}=setup();await docs.open('a.ts');const doc=docs.snapshot().openEditors[0];docs.edit(doc.id,'unsaved user');const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await assert.rejects(service.apply(a.id),/DIRTY_EDITOR/);assert.equal(docs.get(doc.id).content,'unsaved user');assert.equal(disk.get('a.ts'),'user baseline');});
test('multi-file failure rolls back previous writes',async()=>{const {service,record,disk,setFail}=setup();const a=await service.propose(record);await service.approve(a.id,['a.ts','b.ts']);setFail('b.ts');await assert.rejects(service.apply(a.id));assert.equal(disk.get('a.ts'),'user baseline');assert.equal(disk.get('b.ts'),'second baseline');assert.equal(service.get(a.id).status,'failed');});
test('apply and revert synchronize clean open editors and retain prior user baseline',async()=>{const {service,record,docs,disk}=setup();await docs.open('a.ts');const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await service.apply(a.id);assert.equal(docs.snapshot().openEditors[0].content,disk.get('a.ts'));assert.equal(docs.snapshot().dirtyEditors.length,0);await service.revert(a.id);assert.equal(disk.get('a.ts'),'user baseline');assert.equal(docs.snapshot().openEditors[0].content,'user baseline');});
test('revert preserves edits made after AI application',async()=>{const {service,record,disk}=setup();const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await service.apply(a.id);disk.set('a.ts','later user edit');await assert.rejects(service.revert(a.id),/PATCH_CONFLICT/);assert.equal(disk.get('a.ts'),'later user edit');});
test('project escape and foreign proposal rejected',async()=>{const {service,record}=setup();await assert.rejects(service.propose({...record,projectId:crypto.randomUUID()}));record.result.proposal[0].path='../escape';await assert.rejects(service.propose(record,[0]));});
test('immutable approval hash prevents proposal tampering',async()=>{const {service,record,disk}=setup();const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);service.history[0].patches[0].result='unauthorized';await assert.rejects(service.apply(a.id),/APPROVAL_REQUIRED/);assert.equal(disk.get('a.ts'),'user baseline');});
test('history retains independent attempts and caps at three',async()=>{const {service,record}=setup();for(let n=0;n<3;n++){const a=await service.propose(record,[0]);service.reject(a.id);}await assert.rejects(service.propose(record,[0]),/RETRY_LIMIT/);assert.equal(new Set(service.history.map(a=>a.proposalId)).size,3);});
test('redacted targets cannot be overwritten from sanitized model text',async()=>{const {service,record}=setup();record.originals['a.ts']='token=[redacted]';await assert.rejects(service.propose(record,[0]),/REDACTED/);});
test('cancelled remote retest still allows restoring the approved patch baseline',async()=>{const {service,record,disk}=setup();const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await service.apply(a.id);service.beginRetest(a.id,crypto.randomUUID());service.retestResult(a.id,'cancelled');await service.revert(a.id);assert.equal(disk.get('a.ts'),'user baseline');assert.equal(service.get(a.id).status,'reverted');});

test('retry limit follows original failure across retest analysis and tool permissions are scoped',async()=>{const {service,record}=setup();const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await service.execute('apply_patch',{projectId,attemptId:a.id});await assert.rejects(service.execute('shell',{projectId,attemptId:a.id}),/TOOL_UNAVAILABLE/);await assert.rejects(service.execute('apply_patch',{projectId:crypto.randomUUID(),attemptId:a.id}),/PROJECT_BOUNDARY/);service.beginRetest(a.id);const nextRun=crypto.randomUUID();service.linkRetest(a.id,nextRun);service.retestResult(a.id,'failed');await service.revert(a.id);const second=await service.propose({...record,runId:nextRun},[0]);assert.equal(second.attempt,2);service.reject(second.id);const third=await service.propose({...record,runId:nextRun},[0]);assert.equal(third.attempt,3);service.cancel(third.id);await assert.rejects(service.propose({...record,runId:nextRun},[0]),/RETRY_LIMIT/);});

test('applied state persistence failure compensates Source and clean Editor together',async()=>{const {service,record,docs,disk}=setup();await docs.open('a.ts');service.setPersistence({save:async a=>{if(a.status==='applied')throw Error('controlled storage failure');}});const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await assert.rejects(service.apply(a.id),/PERSISTENCE_FAILED/);assert.equal(disk.get('a.ts'),'user baseline');assert.equal(docs.snapshot().openEditors[0].content,'user baseline');assert.equal(docs.snapshot().dirtyEditors.length,0);});
test('reverted state persistence failure restores previously applied Source and Editor',async()=>{const {service,record,docs,disk}=setup();await docs.open('a.ts');service.setPersistence({save:async a=>{if(a.status==='reverted')throw Error('controlled storage failure');}});const a=await service.propose(record,[0]);await service.approve(a.id,['a.ts']);await service.apply(a.id);await assert.rejects(service.revert(a.id),/PERSISTENCE_FAILED/);assert.equal(service.get(a.id).status,'applied');assert.equal(disk.get('a.ts'),'user baseline fixed');assert.equal(docs.snapshot().openEditors[0].content,'user baseline fixed');});
