import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {startCoreServer} from '../transport/server.ts';import {RemoteCoreClient} from '../src/features/core/remote-client.ts';import {FakeIssueProvider} from './helpers/fake-issue-provider.ts';import {FixService} from '../src/features/ai/fix-service.ts';import type {AnalysisRecord} from '../src/features/ai/domain.ts';import {LocalArtifactStore} from '../transport/artifact-store.ts';
const root=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/advancement-1/gateway-unit/',import.meta.url));const token='controlled-persistence-gateway-token';
async function until(check:()=>unknown){const deadline=Date.now()+4000;while(!check()){if(Date.now()>deadline)throw Error('Timed out');await new Promise(r=>setTimeout(r,10));}}
test('authenticated Core reopen exposes Run/Step/Evidence, Analysis/Approval and Issue Link without another external write',async()=>{
 fs.mkdirSync(root,{recursive:true});const dir=fs.mkdtempSync(path.join(root,'case-')),provider=new FakeIssueProvider(),opts={port:0,agentToken:token,studioToken:token,storagePath:path.join(dir,'core.sqlite'),storageKey:Buffer.alloc(32,9),artifactRoot:path.join(dir,'evidence'),issueProvider:provider};let server=await startCoreServer(opts);const client=new RemoteCoreClient(),now=new Date().toISOString(),project={id:crypto.randomUUID(),name:'History reopen',description:'',workspacePath:null,browserFolder:true,repositoryUrl:'https://github.com/owner/test.git',defaultBranch:null,framework:null,runtime:null,packageManager:null,projectType:null,gitEnabled:true,createdAt:now,updatedAt:now,lastOpenedAt:null};
 try{client.connect(`ws://127.0.0.1:${server.port}/studio`,token,project);await until(()=>client.connected);const a=server.service.registerAgent({name:'controlled',platform:'windows',architecture:'x86_64',capabilities:{cpuCores:2,memoryMiB:2048,gpu:false,docker:false,pty:false,runtimes:{},browsers:[]}});server.service.updateAgentStatus(a.id,'idle');const job=await server.service.createJob(project.id,{name:'failed fixture',requirements:{},payload:{task:'smoke',steps:[{name:'smoke',executable:'node',args:['-v'],cwd:'.'}]}}),assignment=server.service.dispatch(project.id,job.id)!;server.service.acceptExecution(project.id,assignment.run.id);server.service.completeExecution(project.id,assignment.run.id,'failed',1,'Controlled failure',now,now);const step=server.service.snapshot(project.id).steps[0],bytes=Buffer.from('{"controlledEvidence":true}');async function* chunks(){yield bytes;}const meta=await new LocalArtifactStore(opts.artifactRoot).put({id:crypto.randomUUID(),runId:assignment.run.id,runStepId:step.id,projectId:project.id,type:'test-report',name:'report.json',size:bytes.length,checksum:createHash('sha256').update(bytes).digest('hex'),mimeType:'application/json',createdAt:now,location:''},chunks());server.service.repository.transaction(tx=>tx.artifacts.save(meta));
 const record:AnalysisRecord={id:crypto.randomUUID(),projectId:project.id,conversationId:crypto.randomUUID(),runId:assignment.run.id,model:'controlled-no-provider',createdAt:now,context:[],originals:{'a.ts':'baseline'},result:{summary:'Controlled failure',observedFailure:'fixture',candidates:[],evidence:[],uncertainty:'controlled',relatedFiles:[],proposal:[{path:'a.ts',proposed:'fixed',rationale:'controlled',impact:'controlled',tests:['smoke']}]}};await client.historyRequest({action:'put',kind:'analysis',id:record.id,version:0,value:record},project.id);const fixes=new FixService(project.id,{read:async()=>({path:'a.ts',content:'baseline',size:8,modified:0}),write:async()=>{throw Error('Source writes forbidden in persistence verification');}}),attempt=await fixes.propose(record);await fixes.approve(attempt.id,['a.ts']);await client.historyRequest({action:'put',kind:'attempt',id:attempt.id,version:0,value:fixes.get(attempt.id)},project.id);
 const candidate=await client.issueRequest<{id:string;version:number}>({action:'build',context:{source:'failed-run',runId:assignment.run.id}},project.id);await client.issueRequest({action:'search',id:candidate.id},project.id);await client.issueRequest({action:'approve',id:candidate.id,version:candidate.version,repository:'owner/test'},project.id);await client.issueRequest({action:'create',id:candidate.id},project.id);assert.equal(provider.writes,1);
 client.disconnect();await server.close();server=await startCoreServer(opts);client.connect(`ws://127.0.0.1:${server.port}/studio`,token,project);await until(()=>client.connected);const snap=client.snapshot(project.id);assert.equal(snap.runs[0].status,'failed');assert.equal(snap.steps[0].status,'failed');assert.equal(snap.artifacts[0].id,meta.id);assert.equal((await client.artifact(snap.artifacts[0],project.id)).size,bytes.length);const loaded=await client.historyRequest<{version:number;value:ReturnType<FixService['get']>}>({action:'get',kind:'attempt',id:attempt.id},project.id);assert.equal(loaded.value.approval?.proposalId,attempt.proposalId);assert.equal((await client.historyRequest<{value:AnalysisRecord}>({action:'get',kind:'analysis',id:record.id},project.id)).value.id,record.id);const link=await client.issueRequest<{externalIssue:{number:number}}>({action:'get',id:candidate.id},project.id);assert.equal(link.externalIssue.number,1);await client.issueRequest({action:'create',id:candidate.id},project.id);assert.equal(provider.writes,1);
 }finally{client.disconnect();await server.close();assert.ok(path.resolve(dir).startsWith(path.resolve(root)+path.sep));fs.rmSync(dir,{recursive:true,force:true});}
});
