import test from 'node:test';
import assert from 'node:assert/strict';
import {CoreService} from '../src/features/core/service.ts';
import {InMemoryCoreRepository} from '../src/features/core/repository.ts';
import {GraphExecutionService} from '../transport/graph-execution.ts';
import {initialGraph,newNode,type ProjectGraph} from '../src/features/orchestration/domain.ts';
import type {Project} from '../src/features/projects/types/project.ts';
import {CoreStore} from '../transport/storage.ts';
const sources={'project.yml':JSON.stringify({version:1,project:{name:'graph',type:'node'}}),'tasks.yml':JSON.stringify({hello:{command:'node',args:['-v']}})};
const caps={cpuCores:2,memoryMiB:2048,docker:false,gpu:false,pty:false,runtimes:{node:'24'},browsers:[]};
function fixture(durable=false){const core=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id,name:'graph'} as Project)});core.connectAgent('agent-a',{name:'A',platform:'windows',architecture:'x86_64',capabilities:caps});core.connectAgent('agent-b',{name:'B',platform:'windows',architecture:'x86_64',capabilities:caps});const graph=initialGraph('p');graph.nodes.push({...newNode('agent','agent',2),reference:'agent-b'},{...newNode('task','task',3),reference:'hello'},newNode('approval','review',4),{...newNode('task','task2',5),reference:'hello'});graph.edges.push({id:'host',from:'current-pc',to:'agent',relation:'hosts'},{id:'perform',from:'role-implementation',to:'task',relation:'performs'},{id:'perform2',from:'role-implementation',to:'task2',relation:'performs'},{id:'next',from:'task',to:'review',relation:'success'},{id:'approved',from:'review',to:'task2',relation:'success'});let saved:unknown;let broken=false,interrupt=false;const store=durable?new CoreStore(':memory:',new Uint8Array(32).fill(3)):undefined;let dispatching=true;let permit=true;let clock=Date.now();const persistence={load:()=>store?.get('graph')??saved,save:(value:unknown)=>{if(broken||interrupt&&core.snapshot('p').jobs.length){interrupt=false;throw Error('Write failure');}if(store)store.put('graph',value);else saved=structuredClone(value);}};const authority=()=>{if(!permit)throw Error('Forbidden');};const make=()=>new GraphExecutionService(core,(p,j)=>dispatching?core.dispatch(p,j):null,(p,j)=>core.cancelJob(p,j),persistence,authority,()=>clock);const service=make();const pub=(input=sources)=>service.request('p','publish',{graph,sources:input,expectedRevision:0},'user');const start=async()=>{const d=service.overview('p').definition!;return service.request('p','start',{revision:d.revision,checksum:d.checksum,entryNodeId:'task',requestId:'execution'},'user');};const finish=(pass=true)=>{const run=core.snapshot('p').runs.findLast(r=>r.status==='pending')!;core.acceptExecution('p',run.id);const now=new Date().toISOString();core.completeExecution('p',run.id,pass?'passed':'failed',pass?0:1,'result',now,now);};return {pauseDispatch:()=>{dispatching=false;},resumeDispatch:()=>{dispatching=true;},core,graph,service,pub,start,finish,make,store,break:()=>{broken=true;},interrupt:()=>{interrupt=true;},deny:()=>{permit=false;},allow:()=>{permit=true;},expire:()=>{clock+=600001;}};}
test('publish is read/propose only; immutable version, pinned assignment and approval gate',async()=>{const f=fixture();await f.pub();assert.equal(f.core.snapshot('p').jobs.length,0);await f.start();assert.equal(f.core.snapshot('p').runs[0].agentId,'agent-b');f.finish();await f.service.tick();let e=f.service.overview('p').executions[0];const approval=e.activations.find(a=>a.status==='approval')!;assert.equal(f.core.snapshot('p').jobs.length,1);await assert.rejects(f.service.request('p','approve',{executionId:e.id,activationId:approval.id,revision:99,checksum:e.checksum},'user'));await f.service.request('p','approve',{executionId:e.id,activationId:approval.id,revision:e.revision,checksum:e.checksum},'user');f.finish();await f.service.tick();e=f.service.overview('p').executions[0];assert.equal(e.status,'passed');assert.equal(e.activations.find(a=>a.id===approval.id)!.approvedBy,'user');});
test('entry cannot bypass approval and optimistic revisions conflict',async()=>{const f=fixture();await f.pub();const d=f.service.overview('p').definition!;await assert.rejects(f.service.request('p','publish',{graph:f.graph,sources,expectedRevision:0},'user'),/Revision conflict/);await assert.rejects(f.service.request('p','start',{revision:d.revision,checksum:d.checksum,entryNodeId:'task2',requestId:'bypass'},'user'),/cannot be bypassed/);assert.equal(f.core.snapshot('p').jobs.length,0);});
test('failure feedback has bounded independent history and per-activation approval',async()=>{const f=fixture();f.graph.edges.push({id:'feedback',from:'task2',to:'task',relation:'failure'});await f.pub();await f.start();for(let i=0;i<3;i++){f.finish();await f.service.tick();const e=f.service.overview('p').executions[0],a=e.activations.findLast(a=>a.status==='approval')!;assert(a);await f.service.request('p','approve',{executionId:e.id,activationId:a.id,revision:e.revision,checksum:e.checksum},'user');f.finish(false);await f.service.tick();await f.service.tick();}const e=f.service.overview('p').executions[0];assert.equal(e.status,'failed');assert.match(e.reason!,/Retry limit/);assert.equal(e.activations.filter(a=>a.nodeId==='task').length,3);assert.equal(e.activations.filter(a=>a.approvedBy).length,3);});
test('restart pauses progression; no duplicate job on resume or lost intent linkage',async()=>{const f=fixture(true);try{await f.pub();await f.start();const restarted=f.make();assert.equal(restarted.overview('p').executions[0].status,'paused');await restarted.tick();assert.equal(f.core.snapshot('p').jobs.length,1);await restarted.request('p','resume',{executionId:'execution'},'user');assert.equal(f.core.snapshot('p').jobs.length,1);f.finish();await restarted.tick();assert.equal(restarted.overview('p').executions[0].activations.filter(a=>a.status==='approval').length,1);}finally{f.store?.close();}});
test('cancel pending approval stops progression; project isolation and current authority enforced',async()=>{const f=fixture();await f.pub();await f.start();f.finish();await f.service.tick();await assert.rejects(f.service.request('other','cancel',{executionId:'execution'},'user'));f.deny();await assert.rejects(f.service.request('p','cancel',{executionId:'execution'},'user'));await f.service.tick();assert.equal(f.service.overview('p').executions[0].status,'paused');f.allow();await f.service.request('p','cancel',{executionId:'execution'},'user');assert.equal(f.service.overview('p').executions[0].status,'cancelled');assert.equal(f.core.snapshot('p').jobs.length,1);});
test('offline assigned Agent never falls back to unrelated device; deadline cancels safely',async()=>{const f=fixture();f.core.observeAgent('agent-b',false);await f.pub();await f.start();assert.equal(f.core.snapshot('p').jobs.length,0);f.expire();await f.service.tick();assert.equal(f.service.overview('p').executions[0].status,'cancelled');});
test('persistence failure cannot acknowledge a publish or create an unapproved job',async()=>{const f=fixture();f.break();await assert.rejects(f.pub(),/Write failure/);assert.equal(f.service.overview('p').definition,null);assert.equal(f.core.snapshot('p').jobs.length,0);});
test('missing Agent and dangling Protocol refs reject publish; multi-parent join rejected',async()=>{const f=fixture();f.graph.nodes.find(n=>n.id==='agent')!.reference='missing';await assert.rejects(f.pub(),/registered Agent/);f.graph.nodes.find(n=>n.id==='agent')!.reference='agent-b';f.graph.nodes.find(n=>n.id==='task')!.reference='missing';await assert.rejects(f.pub(),/no longer exists/);});
test('same request identity is idempotent; new graph revision cannot reuse start identity',async()=>{const f=fixture();await f.pub();await f.start();await f.start();assert.equal(f.core.snapshot('p').jobs.length,1);const changed:ProjectGraph={...f.graph,projectKind:'web'};await f.service.request('p','publish',{graph:changed,sources,expectedRevision:1},'user');await assert.rejects(f.start(),/identity conflict/);});
test('lost job-link commit reconciles the durable activation without creating a second job',async()=>{const f=fixture();await f.pub();f.interrupt();await assert.rejects(f.start(),/Write failure/);assert.equal(f.core.snapshot('p').jobs.length,1);assert.equal(f.core.snapshot('p').runs.length,0);const recovered=f.make();await recovered.request('p','resume',{executionId:'execution'},'user');assert.equal(f.core.snapshot('p').jobs.length,1);assert.equal(f.core.snapshot('p').runs.length,1);assert.equal(recovered.overview('p').executions[0].activations[0].jobId,f.core.snapshot('p').jobs[0].id);});
test('team job quotas keep a stable user identity rather than treating each session as a user',async()=>{const f=fixture();await f.pub();const d=f.service.overview('p').definition!;await f.service.request('p','start',{revision:d.revision,checksum:d.checksum,entryNodeId:'task',requestId:'team-execution'},JSON.stringify({userId:'developer',sessionId:'one-session'}));assert.equal(f.core.snapshot('p').jobs[0].createdBy,'developer');});
test('Core explains assigned Agent status and capability waits; unrelated Agents cannot satisfy them',async()=>{
 const f=fixture();await f.pub({...sources,'tasks.yml':JSON.stringify({hello:{command:'node',args:['-v'],requirements:{runtimes:{node:'>=24'}}}})});f.core.updateCapabilities('agent-b',{...caps,runtimes:{}});f.core.updateAgentStatus('agent-b','busy');await f.start();
 let a=f.service.overview('p').executions[0].activations[0];assert.equal(a.status,'ready');assert.deepEqual(a.waitingReasons,['Agent is busy','node version insufficient']);assert.equal(f.core.snapshot('p').jobs.length,0);
 f.core.updateAgentStatus('agent-b','idle');await f.service.tick();a=f.service.overview('p').executions[0].activations[0];assert.deepEqual(a.waitingReasons,['node version insufficient']);assert.equal(f.core.snapshot('p').jobs.length,0);
 f.core.updateCapabilities('agent-b',caps);await f.service.tick();a=f.service.overview('p').executions[0].activations[0];assert.equal(a.agentId,'agent-b');assert.equal(a.waitingReasons,undefined);assert.equal(f.core.snapshot('p').jobs.length,1);
});
test('waiting reasons survive durable restart, stay paused and clear on cancellation',async()=>{
 const f=fixture(true);try{await f.pub();f.core.observeAgent('agent-b',false);await f.start();const restarted=f.make();let e=restarted.overview('p').executions[0];assert.equal(e.status,'paused');assert.deepEqual(e.activations[0].waitingReasons,['Agent is offline']);await restarted.tick();assert.equal(f.core.snapshot('p').jobs.length,0);await restarted.request('p','cancel',{executionId:e.id},'user');e=restarted.overview('p').executions[0];assert.equal(e.status,'cancelled');assert.equal(e.activations[0].waitingReasons,undefined);}finally{f.store?.close();}
});
test('queued work reports pinned Agent loss, preserves job identity and clears reasons on dispatch',async()=>{
 const f=fixture();await f.pub();f.pauseDispatch();await f.start();await f.service.tick();let a=f.service.overview('p').executions[0].activations[0];const jobId=a.jobId;
 assert.equal(a.status,'queued');assert.deepEqual(a.waitingReasons,['Waiting for Core dispatch.']);
 f.core.observeAgent('agent-b',false);f.resumeDispatch();await f.service.tick();a=f.service.overview('p').executions[0].activations[0];assert.deepEqual(a.waitingReasons,['Agent is offline']);assert.equal(a.jobId,jobId);assert.equal(f.core.snapshot('p').jobs.length,1);assert.equal(f.core.snapshot('p').runs.length,0);
 f.core.observeAgent('agent-b',true);await f.service.tick();a=f.service.overview('p').executions[0].activations[0];assert.equal(a.status,'running');assert.equal(a.waitingReasons,undefined);assert.equal(a.jobId,jobId);assert.equal(f.core.snapshot('p').runs[0].agentId,'agent-b');
});
test('queued waiting work cancellation clears diagnostics and creates no Run',async()=>{
 const f=fixture();await f.pub();f.pauseDispatch();await f.start();await f.service.tick();await f.service.request('p','cancel',{executionId:'execution'},'user');const e=f.service.overview('p').executions[0];assert.equal(e.status,'cancelled');assert.equal(e.activations[0].waitingReasons,undefined);assert.equal(f.core.snapshot('p').jobs[0].status,'cancelled');assert.equal(f.core.snapshot('p').runs.length,0);
});
test('resume rejects replaced Protocol input and preserves completed history and Job identities',async()=>{
 const f=fixture();await f.pub();await f.start();f.finish();await f.service.tick();const paused=f.make(),before=paused.overview('p').executions[0],jobs=f.core.snapshot('p').jobs.length;
 await paused.request('p','publish',{graph:f.graph,sources:{...sources,'tasks.yml':JSON.stringify({hello:{command:'node',args:['--version']}})},expectedRevision:1},'user');
 await assert.rejects(paused.request('p','resume',{executionId:before.id},'user'),/saved graph version/);
 assert.deepEqual(paused.overview('p').executions[0],before);assert.equal(f.core.snapshot('p').jobs.length,jobs);
});
test('expired paused execution cannot resume or create additional Jobs',async()=>{
 const f=fixture();await f.pub();await f.start();const paused=f.make();f.expire();await assert.rejects(paused.request('p','resume',{executionId:'execution'},'user'),/already finished/);assert.equal(paused.overview('p').executions[0].status,'paused');assert.equal(f.core.snapshot('p').jobs.length,1);
});
test('reviewed recovery keeps passed results and waiting approval without replaying completed work',async()=>{
 const f=fixture();await f.pub();await f.start();f.finish();await f.service.tick();const recovered=f.make(),before=recovered.overview('p').executions[0].activations,jobs=f.core.snapshot('p').jobs.length;
 await recovered.request('p','resume',{executionId:'execution'},'user');assert.deepEqual(recovered.overview('p').executions[0].activations,before);assert.equal(f.core.snapshot('p').jobs.length,jobs);assert.equal(before.filter(a=>a.status==='passed').length,1);assert.equal(before.filter(a=>a.status==='approval').length,1);
});
