import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {verifiedGraphFix,failedGraphFix,graphFixScope} from '../src/features/orchestration/graph-fix.ts';
import {FixService,contentHash,type FixAttempt} from '../src/features/ai/fix-service.ts';
import {HistoryStore} from '../transport/history.ts';
import type {GraphActivation} from '../src/features/orchestration/execution.ts';
import type {AnalysisRecord} from '../src/features/ai/domain.ts';
import type {CoreSnapshot,Job,Run} from '../src/features/core/domain.ts';
import type {WorkspaceSnapshot} from '../src/features/ai/snapshot.ts';
import {GraphExecutionService} from '../transport/graph-execution.ts';
import {CoreService} from '../src/features/core/service.ts';
import {InMemoryCoreRepository} from '../src/features/core/repository.ts';
import {initialGraph,newNode} from '../src/features/orchestration/domain.ts';
import {emptyAIConfigurations,newAIConfiguration} from '../src/features/orchestration/ai-config.ts';
import type {Project} from '../src/features/projects/types/project.ts';
async function fixture(){
 const project=randomUUID(),execution='fix-execution',activation=randomUUID(),lease=randomUUID(),disk=new Map([['service.ts','return false;']]);
 const files={read:async(path:string)=>({path,content:disk.get(path)!,size:20,modified:0}),write:async(path:string,value:string,expected:string)=>{assert.equal(disk.get(path),expected);disk.set(path,value);}};
 const history=new HistoryStore(),fix=new FixService(project,files),record:AnalysisRecord={id:randomUUID(),projectId:project,conversationId:randomUUID(),model:'fixture',createdAt:new Date().toISOString(),task:{nodeId:'analysis',profileId:'ai',label:'Repair',graph:{executionId:execution,activationId:activation,leaseId:lease}},context:[],originals:Object.fromEntries(disk),result:{summary:'Proposal',observedFailure:'',candidates:[],evidence:[],relatedFiles:[],proposal:[{path:'service.ts',proposed:'return true;',rationale:'Controlled fixture',impact:'test',tests:['unit']}],uncertainty:'Not real model'}};
 await history.put(project,'analysis',record.id,0,record);fix.setPersistence({save:async a=>{const old=history.get(project,'attempt',a.id);await history.put(project,'attempt',a.id,old?.version??0,a);}});
 const proposed=await fix.propose(record);assert.equal(disk.get('service.ts'),'return false;');await fix.approve(proposed.id,['service.ts']);await fix.apply(proposed.id);
 const a=fix.get(proposed.id),source:WorkspaceSnapshot={provider:'snapshot',snapshotId:randomUUID(),projectId:project,proposalId:a.proposalId,attempt:a.attempt,baseRevision:'fixture-base',changedFiles:['service.ts'],files:[{path:'service.ts',content:'return true;',checksum:await contentHash('return true;')}],checksum:''};source.checksum=await contentHash(JSON.stringify([source.snapshotId,source.projectId,source.proposalId,source.attempt,source.baseRevision,source.changedFiles,...source.files.map(f=>[f.path,f.checksum])]));await fix.recordSnapshot(a.id,source);
 const jobId=randomUUID(),runId=randomUUID(),plan={id:randomUUID(),projectId:project,testName:'unit',type:'unit' as const,requirements:{},environment:{},timeout:60,steps:[{name:'Snapshot',stage:'source' as const,executable:'snapshot',args:[],cwd:'.',source:{provider:'snapshot' as const,repository:'snapshot:'+source.snapshotId,revision:source.baseRevision,snapshot:source}}]};const approval=await fix.approveExecution(a.id,'remote-test','unit',plan);await fix.beginApprovedRetest(a.id,approval.id,plan);fix.setRetestJob(a.id,jobId);fix.linkRetest(a.id,runId);fix.retestResult(a.id,'passed');await fix.flush();
 const job:Job={id:jobId,projectId:project,idempotencyKey:a.id,name:'unit',type:'task',status:'succeeded',requirements:{},payload:{task:'unit',steps:plan.steps,testPlan:plan},priority:0,queuedAt:record.createdAt,createdAt:record.createdAt,updatedAt:record.createdAt,agentId:'controlled-agent',sourceJobId:null,attempt:1,maxAttempts:1,cancellationRequestedAt:null};
 const run:Run={id:runId,jobId,projectId:project,agentId:'controlled-agent',status:'passed',startedAt:record.createdAt,finishedAt:record.createdAt,exitCode:0,createdAt:record.createdAt,result:{summary:'Controlled Core record'},revision:{repository:'snapshot:'+source.snapshotId,branch:'workspace',commit:source.checksum,snapshotId:source.snapshotId,proposalId:a.proposalId,attempt:a.attempt,contentChecksum:source.checksum}};
 const snapshot:CoreSnapshot={jobs:[job],runs:[run],agents:[],steps:[],events:[],artifacts:[]},active:GraphActivation={id:activation,nodeId:'analysis',attempt:1,status:'ai-fix-review',analysisId:record.id,leaseId:lease};
 return{project,execution,record,history,fix,attempt:fix.get(a.id),disk,snapshot,active,source};
}
test('approved real patch + matching controlled Core Run proof is accepted; explicit revert restores baseline',async()=>{const f=await fixture();assert.equal(f.disk.get('service.ts'),'return true;');assert.equal(verifiedGraphFix(f.project,f.execution,f.active,f.attempt,f.snapshot).runId,f.snapshot.runs[0].id);await f.fix.revert(f.attempt.id);assert.equal(f.disk.get('service.ts'),'return false;');assert.throws(()=>verifiedGraphFix(f.project,f.execution,f.active,f.fix.get(f.attempt.id),f.snapshot));});
test('AI status or local validation without real remote Run cannot pass graph fix',async()=>{const f=await fixture();assert.throws(()=>verifiedGraphFix(f.project,f.execution,f.active,f.attempt,{...f.snapshot,runs:[]}));for(const status of ['running','failed','cancelled','timeout'] as const){const snapshot=structuredClone(f.snapshot);snapshot.runs[0].status=status;assert.throws(()=>verifiedGraphFix(f.project,f.execution,f.active,f.attempt,snapshot));}});
test('unrelated Run, checksum, snapshot, proposal, project, activation, lease and idempotency key are rejected',async()=>{const f=await fixture();for(const change of [(s:CoreSnapshot)=>{s.runs[0].revision!.snapshotId=randomUUID();},(s:CoreSnapshot)=>{s.runs[0].revision!.commit='a'.repeat(64);},(s:CoreSnapshot)=>{s.runs[0].revision!.proposalId=randomUUID();},(s:CoreSnapshot)=>{s.runs[0].projectId=randomUUID();},(s:CoreSnapshot)=>{s.jobs[0].idempotencyKey=randomUUID();},(s:CoreSnapshot)=>{s.jobs[0].status='failed';}]){const s=structuredClone(f.snapshot);change(s);assert.throws(()=>verifiedGraphFix(f.project,f.execution,f.active,f.attempt,s));}for(const key of ['activationId','leaseId','executionId','nodeId'] as const){const a=structuredClone(f.attempt);a.graph![key]='wrong';assert.throws(()=>verifiedGraphFix(f.project,f.execution,f.active,a,f.snapshot));}});
test('stored graph lineage cannot be forged or reassigned to another analysis',async()=>{const f=await fixture(),a=structuredClone(f.attempt);a.graph!.leaseId=randomUUID();await assert.rejects(f.history.put(f.project,'attempt',a.id,f.history.get(f.project,'attempt',a.id)!.version,a),/lineage/);assert.equal(graphFixScope({id:f.execution,projectId:f.project},f.active,[f.attempt,{...f.attempt,id:randomUUID(),analysisId:randomUUID()}]).length,1);});
test('graph attempts have independent retry groups and retain their lineage through persistence',async()=>{const f=await fixture();const another={...f.record,id:randomUUID(),task:{...f.record.task!,graph:{...f.record.task!.graph!,executionId:'another-execution'} }};await f.history.put(f.project,'analysis',another.id,0,another);assert.equal((await f.fix.propose(another)).attempt,1);assert.equal((await f.fix.propose(f.record)).attempt,2);assert.equal((await f.fix.propose(f.record)).attempt,3);await assert.rejects(f.fix.propose(f.record),/RETRY_LIMIT/);assert.equal((f.history.get(f.project,'attempt',f.attempt.id)?.value as FixAttempt).graph?.activationId,f.active.id);});
test('Core verified-fix gate follows success only with matching persisted attempt + Core Run; duplicate finish rejected',async()=>{
 const f=await fixture(),core=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id,name:'Fixture'} as Project)});core.repository.transaction(tx=>{tx.jobs.save(f.snapshot.jobs[0]);tx.runs.save(f.snapshot.runs[0]);});
 const graph=initialGraph(f.project);graph.nodes.push(newNode('task','analysis',2),newNode('approval','review',3));graph.edges.push({id:'performs',from:'role-implementation',to:'analysis',relation:'performs'},{id:'next',from:'analysis',to:'review',relation:'success'});
 const profiles={...emptyAIConfigurations(f.project),profiles:[{...newAIConfiguration('ai'),provider:'local' as const,connection:'local' as const,connectionRef:'local',completion:'verified-fix' as const}],bindings:{analysis:'ai'}};
 const service=new GraphExecutionService(core,()=>{},()=>{},undefined,()=>{},Date.now,undefined,{connections:()=>[{id:'local',provider:'local',connection:'local',adapter:'ollama-local',model:'fixture'}],analysis:()=>f.record,attempt:()=>f.attempt});
 await service.request(f.project,'publish',{graph,sources:{'project.yml':JSON.stringify({version:1,project:{name:'Fixture',type:'node'}})},aiConfigurations:profiles,expectedRevision:0},'user');const d=service.overview(f.project).definition!;await service.request(f.project,'start',{revision:1,checksum:d.checksum,entryNodeId:'analysis',requestId:f.execution},'user');let a=service.overview(f.project).executions[0].activations[0];const input={executionId:f.execution,activationId:a.id,revision:1,checksum:d.checksum};await service.request(f.project,'ai-start',input,'user');a=service.overview(f.project).executions[0].activations[0];f.record.task!.graph={executionId:f.execution,activationId:a.id,leaseId:a.leaseId!};f.record.createdAt=new Date().toISOString();f.attempt.graph={...f.record.task!.graph,nodeId:'analysis'};await service.request(f.project,'ai-complete',{...input,leaseId:a.leaseId,analysisId:f.record.id},'user');await service.request(f.project,'ai-fix-complete',{...input,attemptId:f.attempt.id},'user');assert.equal(service.overview(f.project).executions[0].activations[1].status,'approval');await assert.rejects(service.request(f.project,'ai-fix-complete',{...input,attemptId:f.attempt.id},'user'));assert.equal(service.overview(f.project).executions[0].activations.length,2);
});

test('failed remote retest creates a bounded fresh review; stale or unrelated analysis cannot complete it',async()=>{
 const f=await fixture(),core=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id,name:'Fixture'} as Project)});core.repository.transaction(tx=>{tx.jobs.save(f.snapshot.jobs[0]);tx.runs.save(f.snapshot.runs[0]);});
 const graph=initialGraph(f.project);graph.nodes.push(newNode('task','analysis',2),newNode('approval','review',3));graph.edges.push({id:'performs',from:'role-implementation',to:'analysis',relation:'performs'},{id:'next',from:'analysis',to:'review',relation:'success'});
 const profiles={...emptyAIConfigurations(f.project),profiles:[{...newAIConfiguration('ai'),provider:'local' as const,connection:'local' as const,connectionRef:'local',completion:'verified-fix' as const}],bindings:{analysis:'ai'}};
 const service=new GraphExecutionService(core,()=>{},()=>{},undefined,()=>{},Date.now,undefined,{connections:()=>[{id:'local',provider:'local',connection:'local',adapter:'ollama-local',model:'fixture'}],analysis:()=>f.record,attempt:()=>f.attempt});
 await service.request(f.project,'publish',{graph,sources:{'project.yml':JSON.stringify({version:1,project:{name:'Fixture',type:'node'}})},aiConfigurations:profiles,expectedRevision:0},'user');const d=service.overview(f.project).definition!;await service.request(f.project,'start',{revision:1,checksum:d.checksum,entryNodeId:'analysis',requestId:f.execution},'user');let a=service.overview(f.project).executions[0].activations[0];const input={executionId:f.execution,activationId:a.id,revision:1,checksum:d.checksum};await service.request(f.project,'ai-start',input,'user');a=service.overview(f.project).executions[0].activations[0];f.record.task!.graph={executionId:f.execution,activationId:a.id,leaseId:a.leaseId!};f.record.createdAt=new Date().toISOString();f.attempt.graph={...f.record.task!.graph,nodeId:'analysis'};await service.request(f.project,'ai-complete',{...input,leaseId:a.leaseId,analysisId:f.record.id},'user');f.attempt.status='failed';f.snapshot.jobs[0].status='failed';f.snapshot.runs[0].status='failed';f.snapshot.runs[0].exitCode=1;core.repository.transaction(tx=>{tx.jobs.save(f.snapshot.jobs[0]);tx.runs.save(f.snapshot.runs[0]);});
 await service.request(f.project,'ai-reanalyze',{...input,attemptId:f.attempt.id},'user');
 let next=service.overview(f.project).executions[0].activations[1];assert.equal(next.status,'ai-review');assert.equal(next.leaseId,undefined);assert.equal(next.failure?.runId,f.attempt.retestRunId);assert.equal(next.failure?.attemptId,f.attempt.id);assert.equal(service.overview(f.project).executions[0].activations[0].status,'failed');assert.equal(f.disk.get('service.ts'),'return true;');
 await assert.rejects(service.request(f.project,'ai-reanalyze',{...input,attemptId:f.attempt.id},'user'));assert.equal(service.overview(f.project).executions[0].activations.length,2);
 const nextInput={...input,activationId:next.id};await service.request(f.project,'ai-start',nextInput,'user');next=service.overview(f.project).executions[0].activations[1];assert.notEqual(next.leaseId,a.leaseId);
 await assert.rejects(service.request(f.project,'ai-complete',{...nextInput,leaseId:next.leaseId,analysisId:f.record.id},'user'),/lineage/);
 f.record.task!.graph={executionId:f.execution,activationId:next.id,leaseId:next.leaseId!};f.record.task!.failure=next.failure;f.record.runId=next.failure!.runId;f.record.createdAt=new Date().toISOString();
 await service.request(f.project,'ai-complete',{...nextInput,leaseId:next.leaseId,analysisId:f.record.id},'user');
 f.attempt.graph={...f.record.task!.graph,nodeId:'analysis'};f.attempt.attempt=3;f.snapshot.runs[0].revision!.attempt=3;core.repository.transaction(tx=>tx.runs.save(f.snapshot.runs[0]));
 await assert.rejects(service.request(f.project,'ai-reanalyze',{...nextInput,attemptId:f.attempt.id},'user'),/limit/);assert.equal(service.overview(f.project).executions[0].activations[1].status,'ai-fix-review');
});

test('failed retest proof rejects cancellation, missing Run, mismatched snapshot and successful status',async()=>{const f=await fixture();assert.throws(()=>failedGraphFix(f.project,f.execution,f.active,f.attempt,f.snapshot));f.attempt.status='failed';f.snapshot.jobs[0].status='failed';f.snapshot.runs[0].status='timeout';assert.equal(failedGraphFix(f.project,f.execution,f.active,f.attempt,f.snapshot).runId,f.attempt.retestRunId);for(const mutate of [(s:CoreSnapshot)=>{s.runs=[];},(s:CoreSnapshot)=>{s.runs[0].status='cancelled';},(s:CoreSnapshot)=>{s.runs[0].revision!.snapshotId=randomUUID();}]){const s=structuredClone(f.snapshot);mutate(s);assert.throws(()=>failedGraphFix(f.project,f.execution,f.active,f.attempt,s));}});
test('failure analysis history requires bounded exact Run lineage and keeps original origin',async()=>{const f=await fixture();const record=structuredClone(f.record);record.id=randomUUID();record.runId=f.attempt.retestRunId;record.task!.failure={runId:record.runId!,originalRunId:randomUUID(),attemptId:f.attempt.id,previousAnalysisId:f.record.id};await f.history.put(f.project,'analysis',record.id,0,record);assert.equal((await f.fix.propose(record)).originRunId,record.task!.failure.originalRunId);record.id=randomUUID();record.task!.failure.runId=randomUUID();await assert.rejects(f.history.put(f.project,'analysis',record.id,0,record),/lineage/);});

test('graph proof distinguishes verified content identity from transport manifest checksum',async()=>{const f=await fixture();f.snapshot.runs[0].revision!.contentChecksum='b'.repeat(64);assert.equal(verifiedGraphFix(f.project,f.execution,f.active,f.attempt,f.snapshot).snapshotId,f.source.snapshotId);});

test('analysis Source identity persists exactly and malformed or foreign Run identity is rejected',async()=>{const f=await fixture(),record=structuredClone(f.record);record.id=randomUUID();record.runId=f.snapshot.runs[0].id;record.source={runId:record.runId,snapshotId:f.source.snapshotId,checksum:f.source.checksum};await f.history.put(f.project,'analysis',record.id,0,record);assert.deepEqual((f.history.get(f.project,'analysis',record.id)!.value as AnalysisRecord).source,record.source);record.id=randomUUID();record.source.runId=randomUUID();await assert.rejects(f.history.put(f.project,'analysis',record.id,0,record),/Source identity/);record.source.runId=record.runId;record.source.checksum='invalid';await assert.rejects(f.history.put(f.project,'analysis',record.id,0,record),/Source identity/);});
