import test from 'node:test';
import assert from 'node:assert/strict';
import {artifactGraphFixture as fixture} from './helpers/build-artifact-fixture.ts';
import {artifactProducerActivation} from '../src/features/orchestration/artifact-lineage.ts';
import type {GraphExecution} from '../src/features/orchestration/execution.ts';

test('artifact runtime stays disabled until actual Agent transport integration; publish has no side effect',async()=>{
 const f=await fixture(false);await assert.rejects(f.publish(),/runtime is not enabled/);assert.equal(f.service.overview(f.projectId).definition,null);assert.equal(f.core.snapshot(f.projectId).jobs.length,0);
});
test('artifact consumer requires a unique declared success ancestor; no disconnected/failure producer',async()=>{
 const f=await fixture();f.graph.edges=f.graph.edges.filter(e=>e.id!=='built');await assert.rejects(f.publish(),/success-ancestor producer/);assert.equal(f.core.snapshot(f.projectId).jobs.length,0);
 const g=await fixture();g.graph.edges.find(e=>e.id==='built')!.relation='failure';await assert.rejects(g.publish(),/success-ancestor producer/);
});
test('Core derives producer and consumer lineage from real state transitions; env cannot spoof grant identity',async()=>{
 const f=await fixture();await f.publish();await f.start();const producerRun=f.core.snapshot(f.projectId).runs[0],source=f.orchestrator.next(producerRun.id)!;f.orchestrator.complete(producerRun.id,source.step.id,'passed',0,undefined,{repository:source.command.source!.repository,branch:'controlled',commit:f.reference.checksum,snapshotId:f.reference.snapshotId,proposalId:f.reference.proposalId,attempt:1});const producer=f.orchestrator.next(producerRun.id)!;
 const origin=f.service.buildArtifactOrigin(producer.job.id,producer.step.id);assert.equal(origin.origin.producerNodeId,'producer');assert.equal(origin.origin.snapshotId,f.reference.snapshotId);assert.equal(origin.origin.sourceChecksum,f.reference.checksum);assert.equal(origin.origin.producerRunId,producerRun.id);f.core.repository.transaction(tx=>{const job=tx.jobs.get(producer.job.id)!;job.payload.steps[producer.step.order].buildArtifacts!.outputs[0].path='other.exe';tx.jobs.save(job);});assert.throws(()=>f.service.buildArtifactOrigin(producer.job.id,producer.step.id),/differs from the published plan/);f.core.repository.transaction(tx=>{const job=tx.jobs.get(producer.job.id)!;job.payload.steps[producer.step.order].buildArtifacts!.outputs[0].path='out/app.exe';tx.jobs.save(job);});assert.notEqual(producer.command.env!.TASTEDEV_GRAPH_CONTEXT,'spoof');assert.throws(()=>f.service.buildArtifactOrigin(producer.job.id,source.step.id),/active declared step/);
 f.orchestrator.complete(producerRun.id,producer.step.id,'passed',0);let step;while((step=f.orchestrator.next(producerRun.id)))f.orchestrator.complete(producerRun.id,step.step.id,'passed',0);f.orchestrator.finish(producerRun.id);await f.service.tick();assert.throws(()=>f.service.buildArtifactOrigin(producer.job.id,producer.step.id));assert.equal(f.core.snapshot(f.projectId).jobs.length,1);
 const execution=f.service.overview(f.projectId).executions[0],approval=execution.activations.find(a=>a.status==='approval')!;await f.service.request(f.projectId,'approve',{executionId:execution.id,activationId:approval.id,revision:execution.revision,checksum:execution.checksum},'user');const consumerRun=f.core.snapshot(f.projectId).runs.find(r=>r.status==='pending')!,consumerSource=f.orchestrator.next(consumerRun.id)!;f.orchestrator.complete(consumerRun.id,consumerSource.step.id,'passed',0,undefined,{repository:consumerSource.command.source!.repository,branch:'controlled',commit:f.reference.checksum,snapshotId:f.reference.snapshotId,proposalId:f.reference.proposalId,attempt:1});const consumer=f.orchestrator.next(consumerRun.id)!;
 const proof=f.service.buildArtifactProducer(consumer.job.id,consumer.step.id,'build','desktop');assert.deepEqual(proof,origin.origin);assert.throws(()=>f.service.buildArtifactProducer(consumer.job.id,consumer.step.id,'build','other'),/not declared/);
 await f.service.request(f.projectId,'cancel',{executionId:execution.id},'user');assert.throws(()=>f.service.buildArtifactOrigin(consumer.job.id,consumer.step.id),/Active graph Snapshot/);
});
test('a newer failed producer attempt cannot reuse an older successful producer',async()=>{
 const f=await fixture();await f.publish();const definition=f.service.overview(f.projectId).definition!;const execution:GraphExecution={id:'execution',projectId:f.projectId,revision:definition.revision,checksum:definition.checksum,inputChecksum:definition.inputChecksum,status:'running',actor:'user',createdAt:'2026-10-05T00:00:00Z',deadline:'2026-10-05T00:10:00Z',definition:{...definition,plans:{producer:{name:'build',requirements:{},payload:{task:'build',steps:[{name:'build',taskReference:'build',executable:'node',args:[],cwd:'.',buildArtifacts:{outputs:[{name:'desktop',path:'app.exe'}],inputs:[]}}]}}}},activations:[{id:'old',nodeId:'producer',attempt:1,status:'passed',jobId:'j',runId:'r'},{id:'new',nodeId:'producer',attempt:2,status:'failed'},{id:'consumer',nodeId:'consumer',attempt:2,status:'running'}]};
 assert.throws(()=>artifactProducerActivation(execution,execution.activations[2],'build','desktop'),/verified successful Run/);
});
