import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {startCoreServer} from '../transport/server.ts';
import {initialGraph,newNode} from '../src/features/orchestration/domain.ts';
import type {GraphOverview} from '../src/features/orchestration/execution.ts';
const token='dummy-graph-verification-token';
async function until(test:()=>boolean){const end=Date.now()+5000;while(!test()){if(Date.now()>end)throw Error('Graph wire timeout');await new Promise(r=>setTimeout(r,10));}}
async function peer(port:number,route:string){const ws=new WebSocket(`ws://127.0.0.1:${port}/${route}`),messages:Record<string,unknown>[]=[];ws.on('message',data=>messages.push(JSON.parse(data.toString())));await once(ws,'open');return {ws,messages,send:(data:Record<string,unknown>)=>ws.send(JSON.stringify({protocolVersion:1,...data})),call:async(action:string,input?:unknown)=>{const requestId=randomUUID();ws.send(JSON.stringify({protocolVersion:1,type:'rpc',requestId,method:'graph',args:[action,input]}));await until(()=>messages.some(m=>m.requestId===requestId));const result=messages.find(m=>m.requestId===requestId)!;if(result.error)throw Error(String(result.error));return result.value as GraphOverview;}};}
test('authenticated real Core RPC: publish, scoped approval, simulated Agent result, durable restart',async()=>{
 const directory=path.resolve('../../../resources/verification/dev-01/tasks/tastedev-studio/node-orchestration/stage2-wire',randomUUID());fs.mkdirSync(directory,{recursive:true});const storagePath=path.join(directory,'core.sqlite'),storageKey=new Uint8Array(32).fill(7),options={port:0,agentToken:token,studioToken:token,storagePath,storageKey};let server=await startCoreServer(options);const peers:WebSocket[]=[];
 try{const studio=await peer(server.port,'studio'),agent=await peer(server.port,'agent');peers.push(studio.ws,agent.ws);
 studio.send({type:'subscribe',token,project:{id:'wire',name:'Wire graph'}});await until(()=>studio.messages.some(m=>m.type==='snapshot'));
 agent.send({type:'register',token,agentId:'wire-agent',name:'Wire Agent',agentVersion:'test-simulated',platform:'windows',architecture:'x86_64',capabilities:{cpuCores:2,memoryMiB:2048,docker:false,gpu:false,pty:false,runtimes:{node:'24'},browsers:[]}});await until(()=>agent.messages.some(m=>m.type==='registered'));
 const graph=initialGraph('wire');graph.nodes.push({...newNode('agent','agent',2),reference:'wire-agent'},newNode('approval','approval',3),{...newNode('task','task',4),reference:'hello'});graph.edges.push({id:'host',from:'current-pc',to:'agent',relation:'hosts'},{id:'perform',from:'role-implementation',to:'task',relation:'performs'},{id:'next',from:'approval',to:'task',relation:'success'});
 const definition=(await studio.call('publish',{graph,sources:{'project.yml':'version: 1\nproject: { name: graph, type: node }','tasks.yml':'hello: { command: node, args: ["-v"] }'},expectedRevision:0})).definition!;
 const result=await studio.call('start',{revision:definition.revision,checksum:definition.checksum,entryNodeId:'approval',requestId:'wire-execution'});assert.equal(server.service.snapshot('wire').jobs.length,0);assert.equal(agent.messages.filter(m=>m.type==='execute').length,0);
 const activation=result.executions[0].activations[0];await assert.rejects(studio.call('approve',{executionId:'wire-execution',activationId:activation.id,revision:2,checksum:definition.checksum}),/version conflict/);
 await studio.call('approve',{executionId:'wire-execution',activationId:activation.id,revision:1,checksum:definition.checksum});await until(()=>agent.messages.some(m=>m.type==='execute'));const execute=agent.messages.find(m=>m.type==='execute')!;agent.send({type:'accepted',jobId:execute.jobId,runId:execute.runId});await until(()=>server.service.snapshot('wire').runs[0].status==='running');const now=new Date().toISOString();agent.send({type:'result',jobId:execute.jobId,runId:execute.runId,status:'passed',exitCode:0,startedAt:now,finishedAt:now});await until(()=>server.graphExecution!.overview('wire').executions[0].status==='passed');assert.equal((await studio.call('list')).executions[0].activations[1].agentId,'wire-agent');
 // Cancellation remains pending until the simulated Agent acknowledges termination.
 const cancelRun=await studio.call('start',{revision:1,checksum:definition.checksum,entryNodeId:'approval',requestId:'cancel-execution'});const cancelActivation=cancelRun.executions.find(e=>e.id==='cancel-execution')!.activations[0];await studio.call('approve',{executionId:'cancel-execution',activationId:cancelActivation.id,revision:1,checksum:definition.checksum});await until(()=>agent.messages.filter(m=>m.type==='execute').length===2);const second=agent.messages.filter(m=>m.type==='execute')[1];await studio.call('cancel',{executionId:'cancel-execution'});assert.equal(server.graphExecution!.overview('wire').executions.find(e=>e.id==='cancel-execution')!.status,'cancelling');await until(()=>agent.messages.some(m=>m.type==='cancel'&&m.runId===second.runId));agent.send({type:'result',jobId:second.jobId,runId:second.runId,status:'cancelled',exitCode:null,startedAt:now,finishedAt:now});await until(()=>server.graphExecution!.overview('wire').executions.find(e=>e.id==='cancel-execution')!.status==='cancelled');
 // Persist a waiting approval, then recover without auto-approval or execution replay.
 await studio.call('start',{revision:1,checksum:definition.checksum,entryNodeId:'approval',requestId:'restart-execution'});for(const ws of peers)ws.terminate();await server.close();server=await startCoreServer(options);assert.equal(server.graphExecution!.overview('wire').executions.find(e=>e.id==='restart-execution')!.status,'paused');assert.equal(server.service.snapshot('wire').jobs.length,2);assert.equal(server.graphExecution!.overview('wire').executions[0].status,'passed');
 }finally{for(const ws of peers)ws.terminate();await server.close();}
});
