import test from 'node:test';import assert from 'node:assert/strict';import {LanguageService,languagePath,serverPath,serverUri,type LanguageBridge,type LanguageEvent} from '../src/features/editor/language-service.ts';
function fixture(){const calls:{command:string;args:Record<string,unknown>}[]=[];let listener:(event:LanguageEvent)=>void=()=>{};let response:unknown=null;const bridge:LanguageBridge={async invoke<T>(command:string,args:Record<string,unknown>){calls.push({command,args});if(command==='language_start')return{rootUri:'file:///D:/project'} as T;return response as T;},async listen(fn){listener=fn;return()=>{listener=()=>{};};}};const service=new LanguageService(bridge,'workspace');return{service,calls,reply:(value:unknown)=>{response=value;},event:(value:LanguageEvent)=>listener(value)};}
test('queries reject late replies after editor changes or session stop',async()=>{
 let reply!:(value:unknown)=>void;
 const bridge:LanguageBridge={invoke<T>(command:string,args:Record<string,unknown>){if(command==='language_start')return Promise.resolve({rootUri:'file:///D:/project'} as T);if((args.request as {method?:string})?.method==='textDocument/completion')return new Promise<T>(resolve=>{reply=resolve as typeof reply;});return Promise.resolve(null as T);},async listen(){return()=>{};}};
 const service=new LanguageService(bridge,'workspace');await service.start('python','tool','node',[{path:'main.py',content:'value=1'}]);
 const query=service.query('completion','main.py',{line:0,character:2});await new Promise(resolve=>setTimeout(resolve,0));
 const sync=service.sync([{path:'main.py',content:'value=2'}]);reply([{label:'stale'}]);await assert.rejects(query,/index changed/);await sync;
 const stopped=service.query('completion','main.py',{line:0,character:2});await new Promise(resolve=>setTimeout(resolve,0));await service.stop();reply([{label:'stale'}]);await assert.rejects(stopped,/session changed/);
});
test('language URI boundary denies escape/credentials, encodes source names and limits languages',()=>{const root='file:///D:/project';assert.equal(serverPath(root,serverUri(root,'src/한 글.py','python'),'python'),'src/한 글.py');for(const path of ['../outside.py','.env/test.py','.git/main.rs','credentials/test.py','target/test.rs','src/main.ts'])assert.throws(()=>languagePath(path,'python'));for(const url of ['file:///D:/project-else/main.py','file:///D:/project/../main.py','https://example.com/main.py','file:///D:/project/main.py?token=dummy','file:///D:/project/%2e%2e/main.py'])assert.throws(()=>serverPath(root,url,'python'));});
test('source changes synchronize versions; old diagnostics and foreign sessions never publish',async()=>{const f=fixture();await f.service.start('python','pyright-langserver.js','node.exe',[{path:'main.py',content:'value=1'}]);const start=f.calls[0].args.request as {sessionId:string};f.event({sessionId:start.sessionId,workspaceId:'workspace',type:'diagnostics',params:{uri:'file:///D:/project/main.py',version:1,diagnostics:[{message:'controlled'}]}});assert.equal(f.service.diagnosticRows().size,1);await f.service.sync([{path:'main.py',content:'value=2'}]);assert.equal(f.service.diagnosticRows().size,0);f.event({sessionId:start.sessionId,workspaceId:'workspace',type:'diagnostics',params:{uri:'file:///D:/project/main.py',version:1,diagnostics:[{}]}});assert.equal(f.service.diagnosticRows().size,0);f.event({sessionId:'foreign',workspaceId:'workspace',type:'stopped'});assert.equal(f.service.snapshot().status,'ready');await f.service.stop();assert.equal(f.service.snapshot().status,'idle');});
test('multi-file rename is a proposal, preserves dirty bases and blocks resource operations or unindexed targets',async()=>{const f=fixture();await f.service.start('python','pyright-langserver.js','node.exe',[{path:'main.py',content:'add()',savedContent:'old()'},{path:'math.py',content:'def add(): pass'}]);f.reply({changes:{'file:///D:/project/main.py':[{range:{start:{line:0,character:0},end:{line:0,character:3}},newText:'sum'}],'file:///D:/project/math.py':[{range:{start:{line:0,character:4},end:{line:0,character:7}},newText:'sum'}]}});const edits=await f.service.rename('main.py',{line:0,character:1},'sum');assert.equal(edits.length,2);assert.equal(edits[0].expected,'add()');assert.equal(f.service.expectedSaved('main.py'),'old()');assert.equal(f.calls.some(call=>call.command.includes('write')),false);f.reply({documentChanges:[{kind:'rename',oldUri:'file:///D:/project/math.py',newUri:'file:///D:/project/changed.py'}]});await assert.rejects(f.service.rename('main.py',{line:0,character:1},'sum'),/file operations/);f.reply({changes:{'file:///D:/outside.py':[]}});await assert.rejects(f.service.rename('main.py',{line:0,character:1},'sum'),/escapes/);await f.service.stop();});
test('cancel during pending startup ignores late reply and unsubscribes exactly once',async()=>{let resolve!:(value:{rootUri:string})=>void;let off=0,stops=0;const bridge:LanguageBridge={invoke<T>(command:string){if(command==='language_start')return new Promise(r=>{resolve=r as typeof resolve;});if(command==='language_stop')stops++;return Promise.resolve(null as T);},async listen(){return()=>{off++;};}};const service=new LanguageService(bridge,'workspace'),starting=service.start('rust','rust-analyzer.exe','',[]);await new Promise(r=>setTimeout(r,0));await service.stop();resolve({rootUri:'file:///D:/project'});await starting;assert.equal(service.snapshot().status,'idle');assert.equal(stops,1);assert.equal(off,1);});

test('closing a dirty editor restores saved language content; drive case is accepted',async()=>{const f=fixture();await f.service.start('python','tool','node',[{path:'main.py',content:'saved'}]);await f.service.syncEditors([{path:'main.py',content:'dirty',savedContent:'saved'}]);await f.service.syncEditors([]);const changes=f.calls.filter(row=>(row.args.request as {method?:string})?.method==='textDocument/didChange');assert.equal(((changes.at(-1)!.args.request as {params:{contentChanges:{text:string}[]}}).params.contentChanges[0]).text,'saved');assert.equal(serverPath('file:///D:/project','file:///d:/project/main.py','python'),'main.py');await f.service.stop();});
