import test from 'node:test';
import assert from 'node:assert/strict';
import {initialGraph,newNode} from '../src/features/orchestration/domain.ts';
import type {GraphOverview} from '../src/features/orchestration/execution.ts';
import {readinessMarkers} from '../src/features/orchestration/readiness-markers.ts';
import {executionProgress} from '../src/features/orchestration/execution-progress.ts';
import {recoveryPlan} from '../src/features/orchestration/recovery.ts';

function fixture(){const graph=initialGraph('p');graph.nodes.push(newNode('task','build',1),newNode('task','test',2));graph.edges.push({id:'next',from:'build',to:'test',relation:'success'});const overview:GraphOverview={durable:true,definition:{projectId:'p',revision:1,checksum:'g',inputChecksum:'i',graph,agents:{},publishedAt:'now'},executions:[{id:'e',projectId:'p',revision:1,checksum:'g',inputChecksum:'i',status:'paused',actor:'u',createdAt:'now',deadline:'2099-01-01T00:00:00Z',nodeLabels:{},activations:[{id:'a',nodeId:'build',attempt:1,status:'failed'},{id:'b',nodeId:'build',attempt:2,status:'passed',runId:'r'}]}]};return{graph,overview};}
test('configuration markers take priority, target adjacent relations and ignore foreign nodes',()=>{const {graph}=fixture();const m=readinessMarkers(graph,[{nodeId:'build',message:'x',severity:'configuration'},{nodeId:'build',message:'y',severity:'waiting'},{nodeId:'other',message:'z',severity:'configuration'}]);assert.equal(m.nodes.get('build'),'configuration');assert.equal(m.edges.get('next'),'configuration');assert.equal(m.nodes.has('other'),false);});
test('progress uses latest attempt, leaves unvisited nodes incomplete and hides incompatible graphs',()=>{const {graph,overview}=fixture(),before=JSON.stringify(overview);const p=executionProgress(graph,overview)!;assert.equal(p.passed,1);assert.equal(p.total,2);assert.equal(p.failed,0);assert.equal(p.rows[1].activation,undefined);assert.equal(JSON.stringify(overview),before);const changed=structuredClone(graph);changed.nodes[0].label='changed';assert.equal(executionProgress(changed,overview),null);assert.equal(executionProgress(graph,null),null);});
test('recovery retains history but rejects changed input, expired or terminal executions',()=>{const {overview}=fixture(),e=overview.executions[0],before=JSON.stringify(e);const p=recoveryPlan(e,overview.definition);assert.equal(p.blocked,null);assert.equal(p.retained[0].runId,'r');assert.equal(p.failed.length,1);assert.equal(JSON.stringify(e),before);assert(recoveryPlan(e,{...overview.definition!,inputChecksum:'new'}).blocked);assert(recoveryPlan({...e,deadline:'2000-01-01T00:00:00Z'},overview.definition).blocked);assert(recoveryPlan({...e,status:'failed'},overview.definition).blocked);});
