import test from 'node:test';
import assert from 'node:assert/strict';
import { parseProtocol } from '../src/features/protocol/parser.ts';
import { resolveTestPlan, combineRequirements } from '../src/features/protocol/resolver.ts';
import { validateSource, validateHealth, planPayload } from '../src/features/core/test-plan.ts';
import { TestOrchestrator, testResult } from '../src/features/core/orchestrator.ts';
import { CoreService } from '../src/features/core/service.ts';
import { InMemoryCoreRepository } from '../src/features/core/repository.ts';
import { RunLogs } from '../transport/protocol.ts';
import type { Project } from '../src/features/projects/types/project.ts';
const base={version:1,project:{name:'pipeline',type:'node'},environment:{BASE:'base',VALUE:'base'}};
const tasks=Object.fromEntries(['install','build','start','test','cleanup'].map(name=>[name,{command:'node',args:[`${name}.cjs`],timeout:10,env:{VALUE:name},requirements:{runtimes:{node:name==='build'?'>=24':'>=22'}}}]));
function state(extra:object={},project:object={}) {return parseProtocol({'project.yml':JSON.stringify({...base,...project}),'tasks.yml':JSON.stringify(tasks),'tests.yml':JSON.stringify({smoke:{type:'api',task:'test',pipeline:{install:'install',build:'build',start:'start',cleanup:'cleanup'},...extra}})});}
function plan(extra:object={}) {return resolveTestPlan(state(extra),'project','smoke');}
async function fixture(extra:object={}) {
  const core=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id} as Project)});
  const agent=core.registerAgent({name:'agent',platform:'windows',architecture:'x86_64',capabilities:{cpuCores:4,memoryMiB:8192,docker:false,gpu:false,pty:false,runtimes:{node:'24.11.1'},browsers:[]}});core.updateAgentStatus(agent.id,'idle');
  const p=plan(extra),job=await core.createJob('project',{name:p.testName,requirements:p.requirements,payload:planPayload(p)});
  const run=core.dispatch('project')!.run,orchestrator=new TestOrchestrator(core);
  return {core,job,run,orchestrator};
}
test('TestDefinition produces separate typed plan with ordered optional stages and resolved environment',()=>{
  const p=plan({env:{VALUE:'test override'}});assert.equal(p.projectId,'project');assert.equal(p.type,'api');assert.equal(p.timeout,600000);assert.deepEqual(p.steps.map(s=>s.stage),['install','build','start','test','cleanup']);assert.equal(p.steps[1].taskReference,'build');assert.equal(p.steps[1].env!.VALUE,'test override');assert.equal(p.steps[1].env!.BASE,'base');assert.equal(p.requirements.runtimes?.node,'>=24');
});
test('minimal test has mandatory run cleanup without inventing project tasks',()=>assert.deepEqual(plan({pipeline:undefined}).steps.map(s=>s.stage),['test','cleanup']));
test('Git source provider injects first step and source-relative cwd',()=>{const p=resolveTestPlan(state({}, {source:{provider:'git',repository:'https://example.org/repo.git',revision:'main'}}),'project','smoke');assert.equal(p.steps[0].stage,'source');assert.equal(p.steps[1].cwd,'source');assert.equal(p.requirements.runtimes?.git,'>=0');});
for(const repository of ['file:///D:/outside','https://user:secret@example.org/repo','ssh://example.org/repo','https://example.org/repo?token=x','https://example.org/repo#x','-bad','https://example.org/ bad'])test(`source rejects ${repository.split('@').at(-1)}`,()=>assert.throws(()=>validateSource({provider:'git',repository,revision:'main'})));
for(const revision of ['--upload-pack=bad','../main','a..b','x\ny','x//y',''])test(`source rejects unsafe revision ${JSON.stringify(revision)}`,()=>assert.throws(()=>validateSource({provider:'git',repository:'https://example.org/repo',revision})));
test('requirements preserve strongest resolved minimum and reject incompatible stage OS',()=>{assert.equal(combineRequirements([{runtimes:{node:'>=24.2'}},{runtimes:{node:'>=24.11.1'}}]).runtimes?.node,'>=24.11.1');assert.throws(()=>combineRequirements([{platform:'windows'},{platform:'linux'}]),/conflicting/);});
test('health definition defaults and ordering',()=>{const p=plan({healthcheck:{url:'http://127.0.0.1:3000/health'}});assert.equal(p.steps[3].stage,'healthcheck');assert.equal(p.steps[3].healthcheck?.expectedStatus,200);assert.equal(p.steps[3].timeoutMs,30000);});
for(const url of ['https://127.0.0.1/','http://example.org/','http://user@127.0.0.1/','http://127.0.0.1/?token=x','http://127.0.0.1/#x'])test(`health rejects ${url}`,()=>assert.throws(()=>validateHealth({url,expectedStatus:200,retryIntervalMs:100})));
test('health requires start and valid retry/status',()=>{assert.equal(state({pipeline:{},healthcheck:{url:'http://127.0.0.1/'}}).status,'Invalid');assert.equal(state({healthcheck:{url:'http://127.0.0.1/',retryInterval:0}}).status,'Invalid');assert.throws(()=>validateHealth({url:'http://127.0.0.1/',expectedStatus:999,retryIntervalMs:100}));});
test('pipeline all pass preserves one Agent and Run with step timestamps and duration',async()=>{const f=await fixture();let next;while((next=f.orchestrator.next(f.run.id))){assert.equal(next.run.agentId,f.run.agentId);f.orchestrator.complete(f.run.id,next.step.id,'passed',0);}const done=f.orchestrator.finish(f.run.id)!;assert.equal(done.status,'passed');const snapshot=f.core.snapshot('project');assert.equal(snapshot.runs.length,1);assert.ok(snapshot.steps.every(s=>s.startedAt&&s.finishedAt));assert.equal(f.core.listAgents()[0].status,'idle');assert.ok(testResult(done,snapshot.steps,'smoke','api').duration>=0);});
for(const failed of ['install','build','test'])test(`${failed} failure skips dependents and executes cleanup without masking primary failure`,async()=>{
  const f=await fixture();let next;while((next=f.orchestrator.next(f.run.id))){const fail=next.command.stage===failed||next.command.stage==='cleanup';f.orchestrator.complete(f.run.id,next.step.id,fail?'failed':'passed',fail?7:0);}
  const run=f.orchestrator.finish(f.run.id)!,steps=f.core.snapshot('project').steps;assert.equal(run.status,'failed');assert.equal(steps.find(s=>s.id===run.primaryFailureStepId)?.name.toLowerCase(),failed);assert.equal(run.exitCode,7);assert.ok(run.cleanupWarning);assert.equal(steps.at(-1)!.status,'failed');if(failed==='build')assert.equal(steps.find(s=>s.name==='Test')?.status,'skipped');
});
for(const termination of ['timeout','cancelled'] as const)test(`${termination} terminates run after cleanup with remaining states`,async()=>{const f=await fixture();const first=f.orchestrator.next(f.run.id)!;f.orchestrator.terminate(f.run.id,termination);f.orchestrator.complete(f.run.id,first.step.id,termination,null);const cleanup=f.orchestrator.next(f.run.id)!;assert.equal(cleanup.command.stage,'cleanup');f.orchestrator.complete(f.run.id,cleanup.step.id,'passed',0);f.orchestrator.next(f.run.id);assert.equal(f.orchestrator.finish(f.run.id)?.status,termination);assert.equal(f.core.snapshot('project').steps[1].status,termination==='cancelled'?'cancelled':'skipped');});
test('duplicate step completion rejected; retry creates new job and preserves original Run',async()=>{const f=await fixture();const first=f.orchestrator.next(f.run.id)!;f.orchestrator.complete(f.run.id,first.step.id,'failed',2);assert.throws(()=>f.orchestrator.complete(f.run.id,first.step.id,'passed',0));const cleanup=f.orchestrator.next(f.run.id)!;f.orchestrator.complete(f.run.id,cleanup.step.id,'passed',0);f.orchestrator.next(f.run.id);f.orchestrator.finish(f.run.id);const retry=f.core.retryJob('project',f.job.id);assert.notEqual(retry.id,f.job.id);assert.equal(f.core.snapshot('project').runs.length,1);assert.equal(f.core.dispatch('project')?.job.id,retry.id);});
test('no compatible Agent leaves TestPlan queued',async()=>{const core=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id} as Project)}),p=plan();await core.createJob('project',{name:'smoke',requirements:p.requirements,payload:planPayload(p)});assert.equal(core.dispatch(),null);assert.equal(core.queue().length,1);});
test('per-step sequences do not collide and bounded live log preserves step association',()=>{const logs=new RunLogs();logs.append('run',1,'stdout','build','build-step');logs.append('run',1,'stderr','test','test-step');logs.append('run',1,'stderr','duplicate','test-step');assert.equal(logs.read(['run']).run.length,2);assert.deepEqual(logs.read(['run']).run.map(s=>s.runStepId),['build-step','test-step']);});
test('RunStep artifacts reuse existing metadata contract',async()=>{const f=await fixture();const step=f.orchestrator.next(f.run.id)!.step;const artifact=f.core.addArtifact('project',{runId:f.run.id,runStepId:step.id,type:'log',name:'build log',location:'future/log.txt',size:0});assert.equal(artifact.runStepId,step.id);});
