import test from 'node:test';
import assert from 'node:assert/strict';
import {graphKey,initialGraph,loadGraph,newNode,removeNode,saveGraph,validateGraph,type ProjectGraph} from '../src/features/orchestration/domain.ts';
import {ProjectService} from '../src/features/projects/services/project-service.ts';
import {LocalProjectRepository} from '../src/features/projects/services/project-repository.ts';
class Storage { data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){this.data.set(k,v);} }
function flow():ProjectGraph {return {...initialGraph('p'),nodes:['task','approval','task'].map((kind,i)=>newNode(kind as 'task'|'approval',`n${i}`,i)),edges:[{id:'e1',from:'n0',to:'n1',relation:'success'},{id:'e2',from:'n1',to:'n2',relation:'success'}]};}
test('one device supports all roles without inventing agent registrations',()=>{const g=initialGraph('p','composite',['implementation','deployment','testing']);assert.equal(g.nodes.filter(n=>n.kind==='device').length,1);assert.equal(g.nodes.filter(n=>n.kind==='role').length,3);assert.equal(g.nodes.filter(n=>n.kind==='agent').length,0);assert.equal(g.edges.length,3);});
test('graph storage isolates projects and preserves malformed records',()=>{const s=new Storage();saveGraph(s,initialGraph('one'));saveGraph(s,initialGraph('two','web'));assert.equal(loadGraph(s,'two')!.projectKind,'web');assert.equal(loadGraph(s,'missing'),null);s.setItem(graphKey('one'),'{');assert.throws(()=>loadGraph(s,'one'));assert.equal(s.getItem(graphKey('one')),'{');s.setItem(graphKey('one'),JSON.stringify(initialGraph('two')));assert.throws(()=>loadGraph(s,'one'));});
test('relationships validate kinds, duplicates and dangling nodes',()=>{const g=initialGraph('p');for(const edges of [[{id:'e',from:'current-pc',to:'missing',relation:'hosts'}],[{id:'e',from:'current-pc',to:'role-implementation',relation:'success'}],[...g.edges,...g.edges]])assert.throws(()=>validateGraph({...g,edges},'p'));assert.throws(()=>validateGraph({...g,nodes:[...g.nodes,g.nodes[0]]},'p'));});
test('success cycles blocked; failure feedback remains a bounded design declaration',()=>{const g=flow();assert.equal(validateGraph(g,'p').edges.length,2);assert.throws(()=>validateGraph({...g,edges:[...g.edges,{id:'cycle',from:'n2',to:'n0',relation:'success'}]},'p'));assert.equal(validateGraph({...g,edges:[...g.edges,{id:'feedback',from:'n2',to:'n0',relation:'failure'}]},'p').retryLimit,3);assert.throws(()=>validateGraph({...g,retryLimit:4},'p'));});
test('node removal removes incident relationships without changing unrelated nodes',()=>{const g=flow(),next=removeNode(g,'n1');assert.equal(next.nodes.length,2);assert.equal(next.edges.length,0);assert.equal(g.edges.length,2);});
test('stale window saves preserve newer graph and the rejected draft',()=>{const s=new Storage(),a=initialGraph('p');saveGraph(s,a,null);const baseline=s.getItem(graphKey('p'));saveGraph(s,{...a,projectKind:'web'},baseline);assert.throws(()=>saveGraph(s,{...a,projectKind:'desktop'},baseline),/another window/);assert.equal(loadGraph(s,'p')!.projectKind,'web');assert.equal(a.projectKind,'custom');});
test('multiple agents can belong to a device, but one agent cannot belong to two devices or be bound twice',()=>{const g=initialGraph('p');g.nodes.push({...newNode('device','other',2)},newNode('agent','a1',3),newNode('agent','a2',4));g.edges.push({id:'host1',from:'current-pc',to:'a1',relation:'hosts'},{id:'host2',from:'current-pc',to:'a2',relation:'hosts'});assert.equal(validateGraph(g,'p').edges.length,3);assert.throws(()=>validateGraph({...g,edges:[...g.edges,{id:'host3',from:'other',to:'a1',relation:'hosts'}]},'p'),/one device/);assert.throws(()=>validateGraph({...g,nodes:g.nodes.map(n=>n.kind==='agent'?{...n,reference:'same-agent'}:n)},'p'),/bound once/);});
test('unknown fields never become stored credentials; invalid data cannot overwrite prior graph',()=>{const s=new Storage(),g=initialGraph('p');saveGraph(s,g);const before=s.getItem(graphKey('p'));assert.throws(()=>saveGraph(s,{...g,nodes:[{...g.nodes[0],x:-1}]}));assert.equal(s.getItem(graphKey('p')),before);const sanitized=validateGraph({...g,token:'dummy-value',nodes:g.nodes.map(n=>({...n,password:'dummy-value'}))},'p');assert.ok(!JSON.stringify(sanitized).includes('dummy-value'));});
test('new project kinds and first roles persist; existing metadata remains readable',async()=>{const s=new Storage(),service=new ProjectService(new LocalProjectRepository(()=>s),{id:()=> 'p'});const p=await service.create({name:'TASTEDEV',workspacePath:'D:/copy',description:'',projectKind:'composite',initialRoles:['implementation','testing']});assert.equal(p.projectType,'composite');assert.deepEqual((await service.get('p'))!.initialRoles,['implementation','testing']);assert.throws(()=>initialGraph('p','custom',['bad' as 'implementation']));await assert.rejects(service.create({name:'bad',workspacePath:'D:/bad',description:'',initialRoles:[]}));const browser=await new ProjectService(new LocalProjectRepository(()=>new Storage()),{id:()=> 'browser'}).registerBrowserFolder('browser','',{projectKind:'web',initialRoles:['deployment']});assert.equal(browser.projectType,'web');assert.deepEqual(browser.initialRoles,['deployment']);});
