import fs from 'node:fs';import vm from 'node:vm';
import test from 'node:test';import assert from 'node:assert/strict';import {parseJsonConfig,configPath,projectLanguage} from '../src/features/editor/project-language.ts';import type {IndexReader} from '../src/features/editor/workspace-index.ts';
function reader(files:Record<string,string>):IndexReader{return {read:async file=>{if(!(file in files))throw Error('Missing');return {content:files[file]};},list:async parent=>{const prefix=parent?parent+'/':'';const children=new Map<string,{name:string;path:string;kind:'file'|'directory'}>();for(const file of Object.keys(files)){if(!file.startsWith(prefix))continue;const suffix=file.slice(prefix.length),name=suffix.split('/')[0];children.set(name,{name,path:prefix+name,kind:suffix.includes('/')?'directory':'file'});}return [...children.values()];}};}
test('JSONC preserves comment-like strings, removes comments and trailing commas, and rejects malformed/large inputs',()=>{assert.deepEqual(parseJsonConfig('{/*x*/"url":"https://example.test/a//b", "compilerOptions":{"strict":true,},// tail\n}'),{url:'https://example.test/a//b',compilerOptions:{strict:true}});for(const text of ['[]','{/* unclosed','x'.repeat(65537)])assert.throws(()=>parseJsonConfig(text));});
test('relative config inheritance resolves bounded aliases and compiler options without project escape',async()=>{const result=await projectLanguage(reader({'tsconfig.json':'{"extends":"./config/base","compilerOptions":{"strict":false}}','config/base.json':'{"compilerOptions":{"strict":true,"baseUrl":"..","paths":{"@app/*":["src/*"]}}}'}),new AbortController().signal);assert.equal(result.options.strict,false);assert.equal(result.baseUrl,'');assert.deepEqual(result.options.paths,{'@app/*':['src/*']});assert.deepEqual(result.warnings,[]);assert.equal(configPath('config','../src'),'src');assert.throws(()=>configPath('','../outside'));assert.throws(()=>configPath('','C:/outside'));});
test('cyclic, external and escaping tsconfig extends fail safely without reading outside the project',async()=>{for(const content of ['{"extends":"./tsconfig"}','{"extends":"../outside"}','{"extends":"./.env.local"}','{"extends":"@external/tsconfig"}','{"compilerOptions":{"baseUrl":"../outside","paths":{"*": ["*"]}}}']){const result=await projectLanguage(reader({'tsconfig.json':content}),new AbortController().signal);assert.ok(result.warnings.length);assert.deepEqual(result.options,{});}});
test('dependency declaration indexing reads only bounded package d.ts and honors explicit types selection',async()=>{const files={'tsconfig.json':'{"compilerOptions":{"types":["node"]}}','package.json':'{"dependencies":{"library":"1"},"devDependencies":{"@types/unselected":"1"}}','node_modules/@types/node/index.d.ts':'declare module "node:fixture" { export const answer: number; }','node_modules/@types/unselected/index.d.ts':'should not read','node_modules/library/index.d.ts':'export const answer: 42;','node_modules/library/index.js':'runtime must not read','node_modules/library/credential.d.ts':'must not read','node_modules/library/.env':'must not read'};const result=await projectLanguage(reader(files),new AbortController().signal);assert.deepEqual(result.declarations.map(f=>f.path).sort(),['node_modules/@types/node/index.d.ts','node_modules/library/index.d.ts']);assert.equal(result.limited,false);});
test('declaration traversal rejects host aliases, stops at its file budget and honors cancellation',async()=>{const files:Record<string,string>={'package.json':'{"dependencies":{"library":"1"}}'};for(let i=0;i<130;i++)files['node_modules/library/file'+i+'.d.ts']='export const x: number;';const result=await projectLanguage(reader(files),new AbortController().signal);assert.equal(result.declarations.length,128);assert.equal(result.limited,true);const controller=new AbortController();controller.abort();await assert.rejects(projectLanguage(reader(files),controller.signal),/Cancelled/);const source=reader({'package.json':'{"dependencies":{"library":"1"}}'});source.list=async()=>[{name:'x.d.ts',path:'../x.d.ts',kind:'file'}];assert.deepEqual((await projectLanguage(source,new AbortController().signal)).declarations,[]);});

test('supported custom Monaco worker factory preserves ESM/CommonJS TypeScript ScriptKind',()=>{const context:{customTSWorkerFactory?: (base:unknown,ts:unknown)=>{new():{getScriptKind(file:string):number}}}={};vm.runInNewContext(fs.readFileSync('scripts/typescript-module-worker.cjs','utf8'),context);class Base {getScriptKind(){return 0;}}const Worker=context.customTSWorkerFactory!(Base,{ScriptKind:{TS:3,JS:1}}),worker=new Worker();for(const file of ['main.mts','main.cts','index.d.mts','index.d.cts'])assert.equal(worker.getScriptKind(file),3);for(const file of ['main.mjs','main.cjs'])assert.equal(worker.getScriptKind(file),1);assert.equal(worker.getScriptKind('main.ts'),0);});
