import test from 'node:test';import assert from 'node:assert/strict';
import {buildProjectSnapshot,projectReference,verifyProjectSnapshot,verifyProjectReference,snapshotBytes,projectManifestRecord,verifyProjectManifest} from '../src/features/ai/project-snapshot.ts';
import {base64Decode,base64Encode,projectSnapshotLimits} from '../src/features/ai/snapshot-bytes.ts';
const identity=()=>({projectId:crypto.randomUUID(),proposalId:crypto.randomUUID(),attempt:1,baseRevision:'working-tree',changedFiles:['src/file-0.ts']});
test('UTF-8 BOM survives byte-identical transfer and long multibyte revisions are rejected',async()=>{const {files,rows}=source(1);const bytes=Uint8Array.from([239,187,191,...new TextEncoder().encode('export const value=1;')]);rows.set('src/file-0.ts',bytes);const {snapshot}=await buildProjectSnapshot(files,identity());assert.deepEqual(snapshotBytes(snapshot.files[0]),bytes);await assert.rejects(buildProjectSnapshot(files,{...identity(),baseRevision:'한'.repeat(100)}),/INVALID_SNAPSHOT/);});
function source(n=200){const rows=new Map<string,Uint8Array>(Array.from({length:n},(_,i)=>['src/file-'+i+'.ts',new TextEncoder().encode('export const value='+i+';/*'+'x'.repeat(500)+'*/')]));return{rows,files:{list:async()=>[...rows.keys()].map(path=>({path,name:path,kind:'file' as const})),read:async(path:string)=>({content:new TextDecoder().decode(rows.get(path)),size:rows.get(path)!.length,modified:0}),readBytes:async(path:string)=>rows.get(path)!}};}
test('project snapshot supports hundreds of files above legacy payload limits',async()=>{const {files}=source();const {snapshot}=await buildProjectSnapshot(files,identity());assert.equal(snapshot.files.length,200);assert(snapshot.files.reduce((n,f)=>n+f.size!,0)>24000);await verifyProjectSnapshot(snapshot);assert(verifyProjectReference(projectReference(snapshot)));assert(JSON.stringify(projectReference(snapshot)).length<2000);await verifyProjectManifest(projectManifestRecord(snapshot));});
test('binary content round trips by original byte checksum without bypassing secret filtering',async()=>{const {files,rows}=source(1),image=Uint8Array.from([137,80,78,71,0,255,1,2]);rows.set('assets/image.png',image);rows.set('assets/unsafe.bin',new Uint8Array([0,...new TextEncoder().encode('DUMMY_KNOWN_SECRET'),255]));rows.set('.env',new TextEncoder().encode('dummy env'));const {snapshot,excluded}=await buildProjectSnapshot(files,identity(),['DUMMY_KNOWN_SECRET']);assert.deepEqual(snapshotBytes(snapshot.files.find(f=>f.path==='assets/image.png')!),image);assert(excluded.includes('assets/unsafe.bin'));assert(excluded.includes('.env'));const tampered=structuredClone(snapshot);tampered.files[0].content+='x';await assert.rejects(verifyProjectSnapshot(tampered),/SNAPSHOT_INTEGRITY/);});
test('case collisions, missing changed files, oversized file and cancellation are explicit failures',async()=>{const {files,rows}=source(1);rows.set('SRC/file-0.ts',rows.get('src/file-0.ts')!);await assert.rejects(buildProjectSnapshot(files,identity()),/SNAPSHOT_INTEGRITY/);rows.delete('SRC/file-0.ts');await assert.rejects(buildProjectSnapshot(files,{...identity(),changedFiles:['missing.ts']}),/SNAPSHOT_INTEGRITY/);rows.set('large.bin',new Uint8Array(projectSnapshotLimits.fileBytes+1));await assert.rejects(buildProjectSnapshot(files,identity()),/SNAPSHOT_LIMIT/);const abort=new AbortController();abort.abort();await assert.rejects(buildProjectSnapshot(files,identity(),[],[],abort.signal));});
test('base64 representations are canonical and references cannot inject URLs or credentials',async()=>{const value=new Uint8Array([0,255,2]);assert.deepEqual(base64Decode(base64Encode(value)),value);assert.throws(()=>base64Decode('Zh=='),/Noncanonical/);assert.throws(()=>base64Decode('abc'));const {snapshot}=await buildProjectSnapshot(source(1).files,identity()),ref=projectReference(snapshot);ref.transfer!.url='https://invalid.test';assert.throws(()=>verifyProjectReference(ref),/REFERENCE/);});
