import test from 'node:test';import assert from 'node:assert/strict';
import {PullRequestService,pullBranch,type PullProvider,type PullDraft,type PullRequest} from '../src/features/git/pull-requests.ts';
import {IssueError} from '../src/features/issues/domain.ts';
import {GitHubPullProvider} from '../transport/pull-request-provider.ts';
function fixture(){let sha='a'.repeat(40),creates=0,fail=false;let existing:PullRequest[]=[];let saved:PullDraft[]=[];const provider:PullProvider={async head(){return sha;},async list(){return existing;},async create(repo,input){creates++;const pull={number:1,url:`https://github.com/${repo}/pull/1`,sha,title:input.title,body:input.body,state:'open',head:input.head,base:input.base};existing=[pull];if(fail)throw Error('controlled timeout');return pull;},async get(){return existing[0];},async checks(){return {sha,state:'success',checks:[],truncated:false};}};const persistence={load:()=>structuredClone(saved),save:(rows:PullDraft[])=>{saved=structuredClone(rows);}};const service=new PullRequestService(provider,['DUMMY_PRIVATE_VALUE_123'],persistence);return{service,provider,persistence,creates:()=>creates,setSHA:(value:string)=>sha=value,setFail:(value:boolean)=>fail=value,input:{base:'main',head:'feature/fix',sha,title:'Reviewed fix',body:'token=DUMMY_PRIVATE_VALUE_123'}};}
test('PR review masks payload, pins revision and does not create until scoped explicit approval',async()=>{const f=fixture();const draft=await f.service.build('p','owner/repo',f.input);assert.equal(f.creates(),0);assert.ok(!draft.body.includes('DUMMY_PRIVATE_VALUE_123'));await assert.rejects(f.service.approveAndCreate('foreign','owner/repo',draft.id));await assert.rejects(f.service.approveAndCreate('p','other/repo',draft.id));const result=await f.service.approveAndCreate('p','owner/repo',draft.id);assert.equal(result.status,'linked');assert.ok(result.approval?.hash);assert.equal(f.creates(),1);await assert.rejects(f.service.approveAndCreate('p','owner/repo',draft.id));assert.equal(f.creates(),1);const state=await f.service.status('p','owner/repo',draft.id);assert.equal(state.checks.sha,state.draft.pull!.sha);});
test('cancel and remote source changes block PR creation; existing PR is reused',async()=>{const f=fixture();const cancelled=await f.service.build('p','owner/repo',f.input);f.service.cancel('p','owner/repo',cancelled.id);await assert.rejects(f.service.approveAndCreate('p','owner/repo',cancelled.id));const stale=await f.service.build('p','owner/repo',f.input);f.setSHA('b'.repeat(40));await assert.rejects(f.service.approveAndCreate('p','owner/repo',stale.id),e=>e instanceof IssueError&&e.code==='stale');assert.equal(f.creates(),0);f.setSHA(f.input.sha);const first=await f.service.build('p','owner/repo',f.input);await f.service.approveAndCreate('p','owner/repo',first.id);const second=await f.service.build('p','owner/repo',f.input);assert.equal((await f.service.approveAndCreate('p','owner/repo',second.id)).pull!.number,1);assert.equal(f.creates(),1);});
test('uncertain creation persists and reconciles without repeated POST or new approval',async()=>{const f=fixture();const draft=await f.service.build('p','owner/repo',f.input);f.setFail(true);await assert.rejects(f.service.approveAndCreate('p','owner/repo',draft.id));const restarted=new PullRequestService(f.provider,[],f.persistence);assert.equal(restarted.list('p')[0].status,'uncertain');await assert.rejects(restarted.approveAndCreate('p','owner/repo',draft.id));const linked=await restarted.reconcile('p','owner/repo',draft.id);assert.equal(linked.status,'linked');assert.equal(f.creates(),1);});
test('branch injection, fork source and CI SHA mismatches are rejected',async()=>{for(const value of ['--all','../main','main..x','main/','x.lock','main//x'])assert.throws(()=>pullBranch(value));const sha='a'.repeat(40);const provider=new GitHubPullProvider(async()=>({status:200,headers:{},body:{number:1,html_url:'https://github.com/owner/repo/pull/1',title:'Untrusted',state:'open',head:{ref:'feature',sha,repo:{full_name:'foreign/repo'}},base:{ref:'main',repo:{full_name:'owner/repo'}}}}));await assert.rejects(provider.get('owner/repo',1));const checks=new GitHubPullProvider(async(_method,path)=>({status:200,headers:{},body:path.includes('check-runs')?{check_runs:[],total_count:0}:{state:'success',sha:'b'.repeat(40)}}));await assert.rejects(checks.checks('owner/repo',sha));});
test('storage failure after external creation retains uncertain state and reconciles in the same runtime',async()=>{const f=fixture();let fail=false;const saved=f.persistence.save;const persistence={load:f.persistence.load,save:(rows:PullDraft[])=>{if(fail&&rows.some(row=>row.status==='linked')){fail=false;throw Error('controlled disk write failure');}saved(rows);}};const service=new PullRequestService(f.provider,[],persistence),draft=await service.build('p','owner/repo',f.input);fail=true;await assert.rejects(service.approveAndCreate('p','owner/repo',draft.id));assert.equal(service.list('p')[0].status,'uncertain');assert.equal((await service.reconcile('p','owner/repo',draft.id)).status,'linked');assert.equal(f.creates(),1);});
test('changed secret masking policy invalidates review before any provider POST',async()=>{const f=fixture(),draft=await f.service.build('p','owner/repo',{...f.input,body:'Reviewed public description: NEW_DUMMY_VALUE_123'});f.service.secrets.push('NEW_DUMMY_VALUE_123');await assert.rejects(f.service.approveAndCreate('p','owner/repo',draft.id),e=>e instanceof IssueError&&e.code==='stale');assert.equal(f.creates(),0);});
