import test from 'node:test';import assert from 'node:assert/strict';
import {CoreStore,SqliteCoreRepository} from '../transport/storage.ts';
import {CoreService} from '../src/features/core/service.ts';import {ScheduleService,type ScheduleRuntime} from '../src/features/scheduler/service.ts';import {MemoryScheduleRepository} from '../src/features/scheduler/domain.ts';import type {Project} from '../src/features/projects/types/project.ts';
const project={id:crypto.randomUUID(),name:'durable schedule'} as Project;
const sources={'project.yml':JSON.stringify({version:1,project:{name:'durable',type:'node'}}),'tasks.yml':JSON.stringify({assertion:{command:'node',args:['-v']}}),'tests.yml':JSON.stringify({smoke:{task:'assertion',type:'unit'}})};
const input={name:'recovery',testName:'smoke',enabled:true,timezone:'UTC',trigger:{type:'interval' as const,seconds:60}};
function fixture(){const store=new CoreStore(':memory:',Buffer.alloc(32,6));let now=Date.parse('2026-10-01T00:00:00Z');const core=new CoreService(new SqliteCoreRepository(store),{get:async()=>project});const persistence={load:()=>store.get<ScheduleRuntime>('scheduler'),save:(v:ScheduleRuntime)=>store.put('scheduler',v)};const open=()=>new ScheduleService(core,new MemoryScheduleRepository(),()=>project,()=>null,()=>now,persistence);return{store,core,open,advance:(ms:number)=>{now+=ms}};}
test('SQLite restores saved Protocol and Schedule, skips missed slots and retains trigger identity',async()=>{const f=fixture();try{let s=f.open();s.register(project.id,sources);const id=s.save(project.id,input).schedules[0].id;await s.runNow(project.id,id,'click');f.advance(3600000);s=f.open();assert.deepEqual(s.list(project.id).tests,['smoke']);assert.equal(s.list(project.id).history.length,1);await assert.rejects(s.runNow(project.id,id,'click'),/duplicate/);await s.tick();assert.equal(f.core.queue().length,1);assert.equal(s.list(project.id).history.at(-1)?.reason,'missed');assert.equal(f.open().list(project.id).history.length,2);}finally{f.store.close();}});
test('crash after durable Job but before scheduler link resumes exactly one queued Job',async()=>{const f=fixture();try{let s=f.open();s.register(project.id,sources);const id=s.save(project.id,input).schedules[0].id;const original=f.core.createJob.bind(f.core);let crash=true;f.core.createJob=async(p,i)=>{const job=await original(p,i);if(crash){crash=false;throw Error('controlled lost reply');}return job;};await s.runNow(project.id,id,'click');assert.equal(f.core.queue().length,1);assert.equal(s.list(project.id).history[0].jobId,undefined);s=f.open();await s.tick();assert.equal(f.core.queue().length,1);assert.equal(s.list(project.id).history[0].jobId,f.core.queue()[0].id);assert.equal(f.store.get<ScheduleRuntime>('scheduler')?.pending.length,0);}finally{f.store.close();}});
test('crash after trigger commit before nextRunAt advance consumes identity without duplicate or stuck tick',async()=>{const f=fixture();try{let s=f.open();s.register(project.id,sources);const definition=s.save(project.id,input).schedules[0];f.advance(60000);await s.fire(project.id,definition.id,{id:definition.nextRunAt!,scheduleId:definition.id,scheduledAt:definition.nextRunAt!,type:'interval'});s=f.open();await s.tick();assert.equal(f.core.queue().length,1);assert.equal(s.list(project.id).history.length,1);assert.ok(Date.parse(s.list(project.id).schedules[0].nextRunAt!)>Date.parse(definition.nextRunAt!));}finally{f.store.close();}});
test('scheduler persistence failure creates no Job and rolls back trigger identity for safe retry',async()=>{const f=fixture();try{const s=f.open();s.register(project.id,sources);const id=s.save(project.id,input).schedules[0].id;f.store.db.exec("CREATE TRIGGER reject_scheduler BEFORE UPDATE ON units WHEN NEW.name='scheduler' BEGIN SELECT RAISE(ABORT,'controlled disk failure');END");await assert.rejects(s.runNow(project.id,id,'click'),/persistence/);assert.equal(f.core.queue().length,0);assert.equal(s.list(project.id).history.length,0);f.store.db.exec('DROP TRIGGER reject_scheduler');await s.runNow(project.id,id,'click');assert.equal(f.core.queue().length,1);}finally{f.store.close();}});
test('same durable Job identity with a changed payload is rejected',async()=>{const f=fixture();try{const input={name:'one',idempotencyKey:'one',requirements:{},payload:{task:'one',steps:[{name:'node',executable:'node',args:['-v'],cwd:'.'}]}};await f.core.createJob(project.id,input);await assert.rejects(f.core.createJob(project.id,{...input,payload:{...input.payload,steps:[{...input.payload.steps[0],args:['--help']}]}}),/identity conflicts/);assert.equal(f.core.queue().length,1);}finally{f.store.close();}});
