import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';
import {backupCore,restoreCore} from '../transport/backup.ts';import {diagnoseStorage} from '../transport/storage-diagnostics.ts';import {CoreStore,SqliteCoreRepository,storageKey} from '../transport/storage.ts';import {SourceSnapshotStore} from '../transport/source-snapshot-store.ts';import {buildProjectSnapshot,projectManifestRecord} from '../src/features/ai/project-snapshot.ts';import {recoveryGuide} from '../src/features/core/recovery-guide.ts';
import {projectReference} from '../src/features/ai/project-snapshot.ts';
const root=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/fifth-advancement/phase-5/unit/',import.meta.url)),hash=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
test('graph Source without Jobs is checked by offline diagnosis, backup and retention',async()=>{
 const f=await fixture();try{const key=storageKey(f.database),store=new CoreStore(f.database,key),reference=projectReference(f.snapshot);store.put('node-orchestration',{definitions:[{projectId:reference.projectId,plans:{one:{payload:{task:'graph',steps:[{name:'Source',executable:'snapshot',args:[],cwd:'.',source:{provider:'snapshot',repository:'snapshot:'+reference.snapshotId,revision:reference.baseRevision,snapshot:reference}}]}}}}],executions:[]});store.close();key.fill(0);
 const {offlineSourceMaintenance}=await import('../transport/source-maintenance.ts');const retained=await offlineSourceMaintenance(f.database,f.artifacts,Date.now(),true);assert.equal(retained.reclaimableSnapshots,0);assert.equal((await diagnoseStorage(f.database,f.artifacts)).ok,true);await backupCore(f.database,f.artifacts,path.join(f.dir,'graph-backup'));
 fs.unlinkSync(path.join(f.artifacts+'-sources','manifests',reference.projectId,reference.snapshotId+'.json.complete'));assert.equal((await diagnoseStorage(f.database,f.artifacts)).code,'SOURCE_INVALID');await assert.rejects(backupCore(f.database,f.artifacts,path.join(f.dir,'missing-source-backup')),/snapshot|Source/i);
 }finally{f.cleanup();}
});
async function fixture(){fs.mkdirSync(root,{recursive:true});const dir=fs.mkdtempSync(path.join(root,'case-')),database=path.join(dir,'core.sqlite'),artifacts=path.join(dir,'artifacts'),key=storageKey(database),store=new CoreStore(database,key);new SqliteCoreRepository(store);store.put('diagnosis-fixture',{retained:true});store.close();key.fill(0);const projectId=crypto.randomUUID(),source=new SourceSnapshotStore(artifacts+'-sources'),disk=new Map([['a.ts','export const value=1;']]);const {snapshot}=await buildProjectSnapshot({list:async()=>[{path:'a.ts',name:'a.ts',kind:'file'}],read:async p=>({content:disk.get(p)!,size:21,modified:0})},{projectId,proposalId:crypto.randomUUID(),attempt:1,baseRevision:'working-tree',changedFiles:['a.ts']});await source.begin(projectManifestRecord(snapshot));for(const f of snapshot.files){const bytes=Buffer.from(f.content);await source.append(projectId,snapshot.snapshotId,f.checksum,0,(async function*(){yield bytes;})(),hash(bytes));}await source.complete(projectId,snapshot.snapshotId);return{dir,database,artifacts,snapshot,source,cleanup(){assert(path.resolve(dir).startsWith(path.resolve(root)+path.sep));fs.rmSync(dir,{recursive:true,force:true});}};}
test('offline backup includes completed v2 blobs and manifests; restore verifies source and retains encrypted units',async()=>{const f=await fixture();try{const before=hash(fs.readFileSync(f.database)),diagnosis=await diagnoseStorage(f.database,f.artifacts);assert.equal(diagnosis.ok,true);assert.equal(diagnosis.snapshots,1);assert.equal(hash(fs.readFileSync(f.database)),before);const bundle=path.join(f.dir,'backup'),manifest=await backupCore(f.database,f.artifacts,bundle);assert.equal(manifest.version,2);assert.equal(manifest.snapshotCount,1);assert(manifest.files.some(row=>row.path.includes('/blobs/')));const backupHash=hash(fs.readFileSync(path.join(bundle,'core.sqlite')));const restored=await restoreCore(bundle,path.join(f.dir,'restored')),source=new SourceSnapshotStore(restored.sourceRoot);assert.equal((await source.completed(f.snapshot.projectId,f.snapshot.snapshotId,f.snapshot.checksum)).checksum,f.snapshot.checksum);assert.equal((await source.blob(f.snapshot.projectId,f.snapshot.files[0].checksum,f.snapshot.files[0].size!)).toString(),f.snapshot.files[0].content);assert.equal((await diagnoseStorage(restored.database,restored.artifactRoot)).ok,true);assert.equal(hash(fs.readFileSync(path.join(bundle,'core.sqlite'))),backupHash);}finally{f.cleanup();}});
test('tampered snapshot backup is rejected before any restore destination is created',async()=>{const f=await fixture();try{const bundle=path.join(f.dir,'backup'),manifest=await backupCore(f.database,f.artifacts,bundle),file=manifest.files.find(row=>row.path.includes('/blobs/'))!;fs.appendFileSync(path.join(bundle,file.path),'bad');const target=path.join(f.dir,'rejected');await assert.rejects(restoreCore(bundle,target),/checksum/);assert.equal(fs.existsSync(target),false);file.size=fs.statSync(path.join(bundle,file.path)).size;file.sha256=hash(fs.readFileSync(path.join(bundle,file.path)));fs.writeFileSync(path.join(bundle,'manifest.json'),JSON.stringify(manifest));await assert.rejects(restoreCore(bundle,target),/integrity/);assert.equal(fs.existsSync(target),false);assert.equal((await diagnoseStorage(f.database,f.artifacts)).ok,true);}finally{f.cleanup();}});
test('diagnosis never generates a key or upgrades a newer schema; incomplete snapshots are excluded',async()=>{const f=await fixture();try{const keypath=f.database+'.key',saved=fs.readFileSync(keypath);fs.unlinkSync(keypath);assert.equal((await diagnoseStorage(f.database,f.artifacts)).code,'KEY_MISSING');assert.equal(fs.existsSync(keypath),false);fs.writeFileSync(keypath,saved);const db=new DatabaseSync(f.database);db.exec('PRAGMA user_version=999');db.close();const before=hash(fs.readFileSync(f.database));assert.equal((await diagnoseStorage(f.database,f.artifacts)).code,'SCHEMA_NEWER');assert.equal(hash(fs.readFileSync(f.database)),before);}finally{f.cleanup();}});
test('connection recovery distinguishes authentication from transport and never automatically resubmits writes',()=>{assert.equal(recoveryGuide('authentication').retry,false);assert.equal(recoveryGuide('protocol-error').retry,false);assert.equal(recoveryGuide('unavailable').retry,true);assert.equal(recoveryGuide('connected').action,'');});

test('incomplete Source upload is diagnosed and excluded while completed bodies remain recoverable',async()=>{const f=await fixture();try{const next={...projectManifestRecord(f.snapshot),snapshotId:crypto.randomUUID()};const {contentHash}=await import('../src/features/ai/fix-service.ts');const {projectManifest}=await import('../src/features/ai/project-snapshot.ts');next.checksum=await contentHash(projectManifest(next));await f.source.begin(next);const diagnosis=await diagnoseStorage(f.database,f.artifacts);assert.equal(diagnosis.incompleteSnapshots,1);const bundle=path.join(f.dir,'backup');const manifest=await backupCore(f.database,f.artifacts,bundle);assert.equal(manifest.snapshotCount,1);assert(!manifest.files.some(row=>row.path.includes(next.snapshotId)));}finally{f.cleanup();}});
