import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSnapshot,verifySnapshot,snapshotManifest} from '../src/features/ai/snapshot.ts';
import {contentHash} from '../src/features/ai/fix-service.ts';
import {FakeFileSystemHost} from './helpers/fake-host.ts';
import {WorkspaceFileService} from '../src/features/filesystem/file-service.ts';
async function setup(){const host=new FakeFileSystemHost();host.entries.set('src',null);host.entries.set('src/main.ts','export const value=1;');host.entries.set('.env','dummy secret');host.entries.set('credential.json','dummy credential');host.entries.set('debug.txt','token=dummy-secret');const files=new WorkspaceFileService(host);await files.restore('test');const identity={projectId:crypto.randomUUID(),proposalId:crypto.randomUUID(),attempt:1,baseRevision:'main',changedFiles:['src/main.ts']};return{host,files,identity};}
test('snapshot excludes secret files/content and includes immutable manifest',async()=>{const {files,identity}=await setup();const {snapshot,excluded}=await buildSnapshot(files,identity);assert.deepEqual(snapshot.files.map(f=>f.path),['src/main.ts']);assert(excluded.includes('.env'));assert(excluded.includes('debug.txt'));await verifySnapshot(snapshot);});
test('snapshot configured patterns and known environment values excluded',async()=>{const {files,host,identity}=await setup();host.entries.set('notes.txt','dummy-env-value');host.entries.set('private.txt','private info');const {snapshot}=await buildSnapshot(files,identity,['dummy-env-value'],['private']);assert(!snapshot.files.some(f=>['notes.txt','private.txt'].includes(f.path)));});
test('snapshot content and manifest checksum failures reject',async()=>{const {files,identity}=await setup();const {snapshot}=await buildSnapshot(files,identity);snapshot.files[0].content+='changed';await assert.rejects(verifySnapshot(snapshot));});
test('snapshot path traversal and case aliases reject even with correct manifest',async()=>{const {files,identity}=await setup();const {snapshot}=await buildSnapshot(files,identity);snapshot.files[0].path='../outside';snapshot.checksum=await contentHash(snapshotManifest(snapshot));await assert.rejects(verifySnapshot(snapshot));snapshot.files[0].path='src/main.ts';snapshot.files.push({...snapshot.files[0],path:'SRC/MAIN.ts'});snapshot.checksum=await contentHash(snapshotManifest(snapshot));await assert.rejects(verifySnapshot(snapshot));});
test('snapshot refuses over-budget and missing changed files instead of silently truncating',async()=>{const {files,identity,host}=await setup();host.entries.set('large.txt','x'.repeat(24001));await assert.rejects(buildSnapshot(files,identity),/SNAPSHOT_LIMIT/);host.entries.delete('large.txt');await assert.rejects(buildSnapshot(files,{...identity,changedFiles:['missing.ts']}));});
