import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {maintainSources,offlineSourceMaintenance} from '../transport/source-maintenance.ts';import {SourceSnapshotStore} from '../transport/source-snapshot-store.ts';import {CoreStore} from '../transport/storage.ts';
import {buildProjectSnapshot,projectManifestRecord,projectReference} from '../src/features/ai/project-snapshot.ts';import {bytesHash} from '../src/features/ai/snapshot-bytes.ts';
const base=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/sixth-advancement/phase-4/maintenance-tests/',import.meta.url));fs.mkdirSync(base,{recursive:true});
async function fixture(){const root=fs.mkdtempSync(path.join(base,'case-')),store=new SourceSnapshotStore(root),projectId=crypto.randomUUID();const create=async(text:string,complete=true)=>{const {snapshot}=await buildProjectSnapshot({list:async()=>[{name:'file.ts',path:'file.ts',kind:'file'}],read:async()=>({content:text,size:new TextEncoder().encode(text).length,modified:0})},{projectId,proposalId:crypto.randomUUID(),attempt:1,baseRevision:'test',changedFiles:[]});await store.begin(projectManifestRecord(snapshot));const bytes=new TextEncoder().encode(text);await store.append(projectId,snapshot.snapshotId,snapshot.files[0].checksum,0,(async function*(){yield bytes;})(),await bytesHash(bytes));if(complete)await store.complete(projectId,snapshot.snapshotId);for(const name of [path.join(root,'manifests',projectId,snapshot.snapshotId+'.json'),path.join(root,'blobs',projectId,snapshot.files[0].checksum)])fs.utimesSync(name,new Date(1),new Date(1));return snapshot;};return{root,projectId,store,create,close(){assert(path.resolve(root).startsWith(path.resolve(base)+path.sep));fs.rmSync(root,{recursive:true,force:true});}};}
test('dry-run and apply preserve referenced/shared/incomplete source and reclaim only old unreferenced bytes',async()=>{
 const f=await fixture();try{const kept=await f.create('shared source'),shared=await f.create('shared source'),old=await f.create('orphan source'),incomplete=await f.create('incomplete source',false);
 const jobs=[{projectId:f.projectId,payload:{task:'test',steps:[{name:'Source',executable:'snapshot',args:[],cwd:'.',source:{provider:'snapshot' as const,repository:'snapshot:'+kept.snapshotId,revision:kept.baseRevision,snapshot:projectReference(kept)}}]}}];
 const preview=await maintainSources(f.root,jobs,Date.now());assert.equal(preview.reclaimableSnapshots,2);assert.equal(preview.reclaimableBlobs,1);assert.equal(preview.incomplete,1);await f.store.completed(f.projectId,old.snapshotId,old.checksum);
 const applied=await maintainSources(f.root,jobs,Date.now(),true);assert.equal(applied.reclaimableBytes,'orphan source'.length);await f.store.completed(f.projectId,kept.snapshotId,kept.checksum);await f.store.manifest(f.projectId,incomplete.snapshotId);await assert.rejects(f.store.manifest(f.projectId,shared.snapshotId));await assert.rejects(f.store.blob(f.projectId,old.files[0].checksum,old.files[0].size!));assert.equal((await maintainSources(f.root,jobs,Date.now(),true)).reclaimableSnapshots,0);
 }finally{f.close();}
});
test('corrupt manifest fails before deletion; offline maintenance refuses an active Core writer',async()=>{
 const f=await fixture();try{const first=await f.create('original'),second=await f.create('second');fs.writeFileSync(path.join(f.root,'manifests',f.projectId,second.snapshotId+'.json'),'{bad');await assert.rejects(maintainSources(f.root,[],Date.now(),true));await f.store.completed(f.projectId,first.snapshotId,first.checksum);
 const database=path.join(f.root,'core.sqlite');fs.writeFileSync(database+'.key',Buffer.alloc(32,9));const store=new CoreStore(database,Buffer.alloc(32,9));try{await assert.rejects(offlineSourceMaintenance(database,path.join(f.root,'artifacts'),Date.now(),true));}finally{store.close();}
 }finally{f.close();}
});
