import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {SourceSnapshotStore} from '../transport/source-snapshot-store.ts';
import {buildProjectSnapshot,projectManifestRecord,projectManifest,type ProjectSnapshot} from '../src/features/ai/project-snapshot.ts';
import {bytesHash,projectSnapshotLimits} from '../src/features/ai/snapshot-bytes.ts';
import {contentHash} from '../src/features/ai/fix-service.ts';
const base=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/fifth-advancement/phase-2/source-store-tests/',import.meta.url));
const stream=(bytes:Uint8Array)=>(async function*(){yield bytes;})();
async function fixture(){await fs.mkdir(base,{recursive:true});const root=await fs.mkdtemp(path.join(base,'case-')),bytes=new TextEncoder().encode('x'.repeat(600000)),identity={projectId:crypto.randomUUID(),proposalId:crypto.randomUUID(),attempt:1,baseRevision:'test',changedFiles:['src/file.ts']};const {snapshot}=await buildProjectSnapshot({list:async()=>[{path:'src/file.ts',name:'file.ts',kind:'file'}],read:async()=>({content:new TextDecoder().decode(bytes),size:bytes.length,modified:0})},identity);const store=new SourceSnapshotStore(root);await store.begin(projectManifestRecord(snapshot));return{root,store,snapshot,bytes,async cleanup(){assert(root.startsWith(base));await fs.rm(root,{recursive:true,force:true});}};}
test('chunk restart resumes acknowledged bytes and a completed project cache omits repeated transfer',async()=>{const f=await fixture();try{const file=f.snapshot.files[0],first=f.bytes.subarray(0,100000);await f.store.append(f.snapshot.projectId,f.snapshot.snapshotId,file.checksum,0,stream(first),await bytesHash(first));const resumed=new SourceSnapshotStore(f.root);assert.equal(await resumed.progress(f.snapshot.projectId,f.snapshot.snapshotId,file.checksum),100000);for(let start=100000;start<f.bytes.length;){const next=f.bytes.subarray(start,start+projectSnapshotLimits.chunkBytes);await resumed.append(f.snapshot.projectId,f.snapshot.snapshotId,file.checksum,start,stream(next),await bytesHash(next));start+=next.length;}await resumed.complete(f.snapshot.projectId,f.snapshot.snapshotId);assert.equal((await resumed.completed(f.snapshot.projectId,f.snapshot.snapshotId,f.snapshot.checksum)).files.length,1);assert.deepEqual(await resumed.blob(f.snapshot.projectId,file.checksum,file.size!),Buffer.from(f.bytes));const second=structuredClone(f.snapshot);second.snapshotId=crypto.randomUUID();second.checksum=await contentHash(projectManifest(second));await resumed.begin(projectManifestRecord(second));assert.equal(await resumed.progress(second.projectId,second.snapshotId,file.checksum),f.bytes.length);await resumed.complete(second.projectId,second.snapshotId);}finally{await f.cleanup();}});
test('chunk corruption/oversize and interrupted bodies never acknowledge or publish data',async()=>{const f=await fixture();try{const s=f.snapshot,file=s.files[0];await assert.rejects(f.store.append(s.projectId,s.snapshotId,file.checksum,0,stream(f.bytes.subarray(0,10)),'a'.repeat(64)),/checksum/);assert.equal(await f.store.progress(s.projectId,s.snapshotId,file.checksum),0);await assert.rejects(f.store.append(s.projectId,s.snapshotId,file.checksum,0,stream(f.bytes.subarray(0,projectSnapshotLimits.chunkBytes+1)),await bytesHash(f.bytes.subarray(0,projectSnapshotLimits.chunkBytes+1))),/chunk limit/);const interrupted=(async function*(){yield f.bytes.subarray(0,100);throw Error('connection lost');})();await assert.rejects(f.store.append(s.projectId,s.snapshotId,file.checksum,0,interrupted,await bytesHash(f.bytes.subarray(0,100))),/connection/);assert.equal(await f.store.progress(s.projectId,s.snapshotId,file.checksum),0);await assert.rejects(f.store.complete(s.projectId,s.snapshotId));await assert.rejects(f.store.completed(s.projectId,s.snapshotId,s.checksum));}finally{await f.cleanup();}});
test('manifest traversal/project scope and decoded dummy secrets are blocked',async()=>{const f=await fixture();try{const s=f.snapshot,malicious=projectManifestRecord(s);malicious.files[0].path='../outside.ts';await assert.rejects(f.store.begin(malicious));await assert.rejects(f.store.progress(crypto.randomUUID(),s.snapshotId,s.files[0].checksum));const bytes=new Uint8Array([0,...new TextEncoder().encode('api_key=DUMMY_SECRET_123'),255]),unsafe:ProjectSnapshot={...s,snapshotId:crypto.randomUUID(),files:[{path:'binary.bin',content:'',encoding:'base64',size:bytes.length,checksum:await bytesHash(bytes)}],changedFiles:[]};unsafe.checksum=await contentHash(projectManifest(unsafe));await f.store.begin(unsafe);await assert.rejects(f.store.append(unsafe.projectId,unsafe.snapshotId,unsafe.files[0].checksum,0,stream(bytes),await bytesHash(bytes)),/secret/);await assert.rejects(f.store.complete(unsafe.projectId,unsafe.snapshotId));}finally{await f.cleanup();}});

test('Core stores typed Rust across chunks and cannot reuse its blob under a stricter data-file path',async()=>{
 const f=await fixture();try{
  const text='struct Options { password: Option<String>, token: String }',bytes=Buffer.from(text);
  const built=await buildProjectSnapshot({list:async()=>[{path:'src/main.rs',name:'main.rs',kind:'file' as const}],read:async()=>({content:text,size:bytes.length,modified:0})},{projectId:f.snapshot.projectId,proposalId:crypto.randomUUID(),attempt:1,baseRevision:'typed-rust',changedFiles:[]});
  const s=built.snapshot,file=s.files[0];await f.store.begin(projectManifestRecord(s));const cut=17;
  await f.store.append(s.projectId,s.snapshotId,file.checksum,0,stream(bytes.subarray(0,cut)),await bytesHash(bytes.subarray(0,cut)));
  await f.store.append(s.projectId,s.snapshotId,file.checksum,cut,stream(bytes.subarray(cut)),await bytesHash(bytes.subarray(cut)));await f.store.complete(s.projectId,s.snapshotId);assert.deepEqual(await f.store.blob(s.projectId,file.checksum,file.size!),bytes);
  const renamed=projectManifestRecord(s);renamed.snapshotId=crypto.randomUUID();renamed.files[0].path='data.txt';renamed.checksum=await contentHash(projectManifest(renamed));await f.store.begin(renamed);
  await assert.rejects(f.store.progress(renamed.projectId,renamed.snapshotId,file.checksum),/secret/);await assert.rejects(f.store.complete(renamed.projectId,renamed.snapshotId),/secret/);
 }finally{await f.cleanup();}
});
