import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CoreStore, SqliteCoreRepository, storageKey } from '../transport/storage.ts';
const fixtureRoot=fileURLToPath(new URL('../../../../resources/verification/dev-01/tasks/tastedev-studio/advancement-1/sqlite-unit/',import.meta.url));
function fixture(){fs.mkdirSync(fixtureRoot,{recursive:true});const dir=fs.mkdtempSync(path.join(fixtureRoot,'case-'));return{dir,file:path.join(dir,'core.sqlite'),key:Buffer.alloc(32,7),cleanup(){assert.ok(path.resolve(dir).startsWith(path.resolve(fixtureRoot)+path.sep));fs.rmSync(dir,{recursive:true,force:true});}};}

test('SQLite migration, committed revision and state survive reopen',()=>{const f=fixture();try{let s=new CoreStore(f.file,f.key);const r=new SqliteCoreRepository(s);r.transaction(tx=>tx.events.save({id:'e',entityId:'j',projectId:'p',type:'job.created',timestamp:'2026-10-01T00:00:00Z'}));assert.equal(r.revision(),1);s.close();s=new CoreStore(f.file,f.key);const loaded=new SqliteCoreRepository(s);assert.equal(loaded.revision(),1);assert.equal(loaded.read().events[0].id,'e');assert.equal(s.db.prepare('SELECT count(*) AS n FROM migrations').get()?.n,1);s.close();}finally{f.cleanup();}});
test('write rejection never changes memory, revision or observer state',()=>{const f=fixture();const s=new CoreStore(f.file,f.key);try{const r=new SqliteCoreRepository(s);let events=0;r.subscribe(()=>events++);s.db.exec("CREATE TRIGGER deny BEFORE INSERT ON units BEGIN SELECT RAISE(ABORT,'controlled write failure'); END;");assert.throws(()=>r.transaction(tx=>tx.events.save({id:'e',entityId:'j',projectId:null,type:'job.created',timestamp:'now'})));assert.deepEqual(r.read().events,[]);assert.equal(r.revision(),0);assert.equal(events,0);assert.equal(s.get('core'),undefined);}finally{s.close();f.cleanup();}});
test('multi-unit write is rolled back in full when a later unit fails',()=>{const f=fixture();const s=new CoreStore(f.file,f.key);try{s.put('a',{value:1});s.db.exec("CREATE TRIGGER deny BEFORE INSERT ON units WHEN NEW.name='bad' BEGIN SELECT RAISE(ABORT,'controlled failure'); END;");assert.throws(()=>s.putMany([['a',{value:2}],['bad',{}]]));assert.deepEqual(s.get('a'),{value:1});assert.equal(s.get('bad'),undefined);}finally{s.close();f.cleanup();}});
test('dummy sensitive values are not present in the database bytes',()=>{const f=fixture();const s=new CoreStore(f.file,f.key);try{s.put('protocol',{env:{PASSWORD:'DUMMY_SECRET_FOR_STORAGE_ONLY'}});assert.ok(!fs.readFileSync(f.file).includes(Buffer.from('DUMMY_SECRET_FOR_STORAGE_ONLY')));assert.equal(s.get<{env:{PASSWORD:string}}>('protocol')?.env.PASSWORD,'DUMMY_SECRET_FOR_STORAGE_ONLY');}finally{s.close();f.cleanup();}});
test('wrong key and tampered authenticated payload fail without silent clearing',()=>{const f=fixture();let s=new CoreStore(f.file,f.key);try{s.put('data',{v:1});s.close();assert.throws(()=>new CoreStore(f.file,Buffer.alloc(32,8)),/integrity/);s=new CoreStore(f.file,f.key);s.db.prepare('UPDATE units SET payload=?').run(Buffer.alloc(32));s.close();assert.throws(()=>new CoreStore(f.file,f.key),/integrity/);}finally{f.cleanup();}});
test('backup restores the same encrypted units and refuses overwrite',async()=>{const f=fixture();const s=new CoreStore(f.file,f.key);try{s.putMany([['logs',{chunks:[{text:'safe evidence'}]}],['attempts',[{id:'a',status:'failed'}]]]);const target=path.join(f.dir,'backup.sqlite');await s.backup(target);await assert.rejects(s.backup(target),/new absolute/);const restored=new CoreStore(target,f.key);assert.deepEqual(restored.get('logs'),s.get('logs'));assert.deepEqual(restored.get('attempts'),s.get('attempts'));restored.close();}finally{s.close();f.cleanup();}});
test('second Core writer and future schema are rejected',()=>{const f=fixture();const s=new CoreStore(f.file,f.key);try{assert.throws(()=>new CoreStore(f.file,f.key));s.db.exec('PRAGMA user_version=99');s.close();assert.throws(()=>new CoreStore(f.file,f.key),/newer/);}finally{f.cleanup();}});
test('existing database never gets a replacement key when original is missing',()=>{const f=fixture();try{const k=storageKey(f.file);assert.deepEqual(storageKey(f.file),k);const s=new CoreStore(f.file,k);s.close();fs.unlinkSync(f.file+'.key');assert.throws(()=>storageKey(f.file),/missing/);assert.equal(fs.existsSync(f.file+'.key'),false);}finally{f.cleanup();}});
