import test from 'node:test';
import assert from 'node:assert/strict';
import {TeamAccess,teamTokenHash,type TeamConfiguration} from '../transport/team-access.ts';
import {TeamAllocation} from '../transport/team-allocation.ts';
import {CoreService} from '../src/features/core/service.ts';
import {InMemoryCoreRepository} from '../src/features/core/repository.ts';
import type {Job,Run} from '../src/features/core/domain.ts';
const config:TeamConfiguration={users:[{id:'owner',role:'Owner',projects:['alpha','beta']}],sessions:[{id:'owner-session',userId:'owner',tokenHash:teamTokenHash('Dummy-team-allocation-20261001'),expiresAt:'2099-01-01T00:00:00Z'}],projects:[{id:'alpha',agentGroups:['a'],maxQueued:3,maxActive:1},{id:'beta',agentGroups:['b'],maxQueued:3,maxActive:1}],agents:[{id:'agent-a',tokenHash:teamTokenHash('Dummy-agent-a-allocation-20261001'),groups:['a'],labels:{}},{id:'agent-b',tokenHash:teamTokenHash('Dummy-agent-b-allocation-20261001'),groups:['b'],labels:{}}],maxQueuedPerUser:2,maxActivePerUser:1};
function fixture(){const access=new TeamAccess(config);const policy=new TeamAllocation(access,()=>core.repository.read());const core:CoreService=new CoreService(new InMemoryCoreRepository(),{get:async id=>({id,name:id}) as never},{allowAgent:access.allowedAgent.bind(access),admitJob:policy.admit.bind(policy),allowAssignment:policy.eligible.bind(policy),strategy:policy.strategy});for(const id of ['agent-a','agent-b'])core.connectAgent(id,{name:id,platform:'windows',architecture:'x86_64',capabilities:{cpuCores:1,memoryMiB:1024,docker:false,gpu:false,pty:false,runtimes:{node:'24'},browsers:[]}});return{core,policy};}
const job=(key?:string)=>({name:'Controlled bounded allocation',requirements:{},payload:{task:'controlled',steps:[{name:'controlled',executable:'node',args:['-e','process.exit(0)'],cwd:'.'}]},...(key?{idempotencyKey:key}:{})});
test('admission is transaction scoped, user bounded and idempotent at the limit',async()=>{const {core}=fixture();const a=await core.createJob('alpha',job('a'),'alice');await core.createJob('alpha',job('b'),'alice');await assert.rejects(core.createJob('alpha',job('c'),'alice'),/TEAM_QUEUE_LIMIT/);assert.equal((await core.createJob('alpha',job('a'),'alice')).id,a.id);assert.equal(core.queue().length,2);});
test('project queue flood is bounded across multiple actors',async()=>{const {core}=fixture();await Promise.all(['one','two','three'].map(actor=>core.createJob('alpha',job(),actor)));await assert.rejects(core.createJob('alpha',job(),'four'),/TEAM_QUEUE_LIMIT/);assert.equal(core.queue('alpha').length,3);});
test('group policy and project active quota apply to actual domain assignment',async()=>{const {core}=fixture();await core.createJob('alpha',job(),'alice');await core.createJob('alpha',job(),'bob');await core.createJob('beta',job(),'carol');const a=core.dispatch('alpha');assert.equal(a?.agent.id,'agent-a');assert.equal(core.dispatch('alpha'),null);assert.equal(core.dispatch('beta')?.agent.id,'agent-b');assert.equal(core.repository.read().runs.filter(r=>r.status==='pending').length,2);});
test('user active quota spans projects and keeps pending assignments reserved',async()=>{const {core}=fixture();await core.createJob('alpha',job(),'alice');await core.createJob('beta',job(),'alice');assert.ok(core.dispatch('alpha'));assert.equal(core.dispatch('beta'),null);});
test('fair ordering prevents priority from overtaking a never-served tenant or actor',()=>{const {policy}=fixture();const base={...job(),id:'first',projectId:'alpha',createdBy:'alice',status:'queued',queuedAt:'2026-10-01T00:00:00Z',priority:100} as unknown as Job;const other={...base,id:'second',projectId:'beta',createdBy:'bob',priority:0};const history={jobs:[base,other],runs:[{id:'prior',jobId:base.id,projectId:'alpha',status:'passed',createdAt:'2026-10-01T00:00:01Z'} as Run]};const custom=new TeamAllocation(new TeamAccess(config),()=>history);assert.equal(custom.strategy.jobs([base,other])[0].id,'second');assert.equal(policy.strategy.jobs([{...other,queuedAt:'2026-10-01T00:00:02Z'},base])[0].id,'first');});
