import test from 'node:test';import assert from 'node:assert/strict';
import {parseProtocol} from '../src/features/protocol/parser.ts';import {validationImpact,validateImpactPlan} from '../src/features/ai/validation-impact.ts';import {affectedPattern,matchesAffected} from '../src/features/protocol/affected-files.ts';
import type {TasteDevProjectDefinition} from '../src/features/protocol/domain.ts';
function definition():TasteDevProjectDefinition{const state=parseProtocol({'project.yml':'version: 1\nproject: { name: Fixture, type: node }','tasks.yml':JSON.stringify({typecheck:{command:'node',args:['check.cjs']},lint:{command:'node',args:['lint.cjs']},unit:{command:'node',args:['test.cjs']}}),'tests.yml':JSON.stringify({auth:{task:'unit',type:'unit',affectedFiles:['src/auth/**','tests/auth*.cjs']},billing:{task:'unit',type:'unit',affectedFiles:['src/billing/**']}})});assert.equal(state.status,'Valid');return(state as {status:'Valid';definition:TasteDevProjectDefinition}).definition;}
const ids=()=>[crypto.randomUUID(),crypto.randomUUID()] as const;
test('explicit affected files select related tests while standard tasks and original failure remain',async()=>{const [project,proposal]=ids(),d=definition(),p=await validationImpact(d,project,proposal,['src/auth/login.ts'],['test:auth','node arbitrary.cjs'],'billing');assert.equal(p.coverage,'explicit');assert.deepEqual(p.recommendations.map(r=>r.kind+':'+r.name),['task:typecheck','task:lint','test:billing','test:auth']);assert.deepEqual(p.ignoredSuggestions,['node arbitrary.cjs']);assert.equal(validateImpactPlan(p,project,proposal,['src/auth/login.ts']),p);assert.throws(()=>validateImpactPlan(p,crypto.randomUUID(),proposal,['src/auth/login.ts']));});
test('unmapped and shared configuration changes conservatively include all saved tests',async()=>{const [project,proposal]=ids(),d=definition();for(const path of ['src/unknown.ts','package.json','pnpm-lock.yaml','.tastedev/tests.yml']){const p=await validationImpact(d,project,proposal,[path]);assert.equal(p.coverage,path==='src/unknown.ts'?'fallback':'global');assert.deepEqual(p.recommendations.filter(r=>r.kind==='test').map(r=>r.name),['auth','billing']);}await assert.rejects(validationImpact(d,project,proposal,['../outside.ts']));});
test('safe globs support zero/multiple directory segments without interpreting regex or traversal',()=>{for(const path of ['src/auth/a.ts','src/auth/deep/b.ts'])assert(matchesAffected('src/auth/**',path));assert(matchesAffected('**/login*.ts','login.ts'));assert(matchesAffected('**/login*.ts','src/login-page.ts'));assert(!matchesAffected('src/auth/*.ts','src/auth/deep/b.ts'));for(const value of ['../escape','/absolute','C:/outside','src/(a+)+','src/a**b','src/'])assert.throws(()=>affectedPattern(value));assert(matchesAffected('**/**/**/**/a','one/two/three/a'));});
test('Protocol rejects invalid affected patterns and retains optional mappings without changing task execution',()=>{const d=definition();assert.deepEqual(d.tests.auth.affectedFiles,['src/auth/**','tests/auth*.cjs']);const state=parseProtocol({'project.yml':'version: 1\nproject: { name: Fixture, type: node }','tasks.yml':'unit: { command: node }','tests.yml':'bad: { task: unit, type: unit, affectedFiles: ["../escape"] }'});assert.equal(state.status,'Invalid');});
