import {snapshotHasSecret} from './snapshot-content-policy.ts';
import type {WorkspaceFileService} from '../filesystem/file-service.ts';
import {snapshotPath,type WorkspaceSnapshot,type SnapshotFile} from './snapshot.ts';
import {uuid} from './security.ts';
import {FixError,contentHash} from './fix-service.ts';
import {base64Decode,base64Encode,binaryText,bytesHash,projectSnapshotLimits as limits} from './snapshot-bytes.ts';
export interface ProjectSnapshot extends WorkspaceSnapshot {schemaVersion:2}
export function projectSnapshotPath(path:string){snapshotPath(path);if(new TextEncoder().encode(path).length>240||path.split('/').some(p=>/[. ]$/.test(p)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(p)))throw new FixError('SNAPSHOT_PATH');return path;}
export function snapshotBytes(file:SnapshotFile){if(file.encoding==='base64'){try{return base64Decode(file.content);}catch{throw new FixError('SNAPSHOT_INTEGRITY');}}if(file.encoding!=='utf8')throw new FixError('SNAPSHOT_ENCODING');return new TextEncoder().encode(file.content);}
export function projectManifest(snapshot:ProjectSnapshot){return JSON.stringify([2,snapshot.snapshotId,snapshot.projectId,snapshot.proposalId,snapshot.attempt,snapshot.baseRevision,snapshot.changedFiles,...snapshot.files.map(f=>[f.path,f.checksum,f.encoding,f.size])]);}
export function projectManifestRecord(snapshot:ProjectSnapshot){return {...snapshot,files:snapshot.files.map(f=>({...f,content:''})),transfer:undefined};}
export function projectReference(snapshot:ProjectSnapshot):ProjectSnapshot {return{...snapshot,files:[],changedFiles:[],transfer:{manifestChecksum:snapshot.checksum,fileCount:snapshot.files.length,changedFileCount:snapshot.changedFiles.length,totalBytes:snapshot.files.reduce((n,f)=>n+(f.size??0),0)}};}
function identity(s:ProjectSnapshot){uuid(s.snapshotId);uuid(s.projectId);uuid(s.proposalId);if(s.schemaVersion!==2||s.provider!=='snapshot'||!Number.isInteger(s.attempt)||s.attempt<1||s.attempt>10||typeof s.baseRevision!=='string'||new TextEncoder().encode(s.baseRevision).length>200||!Array.isArray(s.changedFiles)||s.changedFiles.length>limits.files||new Set(s.changedFiles).size!==s.changedFiles.length||!Array.isArray(s.files)||!/^[a-f0-9]{64}$/.test(s.checksum)||Object.keys(s).some(k=>!['schemaVersion','provider','snapshotId','projectId','proposalId','attempt','baseRevision','changedFiles','files','checksum','transfer'].includes(k)))throw new FixError('INVALID_SNAPSHOT');for(const p of s.changedFiles)projectSnapshotPath(p);}
/** Reference validation is separate from manifest/body verification; Core must
 * resolve its own completed upload before accepting a reference into a Job. */
export function verifyProjectReference(s:ProjectSnapshot){identity(s);const t=s.transfer;if(s.files.length||s.changedFiles.length||!t||t.manifestChecksum!==s.checksum||!Number.isInteger(t.fileCount)||t.fileCount<1||t.fileCount>limits.files||!Number.isInteger(t.changedFileCount)||t.changedFileCount!<0||t.changedFileCount!>limits.files||!Number.isSafeInteger(t.totalBytes)||t.totalBytes<0||t.totalBytes>limits.bytes||t.url!==undefined||t.token!==undefined||Object.keys(t).some(k=>!['manifestChecksum','fileCount','changedFileCount','totalBytes'].includes(k)))throw new FixError('INVALID_SNAPSHOT_REFERENCE');return s;}
export async function verifyProjectManifest(s:ProjectSnapshot){identity(s);if(s.transfer||!s.files.length||s.files.length>limits.files)throw new FixError('INVALID_SNAPSHOT');const paths=new Set<string>();let bytes=0;for(const f of s.files){projectSnapshotPath(f.path);if(paths.has(f.path.toLowerCase())||!['utf8','base64'].includes(f.encoding??'')||!Number.isSafeInteger(f.size)||f.size!<0||f.size!>limits.fileBytes||!/^[a-f0-9]{64}$/.test(f.checksum)||Object.keys(f).some(k=>!['path','content','checksum','encoding','size'].includes(k)))throw new FixError('SNAPSHOT_INTEGRITY');paths.add(f.path.toLowerCase());bytes+=f.size!;}if(bytes>limits.bytes||s.changedFiles.some(p=>!s.files.some(f=>f.path===p))||new TextEncoder().encode(projectManifest(s)).length>limits.manifestBytes||await contentHash(projectManifest(s))!==s.checksum)throw new FixError('SNAPSHOT_INTEGRITY');return s;}
export async function verifyProjectSnapshot(s:ProjectSnapshot,secrets:string[]=[]){await verifyProjectManifest(s);for(const f of s.files){const bytes=snapshotBytes(f);if(bytes.length!==f.size||await bytesHash(bytes)!==f.checksum)throw new FixError('SNAPSHOT_INTEGRITY');const raw=binaryText(bytes),decoded=new TextDecoder().decode(bytes);if(snapshotHasSecret(f.path,raw,secrets)||snapshotHasSecret(f.path,decoded,secrets))throw new FixError('SNAPSHOT_SECRET');}return s;}
export async function buildProjectSnapshot(files:Pick<WorkspaceFileService,'list'|'read'> & Partial<Pick<WorkspaceFileService,'readBytes'>>,identityValue:Omit<ProjectSnapshot,'provider'|'schemaVersion'|'snapshotId'|'files'|'checksum'|'transfer'>,secrets:string[]=[],excludedPatterns:string[]=[],signal?:AbortSignal){
 const pending=[''],entries:SnapshotFile[]=[],excluded:string[]=[];let bytes=0,directories=0;
 while(pending.length){signal?.throwIfAborted();const dir=pending.shift()!;if(++directories>20000)throw new FixError('SNAPSHOT_LIMIT');for(const entry of await files.list(dir,true)){signal?.throwIfAborted();try{projectSnapshotPath(entry.path);}catch{excluded.push(entry.path);continue;}if(excludedPatterns.some(p=>entry.path.includes(p))){excluded.push(entry.path);continue;}if(entry.kind==='directory'){pending.push(entry.path);continue;}
  const value=files.readBytes?await files.readBytes(entry.path):new TextEncoder().encode((await files.read(entry.path)).content);if(value.length>limits.fileBytes)throw new FixError('SNAPSHOT_LIMIT');const raw=binaryText(value),decoded=new TextDecoder().decode(value);if(snapshotHasSecret(entry.path,raw,secrets)||snapshotHasSecret(entry.path,decoded,secrets)){excluded.push(entry.path);continue;}
  bytes+=value.length;if(entries.length>=limits.files||bytes>limits.bytes)throw new FixError('SNAPSHOT_LIMIT');let content:string,encoding:'utf8'|'base64';try{content=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(value);if(content.includes('\0'))throw Error('binary');encoding='utf8';}catch{content=base64Encode(value);encoding='base64';}entries.push({path:entry.path,content,encoding,size:value.length,checksum:await bytesHash(value)});
 }}
 entries.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);const snapshot:ProjectSnapshot={...identityValue,provider:'snapshot',schemaVersion:2,snapshotId:crypto.randomUUID(),files:entries,checksum:''};snapshot.checksum=await contentHash(projectManifest(snapshot));await verifyProjectSnapshot(snapshot,secrets);return{snapshot,excluded};
}
