import type { WorkspaceFileService } from '../filesystem/file-service.ts';
import {aiPath,mask,uuid} from './security.ts';
import {contentHash,FixError} from './fix-service.ts';
export interface SnapshotFile {path:string;content:string;checksum:string;encoding?:'utf8'|'base64';size?:number}
export interface SnapshotTransfer {manifestChecksum:string;fileCount:number;changedFileCount?:number;totalBytes:number;url?:string;token?:string}
export interface WorkspaceSnapshot {provider:'snapshot';schemaVersion?:2;snapshotId:string;projectId:string;proposalId:string;attempt:number;baseRevision:string;changedFiles:string[];files:SnapshotFile[];checksum:string;transfer?:SnapshotTransfer}
export const snapshotLimits={files:100,bytes:24000};
export function snapshotPath(path:string){aiPath(path);if(path.split('/').some((p,i,parts)=>/^(\.tastedev-artifacts|\.cache|artifacts|resources|vendor|bin|obj)$/i.test(p)&&!(p.toLowerCase()==='bin'&&i>0&&parts[i-1].toLowerCase()==='src')&&!(p.toLowerCase()==='resources'&&(i===parts.length-1||parts[i+1].toLowerCase()==='branding'))))throw new FixError('SNAPSHOT_EXCLUDED');return path;}
export function snapshotManifest(s:WorkspaceSnapshot){return JSON.stringify([s.snapshotId,s.projectId,s.proposalId,s.attempt,s.baseRevision,s.changedFiles,...s.files.map(f=>[f.path,f.checksum])]);}
export async function verifySnapshot(s:WorkspaceSnapshot){if(s.schemaVersion===2){const {verifyProjectSnapshot}=await import('./project-snapshot.ts');return verifyProjectSnapshot(s as import('./project-snapshot.ts').ProjectSnapshot);}uuid(s.snapshotId);uuid(s.projectId);uuid(s.proposalId);if(s.provider!=='snapshot'||!Number.isInteger(s.attempt)||s.attempt<1||s.attempt>10||!Array.isArray(s.files)||!s.files.length||s.files.length>snapshotLimits.files||typeof s.baseRevision!=='string'||s.baseRevision.length>200||s.changedFiles.some(p=>!s.files.some(f=>f.path===p)))throw new FixError('INVALID_SNAPSHOT');let bytes=0;const paths=new Set<string>();for(const f of s.files){snapshotPath(f.path);const key=f.path.toLowerCase();if(paths.has(key)||typeof f.content!=='string'||f.content.includes('\0')||mask(f.content)!==f.content||await contentHash(f.content)!==f.checksum)throw new FixError('SNAPSHOT_INTEGRITY');paths.add(key);bytes+=new TextEncoder().encode(f.content).length;}if(bytes>snapshotLimits.bytes||await contentHash(snapshotManifest(s))!==s.checksum)throw new FixError('SNAPSHOT_INTEGRITY');return s;}
/** Small text workspace transfer over the existing authenticated transport, no archive extraction. */
export async function buildSnapshot(files:Pick<WorkspaceFileService,'list'|'read'>,identity:Omit<WorkspaceSnapshot,'provider'|'snapshotId'|'files'|'checksum'>,secrets:string[]=[],excludedPatterns:string[]=[]){const entries:SnapshotFile[]=[],pending=[''],excluded:string[]=[];let bytes=0;while(pending.length){const dir=pending.shift()!;for(const entry of await files.list(dir,true)){try{snapshotPath(entry.path);}catch{excluded.push(entry.path);continue;}if(excludedPatterns.some(pattern=>entry.path.includes(pattern))){excluded.push(entry.path);continue;}if(entry.kind==='directory'){pending.push(entry.path);if(pending.length>100)throw new FixError('SNAPSHOT_LIMIT');continue;}const file=await files.read(entry.path);if(file.content.includes('\0')||mask(file.content,secrets)!==file.content){excluded.push(entry.path);continue;}bytes+=new TextEncoder().encode(file.content).length;if(entries.length>=snapshotLimits.files||bytes>snapshotLimits.bytes)throw new FixError('SNAPSHOT_LIMIT');entries.push({path:entry.path,content:file.content,checksum:await contentHash(file.content)});}}entries.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);const snapshot:WorkspaceSnapshot={...identity,provider:'snapshot',snapshotId:crypto.randomUUID(),files:entries,checksum:''};snapshot.checksum=await contentHash(snapshotManifest(snapshot));await verifySnapshot(snapshot);return{snapshot,excluded};}
