'use client';
import {useEffect,useRef,useState} from 'react';
import {CustomSelect} from '@/components/ui/custom-select';
import {useI18n} from '@/i18n/react';
import {useAI} from './views';
import {useCore} from '../core/context';
import {useFiles} from '../editor/session';
import {immutableRunSource} from './run-source';
import {SourceReview,type SourceReviewState} from './source-review';
import {GitDiffEditor} from '../git/diff-editor';
export function SnapshotSourceReview(){
 const ai=useAI(),core=useCore(),files=useFiles(),{t}=useI18n(),target=ai.sourceReview!;
 const generation=core.connection.generation;
 const [state,setState]=useState<SourceReviewState>({status:'closed',paths:[],path:'',text:'',line:1});const controller=useRef<SourceReview|null>(null);
 useEffect(()=>{let live=true;const project=core.project.id;const review=new SourceReview((identity,signal)=>immutableRunSource(project,identity.runId,(path,max,abort)=>core.connection.runSourceRequest(path,project,max,abort),signal),()=>live&&core.connection.connected&&generation===core.connection.generation,state=>{if(live)setState(state);});controller.current=review;void review.open(target);return()=>{live=false;review.close();if(controller.current===review)controller.current=null;};},[target,core.connection,core.connection.connected,core.project.id,generation]);
 function compare(){const folder=files.files.connection?.id,path=state.path,doc=files.documents.snapshot().openEditors.find(d=>d.path===path),baseline=doc?.content,savedBaseline=doc?.savedContent;const captured=doc?{content:doc.content,kind:doc.content!==doc.savedContent?'dirty-editor' as const:'saved-editor' as const}:undefined;
  void controller.current?.compare(async()=>{if(captured)return captured;return{content:(await files.files.read(path)).content,kind:'disk'};},()=>files.files.connection?.id===folder&&files.documents.snapshot().openEditors.find(d=>d.path===path)?.content===baseline&&files.documents.snapshot().openEditors.find(d=>d.path===path)?.savedContent===savedBaseline);
 }
 return <section className="ai-snapshot-review" aria-label={t('Run Snapshot source')}><div className="ai-snapshot-heading"><h2>{t('Run Snapshot source')}</h2><button className="fs-button" onClick={ai.closeSnapshot}>{t('Close Snapshot source')}</button></div><p>{t('Read only. This is the source used by the test Run, not the current workspace.')}</p><p>{t('Displayed text masks credential patterns. No files are changed.')}</p><dl className="ai-snapshot-identity"><dt>Run</dt><dd>{target.identity.runId}</dd><dt>Snapshot</dt><dd>{target.identity.snapshotId}</dd><dt>{t('Checksum')}</dt><dd>{target.identity.checksum}</dd></dl><div className="ai-snapshot-controls"><label>{t('Snapshot file')}<CustomSelect value={state.path} disabled={state.status==='loading'||!state.paths.length} onChange={e=>void controller.current?.select(e.target.value)}><option value="">{t('Select file')}</option>{state.paths.map(path=><option key={path}>{path}</option>)}</CustomSelect></label><button className="fs-button" disabled={!ai.connected||state.status!=='ready'||!state.path} onClick={compare}>{t('Compare with current editor / disk')}</button><button className="fs-button" disabled={!ai.connected||state.status==='loading'} onClick={()=>void controller.current?.open(target)}>{t('Retry Snapshot read')}</button></div>{!ai.connected&&<p role="status">{t('Connect to Core to review Snapshot source.')}</p>}{ai.connected&&state.status==='loading'&&<p role="status">{t('Reading Snapshot source…')}</p>}{state.status==='ready'&&!state.paths.length&&<p>{t('No readable text files in this Snapshot.')}</p>}{state.error&&<p role="alert">{t(state.error)}</p>}{ai.connected&&state.status==='ready'&&state.path&&<><div className="ai-snapshot-labels"><strong>{t('Tested Snapshot')} · {state.path}</strong><strong>{state.comparison?t(state.comparison.kind==='dirty-editor'?'Current unsaved editor':state.comparison.kind==='saved-editor'?'Current saved editor':'Current disk'):t('Read only')}</strong></div><GitDiffEditor diff={{path:state.path,side:'working',binary:false,original:state.text,modified:state.comparison?.content??state.text}} sideBySide={!!state.comparison} labels={{original:t('Tested Snapshot'),modified:state.comparison?t('Current workspace comparison'):t('Tested Snapshot')}} line={state.line}/></>}</section>;
}
