import {mask,aiPath} from './security.ts';
import type {RunSourceIdentity,immutableRunSource} from './run-source.ts';
export interface SourceReviewTarget {identity:RunSourceIdentity;path?:string;line?:number}
export interface SourceReviewState {status:'closed'|'loading'|'ready'|'error';paths:string[];path:string;text:string;line:number;identity?:RunSourceIdentity;comparison?:{content:string;kind:'dirty-editor'|'saved-editor'|'disk'};error?:string}
type Source=Awaited<ReturnType<typeof immutableRunSource>>;
/** This controller accepts only reads. Late replies never replace a newer selection or session. */
export class SourceReview {
 state:SourceReviewState={status:'closed',paths:[],path:'',text:'',line:1};private abort=new AbortController();private epoch=0;private source?:Source;
 private load:(identity:RunSourceIdentity,signal:AbortSignal)=>Promise<Source>;private current:()=>boolean;private changed:(state:SourceReviewState)=>void;
 constructor(load:(identity:RunSourceIdentity,signal:AbortSignal)=>Promise<Source>,current:()=>boolean,changed:(state:SourceReviewState)=>void){this.load=load;this.current=current;this.changed=changed;}
 private publish(state:SourceReviewState){this.state=state;this.changed(structuredClone(state));}
 close(){this.epoch++;this.abort.abort();this.source=undefined;this.publish({status:'closed',paths:[],path:'',text:'',line:1});}
 async open(target:SourceReviewTarget){this.close();this.abort=new AbortController();const id=++this.epoch,pinned=structuredClone(target);this.publish({status:'loading',paths:[],path:'',text:'',line:1});try{const source=await this.load(pinned.identity,this.abort.signal);if(id!==this.epoch||!this.current()||this.abort.signal.aborted)return;if(source.identity.runId!==pinned.identity.runId||source.identity.snapshotId!==pinned.identity.snapshotId||source.identity.checksum!==pinned.identity.checksum)throw Error('Snapshot identity mismatch.');this.source=source;this.publish({status:'ready',paths:source.paths,path:'',text:'',line:1,identity:source.identity});if(pinned.path&&!source.paths.includes(pinned.path))throw Error('Snapshot file unavailable.');if(pinned.path||source.paths.length)await this.select(pinned.path??source.paths[0],pinned.line);}catch{if(id===this.epoch&&this.current()&&!this.abort.signal.aborted)this.publish({...this.state,status:'error',text:'',comparison:undefined,error:'Snapshot source unavailable. Reconnect or choose another Run.'});}}
 async select(path:string,line=1){const source=this.source;if(!source||!this.current()||!source.paths.includes(path))return;const id=++this.epoch;this.publish({...this.state,status:'loading',path,text:'',comparison:undefined,error:undefined,line:Number.isInteger(line)&&line>0&&line<=100000?line:1});try{aiPath(path);const file=await source.files.read(path);if(id!==this.epoch||!this.current()||this.abort.signal.aborted)return;this.publish({...this.state,status:'ready',text:mask(file.content)});}catch{if(id===this.epoch&&this.current()&&!this.abort.signal.aborted)this.publish({...this.state,status:'error',text:'',comparison:undefined,error:'Snapshot source unavailable. Reconnect or choose another Run.'});}}
 async compare(read:(path:string)=>Promise<NonNullable<SourceReviewState['comparison']>>,unchanged:()=>boolean){if(this.state.status!=='ready'||!this.state.path||!this.current())return;const id=++this.epoch,path=this.state.path;this.publish({...this.state,comparison:undefined,error:undefined});try{const comparison=await read(path);if(id!==this.epoch||!this.current()||!unchanged()||this.abort.signal.aborted)return;this.publish({...this.state,comparison:{...comparison,content:mask(comparison.content)}});}catch{if(id===this.epoch&&this.current()&&!this.abort.signal.aborted)this.publish({...this.state,error:'Current file comparison unavailable. Snapshot source is unchanged.'});}}
}
