import type {TasteDevProjectDefinition} from '../protocol/domain.ts';
import {matchesAffected} from '../protocol/affected-files.ts';
import {sourceLanguage} from './language-context.ts';
import {aiPath,uuid,mask} from './security.ts';import {contentHash} from './fix-service.ts';
export interface ValidationRecommendation{kind:'task'|'test';name:string;reason:'standard-validation'|'affected-files'|'original-failure'|'global-change'|'unmapped-change'|'ai-protocol-reference'|'language-validation'}
export interface ValidationImpactPlan{id:string;projectId:string;proposalId:string;createdAt:string;definitionHash:string;changedFiles:string[];coverage:'explicit'|'fallback'|'global';unmappedFiles:string[];recommendations:ValidationRecommendation[];ignoredSuggestions:string[]}
const global=(path:string)=>/^\.tastedev\//.test(path)||/^(?:package\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb?|package-lock\.json|Cargo\.(?:toml|lock)|pyproject\.toml|requirements[^/]*\.txt|tsconfig[^/]*\.json|next\.config\.[cm]?[jt]s)$/.test(path);
export function validateImpactPlan(plan:ValidationImpactPlan,projectId:string,proposalId:string,paths:string[]){uuid(plan.id);if(plan.projectId!==projectId||plan.proposalId!==proposalId||!Number.isFinite(Date.parse(plan.createdAt))||!/^[a-f0-9]{64}$/.test(plan.definitionHash)||!['explicit','fallback','global'].includes(plan.coverage)||!Array.isArray(plan.changedFiles)||plan.changedFiles.length!==paths.length||new Set(plan.changedFiles).size!==paths.length||plan.changedFiles.some(p=>!paths.includes(p))||!Array.isArray(plan.unmappedFiles)||plan.unmappedFiles.some(p=>!paths.includes(p))||!Array.isArray(plan.recommendations)||plan.recommendations.length>140||plan.recommendations.some(r=>!['task','test'].includes(r.kind)||!/^[A-Za-z][A-Za-z0-9_-]{0,63}$/.test(r.name)||!['standard-validation','affected-files','original-failure','global-change','unmapped-change','ai-protocol-reference','language-validation'].includes(r.reason)||Object.keys(r).some(k=>!['kind','name','reason'].includes(k)))||new Set(plan.recommendations.map(r=>r.kind+':'+r.name)).size!==plan.recommendations.length||!Array.isArray(plan.ignoredSuggestions)||plan.ignoredSuggestions.length>30||plan.ignoredSuggestions.some(v=>typeof v!=='string'||v.length>200||/[\x00-\x1f]/.test(v))||Object.keys(plan).some(k=>!['id','projectId','proposalId','createdAt','definitionHash','changedFiles','coverage','unmappedFiles','recommendations','ignoredSuggestions'].includes(k)))throw Error('Invalid validation impact plan.');plan.changedFiles.forEach(aiPath);return plan;}
/** Recommendations grant no execution or source write permission. */
export async function validationImpact(definition:TasteDevProjectDefinition,projectId:string,proposalId:string,changedFiles:string[],suggestions:string[]=[],originalTest?:string):Promise<ValidationImpactPlan>{
 uuid(projectId);uuid(proposalId);if(!changedFiles.length||changedFiles.length>8||new Set(changedFiles).size!==changedFiles.length)throw Error('Invalid validation scope.');changedFiles.forEach(aiPath);
 const recommendations:ValidationRecommendation[]=[],ignoredSuggestions:string[]=[],add=(kind:ValidationRecommendation['kind'],name:string,reason:ValidationRecommendation['reason'])=>{if(!recommendations.some(r=>r.kind===kind&&r.name===name))recommendations.push({kind,name,reason});};
 const tests=Object.entries(definition.tests),globalChange=changedFiles.some(global),unmappedFiles=changedFiles.filter(path=>!tests.some(([,test])=>test.affectedFiles?.some(pattern=>matchesAffected(pattern,path))));
 for(const name of ['typecheck','lint','build'])if(Object.hasOwn(definition.tasks,name))add('task',name,'standard-validation');
 const languages=new Set<string>(changedFiles.map(sourceLanguage));
 for(const [language,names]of Object.entries({rust:['rust-check','rust-test'],python:['python-check','python-test'],typescript:['ts-check','ts-test'],javascript:['js-check','js-test']}))if(languages.has(language))for(const name of names)if(Object.hasOwn(definition.tasks,name))add('task',name,'language-validation');
 if(originalTest&&Object.hasOwn(definition.tests,originalTest))add('test',originalTest,'original-failure');
 const coverage=globalChange?'global':unmappedFiles.length?'fallback':'explicit';
 for(const [name,test]of tests)if(coverage!=='explicit'||test.affectedFiles?.some(pattern=>changedFiles.some(path=>matchesAffected(pattern,path))))add('test',name,coverage==='global'?'global-change':coverage==='fallback'?'unmapped-change':'affected-files');
 for(const text of suggestions.slice(0,30)){const value=mask(text).replace(/[\x00-\x1f]/g,' ').slice(0,200),reference=/^(task|test):([A-Za-z][A-Za-z0-9_-]{0,63})$/.exec(value);if(reference&&Object.hasOwn(reference[1]==='task'?definition.tasks:definition.tests,reference[2]))add(reference[1] as 'task'|'test',reference[2],'ai-protocol-reference');else if(Object.hasOwn(definition.tests,value))add('test',value,'ai-protocol-reference');else if(['typecheck','lint','build'].includes(value)&&Object.hasOwn(definition.tasks,value))add('task',value,'ai-protocol-reference');else ignoredSuggestions.push(value);}
 return{id:crypto.randomUUID(),projectId,proposalId,createdAt:new Date().toISOString(),definitionHash:await contentHash(JSON.stringify(definition)),changedFiles:[...changedFiles],coverage,unmappedFiles,recommendations,ignoredSuggestions};
}
