'use client';
import {useState} from 'react';
import {useCore} from './context';
import {ConnectionProfiles,type ConnectionProfile} from './connection-profiles';
import {useI18n} from '@/i18n/react';
const message=(error:unknown)=>error instanceof Error?error.message:'Core operation failed.';
interface AgentOverview {groups:string[];agents:{id:string;groups:string[];disabled:boolean;etag:string}[]}
function overview(value:unknown):AgentOverview{
 const row=value as AgentOverview;
 if(!row||!Array.isArray(row.groups)||row.groups.length>1000||row.groups.some(g=>typeof g!=='string')||!Array.isArray(row.agents)||row.agents.length>1000||row.agents.some(a=>!a||typeof a.id!=='string'||!Array.isArray(a.groups)||a.groups.some(g=>typeof g!=='string')||typeof a.disabled!=='boolean'||typeof a.etag!=='string'||!/^[a-f0-9]{64}$/.test(a.etag)))throw Error('Invalid Agent access response.');
 return row;
}
export function ConnectionManagement(){
 const {t}=useI18n(),{connection,connectionDraft:draft,setConnectionDraft,setConnectionToken,setMessage}=useCore();
 const [profiles,setProfiles]=useState<ConnectionProfile[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState(''),[name,setName]=useState('');
 const [agents,setAgents]=useState<AgentOverview|null>(null),[id,setId]=useState(''),[token,setToken]=useState(''),[group,setGroup]=useState(''),[pending,setPending]=useState(false);
 const store=()=>new ConnectionProfiles(window.localStorage);
 function load(){try{setProfiles(store().load());setLoaded(true);}catch(error){setMessage(message(error));}}
 function choose(value:string){setSelected(value);const profile=profiles.find(row=>row.id===value);setName(profile?.name??'');if(profile){connection.disconnect();setConnectionToken('');setAgents(null);setToken('');setConnectionDraft({endpoint:profile.endpoint,mode:profile.mode});}}
 async function agentAction(action:string,...args:unknown[]){setPending(true);try{const next=overview(await connection.teamRequest(action,...args));setAgents(next);setGroup(current=>next.groups.includes(current)?current:next.groups[0]??'');setMessage('');}catch(error){setMessage(message(error));}finally{setToken('');setPending(false);}}
 return <section className="core-readiness core-profiles" aria-label={t('Connection profiles')}><h2>{t('Connection profiles')}</h2>
 <p>{t('Profiles save addresses only. Tokens must be entered for each connection.')}</p>
 {!loaded?<button className="button" type="button" onClick={load}>{t('Load profiles')}</button>:<><label>{t('Saved profile')}<select value={selected} onChange={e=>choose(e.target.value)}><option value="">{t('New profile')}</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('Profile name')}<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><div className="core-actions"><button className="button" type="button" onClick={()=>{try{const profileId=selected||crypto.randomUUID();setProfiles(store().save({id:profileId,name,endpoint:draft.endpoint,mode:draft.mode}));setSelected(profileId);setMessage('Profile saved.');}catch(error){setMessage(message(error));}}}>{t('Save profile')}</button><button className="button" type="button" disabled={!selected} onClick={()=>{try{setProfiles(store().remove(selected));setSelected('');setName('');}catch(error){setMessage(message(error));}}}>{t('Delete profile')}</button></div></>}
 <details><summary>{t('Secure remote setup and recovery')}</summary><p>{t('Use wss:// for remote Core with a trusted TLS certificate. Only local loopback accepts ws://.')}</p><p>{t('Keep Core behind the TLS proxy and restrict origins. Obtain a scoped, expiring Studio session from the Owner. Tokens are never saved in profiles.')}</p><p>{t('Backup and restore are administrator operations. Stop Core, back up to a new directory, and restore only into a new directory. Keep the protected storage key with the backup.')}</p><code>pnpm core:storage backup &lt;new-directory&gt;</code><br/><code>pnpm core:storage restore &lt;backup-directory&gt; &lt;new-directory&gt;</code></details>
 {connection.connected&&connection.access?.mode==='team'&&connection.access.role==='Owner'&&<details><summary>{t('Agent access')}</summary><p>{t('Use the existing Agent ID from agent-id.json in its workspace. Grant an assigned project group and provide a dedicated Agent token. Only its hash is sent to Core.')}</p><button type="button" className="button" disabled={pending} onClick={()=>void agentAction('agents')}>{t('Refresh Agent access')}</button>{agents&&<><ul>{agents.agents.map(a=><li key={a.id}>{a.id} · {t(a.disabled?'Revoked':'Active')}<button type="button" className="button" disabled={pending||a.disabled} onClick={()=>{if(window.confirm(t('Revoke this Agent for all projects using it? Active cancellation is requested and the connection is closed.')))void agentAction('revoke-agent',a.id,a.etag);}}>{t('Revoke Agent')}</button></li>)}</ul><label>{t('Agent ID')}<input value={id} maxLength={128} onChange={e=>setId(e.target.value)}/></label><label>{t('Agent token')}<input type="password" autoComplete="off" value={token} maxLength={512} onChange={e=>setToken(e.target.value)}/></label><label>{t('Agent group')}<select value={group} onChange={e=>setGroup(e.target.value)}>{agents.groups.map(g=><option key={g}>{g}</option>)}</select></label><button type="button" className="button" disabled={pending||!group} onClick={async()=>{try{if(token.length<16||token.length>512||/[\r\n\0]/.test(token))throw Error('Enter a dedicated Agent token of 16–512 characters.');const boundary=connection.connectionKey;const tokenHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(n=>n.toString(16).padStart(2,'0')).join('');if(boundary!==connection.connectionKey||!connection.connected)throw Error('Core connection changed. Review Agent access again.');await agentAction('register-agent',{id:id.trim(),tokenHash,groups:[group]});}catch(error){setToken('');setMessage(message(error));}}}>{t('Grant Agent access')}</button></>}</details>}
 </section>;
}
