'use client';
import { useI18n } from '@/i18n/react';
/* eslint-disable @next/next/no-img-element -- Authenticated local blob previews cannot use an image proxy. */
import {useEffect,useState} from 'react';
import type {Artifact,BrowserResult} from './domain';
import {useCore} from './context';
export function EvidenceSummary({result,artifacts}:{result:BrowserResult;artifacts:Artifact[]}){
  const { t } = useI18n();

 return <div className="core-notice"><strong>{result.classification==='PASSED'?t("Browser test passed"):result.classification.replaceAll('_',' ')}</strong>{result.failures[0]&&<><p><strong>{result.failures[0].name}</strong></p><p>{result.failures[0].message}</p></>}<p>{result.passed}/{result.total} {t("passed · Screenshot")} {artifacts.filter(a=>a.type==='screenshot').length} {t("· Console errors")} {result.consoleErrors} {t("· Page errors")} {result.pageErrors} {t("· Network failures")} {result.networkFailures} {t("· Trace")} {artifacts.filter(a=>a.type==='trace').length}</p><p className="core-description">{t("Chromium")} {result.browserVersion} {t("· Playwright")} {result.playwrightVersion}</p>{result.evidenceWarnings.map((warning,i)=><p key={i} role="status">{t("Evidence warning:")} {warning}</p>)}</div>;
}
export function EvidenceViewer({runId}:{runId:string}){
  const { t, locale } = useI18n();const {snapshot}=useCore();const artifacts=snapshot.artifacts.filter(a=>a.runId===runId&&a.checksum);
 const [selected,setSelected]=useState<string|null>(null);const chosen=artifacts.find(a=>a.id===selected);
 return <section aria-label={t("Browser evidence")}><h2>{t("Evidence")}</h2>{!artifacts.length?<p className="core-description">{t("No evidence available. Artifacts appear after verified transfer; an interrupted run may have partial evidence.")}</p>:<><p className="core-description">{t("Select an artifact to preview or export. Files are loaded on demand.")}</p><div className="core-table-scroll"><table><thead><tr><th>{t("Evidence")}</th><th>{t("Size")}</th><th>{t("Captured")}</th><th>{t("Step")}</th></tr></thead><tbody>{artifacts.map(a=><tr key={a.id}><td><button className="ws-text-button" aria-pressed={a.id===selected} onClick={()=>setSelected(a.id)}>{a.type}</button></td><td>{(a.size/1024).toFixed(1)} {t("KiB")}</td><td>{new Date(a.createdAt).toLocaleTimeString(locale)}</td><td>{snapshot.steps.find(s=>s.id===a.runStepId)?.name??a.runStepId}</td></tr>)}</tbody></table></div>{chosen&&<ArtifactPreview key={chosen.id} artifact={chosen}/>}</>}</section>;
}
function ArtifactPreview({artifact}:{artifact:Artifact}){
  const { t } = useI18n();

 const {connection,project}=useCore();const [value,setValue]=useState<{url:string;text:string}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[level,setLevel]=useState('all');
 const {location,size,checksum}=artifact;
 useEffect(()=>{const abort=new AbortController();let url='';connection.artifact({location,size,checksum},project.id,abort.signal).then(async blob=>{const text=blob.type==='application/json'?await blob.text():'';if(abort.signal.aborted)return;url=URL.createObjectURL(blob);setValue({url,text});}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Artifact unavailable.');});return()=>{abort.abort();if(url)URL.revokeObjectURL(url);};},[location,size,checksum,connection,project.id,retry]);
 let entries:Record<string,unknown>[]=[];if(value?.text){try{const parsed=JSON.parse(value.text);entries=Array.isArray(parsed)?parsed:[];}catch{}}
 return <div className="evidence-preview"><h3>{artifact.type}</h3><p className="core-description" style={{overflowWrap:'anywhere'}}>{artifact.name} · {(artifact.size/1024).toFixed(1)} {t("KiB")}</p>{error?<p role="alert">{error} <button className="ws-text-button" onClick={()=>{setError('');setRetry(r=>r+1);}}>{t("Retry load")}</button></p>:!value?<p role="status">{t("Loading verified artifact…")}</p>:<><div className="core-actions"><a className="ws-text-button" href={value.url} download={artifact.name}>{t("Export")} {artifact.type}</a>{artifact.type==='browser-console'&&<label>{t("Level")} <select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">{t("All")}</option><option value="error">{t("Error")}</option><option value="warning">{t("Warning")}</option></select></label>}</div>{artifact.type==='screenshot'&&<a href={value.url} target="_blank" rel="noreferrer" aria-label={t("Open full screenshot")}>{/* Blob is authenticated, verified, bounded PNG; Next Image cannot proxy it. */}<img src={value.url} alt="Browser test failure screenshot" style={{display:'block',maxWidth:'100%',maxHeight:440,objectFit:'contain',marginTop:12}}/></a>}{artifact.type==='trace'&&<p className="core-description">{t("Export the trace, then open it locally with Playwright show-trace. Source files and response bodies are excluded; visual content may contain sensitive information.")}</p>}{value.text&&(artifact.type==='network-log'?<div className="core-table-scroll"><table><thead><tr><th>{t("Method")}</th><th>{t("URL")}</th><th>{t("Status")}</th><th>{t("Failure")}</th></tr></thead><tbody>{entries.slice(0,200).map((e,i)=><tr key={i}><td>{String(e.method??'')}</td><td style={{overflowWrap:'anywhere'}}>{String(e.url??'')}</td><td>{String(e.status??'')}</td><td>{String(e.failure??'')}</td></tr>)}</tbody></table>{!entries.length&&<p>{t("No network failures recorded.")}</p>}</div>:<pre className="core-live-log" tabIndex={0} aria-label={t("Evidence content")}>{entries.length?entries.filter(e=>level==='all'||e.level===level).slice(0,200).map(e=>JSON.stringify(e,null,2)).join('\n'):value.text.slice(0,65536)}</pre>)}</>}</div>;
}
