'use client';
import {useState,useRef,useEffect} from 'react';import {useCore} from './context';import {useI18n} from '@/i18n/react';import {useAI} from '../ai/views';import {useWorkspace} from '../workspace/context';
import {RunComparison} from './run-comparison-view';import {HistoryRequestGuard,historyPage,type HistoryRow as Row,type HistoryPage as Page} from './history-navigation';
interface Retention {days:number;retainedBytes:number;candidateCount:number;candidateBytes:number;deletedCount:number;candidates:{id:string;runId:string;name:string;size:number;checksum:string}[]}
export function HistoryBrowser(){
 const {t}=useI18n(),{connection,project,select,setMessage}=useCore(),ai=useAI(),{dispatch}=useWorkspace();
 const [kind,setKind]=useState<'run'|'analysis'|'attempt'>('run'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState<Page|null>(null),[pending,setPending]=useState(false),[retention,setRetention]=useState<Retention|null>(null),[days,setDays]=useState(30),[logGap,setLogGap]=useState(false),[cursor,setCursor]=useState<string|undefined>(),[previous,setPrevious]=useState<(string|undefined)[]>([]);
 const guard=useRef(new HistoryRequestGuard()),busy=useRef(false),mounted=useRef(true),operationEpoch=useRef(0);
 useEffect(()=>{const requestGuard=guard.current;mounted.current=true;return()=>{mounted.current=false;requestGuard.cancel();};},[]);
 const boundary=()=>connection.connectionKey+':'+connection.generation+':'+JSON.stringify(connection.access);
 function clearPage(){guard.current.cancel();setPage(null);setPrevious([]);setCursor(undefined);}
 async function perform(action:(current:()=>boolean)=>Promise<void>){if(busy.current)return;busy.current=true;setPending(true);const operation=++operationEpoch.current,scope=boundary(),current=()=>operation===operationEpoch.current&&mounted.current&&connection.connected&&scope===boundary();try{await action(current);if(current())setMessage('');}catch(error){if(current())setMessage(error instanceof Error?error.message:'History operation failed.');}finally{if(operation===operationEpoch.current){busy.current=false;if(mounted.current)setPending(false);}}}
 function cancelLoad(){guard.current.cancel();operationEpoch.current++;busy.current=false;setPending(false);setMessage('History display request cancelled. Server work is unchanged.');}
 async function load(after?:string,direction:'first'|'next'|'previous'='first'){await perform(async current=>{const query={limit:25,search,status,...(from?{from:new Date(from).toISOString()}:{}),...(to?{to:new Date(to+'T23:59:59.999Z').toISOString()}:{}),...(after?{after}:{})};const ticket=guard.current.begin(boundary(),kind,query),value=kind==='run'?await connection.recordsRequest('page',query):await connection.historyRequest({action:'page',kind,query},project.id);if(!current()||!guard.current.current(ticket,boundary()))return;setPage(historyPage(value));setCursor(after);setPrevious(rows=>direction==='next'?[...rows,cursor]:direction==='previous'?rows.slice(0,-1):[]);});}
 async function openRow(row:Row){await perform(async current=>{if(kind==='run'){await connection.loadRun(row.id);const gap=await connection.resumeLogs(row.id);if(!current())return;setLogGap(gap);select({kind:'run',id:row.id});return;}if(!ai.historyReady)throw Error('Wait for Core history recovery before starting AI analysis.');const attempt=kind==='attempt'?ai.fixes.history.find(a=>a.id===row.id):undefined,record=ai.service.history.find(r=>r.id===(attempt?.analysisId??row.id));if(!record||record.projectId!==project.id||kind==='attempt'&&!attempt)throw Error('Review data unavailable. Reconnect and retry.');if(!current())return;ai.selectRecord(record);if(attempt){const index=record.result.proposal.findIndex(p=>p.path===attempt.patches[0]?.path);if(index<0)throw Error('Review data unavailable. Reconnect and retry.');ai.setProposal({record,index});ai.setReview({left:attempt.id,right:''});}dispatch({type:'activity',value:'ai'});});}
 async function exportRow(row:Row){await perform(async current=>{const value=kind==='run'?await connection.recordsRequest('detail',row.id):await connection.historyRequest({action:'get',kind,id:row.id},project.id);if(!current())return;const blob=new Blob([JSON.stringify({schema:1,projectId:project.id,kind,id:row.id,exportedAt:new Date().toISOString(),value},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='tastestudio-'+kind+'-'+row.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 async function policy(save=false){await perform(async current=>{const value=await connection.recordsRequest<Retention>(save?'policy-save':'retention-preview',save?days:undefined);if(current()){setRetention(value);setDays(value.days);}});}
 return <section className="core-detail" aria-label={t('History browser')} aria-busy={pending}><h2>{t('History browser')}</h2><p className="core-description">{t('History metadata is paged. Source patches require separate approvals.')}</p>
 <form className="core-form" onSubmit={e=>{e.preventDefault();void load();}}><label>{t('History type')}<select disabled={pending} value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setStatus('');clearPage();}}><option value="run">{t('Run history')}</option><option value="analysis">{t('Analysis history')}</option><option value="attempt">{t('Attempt History')}</option></select></label>
 <label>{t('Search')}<input disabled={pending} value={search} maxLength={120} onChange={e=>{setSearch(e.target.value);clearPage();}}/></label><label>{t('Status')}<input disabled={pending} value={status} maxLength={40} onChange={e=>{setStatus(e.target.value);clearPage();}}/></label>
 <div className="core-form-row"><label>{t('From')}<input disabled={pending} type="date" value={from} onChange={e=>{setFrom(e.target.value);clearPage();}}/></label><label>{t('To')}<input disabled={pending} type="date" value={to} onChange={e=>{setTo(e.target.value);clearPage();}}/></label></div>
 <button type="submit" className="button" disabled={pending}>{t('Load history')}</button></form>{pending&&<p role="status">{t('Loading…')} <button className="button" onClick={cancelLoad}>{t('Cancel')}</button></p>}
 {page&&<><p role="status">{page.total} {t('records')} · {page.items.length} {t('shown')}</p>{!page.items.length&&<p>{t('No history matches these filters. Change filters and load again.')}</p>}
 <ul className="core-match-list">{page.items.map(row=><li key={row.id}><button className="ws-text-button" disabled={pending||kind!=='run'&&!ai.historyReady} onClick={()=>void openRow(row)}>{row.name} · {t(row.status)} · {row.id.slice(0,8)}</button><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleString()}</time><button type="button" className="button" disabled={pending} onClick={()=>void exportRow(row)}>{t('Export manifest')}</button></li>)}</ul>
 <div className="core-actions"><button type="button" className="button" disabled={pending} onClick={()=>void load()}>{t('First page')}</button><button type="button" className="button" disabled={pending||!previous.length} onClick={()=>void load(previous.at(-1),'previous')}>{t('Previous page')}</button><button type="button" className="button" disabled={pending||!page.next} onClick={()=>void load(page.next!,'next')}>{t('Next page')}</button></div></>}
 {kind==='run'&&page&&<RunComparison key={project.id+JSON.stringify(page.items.map(r=>r.id))} rows={page.items}/>}
 {logGap&&<p role="status">{t('Some log chunks were evicted. Full output cannot be reconstructed.')}</p>}<details><summary>{t('Evidence retention')}</summary><p>{t('Deletion requires review. Metadata remains; active Run evidence is protected.')}</p><label>{t('Retention days')} <input type="number" min={1} max={3650} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><button type="button" className="button" disabled={pending} onClick={()=>void policy(true)}>{t('Save retention policy')}</button><button type="button" className="button" disabled={pending} onClick={()=>void policy()}>{t('Review retention')}</button>{retention&&<><p>{t('Retained bytes')}: {retention.retainedBytes} · {t('Deletion candidates')}: {retention.candidateCount} / {retention.candidateBytes} {t('bytes')} · {t('Deleted')}: {retention.deletedCount}</p><ul className="core-match-list">{retention.candidates.map(a=><li key={a.id}>{a.name} · {a.size} {t('bytes')}<button className="button" disabled={pending} onClick={()=>{if(window.confirm(t('Confirm evidence deletion? Run/history identity and checksum are retained.')))void perform(async current=>{const detail=await connection.loadRun(a.runId),artifact=detail.artifacts.find(row=>row.id===a.id);if(!current())return;if(!artifact||artifact.checksum!==a.checksum)throw Error('Evidence changed since retention preview.');await connection.deleteArtifact(artifact,project.id);const next=await connection.recordsRequest<Retention>('retention-preview');if(current())setRetention(next);});}}>{t('Delete evidence body')}</button></li>)}</ul></>}</details></section>;
}
