'use client';
import {useState} from 'react';import {useCore} from './context';import {useI18n} from '@/i18n/react';
interface Row {id:string;createdAt:string;name:string;status:string;version?:number}
interface Page {items:Row[];total:number;next:string|null}
interface Retention {days:number;retainedBytes:number;candidateCount:number;candidateBytes:number;deletedCount:number;candidates:{id:string;runId:string;name:string;size:number;checksum:string}[]}
export function HistoryBrowser(){
 const {t}=useI18n(),{connection,project,select,setMessage}=useCore();const [kind,setKind]=useState<'run'|'analysis'|'attempt'>('run'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState<Page|null>(null),[pending,setPending]=useState(false),[retention,setRetention]=useState<Retention|null>(null),[days,setDays]=useState(30),[logGap,setLogGap]=useState(false);
 async function perform(action:()=>Promise<void>){setPending(true);try{await action();setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'History operation failed.');}finally{setPending(false);}}
 async function load(after?:string){await perform(async()=>{const query={limit:25,search,status,...(from?{from:new Date(from).toISOString()}:{}),...(to?{to:new Date(to+'T23:59:59.999Z').toISOString()}:{}),...(after?{after}:{})};const value=kind==='run'?await connection.recordsRequest<Page>('page',query):await connection.historyRequest<Page>({action:'page',kind,query},project.id);if(!value||!Array.isArray(value.items)||value.items.length>100||!Number.isSafeInteger(value.total)||value.items.some(r=>typeof r.id!=='string'||typeof r.name!=='string'||typeof r.createdAt!=='string'))throw Error('Invalid history page.');setPage(value);});}
 async function exportRow(row:Row){await perform(async()=>{const value=kind==='run'?await connection.recordsRequest('detail',row.id):await connection.historyRequest({action:'get',kind,id:row.id},project.id);const blob=new Blob([JSON.stringify({schema:1,projectId:project.id,kind,id:row.id,exportedAt:new Date().toISOString(),value},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tastestudio-${kind}-${row.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 async function policy(save=false){await perform(async()=>{const value=await connection.recordsRequest<Retention>(save?'policy-save':'retention-preview',save?days:undefined);setRetention(value);setDays(value.days);});}
 return <section className="core-detail" aria-label={t('History browser')}><h2>{t('History browser')}</h2><p className="core-description">{t('History metadata is paged. Source patches require separate approvals.')}</p><div className="core-form"><label>{t('History type')}<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setPage(null);setStatus('');}}><option value="run">{t('Run history')}</option><option value="analysis">{t('Analysis history')}</option><option value="attempt">{t('Attempt History')}</option></select></label><label>{t('Search')}<input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)}/></label><label>{t('Status')}<input value={status} maxLength={40} onChange={e=>setStatus(e.target.value)}/></label><div className="core-form-row"><label>{t('From')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('To')}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></div><button type="button" className="button" disabled={pending} onClick={()=>void load()}>{t('Load history')}</button>{page&&<><p>{page.total} {t('records')} · {page.items.length} {t('shown')}</p><ul className="core-match-list">{page.items.map(row=><li key={row.id}><button className="ws-text-button" disabled={pending||kind!=='run'} onClick={()=>void perform(async()=>{await connection.loadRun(row.id);setLogGap(await connection.resumeLogs(row.id));select({kind:'run',id:row.id});})}>{row.name} · {row.status} · {row.id.slice(0,8)}</button><span>{new Date(row.createdAt).toLocaleString()}</span><button type="button" className="button" disabled={pending} onClick={()=>void exportRow(row)}>{t('Export manifest')}</button></li>)}</ul><div className="core-actions"><button type="button" className="button" disabled={pending} onClick={()=>void load()}>{t('First page')}</button><button type="button" className="button" disabled={pending||!page.next} onClick={()=>void load(page.next!)}>{t('Next page')}</button></div></>}
 {logGap&&<p role="status">{t('Some log chunks were evicted. Full output cannot be reconstructed.')}</p>}<details><summary>{t('Evidence retention')}</summary><p>{t('Deletion requires review. Metadata remains; active Run evidence is protected.')}</p><label>{t('Retention days')} <input type="number" min={1} max={3650} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><button type="button" className="button" disabled={pending} onClick={()=>void policy(true)}>{t('Save retention policy')}</button><button type="button" className="button" disabled={pending} onClick={()=>void policy()}>{t('Review retention')}</button>{retention&&<><p>{t('Retained bytes')}: {retention.retainedBytes} · {t('Deletion candidates')}: {retention.candidateCount} / {retention.candidateBytes} {t('bytes')} · {t('Deleted')}: {retention.deletedCount}</p><ul className="core-match-list">{retention.candidates.map(a=><li key={a.id}>{a.name} · {a.size} {t('bytes')}<button className="button" disabled={pending} onClick={()=>{if(window.confirm(t('Confirm evidence deletion? Run/history identity and checksum are retained.')))void perform(async()=>{const detail=await connection.loadRun(a.runId),artifact=detail.artifacts.find(row=>row.id===a.id);if(!artifact||artifact.checksum!==a.checksum)throw Error('Evidence changed since retention preview.');await connection.deleteArtifact(artifact,project.id);setRetention(await connection.recordsRequest<Retention>('retention-preview'));});}}>{t('Delete evidence body')}</button></li>)}</ul></>}</details></section>;
}
