'use client';
import {useState} from 'react';import {useCore} from './context';import {useI18n} from '@/i18n/react';import {compareRuns} from './run-comparison';import type {CoreSnapshot} from './domain';
export function RunComparison({rows}:{rows:{id:string;name:string}[]}){
 const {t}=useI18n(),{connection,project,select,setMessage}=useCore();const [left,setLeft]=useState(''),[right,setRight]=useState(''),[busy,setBusy]=useState(false),[value,setValue]=useState<ReturnType<typeof compareRuns>|null>(null);
 async function compare(){if(busy)return;setBusy(true);setValue(null);try{const a=await connection.recordsRequest<CoreSnapshot>('detail',left),b=await connection.recordsRequest<CoreSnapshot>('detail',right);setValue(compareRuns(project.id,a,b,left,right));}catch{setMessage(t('Review data unavailable. Reconnect and retry.'));}finally{setBusy(false);}}
 return <details><summary>{t('Compare Runs')}</summary><p>{t('Candidates require matching source, saved test definition and reported Agent environment. They are not confirmed defects.')}</p><div className="core-form-row">{([['left',left],['right',right]] as const).map(([side,id])=><label key={side}>{t(side==='left'?'Earlier attempt':'Later attempt')}<select value={id} disabled={busy} onChange={e=>{(side==='left'?setLeft:setRight)(e.target.value);setValue(null);}}><option value="">{t('Run')}</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(0,8)}</option>)}</select></label>)}</div><button className="button" disabled={busy||!left||!right||left===right} onClick={()=>void compare()}>{t('Compare Runs')}</button>
 {value&&<><dl className="core-fields">{([[t('Source identity'),value.sameSource],[t('Test definition'),value.samePlan],[t('Reported environment'),value.sameEnvironment],[t('Comparable'),value.comparable]] as const).map(([label,same])=><div key={label}><dt>{label}</dt><dd>{t(same?'Match':'Different / unknown')}</dd></div>)}<div><dt>{t('Duration')}</dt><dd>{value.durationA??'—'} ms → {value.durationB??'—'} ms</dd></div></dl><p>{t(value.environmentObservation)}</p><ul>{value.differences.map(reason=><li key={reason}>{t(reason)}</li>)}</ul><p>{t('Source')}: {JSON.stringify(value.leftSource)} → {JSON.stringify(value.rightSource)}</p>{value.slower&&<p role="status">{t('Slowdown candidate')}</p>}{value.flakyCandidate&&<p role="status">{t('Flaky candidate')}</p>}<h3>{t('Steps')}</h3><ul>{value.steps.map(s=><li key={s.order}>{s.name} · {s.leftStatus} → {s.rightStatus??'—'} · {s.leftMs??'—'} ms → {s.rightMs??'—'} ms</li>)}</ul><h3>{t('Evidence')}</h3><ul>{value.evidence.map(e=><li key={e.type+e.name}>{e.name} · {e.type} · {t(e.equal?'Match':'Different / unknown')} · {e.left.map(x=>x.available?x.checksum??'—':t('Deleted')).join(', ')} → {e.right.map(x=>x.available?x.checksum??'—':t('Deleted')).join(', ')}</li>)}</ul><div className="core-actions">{[value.leftId,value.rightId].map(id=><button className="button" key={id} disabled={busy} onClick={()=>{setBusy(true);void connection.loadRun(id).then(()=>select({kind:'run',id})).catch(()=>setMessage(t('Review data unavailable. Reconnect and retry.'))).finally(()=>setBusy(false));}}>{t('Review test result')} {id.slice(0,8)}</button>)}</div></>}
 </details>;
}
