import type { Project } from '../projects/types/project.ts';
import { CoreError, activeRun, transition, jobTransitions, runTransitions, stepTransitions, type Agent, type AgentStatus, type Artifact, type CoreEvent, type Job, type JobPayload, type JobRequirement, type Run, type RunStatus, type StepStatus } from './domain.ts';
import type { CoreRepositories, CoreRepository } from './repository.ts';
import { defaultStrategy, matchAgent, text, validateAgent, validateCapabilities, validatePayload, validateRequirements, type SchedulingStrategy } from './matcher.ts';
export interface CoreOptions { now?: () => string; id?: () => string; strategy?: SchedulingStrategy;allowAgent?:(projectId:string,agentId:string)=>boolean;agentSessionValid?:(agentId:string)=>boolean;admitJob?:(projectId:string,actor:string|undefined,jobs:Job[])=>void;allowAssignment?:(job:Job,runs:Run[],jobs:Job[])=>boolean }
export interface ProjectRegistry { get(id: string): Promise<Project | null> }
export interface CreateJob { name: string; requirements: JobRequirement; payload: JobPayload; priority?: number; maxAttempts?: number; idempotencyKey?:string }
function required<T>(value: T | undefined, label: string): T { if (!value) throw new CoreError(`${label} not found.`); return value; }
export class CoreService {
  readonly repository: CoreRepository; private projects: ProjectRegistry; private options: CoreOptions;
  constructor(repository: CoreRepository, projects: ProjectRegistry, options: CoreOptions = {}) { this.repository=repository; this.projects=projects; this.options=options; }
  private now() { return this.options.now?.() ?? new Date().toISOString(); }
  private id() { return this.options.id?.() ?? crypto.randomUUID(); }
  private event(tx: CoreRepositories, type: CoreEvent['type'], entityId: string, projectId: string | null = null) { tx.events.save({id:this.id(),type,entityId,projectId,timestamp:this.now()}); }
  private job(tx: CoreRepositories, projectId: string, id: string) { const job=required(tx.jobs.get(id),'Job'); if(job.projectId!==projectId) throw new CoreError('Job belongs to another project.'); return job; }
  private run(tx: CoreRepositories, projectId: string, id: string) { const run=required(tx.runs.get(id),'Run'); if(run.projectId!==projectId) throw new CoreError('Run belongs to another project.'); return run; }
  snapshot(projectId: string) { const s=this.repository.read(); const runs=s.runs.filter(r=>r.projectId===projectId); const ids=new Set(runs.map(r=>r.id));const agents=s.agents.filter(a=>this.options.allowAgent?.(projectId,a.id)??true),agentIds=new Set(agents.map(a=>a.id)); return {...s,agents,jobs:s.jobs.filter(j=>j.projectId===projectId),runs,steps:s.steps.filter(s=>ids.has(s.runId)),artifacts:s.artifacts.filter(a=>ids.has(a.runId)),events:s.events.filter(e=>e.projectId===projectId||!e.projectId&&(!this.options.allowAgent||agentIds.has(e.entityId)))}; }
  registerAgent(input: Pick<Agent,'name'|'platform'|'architecture'|'capabilities'>) { const valid=validateAgent(input); return this.repository.transaction(tx=>{ if(tx.agents.list().some(a=>a.name.toLowerCase()===valid.name.toLowerCase())) throw new CoreError('Agent name is already registered.'); const now=this.now(); const agent:Agent={...valid,id:this.id(),status:'offline',lastSeenAt:null,createdAt:now,updatedAt:now};tx.agents.save(agent);this.event(tx,'agent.registered',agent.id);return agent; }); }
  getAgent(id:string) { return this.repository.read().agents.find(a=>a.id===id); }
  /** Called only by an authenticated transport adapter. Identity is supplied by the agent. */
  connectAgent(id:string,input:Pick<Agent,'name'|'platform'|'architecture'|'capabilities'>) {
    text(id,'Agent ID',100);const valid=validateAgent(input);
    return this.repository.transaction(tx=>{const old=tx.agents.get(id);const now=this.now();const agent:Agent={...valid,id,status:tx.runs.list().some(r=>r.agentId===id&&activeRun(r))?'busy':'idle',lastSeenAt:now,createdAt:old?.createdAt??now,updatedAt:now};tx.agents.save(agent);this.event(tx,old?'agent.updated':'agent.registered',id);return agent;});
  }
  observeAgent(id:string,connected:boolean) { return this.repository.transaction(tx=>{const agent=required(tx.agents.get(id),'Agent');agent.status=connected?(tx.runs.list().some(r=>r.agentId===id&&activeRun(r))?'busy':'idle'):'offline';if(connected)agent.lastSeenAt=this.now();agent.updatedAt=this.now();return agent;}); }
  listAgents() { return this.repository.read().agents; }
  updateAgent(id:string,input:Pick<Agent,'name'|'platform'|'architecture'|'capabilities'>) { const valid=validateAgent(input);return this.repository.transaction(tx=>{const agent=required(tx.agents.get(id),'Agent');if(tx.runs.list().some(r=>r.agentId===id&&activeRun(r)))throw new CoreError('Cannot edit a reserved agent.');if(tx.agents.list().some(a=>a.id!==id&&a.name.toLowerCase()===valid.name.toLowerCase()))throw new CoreError('Agent name is already registered.');const updated={...agent,...valid,updatedAt:this.now()};tx.agents.save(updated);this.event(tx,'agent.updated',id);return updated;}); }
  updateCapabilities(id:string,capabilities:Agent['capabilities']) { return this.updateAgent(id,{...required(this.getAgent(id),'Agent'),capabilities:validateCapabilities(capabilities)}); }
  updateAgentStatus(id:string,status:AgentStatus) { if(!['offline','online','idle','busy','error'].includes(status))throw new CoreError('Invalid agent status.');return this.repository.transaction(tx=>{const a=required(tx.agents.get(id),'Agent');if(tx.runs.list().some(r=>r.agentId===id&&activeRun(r)))throw new CoreError('Agent is reserved by a pending or running job.');const updated={...a,status,lastSeenAt:['online','idle','busy'].includes(status)?this.now():a.lastSeenAt,updatedAt:this.now()};tx.agents.save(updated);this.event(tx,'agent.status.changed',id);return updated;}); }
  removeAgent(id:string) { this.repository.transaction(tx=>{required(tx.agents.get(id),'Agent');if(tx.runs.list().some(r=>r.agentId===id&&activeRun(r)))throw new CoreError('Cannot remove a reserved agent.');tx.agents.remove(id);this.event(tx,'agent.removed',id);}); }
  async createJob(projectId:string,input:CreateJob,actor?:string) { if(!await this.projects.get(projectId))throw new CoreError('Project not found.');const name=text(input.name,'Job name'),requirements=validateRequirements(input.requirements),payload=validatePayload(input.payload),priority=input.priority??0,maxAttempts=input.maxAttempts??3;if(!Number.isInteger(priority)||priority<0||priority>100||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>10)throw new CoreError('Priority must be 0–100 and attempts 1–10.');if(payload.testPlan && (payload.testPlan.projectId!==projectId || JSON.stringify(validateRequirements(payload.testPlan.requirements))!==JSON.stringify(requirements)))throw new CoreError('TestPlan project or requirements mismatch.');if(input.idempotencyKey!==undefined)text(input.idempotencyKey,'Job idempotency key',120);return this.repository.transaction(tx=>{if(input.idempotencyKey){const existing=tx.jobs.list().find(j=>j.projectId===projectId&&j.idempotencyKey===input.idempotencyKey);if(existing){if(JSON.stringify(existing.payload)!==JSON.stringify(payload)||JSON.stringify(existing.requirements)!==JSON.stringify(requirements))throw new CoreError('Job identity conflicts with a different payload.');return existing;}}this.options.admitJob?.(projectId,actor,tx.jobs.list());const now=this.now();const job:Job={id:this.id(),projectId,...(actor?{createdBy:actor}:{}),...(input.idempotencyKey?{idempotencyKey:input.idempotencyKey}:{}),type:'task',name,status:'queued',requirements,payload,priority,maxAttempts,attempt:1,sourceJobId:null,agentId:null,queuedAt:now,createdAt:now,updatedAt:now,cancellationRequestedAt:null};tx.jobs.save(job);this.event(tx,'job.created',job.id,projectId);this.event(tx,'job.queued',job.id,projectId);return job;}); }
  enqueue(projectId:string,jobId:string) { return this.repository.transaction(tx=>{const job=this.job(tx,projectId,jobId);if(job.status!=='queued')throw new CoreError('Only queued jobs can be enqueued.');return job;}); }
  queue(projectId?:string) { return (this.options.strategy??defaultStrategy).jobs(this.repository.read().jobs.filter(j=>j.status==='queued'&&(!projectId||j.projectId===projectId))); }
  dequeueCandidate(projectId?:string) { return this.queue(projectId)[0]??null; }
  matches(projectId:string,jobId:string) { const job=required(this.snapshot(projectId).jobs.find(j=>j.id===jobId),'Job');return this.listAgents().map(a=>matchAgent(a,job.requirements)); }
  dispatch(projectId?:string,jobId?:string) { return this.repository.transaction(tx=>{
    const policy=this.options.strategy??defaultStrategy;
    for(const job of policy.jobs(tx.jobs.list().filter(j=>j.status==='queued'&&(!projectId||j.projectId===projectId)&&(!jobId||j.id===jobId)))) {
      if(this.options.allowAssignment&&!this.options.allowAssignment(job,tx.runs.list(),tx.jobs.list()))continue;
      const agent=policy.agents(tx.agents.list()).find(a=>(this.options.allowAgent?.(job.projectId,a.id)??true)&&(this.options.agentSessionValid?.(a.id)??true)&&matchAgent(a,job.requirements).matches&&!tx.runs.list().some(r=>r.agentId===a.id&&activeRun(r)));
      if(!agent)continue;
      transition(job.status,'assigned',jobTransitions);job.status='assigned';job.agentId=agent.id;job.updatedAt=this.now();agent.status='busy';agent.updatedAt=this.now();
      const run:Run={id:this.id(),jobId:job.id,projectId:job.projectId,agentId:agent.id,status:'pending',startedAt:null,finishedAt:null,exitCode:null,createdAt:this.now(),result:null};tx.runs.save(run);
      job.payload.steps.forEach((step,order)=>tx.steps.save({id:this.id(),runId:run.id,name:step.name,order,status:'pending',startedAt:null,finishedAt:null,exitCode:null}));
      this.event(tx,'job.assigned',job.id,job.projectId);this.event(tx,'agent.status.changed',agent.id);this.event(tx,'run.created',run.id,job.projectId);return {job,run,agent};
    }
    return null;
  }); }
  cancelJob(projectId:string,id:string) { return this.repository.transaction(tx=>{const job=this.job(tx,projectId,id);if(job.status==='queued'){transition(job.status,'cancelled',jobTransitions);job.status='cancelled';job.updatedAt=this.now();this.event(tx,'job.cancelled',id,projectId);}else if(job.status==='assigned'||job.status==='running'){if(!job.cancellationRequestedAt){job.cancellationRequestedAt=this.now();job.updatedAt=this.now();this.event(tx,'job.cancellation.requested',id,projectId);}}else throw new CoreError('This job is already finished.');return job;}); }
  retryJob(projectId:string,id:string) { return this.repository.transaction(tx=>{const old=this.job(tx,projectId,id);if(old.status!=='failed'||old.attempt>=old.maxAttempts)throw new CoreError('Only failed jobs with attempts remaining can be retried.');const sourceJobId=old.sourceJobId??old.id;if(tx.jobs.list().some(j=>j.sourceJobId===sourceJobId&&j.attempt===old.attempt+1))throw new CoreError('A retry already exists for this attempt.');this.options.admitJob?.(projectId,old.createdBy,tx.jobs.list());const now=this.now();const job:Job={...old,id:this.id(),idempotencyKey:undefined,sourceJobId,attempt:old.attempt+1,status:'queued',agentId:null,cancellationRequestedAt:null,createdAt:now,updatedAt:now,queuedAt:now};tx.jobs.save(job);this.event(tx,'job.created',job.id,projectId);this.event(tx,'job.queued',job.id,projectId);return job;}); }
  startRun(projectId:string,id:string) { return this.repository.transaction(tx=>{const run=this.run(tx,projectId,id),job=this.job(tx,projectId,run.jobId);if(job.cancellationRequestedAt)throw new CoreError('Cancellation is awaiting acknowledgement.');transition(run.status,'running',runTransitions);transition(job.status,'running',jobTransitions);run.status='running';run.startedAt=this.now();job.status='running';job.updatedAt=this.now();this.event(tx,'run.started',id,projectId);return run;}); }
  changeStep(projectId:string,runId:string,stepId:string,status:StepStatus,exitCode:number|null=null) { return this.repository.transaction(tx=>{const run=this.run(tx,projectId,runId);if(run.status!=='running')throw new CoreError('Run is not running.');const step=required(tx.steps.get(stepId),'Step');if(step.runId!==runId)throw new CoreError('Step belongs to another run.');transition(step.status,status,stepTransitions);if((status==='running'||status==='skipped')&&tx.steps.list().some(s=>s.runId===runId&&s.order<step.order&&!['passed','skipped'].includes(s.status)))throw new CoreError('Complete earlier steps first.');if(exitCode!==null&&!Number.isInteger(exitCode))throw new CoreError('Invalid exit code.');if(status==='passed'&&exitCode!==0)throw new CoreError('A passed step requires exit code 0.');if(status==='failed'&&(exitCode===null||exitCode===0))throw new CoreError('A failed step requires a nonzero exit code.');step.status=status;if(status==='running')step.startedAt=this.now();else{step.finishedAt=this.now();step.exitCode=exitCode;}this.event(tx,'run.step.changed',stepId,projectId);if(status==='failed')this.finish(tx,run,'failed',exitCode,'A run step failed.');return step;}); }
  private finish(tx:CoreRepositories,run:Run,status:Extract<RunStatus,'passed'|'failed'|'cancelled'|'timeout'>,exitCode:number|null,summary:string) {
    transition(run.status,status,runTransitions);if(exitCode!==null&&!Number.isInteger(exitCode))throw new CoreError('Invalid exit code.');const steps=tx.steps.list().filter(s=>s.runId===run.id);
    if(status==='passed'&&(exitCode!==0||steps.some(s=>!['passed','skipped'].includes(s.status))))throw new CoreError('Passing requires successful steps and exit code 0.');
    if(status==='failed'&&exitCode===0)throw new CoreError('Failed runs cannot have exit code 0.');
    const job=this.job(tx,run.projectId,run.jobId);const next=status==='passed'?'succeeded':status==='cancelled'?'cancelled':'failed';transition(job.status,next,jobTransitions);
    run.status=status;run.finishedAt=this.now();run.exitCode=exitCode;run.result={summary:text(summary,'Result summary',300)};job.status=next;job.updatedAt=this.now();
    for(const s of steps)if(s.status==='running'||s.status==='pending'){s.status=status==='failed'&&s.status==='running'?'failed':'cancelled';s.exitCode=s.status==='failed'?exitCode:s.exitCode;s.finishedAt=this.now();this.event(tx,'run.step.changed',s.id,run.projectId);}
    const agent=required(tx.agents.get(run.agentId),'Agent');agent.status='idle';agent.updatedAt=this.now();this.event(tx,'agent.status.changed',agent.id);
    if(next==='cancelled')this.event(tx,'job.cancelled',job.id,job.projectId);this.event(tx,status==='failed'||status==='timeout'?'run.failed':'run.completed',run.id,run.projectId);return run;
  }
  finishRun(projectId:string,id:string,status:Extract<RunStatus,'passed'|'failed'|'cancelled'|'timeout'>,exitCode:number|null,summary:string) { return this.repository.transaction(tx=>this.finish(tx,this.run(tx,projectId,id),status,exitCode,summary)); }
  /** One durable boundary for legacy command acceptance and its initial step. */
  acceptExecution(projectId:string,id:string) { return this.repository.transaction(tx=>{
    const run=this.run(tx,projectId,id),job=this.job(tx,projectId,run.jobId);
    if(job.payload.testPlan)throw new CoreError('Use pipeline acceptance.');
    if(job.cancellationRequestedAt||run.status!=='pending')return run;
    run.status='running';run.startedAt=this.now();job.status='running';job.updatedAt=this.now();
    const step=required(tx.steps.list().find(s=>s.runId===id),'Step');step.status='running';step.startedAt=run.startedAt;
    this.event(tx,'run.started',id,projectId);this.event(tx,'run.step.changed',step.id,projectId);return run;
  }); }
  /** Persist Step/Run/Job/result times together before acknowledging the Agent. */
  completeExecution(projectId:string,id:string,status:Extract<RunStatus,'passed'|'failed'|'cancelled'|'timeout'>,exitCode:number|null,summary:string,start:string,end:string,executionReport?:import('./domain.ts').ExecutionReport) {return this.repository.transaction(tx=>{
    const run=this.run(tx,projectId,id);if(!activeRun(run))return run;
    const job=this.job(tx,projectId,run.jobId);if(job.payload.testPlan)throw new CoreError('Use pipeline result.');
    if(status==='passed'&&(exitCode!==0||run.status!=='running'))throw new CoreError('Result before acceptance or invalid exit code.');
    if(status==='passed'){const step=required(tx.steps.list().find(s=>s.runId===id),'Step');step.status='passed';step.exitCode=0;step.finishedAt=end;this.event(tx,'run.step.changed',step.id,projectId);}
    this.finish(tx,run,status,exitCode,summary);run.startedAt=start;run.finishedAt=end;if(executionReport)run.executionReport=structuredClone(executionReport);return run;
  });}
  addArtifact(projectId:string,input:Omit<Artifact,'id'|'createdAt'>) { return this.repository.transaction(tx=>{this.run(tx,projectId,input.runId);if(input.runStepId&&required(tx.steps.get(input.runStepId),'Step').runId!==input.runId)throw new CoreError('Artifact step belongs to another run.');if(!['log','screenshot','report','trace','video'].includes(input.type)||!Number.isSafeInteger(input.size)||input.size<0)throw new CoreError('Invalid artifact metadata.');const location=text(input.location,'Artifact location',500);if(/^[a-z]+:/i.test(location)&&!/^https?:\/\//i.test(location))throw new CoreError('Unsupported artifact location.');if(/[?#@]/.test(location))throw new CoreError('Artifact location must not contain credentials or query values.');const artifact:Artifact={id:this.id(),runId:input.runId,runStepId:input.runStepId,type:input.type,name:text(input.name,'Artifact name'),location,size:input.size,createdAt:this.now()};tx.artifacts.save(artifact);this.event(tx,'artifact.created',artifact.id,projectId);return artifact;}); }
}

