'use client';
import { useI18n } from '@/i18n/react';
import {systemLanguage} from '@/i18n/core';
import {translate} from '@/i18n/messages';
import { useState, type FormEvent, type ChangeEvent } from 'react';
import { Bot, ListOrdered, History } from 'lucide-react';
import type { Activity } from '../workspace/state';
import type { Agent, Architecture, Browser, JobRequirement, Platform } from './domain';
import { useCore } from './context';
import { PipelineRunDetail } from './run-detail';
import {useProtocol} from '../protocol/views';
import {useRun} from '../process/context';
import {connectionReadiness} from './onboarding';
import {jobCreationKey} from './form-drafts';
import {CoreAccessNotice} from './access-notice';
import {ConnectionManagement} from './connection-management';
const date=(value:string|null,locale:string)=>value?new Date(value).toLocaleString(locale):translate(systemLanguage([locale]),'Not reported');
const reason=(error:unknown)=>error instanceof Error?error.message:'Core operation failed.';
export function CoreSidebar({activity}:{activity:Activity}) {
  const { t } = useI18n();

  const {snapshot,selection,select,setMessage,remote}=useCore();
  const agents=activity==='agents',jobs=activity==='queue';
  const rows=agents?snapshot.agents:jobs?[...snapshot.jobs].sort((a,b)=>b.priority-a.priority||a.queuedAt.localeCompare(b.queuedAt)):[...snapshot.runs].reverse();
  const kind=agents?'agent':jobs?'job':'run';
  return <div className="core-sidebar">
    {(agents||jobs)&&<button className="core-create" onClick={()=>{setMessage('');select({kind:agents?'new-agent':'new-job'});}}>{agents?t("Register agent"):t("Run on Agent")}</button>}
    <p className="core-scope">{agents?t("Shared agent registry"):t("Current project")} · {remote?t("Core session"):t("App session")}</p>
    {!rows.length?<p className="core-empty-list">{agents?t("No agents registered."):jobs?t("No jobs queued."):t("No runs recorded.")}</p>:<ul className="core-list">{rows.map(row=><li key={row.id}><button aria-pressed={selection?.kind===kind&&'id'in selection&&selection.id===row.id} onClick={()=>{select({kind,id:row.id});setMessage('');}}><strong>{'name'in row?row.name:snapshot.jobs.find(j=>j.id===row.jobId)?.name??row.id}</strong><span>{t(row.status)}{'priority'in row?` · ${t("Priority")} ${row.priority}`:''}</span><small>{'platform'in row?`${row.platform} / ${row.architecture}`:'attempt'in row?`${t("Attempt")} ${row.attempt}`:row.id.slice(0,8)}</small></button></li>)}</ul>}
  </div>;
}
function Fields({values}:{values:[string,React.ReactNode][]}) {const {t}=useI18n(); return <dl className="core-fields">{values.map(([key,value])=><div key={key}><dt>{t(key)}</dt><dd>{typeof value==='string'&&['Status','Cancellation','Exit code'].includes(key)?t(value):value}</dd></div>)}</dl>;}
function AgentForm(){
  const { t } = useI18n();
const {service,select,setMessage,formDrafts,setFormDraftField}=useCore();const draft=formDrafts.agent;const field=(key:string)=>({value:String(draft[key]),onChange:(e:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setFormDraftField('agent',key,e.target.value)});const [pending,setPending]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);try{const node=String(f.get('node')).trim();const agent=await service.registerAgent({name:String(f.get('name')),platform:f.get('platform')as Platform,architecture:f.get('architecture')as Architecture,capabilities:{cpuCores:Number(f.get('cpu')),memoryMiB:Number(f.get('memory')),docker:f.has('docker'),gpu:f.has('gpu'),pty:f.has('pty'),runtimes:node?{node}:{},browsers:f.has('browser')?['chromium']:[]}});select({kind:'agent',id:agent.id});setMessage('Agent registered offline. No connection has been established.');}catch(error){setMessage(reason(error));}finally{setPending(false);}}
return <section className="core-detail"><h1>{t("Register agent")}</h1><p className="core-description">{t("Record an execution environment. Declared capabilities are unverified until an agent connects.")}</p><form className="core-form" onSubmit={submit}><label>{t("Name")}<input name="name" {...field('name')} required maxLength={120}/></label><div className="core-form-row"><label>{t("OS")}<select name="platform" {...field('platform')}><option value="windows">{t("Windows")}</option><option value="linux">{t("Linux")}</option><option value="macos">{t("macOS")}</option></select></label><label>{t("Architecture")}<select name="architecture" {...field('architecture')}><option>{t("x86_64")}</option><option>{t("arm64")}</option></select></label></div><div className="core-form-row"><label>{t("CPU cores")}<input name="cpu" {...field('cpu')} type="number" min="1" required/></label><label>{t("Memory (MiB)")}<input name="memory" {...field('memory')} type="number" min="1" required/></label></div><label>{t("Node version")}<input name="node" {...field('node')} placeholder={t("e.g. 24.11.1")}/></label><fieldset><legend>{t("Declared capabilities")}</legend>{['docker','gpu','pty','browser'].map(key=><label className="core-check" key={key}><input type="checkbox" name={key} checked={!!draft[key]} onChange={e=>setFormDraftField('agent',key,e.target.checked)}/>{key==='browser'?t("Chromium"):key.toUpperCase()}</label>)}</fieldset><div className="core-actions"><button className="button primary" disabled={pending}>{t("Register offline")}</button><button type="button" className="button" onClick={()=>select(null)}>{t("Cancel")}</button></div></form></section>;}
function JobForm(){
  const { t } = useI18n();
const {service,project,select,setMessage,remote,formDrafts,setFormDraftField,snapshot}=useCore();const draft=formDrafts.job;const field=(key:string)=>({value:String(draft[key]),onChange:(e:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setFormDraftField('job',key,e.target.value)});const [pending,setPending]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);try{const requirements:JobRequirement={};if(f.get('platform'))requirements.platform=f.get('platform')as Platform;if(f.get('architecture'))requirements.architecture=f.get('architecture')as Architecture;if(f.get('node'))requirements.runtimes={node:String(f.get('node'))};if(f.get('browser'))requirements.browser=f.get('browser')as Browser;if(f.has('docker'))requirements.docker='required';const name=String(f.get('name'));const key=jobCreationKey(draft);setFormDraftField('job','requestId',key);const job=await service.createJob(project.id,{idempotencyKey:key,name,priority:Number(f.get('priority')),requirements,payload:{task:name,steps:[{name,executable:String(f.get('executable')),args:JSON.parse(String(f.get('args'))),cwd:'.',timeoutMs:Number(f.get('timeout'))*1000}]}});setFormDraftField('job','requestId','');select({kind:'job',id:job.id});setMessage(remote?'Job queued. Select Assign next compatible job to execute.':'Job queued locally. Connect to Core to create executable remote jobs.');}catch(error){setMessage(reason(error));}finally{setPending(false);}}
return <section className="core-detail"><h1>{t("Run on Agent")}</h1><p className="core-description">{t("Queue a structured task for")} {project.name}{t(". This creates a request; it does not execute a command.")}</p><form className="core-form" onSubmit={submit}><label>{t("Job name")}<input name="name" {...field('name')} required maxLength={120}/></label><label>{t("Executable")}<input name="executable" {...field('executable')} required placeholder={t("e.g. node")}/></label><label>{t("Timeout (seconds)")}<input name="timeout" {...field('timeout')} type="number" min="0.1" max="3600" step="0.1" required/></label><label>{t("Arguments (JSON array)")}<input name="args" {...field('args')} required/></label><div className="core-form-row"><label>{t("OS")}<select name="platform" {...field('platform')}><option value="">{t("Any OS")}</option><option value="windows">{t("Windows")}</option><option value="linux">{t("Linux")}</option><option value="macos">{t("macOS")}</option></select></label><label>{t("Architecture")}<select name="architecture" {...field('architecture')}><option value="">{t("Any architecture")}</option><option>{t("x86_64")}</option><option>{t("arm64")}</option></select></label></div><div className="core-form-row"><label>{t("Node requirement")}<input name="node" {...field('node')} placeholder=">=24"/></label><label>{t("Priority (0–100)")}<input name="priority" {...field('priority')} type="number" min="0" max="100" required/></label></div><label>{t("Browser")}<select name="browser" {...field('browser')}><option value="">{t("Not required")}</option><option>{t("chromium")}</option><option>{t("firefox")}</option><option>{t("webkit")}</option></select></label><label className="core-check"><input name="docker" type="checkbox" checked={!!draft.docker} onChange={e=>setFormDraftField('job','docker',e.target.checked)}/>{t("Docker required")}</label><div className="core-actions">{draft.requestId&&<button type="button" className="button" onClick={()=>{const existing=snapshot.jobs.find(j=>j.idempotencyKey===draft.requestId);if(existing)select({kind:'job',id:existing.id});else setMessage('Inspect the refreshed Queue, then retry the same request.');}}>{t("Inspect previous request")}</button>}<button className="button primary" disabled={pending}>{t("Queue job")}</button><button type="button" className="button" onClick={()=>select(null)}>{t("Cancel")}</button></div></form></section>;}
function AgentDetail({agent}:{agent:Agent}) {
  const { t, locale } = useI18n();
const {service,select,setMessage,remote}=useCore();return <section className="core-detail"><h1>{agent.name}</h1><p className="core-description">{t("Agent identity and declared capabilities")}</p><Fields values={[
['Agent ID',agent.id],['Status',agent.status],['OS / Architecture',`${agent.platform} / ${agent.architecture}`],['Last seen',date(agent.lastSeenAt,locale)||t('Not reported')],['CPU / Memory',`${agent.capabilities.cpuCores} / ${agent.capabilities.memoryMiB} MiB`],['Runtimes',Object.entries(agent.capabilities.runtimes).map(([k,v])=>`${k} ${v}`).join(', ')||t('None declared')],['Browsers',agent.capabilities.browsers.join(', ')||t('None declared')],['Docker / GPU / PTY',[agent.capabilities.docker,agent.capabilities.gpu,agent.capabilities.pty].map(v=>v?t('Yes'):t('No')).join(' / ')],['Created',date(agent.createdAt,locale)]
]}/><p className="core-notice">{remote?t("Status and last seen are reported by Core. Capability probes describe the connected agent."):t("Remote agent transport is not connected. Registration does not establish a connection.")}</p><button className="button" onClick={async()=>{try{await service.removeAgent(agent.id);select(null);setMessage('Agent registration removed.');}catch(e){setMessage(reason(e));}}}>{t("Remove registration")}</button></section>;}
export function CoreDetail({activity}:{activity:Activity}) {
  const { t, locale } = useI18n();

 const {service,project,snapshot,selection,select,message,setMessage,remote,logs,draftError}=useCore();
 let content:React.ReactNode;
 if(activity==='agents'&&selection?.kind==='new-agent')content=<AgentForm/>;
 else if(activity==='queue'&&selection?.kind==='new-job')content=<JobForm/>;
 else if(activity==='agents'&&selection?.kind==='agent'&&snapshot.agents.some(a=>a.id===selection.id))content=<AgentDetail agent={snapshot.agents.find(a=>a.id===selection.id)!}/>;
 else if(activity==='queue'&&selection?.kind==='job'&&snapshot.jobs.some(j=>j.id===selection.id)){
 const job=snapshot.jobs.find(j=>j.id===selection.id)!;const matches=service.matches(project.id,job.id);const run=snapshot.runs.find(r=>r.jobId===job.id);
 content=<section className="core-detail"><h1>{job.name}</h1><p className="core-description">{t("Project job request ·")} {project.name}</p><Fields values={[
 ['Job ID',job.id],['Status',job.status],['Priority',String(job.priority)],['Queued',date(job.queuedAt,locale)],['Attempt',`${job.attempt} / ${job.maxAttempts}`],['Requirements',JSON.stringify(job.requirements)],['Task',job.payload.task],['Steps',job.payload.steps.map(s=>s.name).join(' → ')],['Cancellation',job.cancellationRequestedAt?'Requested; awaiting acknowledgement':'Not requested']
 ]}/><h2>{t("Agent matching")}</h2>{matches.some(m=>m.matches)?<p>{remote?t("Compatible agent connected. Assignment sends this command for execution."):t("Compatible registration available. Assignment does not start execution.")}</p>:<p className="core-notice">{t("No compatible agent available.")}</p>}{matches.length>0&&<ul className="core-match-list">{matches.map(m=><li key={m.agentId}><strong>{snapshot.agents.find(a=>a.id===m.agentId)?.name}</strong><span>{m.matches?t("Match"):m.reasons.join(' · ')}</span></li>)}</ul>}<div className="core-actions">{job.status==='queued'&&<button className="button" onClick={async()=>{try{const result=await service.dispatch(project.id);if(result&&remote)select({kind:'job',id:result.job.id});setMessage(result?(remote?'':`Assigned ${result.job.name}. Remote execution is not connected.`):'No compatible agent available. Jobs remain queued.');}catch(e){setMessage(reason(e));}}}>{t("Assign next compatible job")}</button>}{['queued','assigned','running'].includes(job.status)&&<button className="button" disabled={!!job.cancellationRequestedAt} onClick={async()=>{try{await service.cancelJob(project.id,job.id);setMessage(job.status==='queued'?'Job cancelled.':'Cancellation requested; waiting for execution acknowledgement.');}catch(e){setMessage(reason(e));}}}>{job.status==='queued'?t("Cancel job"):t("Request cancellation")}</button>}{job.status==='failed'&&<button className="button" onClick={async()=>{try{const retry=await service.retryJob(project.id,job.id);select({kind:'job',id:retry.id});setMessage('Retry queued as a new attempt.');}catch(e){setMessage(reason(e));}}}>{t("Queue retry")}</button>}</div>{run&&<p className="core-description">{t("Run")} {run.id} · {t(run.status)}{t(". Open Runs to inspect this record.")}</p>}</section>;
 }else if(activity==='runs'&&selection?.kind==='run'&&snapshot.runs.some(r=>r.id===selection.id)){
 const run=snapshot.runs.find(r=>r.id===selection.id)!;const job=snapshot.jobs.find(j=>j.id===run.jobId);const steps=snapshot.steps.filter(s=>s.runId===run.id).sort((a,b)=>a.order-b.order);const artifacts=snapshot.artifacts.filter(a=>a.runId===run.id);const duration=run.startedAt&&run.finishedAt?`${Math.max(0,Date.parse(run.finishedAt)-Date.parse(run.startedAt)) / 1000}s`:run.startedAt?'In progress':'Not started';
 content=job?.payload.testPlan?<PipelineRunDetail key={run.id} id={run.id}/>:<section className="core-detail"><h1>{t("Run detail")}</h1><p className="core-description">{job?.name??run.jobId} · {t(run.status)}</p><Fields values={[
 ['Run ID',run.id],['Project',project.name],['Job',job?.name??run.jobId],['Agent',snapshot.agents.find(a=>a.id===run.agentId)?.name??run.agentId],['Status',run.status],['Start',date(run.startedAt,locale)],['Duration',duration],['Exit code',run.exitCode===null?'Not reported':String(run.exitCode)]
 ]}/><h2>{t("Steps")}</h2><div className="core-table-scroll"><table><thead><tr><th>{t("Order")}</th><th>{t("Step")}</th><th>{t("Status")}</th><th>{t("Exit")}</th></tr></thead><tbody>{steps.map(s=><tr key={s.id}><td>{s.order+1}</td><td>{s.name}</td><td>{t(s.status)}</td><td>{s.exitCode??'—'}</td></tr>)}</tbody></table></div><h2>{t("Result")}</h2><p>{run.result?.summary??t("No result reported yet.")}</p><h2>{t("Remote Agent log")}</h2><p className="core-description">{t("stdout / stderr · latest 128 KiB retained · separate from Local Terminal")}</p><pre className="core-live-log" aria-label={t("Remote Agent log")} tabIndex={0}>{(logs[run.id]??[]).length?(logs[run.id]??[]).map(chunk=><span key={chunk.sequence} className={chunk.stream==='stderr'?'core-stderr':undefined}>{'['+chunk.stream+'] '+chunk.text}</span>):t("No output received.")}</pre><h2>{t("Artifacts")}</h2>{artifacts.length?<ul>{artifacts.map(a=><li key={a.id}>{a.name} · {a.type} · {a.size} {t("bytes")}<br/><code>{a.location}</code></li>)}</ul>:<p className="core-description">{t("No artifact metadata recorded.")}</p>}</section>;
 }else if(activity==='runs'&&snapshot.runs.length){
 content=<section className="core-detail"><h1>{t("Run history")}</h1><p className="core-description">{t("Execution records for")} {project.name}. {remote?t("Live Core execution records."):t("No remote transport is connected.")}</p><div className="core-table-scroll"><table><thead><tr><th>{t("Run / Job")}</th><th>{t("Project")}</th><th>{t("Agent")}</th><th>{t("Status")}</th><th>{t("Start / Duration")}</th></tr></thead><tbody>{[...snapshot.runs].reverse().map(run=><tr key={run.id}><td><button className="ws-text-button" onClick={()=>select({kind:'run',id:run.id})}>{run.id.slice(0,8)}</button><br/>{snapshot.jobs.find(j=>j.id===run.jobId)?.name}</td><td>{project.name}</td><td>{snapshot.agents.find(a=>a.id===run.agentId)?.name??run.agentId}</td><td>{t(run.status)}</td><td>{date(run.startedAt,locale)}<br/>{run.startedAt&&run.finishedAt?((Date.parse(run.finishedAt)-Date.parse(run.startedAt))/1000)+'s':run.startedAt?t("In progress"):t("Not started")}</td></tr>)}</tbody></table></div></section>;
 }else {const Icon=activity==='agents'?Bot:activity==='queue'?ListOrdered:History;content=<section className="core-detail core-welcome"><Icon size={28} aria-hidden="true"/><h1>{activity==='agents'?t("Agents"):activity==='queue'?t("Job queue"):t("Run history")}</h1><p>{activity==='agents'?t("Inspect registered execution environments and their capabilities."):activity==='queue'?t("Create and inspect work requests for this project."):t("Inspect run attempts, ordered steps and recorded results.")}</p><p className="core-description">{activity==='agents'?(snapshot.agents.length?t("Select an agent to view its details."):t("No agents registered.")):activity==='queue'?(snapshot.jobs.length?t("Select a job to inspect its requirements."):t("No jobs queued.")):(snapshot.runs.length?t("Select a run to inspect its steps and result."):t("No runs recorded."))}</p><p className="core-notice">{remote?t("Core retains state while its server process runs. Reconnect after reloading Studio."):t("Local Core state resets on reload. Connect to Core for actual Agent execution.")}</p></section>;}
 return <main id="core-content" className="core-center" aria-label={t("Core details")}>{message&&<p role="status" className="core-feedback">{t(message)}</p>}{draftError&&<p role="alert" className="core-feedback">{t(draftError)}</p>}{activity==='agents'&&<ConnectionForm/>}<CoreAccessNotice/>{content}</main>;
}

function ConnectionForm(){
  const { t } = useI18n();
 const {connection,project,setMessage,snapshot,connectionDraft:draft,setConnectionDraft,connectionToken,setConnectionToken,draftError}=useCore();const protocol=useProtocol(),local=useRun();
 const checks=connectionReadiness(connection.phase,snapshot,{loading:protocol.loading,status:protocol.state.status});
 return <section className="core-onboarding" aria-label={t("Connection guide")}><ConnectionManagement key={project.id+connection.connectionKey}/><form className="core-connection" onSubmit={e=>{e.preventDefault();try{connection.connect(draft.endpoint,connectionToken,project);setMessage('');}catch(error){setMessage(reason(error));}}}>
 <strong>{t("Core connection")}</strong><span role="status" aria-live="polite">{t(connection.status)}</span>
 <label>{t("Connection mode")}<select value={draft.mode} onChange={e=>setConnectionDraft({...draft,mode:e.target.value as 'local'|'team'})}><option value="local">{t("Local Core")}</option><option value="team">{t("Team Core")}</option></select></label>
 <label>{t("Endpoint")}<input name="endpoint" type="url" required value={draft.endpoint} onChange={e=>setConnectionDraft({...draft,endpoint:e.target.value})}/></label>
 <label>{t("Studio token")}<input name="token" type="password" autoComplete="off" required minLength={16} value={connectionToken} onChange={e=>setConnectionToken(e.target.value)}/></label>
 <button className="button" type="submit">{t("Connect Core")}</button>{connection.enabled&&<><button type="button" className="button" onClick={()=>connection.reconnect()}>{t("Retry connection")}</button><button type="button" className="button" onClick={()=>{connection.disconnect();setConnectionToken('');}}>{t("Disconnect Core")}</button></>}
 <small>{t("Execution history is saved by Core. Connection credentials stay in memory.")}</small><small>{t("After reloading, enter your token again. Saved addresses do not contain credentials.")}</small>
 </form><div className="core-readiness"><h2>{t("Connection guide")}</h2><p>{draft.mode==='local'?t("Start Core locally, then connect an Agent to the same Core."):t("Enter the address and Studio token supplied by your team administrator.")}</p><p>{local.service.host.capabilities.process?t("Desktop supports local processes and native file access."):t("Web keeps remote Agent execution available; local processes and native Git require Desktop.")}</p><ul>{checks.map(check=><li key={check.label} data-state={check.state}><strong>{t(check.label)}</strong><span>{t(check.state)}</span><p>{t(check.detail)}</p>{check.label==='TASTEDEV Protocol'&&<button className="ws-text-button" type="button" onClick={protocol.reload}>{t("Reload project definition")}</button>}</li>)}</ul>{connection.lastError&&<p role="alert">{t(connection.lastError)}</p>}{draftError&&<p role="alert">{t(draftError)}</p>}</div></section>;
}
