import {spawn} from 'node:child_process';
import {IssueError,type IssueProvider,type ExternalIssue} from '../src/features/issues/domain.ts';
import {repository,externalURL,safeText} from '../src/features/issues/security.ts';
import {requestMarker} from '../src/features/issues/service.ts';
export interface GitHubResponse {status:number;headers:Record<string,string>;body:unknown}
export type GitHubRequest=(method:'GET'|'POST',path:string,body?:unknown)=>Promise<GitHubResponse>;
/** Uses gh's managed keyring authentication without reading or returning an account token. */
export function ghRequest(executable=process.env.TASTEDEV_GITHUB_EXECUTABLE??'gh'):GitHubRequest{return(method,path,body)=>new Promise((resolve,reject)=>{
 const child=spawn(executable,['api',path,'--method',method,'--include','-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: 2026-03-10',...(body?['--input','-']:[])],{windowsHide:true,shell:false,stdio:['pipe','pipe','pipe']});let output='',size=0,settled=false;const finish=(error?:IssueError,value?:GitHubResponse)=>{if(settled)return;settled=true;clearTimeout(timer);if(error)reject(error);else resolve(value!);};const timer=setTimeout(()=>{child.kill();finish(new IssueError(method==='POST'?'create-uncertain':'timeout'));},15000);child.on('error',()=>finish(new IssueError('unavailable')));child.stdout.on('data',chunk=>{size+=chunk.length;if(size>1000000){child.kill();finish(new IssueError(method==='POST'?'create-uncertain':'validation'));}else output+=chunk.toString();});child.stderr.resume();child.on('close',code=>{if(settled)return;const split=output.search(/\r?\n\r?\n/);const head=split>=0?output.slice(0,split):'',status=Number(head.match(/^HTTP\/[\d.]+ (\d+)/)?.[1]);const headers:Record<string,string>={};for(const line of head.split(/\r?\n/).slice(1)){const colon=line.indexOf(':');if(colon>0)headers[line.slice(0,colon).toLowerCase()]=line.slice(colon+1).trim();}let parsed:unknown;try{parsed=JSON.parse(output.slice(split).trim());}catch{finish(new IssueError(method==='POST'?'create-uncertain':'unavailable'));return;}if(!status){finish(new IssueError(code===0?'validation':'authentication'));return;}finish(undefined,{status,headers,body:parsed});});if(body)child.stdin.end(JSON.stringify(body));else child.stdin.end();
 });}
/** Optional Core-only fine-grained token with Issues permissions. No NEXT_PUBLIC configuration. */
export function tokenRequest(token:string,request:typeof fetch=fetch):GitHubRequest{return async(method,path,body)=>{try{const res=await request('https://api.github.com/'+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2026-03-10',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000),redirect:'error'});return{status:res.status,headers:Object.fromEntries(res.headers),body:await res.json()};}catch{throw new IssueError(method==='POST'?'create-uncertain':'timeout');}};}
export class GitHubIssueProvider implements IssueProvider {
 readonly name='github';readonly capabilities={comments:false,labels:true};private blockedUntil=0;
 readonly request:GitHubRequest;readonly secrets:string[];
 constructor(request:GitHubRequest=process.env.TASTEDEV_GITHUB_TOKEN?tokenRequest(process.env.TASTEDEV_GITHUB_TOKEN):ghRequest(),secrets:string[]=[]){this.request=request;this.secrets=secrets;}
 private async api(method:'GET'|'POST',path:string,body?:unknown){if(Date.now()<this.blockedUntil)throw new IssueError('rate-limit');const r=await this.request(method,path,body);if(r.status===429||r.status===403&&(r.headers['x-ratelimit-remaining']==='0'||r.headers['retry-after'])){this.blockedUntil=Math.max(Date.now()+5000,Number(r.headers['x-ratelimit-reset']??0)*1000,Date.now()+Number(r.headers['retry-after']??5)*1000);throw new IssueError('rate-limit');}if(r.status>=200&&r.status<300)return r.body;if(r.status===401)throw new IssueError('authentication');if(r.status===403)throw new IssueError('permission');if(r.status===404)throw new IssueError('repository');if(r.status===422)throw new IssueError('validation');throw new IssueError(method==='POST'?'create-uncertain':'unavailable');}
 private issue(repo:string,raw:unknown):ExternalIssue{const v=raw as Record<string,unknown>;if(!v||v.pull_request||!Number.isSafeInteger(v.number)||!(typeof v.id==='number'||typeof v.id==='string')||!['open','closed'].includes(v.state as string)||typeof v.title!=='string'||typeof v.created_at!=='string')throw new IssueError('validation');const number=v.number as number;return{provider:this.name,repository:repo,externalId:String(v.id),number,url:externalURL(v.html_url,repo,number),state:v.state as string,title:safeText(v.title,this.secrets),body:safeText(typeof v.body==='string'?v.body:'',this.secrets),createdAt:v.created_at};}
 async identify(repo:string){repo=repository(repo);const data=await this.api('GET',`repos/${repo}`) as {full_name?:string;has_issues?:boolean};if(data.full_name?.toLowerCase()!==repo||!data.has_issues)throw new IssueError('repository');}
 async search(repo:string,terms:string[]){repo=repository(repo);const results=new Map<number,ExternalIssue>();for(const term of [...new Set(terms)].slice(0,4)){const q=`repo:${repo} is:issue ${term.slice(0,160)} in:title,body`;const data=await this.api('GET','search/issues?q='+encodeURIComponent(q)+'&per_page=20') as {items?:unknown[]};if(!Array.isArray(data.items))throw new IssueError('validation');for(const raw of data.items){const item=this.issue(repo,raw);results.set(item.number,item);}}return [...results.values()];}
 async get(repo:string,number:number){repo=repository(repo);if(!Number.isSafeInteger(number)||number<1)throw new IssueError('validation');return this.issue(repo,await this.api('GET',`repos/${repo}/issues/${number}`));}
 async create(repo:string,input:{title:string;body:string;labels:string[]}){repo=repository(repo);return this.issue(repo,await this.api('POST',`repos/${repo}/issues`,input));}
 async reconcile(repo:string,id:string){repo=repository(repo);const data=await this.api('GET',`repos/${repo}/issues?state=all&sort=created&direction=desc&per_page=100`);if(!Array.isArray(data))throw new IssueError('validation');return data.filter(v=>!v.pull_request&&typeof v.body==='string'&&v.body.includes(requestMarker(id))).map(v=>this.issue(repo,v));}
}

