import type {IncomingMessage,ServerResponse} from 'node:http';
import {pageHistory} from '../src/features/core/history-query.ts';
import {TeamAccessError} from './team-access.ts';
import {createHash,timingSafeEqual} from 'node:crypto';
import type {AnalysisRecord} from '../src/features/ai/domain.ts';
import {aiPath,uuid} from '../src/features/ai/security.ts';
import {applyEdits,contentHash,type FixAttempt} from '../src/features/ai/fix-service.ts';
import {snapshotPath} from '../src/features/ai/snapshot.ts';
import type {CoreStore} from './storage.ts';
export type HistoryKind='analysis'|'attempt';
export interface HistoryRow {version:number;value:AnalysisRecord|FixAttempt}
/** Project-scoped record CAS. This endpoint stores review data; it cannot execute tools. */
export class HistoryStore {
 private memory=new Map<string,HistoryRow>();private store?:CoreStore;
 constructor(store?:CoreStore){this.store=store;}
 private key(project:string,kind:HistoryKind,id:string){return `history:${project}:${kind}:${id}`;}
 list(project:string,kind:HistoryKind){const prefix=`history:${project}:${kind}:`,names=this.store?this.store.names(prefix):[...this.memory.keys()].filter(k=>k.startsWith(prefix));return names.map(name=>({id:name.slice(prefix.length),version:(this.store?.get<HistoryRow>(name)??this.memory.get(name))!.version}));}
 get(project:string,kind:HistoryKind,id:string){return structuredClone(this.store?.get<HistoryRow>(this.key(project,kind,id))??this.memory.get(this.key(project,kind,id)));}
 page(project:string,kind:HistoryKind,query:unknown){return pageHistory(this.list(project,kind).map(entry=>{const row=this.get(project,kind,entry.id)!;return {...entry,createdAt:row.value.createdAt,name:kind==='analysis'?(row.value as AnalysisRecord).result.summary.slice(0,160):row.value.id,status:kind==='attempt'?(row.value as FixAttempt).status:'analysis'};}),query);}
 async put(project:string,kind:HistoryKind,id:string,expectedVersion:number,value:AnalysisRecord|FixAttempt){
  uuid(id);if(value.id!==id||value.projectId!==project||!Number.isSafeInteger(expectedVersion)||expectedVersion<0||!Number.isFinite(Date.parse(value.createdAt)))throw Error('Invalid history record.');
  if(kind==='attempt'){
   const a=value as FixAttempt;uuid(a.proposalId);uuid(a.analysisId);if(!Number.isInteger(a.attempt)||a.attempt<1||a.attempt>10||!['proposed','approved','applied','validating','retesting','passed','failed','reverted','cancelled','rejected','recovery-required'].includes(a.status)||!Array.isArray(a.patches)||!a.patches.length||a.patches.length>8)throw Error('Invalid attempt.');
   if(a.events){if(!Array.isArray(a.events)||a.events.length>200||new Set(a.events.map(e=>e.id)).size!==a.events.length)throw Error('Invalid Fix event history.');for(const e of a.events){uuid(e.id);if(!['proposal','approval','patch','validation','retest','recovery','result'].includes(e.phase)||!['proposed','approved','applied','validating','retesting','passed','failed','reverted','cancelled','rejected','recovery-required'].includes(e.status)||!Number.isFinite(Date.parse(e.timestamp))||Object.keys(e).some(k=>!['id','phase','status','timestamp'].includes(k)))throw Error('Invalid Fix event history.');}}
   for(const p of a.patches){aiPath(p.path);if(typeof p.base!=='string'||typeof p.result!=='string'||p.base.length>32768||p.result.length>32768||await contentHash(p.base)!==p.baseHash||await contentHash(p.result)!==p.resultHash||applyEdits(p.base,p.edits)!==p.result)throw Error('Invalid stored patch.');}
   if(['approved','applied','validating','retesting','passed','reverted','recovery-required'].includes(a.status)&&!a.approval)throw Error('Invalid approval scope.');
   if(a.approval&&(a.approval.proposalId!==a.proposalId||a.approval.changeHash!==await contentHash(JSON.stringify(a.patches))||a.approval.files.length!==a.patches.length||new Set(a.approval.files).size!==a.patches.length||a.approval.files.some(p=>!a.patches.some(f=>f.path===p))))throw Error('Invalid approval scope.');
   if(a.journal){const j=a.journal;if(!a.approval||!['apply','revert'].includes(j.operation)||!Number.isFinite(Date.parse(j.startedAt))||j.completedAt!==undefined&&(!Number.isFinite(Date.parse(j.completedAt))||Date.parse(j.completedAt)<Date.parse(j.startedAt))||!Array.isArray(j.files)||j.files.length!==a.patches.length||j.files.some((f,i)=>f.path!==a.patches[i].path||f.beforeHash!==a.patches[i].baseHash||f.afterHash!==a.patches[i].resultHash))throw Error('Invalid stored patch journal.');}
   if(a.executionApprovals!==undefined){if(!Array.isArray(a.executionApprovals)||a.executionApprovals.length>100||new Set(a.executionApprovals.map(v=>v.id)).size!==a.executionApprovals.length)throw Error('Invalid approval scope.');for(const v of a.executionApprovals){uuid(v.id);if(!a.approval||v.proposalId!==a.proposalId||!['local-task','remote-test'].includes(v.kind)||typeof v.name!=='string'||!v.name.trim()||v.name.length>200||!Number.isFinite(Date.parse(v.timestamp))||!/^[a-f0-9]{64}$/.test(v.definitionHash)||Object.keys(v).some(k=>!['id','proposalId','kind','name','definitionHash','timestamp'].includes(k)))throw Error('Invalid approval scope.');}}
   if(a.snapshot){const s=a.snapshot;uuid(s.snapshotId);if(s.provider!=='snapshot'||s.projectId!==project||s.proposalId!==a.proposalId||s.attempt!==a.attempt||typeof s.baseRevision!=='string'||s.baseRevision.length>200||!Array.isArray(s.changedFiles)||s.changedFiles.length!==a.patches.length||new Set(s.changedFiles).size!==s.changedFiles.length||s.changedFiles.some(p=>!a.patches.some(f=>f.path===p))||!Array.isArray(s.files)||!s.files.length||s.files.length>100||new Set(s.files.map(f=>f.path.toLowerCase())).size!==s.files.length||Object.keys(s).some(k=>!['provider','snapshotId','projectId','proposalId','attempt','baseRevision','changedFiles','files','checksum'].includes(k)))throw Error('Invalid stored patch snapshot.');for(const f of s.files){snapshotPath(f.path);if(!/^[a-f0-9]{64}$/.test(f.checksum)||Object.keys(f).some(k=>!['path','checksum'].includes(k)))throw Error('Invalid stored patch snapshot.');}if(a.patches.some(p=>s.files.find(f=>f.path===p.path)?.checksum!==p.resultHash)||await contentHash(JSON.stringify([s.snapshotId,s.projectId,s.proposalId,s.attempt,s.baseRevision,s.changedFiles,...s.files.map(f=>[f.path,f.checksum])]))!==s.checksum)throw Error('Invalid stored patch snapshot.');}
  }else{
   const a=value as AnalysisRecord;uuid(a.conversationId);if(!a.result||typeof a.result.summary!=='string'||!Array.isArray(a.context)||!a.originals||Object.entries(a.originals).some(([p,v])=>{try{aiPath(p);return typeof v!=='string'||v.length>32768;}catch{return true;}}))throw Error('Invalid analysis.');
  }
  // Recheck after async hash validation; concurrent writers cannot both win.
  const key=this.key(project,kind,id),old=this.store?.get<HistoryRow>(key)??this.memory.get(key);
  if((old?.version??0)!==expectedVersion)throw Error('HISTORY_CONFLICT');
  if(old){if(old.value.createdAt!==value.createdAt)throw Error('History identity is immutable.');if(kind==='analysis'&&JSON.stringify(old.value)!==JSON.stringify(value))throw Error('Analysis is immutable.');if(kind==='attempt'){const before=old.value as FixAttempt,after=value as FixAttempt;if(before.proposalId!==after.proposalId||before.analysisId!==after.analysisId||JSON.stringify(before.patches)!==JSON.stringify(after.patches)||JSON.stringify(before.approval)!==JSON.stringify(after.approval)&&before.approval)throw Error('Reviewed proposal is immutable.');if(before.executionApprovals&&JSON.stringify(before.executionApprovals)!==JSON.stringify(after.executionApprovals?.slice(0,before.executionApprovals.length)))throw Error('Reviewed proposal is immutable.');if(before.events&&JSON.stringify(before.events)!==JSON.stringify(after.events?.slice(0,before.events.length)))throw Error("Fix event history is immutable.");if(before.snapshot&&JSON.stringify(before.snapshot)!==JSON.stringify(after.snapshot))throw Error('Reviewed proposal is immutable.');}}
  const row={version:expectedVersion+1,value:structuredClone(value)};this.store?.put(key,row);if(!this.store)this.memory.set(key,row);return row.version;
 }
}
export function historyGateway(store:HistoryStore,token:string,origins:string[],project:(id:string)=>boolean,authorize?:(req:IncomingMessage,projectId:string,action:string,kind:HistoryKind,value?:AnalysisRecord|FixAttempt)=>void){return async(req:IncomingMessage,res:ServerResponse)=>{
 res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');const origin=req.headers.origin;
 if(origin&&!origins.includes(origin)){res.statusCode=403;res.end('{"error":"permission"}');return;}if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');}res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type, X-Project-Id');if(req.method==='OPTIONS'){res.end();return;}
 try{const actual=req.headers.authorization?.slice(7)??'';if(!req.headers.authorization?.startsWith('Bearer ')||!timingSafeEqual(createHash('sha256').update(actual).digest(),createHash('sha256').update(token).digest())){res.statusCode=401;throw Error('Authentication required.');}
  const p=String(req.headers['x-project-id']??'');if(!project(p))throw Error('Project boundary.');if(req.method!=='POST'||req.url!=='/history/request')throw Error('Invalid history request.');req.setTimeout(15000,()=>req.destroy());const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>1048576)throw Error('History record exceeds safe limit.');chunks.push(Buffer.from(chunk));}
  const input=JSON.parse(Buffer.concat(chunks).toString('utf8')) as {action:string;kind:HistoryKind;id:string;version:number;value:AnalysisRecord|FixAttempt;query:unknown};if(!['analysis','attempt'].includes(input.kind))throw Error('Invalid history kind.');let value:unknown;
  authorize?.(req,p,input.action,input.kind,input.value);
  if(input.action==='page')value=store.page(p,input.kind,input.query);else if(input.action==='list')value=store.list(p,input.kind);else{uuid(input.id);if(input.action==='get')value=store.get(p,input.kind,input.id)??null;else if(input.action==='put')value=await store.put(p,input.kind,input.id,input.version,input.value);else throw Error('Invalid history action.');}res.end(JSON.stringify({value}));
 }catch(e){if(e instanceof TeamAccessError){res.statusCode=403;if(!res.destroyed)res.end(JSON.stringify({error:'TEAM_FORBIDDEN'}));return;}if(res.statusCode===200)res.statusCode=e instanceof Error&&e.message==='HISTORY_CONFLICT'?409:400;if(!res.destroyed)res.end(JSON.stringify({error:e instanceof Error&&/^(HISTORY_CONFLICT|Invalid (history|attempt|stored patch|approval scope|analysis)|History identity|Analysis is immutable|Reviewed proposal|Authentication required|Project boundary|Core storage write failed|History record exceeds)/.test(e.message)?e.message:'History persistence failed.'}));}
};}
