import type {IncomingMessage,ServerResponse} from 'node:http';
import {TeamAccessError} from './team-access.ts';
import {createHash,timingSafeEqual} from 'node:crypto';
import type {Project} from '../src/features/projects/types/project.ts';
import type {CoreSnapshot} from '../src/features/core/domain.ts';
import {IssueService,type IssuePersistence} from '../src/features/issues/service.ts';
import {buildCandidate,type CandidateInput} from '../src/features/issues/builder.ts';
import {IssueError,type IssueProvider} from '../src/features/issues/domain.ts';
import {repository} from '../src/features/issues/security.ts';
export function issueGateway(provider:IssueProvider,token:string,origins:string[],project:(id:string)=>Project|undefined,snapshot:(id:string)=>CoreSnapshot,logs:(id:string)=>string[],secrets:string[]=[],persistence?:IssuePersistence,authorize?:(req:IncomingMessage,projectId:string,action:string,target?:string)=>void){const service=new IssueService(provider,secrets,persistence);let active=0;
 const handle=async(req:IncomingMessage,res:ServerResponse)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');const origin=req.headers.origin;if(origin&&!origins.includes(origin)){res.statusCode=403;res.end('{"error":"permission"}');return;}if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');}res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type, X-Project-Id');if(req.method==='OPTIONS'){res.end();return;}let entered=false;try{const actual=req.headers.authorization?.slice(7)??'';if(!req.headers.authorization?.startsWith('Bearer ')||!timingSafeEqual(createHash('sha256').update(actual).digest(),createHash('sha256').update(token).digest()))throw new IssueError('authentication');const id=String(req.headers['x-project-id']??''),p=project(id);if(!p)throw new IssueError('boundary');if(req.method!=='POST'||req.url!=='/issues/request')throw new IssueError('validation');if(active>=4)throw new IssueError('rate-limit');active++;entered=true;req.setTimeout(15000,()=>req.destroy());let text='';for await(const chunk of req){text+=chunk.toString();if(Buffer.byteLength(text)>100000)throw new IssueError('validation');}const input=JSON.parse(text) as {action:string;id:string;version:number;repository:string;number:number;reason:string;fields:{title:string;body:string;labels:string[]};context:CandidateInput};let result:unknown;
 authorize?.(req,id,input.action,input.id);
 if(input.action==='list')result=service.list(id);else if(input.action==='build'){const c=buildCandidate(p,snapshot(id),input.context,logs(input.context.runId),secrets);result=service.add(c);}else{const c=service.get(id,input.id);if(!['get','dismiss'].includes(input.action)&&c.repository!==repository(p.repositoryUrl))throw new IssueError('boundary');switch(input.action){case 'get':result=c;break;case 'edit':result=service.edit(id,c.id,input.version,input.fields);break;case 'dismiss':result=service.dismiss(id,c.id,input.reason);break;case 'search':result=await service.search(id,c.id);break;case 'approve':result=await service.approve(id,c.id,input.version,input.repository);break;case 'create':result=await service.create(id,c.id);break;case 'link':result=await service.link(id,c.id,input.number);break;case 'reconcile':result=await service.reconcile(id,c.id);break;default:throw new IssueError('validation');}}res.end(JSON.stringify({value:result}));
 }catch(e){const error=e instanceof IssueError?e:new IssueError(e instanceof TeamAccessError?'team-permission':'validation');res.statusCode=error.code==='team-permission'?403:error.code==='authentication'?401:error.code==='rate-limit'?429:400;if(!res.destroyed)res.end(JSON.stringify({error:error.code}));}finally{if(entered)active--;}};return{service,handle};}
