import {GitHubIssueProvider,type GitHubRequest} from './github-provider.ts';
import {IssueError} from '../src/features/issues/domain.ts';
import {repository,safeText} from '../src/features/issues/security.ts';
import {pullBranch,pullURL,type PullProvider,type PullRequest,type PullChecks} from '../src/features/git/pull-requests.ts';
export class GitHubPullProvider implements PullProvider {
 private blockedUntil=0;
 readonly request:GitHubRequest;readonly secrets:string[];
 constructor(request:GitHubRequest=new GitHubIssueProvider().request,secrets:string[]=[]){this.request=request;this.secrets=secrets;}
 private async api(method:'GET'|'POST',path:string,body?:unknown){if(Date.now()<this.blockedUntil)throw new IssueError('rate-limit');const response=await this.request(method,path,body);if(response.status===429||response.status===403&&(response.headers['x-ratelimit-remaining']==='0'||response.headers['retry-after'])){this.blockedUntil=Date.now()+Math.max(5000,Math.min(3600000,Number(response.headers['retry-after']??5)*1000));throw new IssueError('rate-limit');}if(response.status>=200&&response.status<300)return response.body;if(response.status===401)throw new IssueError('authentication');if(response.status===403)throw new IssueError('permission');if(response.status===404)throw new IssueError('repository');if(response.status===422)throw new IssueError('validation');throw new IssueError(method==='POST'?'create-uncertain':'unavailable');}
 private pull(repo:string,raw:unknown):PullRequest{const row=raw as {number:number;html_url:string;title:string;body:string;state:string;merged_at:string|null;head:{sha:string;ref:string;repo:{full_name:string}};base:{ref:string;repo:{full_name:string}}};if(!row||!Number.isSafeInteger(row.number)||row.number<1||typeof row.title!=='string'||!['open','closed'].includes(row.state)||!/^[a-f0-9]{40,64}$/.test(row.head?.sha??'')||row.head?.repo?.full_name?.toLowerCase()!==repo||row.base?.repo?.full_name?.toLowerCase()!==repo)throw new IssueError('boundary');return {number:row.number,url:pullURL(row.html_url,repo,row.number),title:safeText(row.title,this.secrets),body:safeText(row.body??'',this.secrets),state:row.merged_at?'merged':row.state,sha:row.head.sha,head:pullBranch(row.head.ref),base:pullBranch(row.base.ref)};}
 async head(repo:string,branch:string){repo=repository(repo);const row=await this.api('GET',`repos/${repo}/git/ref/heads/${encodeURIComponent(pullBranch(branch))}`) as {object?:{sha?:string}};if(!/^[a-f0-9]{40,64}$/.test(row.object?.sha??''))throw new IssueError('validation');return row.object!.sha!;}
 async list(repo:string,base:string,head:string){repo=repository(repo);const rows=await this.api('GET',`repos/${repo}/pulls?state=all&sort=created&direction=desc&per_page=100&base=${encodeURIComponent(pullBranch(base))}&head=${encodeURIComponent(repo.split('/')[0]+':'+pullBranch(head))}`);if(!Array.isArray(rows))throw new IssueError('validation');return rows.slice(0,100).map(row=>this.pull(repo,row));}
 async create(repo:string,input:{title:string;body:string;base:string;head:string}){repo=repository(repo);return this.pull(repo,await this.api('POST',`repos/${repo}/pulls`,input));}
 async get(repo:string,number:number){repo=repository(repo);if(!Number.isSafeInteger(number)||number<1)throw new IssueError('validation');return this.pull(repo,await this.api('GET',`repos/${repo}/pulls/${number}`));}
 async checks(repo:string,sha:string):Promise<PullChecks>{repo=repository(repo);if(!/^[a-f0-9]{40,64}$/.test(sha))throw new IssueError('validation');const rows=await this.api('GET',`repos/${repo}/commits/${sha}/check-runs?per_page=100`) as {total_count:number;check_runs:{name:string;status:string;conclusion:string|null;head_sha:string}[]};const status=await this.api('GET',`repos/${repo}/commits/${sha}/status?per_page=100`) as {state:string;sha:string;total_count?:number};if(!Array.isArray(rows.check_runs)||status.sha!==sha||!['pending','success','failure','error'].includes(status.state)||rows.check_runs.some(row=>row.head_sha!==sha))throw new IssueError('boundary');return {sha,state:status.state,checks:rows.check_runs.slice(0,100).map(row=>({name:safeText(row.name,this.secrets).slice(0,256),status:row.status,conclusion:row.conclusion})),truncated:rows.total_count>100||(status.total_count??0)>100};}
}
