import type {IncomingMessage,ServerResponse} from 'node:http';
import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import type {CoreService} from '../src/features/core/service.ts';
import {activeRun} from '../src/features/core/domain.ts';
import type {ProjectSnapshot} from '../src/features/ai/project-snapshot.ts';
import {projectReference,verifyProjectReference} from '../src/features/ai/project-snapshot.ts';
import {projectSnapshotLimits as limits} from '../src/features/ai/snapshot-bytes.ts';
import {uuid} from '../src/features/ai/security.ts';
import {SourceSnapshotStore} from './source-snapshot-store.ts';
import {TeamAccessError} from './team-access.ts';
interface Grant {runId:string;stepId:string;projectId:string;snapshotId:string;checksum:string;expires:number;agentId:string}
const equal=(a:string,b:string)=>timingSafeEqual(createHash('sha256').update(a).digest(),createHash('sha256').update(b).digest());
export function sourceSnapshotGateway(core:CoreService,root:string,studioToken:string,origins:string[],authorize:(req:IncomingMessage,projectId:string,action:'read'|'run')=>void=()=>{},agentAllowed:(projectId:string,agentId:string,jobId:string)=>boolean=()=>true){
 const store=new SourceSnapshotStore(root),grants=new Map<string,Grant>();
 function grant(runId:string,stepId:string,snapshot:ProjectSnapshot,base:string){verifyProjectReference(snapshot);const run=core.repository.readEntity?.('runs',runId),step=core.repository.readEntity?.('steps',stepId),job=run?core.repository.readEntity?.('jobs',run.jobId):undefined,source=step?job?.payload.steps[step.order]?.source:undefined;if(!run||run.projectId!==snapshot.projectId||!activeRun(run)||step?.runId!==runId||source?.provider!=='snapshot'||source.snapshot.checksum!==snapshot.checksum||source.snapshot.snapshotId!==snapshot.snapshotId)throw Error('Source grant Run boundary.');for(const [token,g] of grants)if(g.expires<Date.now())grants.delete(token);if(grants.size>=512)throw Error('Source grant capacity.');const url=new URL(base);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw Error('Source grant endpoint.');url.pathname=`/sources/agent/${runId}/${snapshot.snapshotId}/manifest`;const token=randomBytes(32).toString('hex');grants.set(token,{runId,stepId,projectId:snapshot.projectId,snapshotId:snapshot.snapshotId,checksum:snapshot.checksum,expires:Date.now()+300000,agentId:run.agentId});return{...snapshot,transfer:{...snapshot.transfer!,url:url.href,token}};}
 function revoke(stepId:string){for(const [token,g] of grants)if(g.stepId===stepId)grants.delete(token);}
 async function resolve(snapshot:ProjectSnapshot,projectId:string){verifyProjectReference(snapshot);if(snapshot.projectId!==projectId)throw Error('Source project mismatch.');const value=await store.completed(projectId,snapshot.snapshotId,snapshot.checksum),reference=projectReference(value);if(reference.proposalId!==snapshot.proposalId||reference.attempt!==snapshot.attempt||reference.baseRevision!==snapshot.baseRevision||reference.transfer!.fileCount!==snapshot.transfer!.fileCount||reference.transfer!.changedFileCount!==snapshot.transfer!.changedFileCount||reference.transfer!.totalBytes!==snapshot.transfer!.totalBytes)throw Error('Source reference mismatch.');return value;}
 async function handle(req:IncomingMessage,res:ServerResponse){const json=(status:number,value:unknown)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};try{
  if(req.headers.origin&&!origins.includes(req.headers.origin)){json(403,{error:'SOURCE_FORBIDDEN'});return;}if(req.headers.origin)res.setHeader('Access-Control-Allow-Origin',req.headers.origin);res.setHeader('Vary','Origin');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Access-Control-Expose-Headers','X-Upload-Offset,Content-Range,ETag');
  if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,HEAD,POST,PUT,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Authorization,X-Project-Id,Content-Type,X-Upload-Offset,X-Upload-Chunk-Checksum,Range,If-Match');res.writeHead(204).end();return;}
  const parts=(req.url??'').split('/'),token=(req.headers.authorization??'').replace(/^Bearer /,'');req.setTimeout(15000,()=>req.destroy());
  if(parts[2]==='agent'){
   const g=grants.get(token),run=g?core.repository.readEntity?.('runs',g.runId):undefined,step=g?core.repository.readEntity?.('steps',g.stepId):undefined;
   if(!g||g.expires<Date.now()||!run||!activeRun(run)||run.agentId!==g.agentId||step?.runId!==g.runId||step?.status!=='running'||!agentAllowed(g.projectId,g.agentId,run.jobId)||parts[3]!==g.runId||parts[4]!==g.snapshotId||req.method!=='GET'){json(403,{error:'SOURCE_GRANT_INVALID'});return;}
   const snapshot=await store.completed(g.projectId,g.snapshotId,g.checksum);
   if(parts[5]==='manifest'&&parts.length===6){json(200,snapshot);return;}
   if(parts[5]!=='blobs'||parts.length!==7){json(404,{error:'SOURCE_NOT_FOUND'});return;}const checksum=parts[6],file=snapshot.files.find(f=>f.checksum===checksum);if(!file){json(403,{error:'SOURCE_OUTSIDE_SCOPE'});return;}if(req.headers['if-match']!==`"${checksum}"`){json(412,{error:'SOURCE_PRECONDITION'});return;}const bytes=await store.blob(g.projectId,checksum,file.size!),range=String(req.headers.range??'');const match=/^bytes=(\d+)-(\d+)$/.exec(range);if(!match){json(416,{error:'SOURCE_RANGE_REQUIRED'});return;}const start=Number(match[1]),end=Number(match[2]);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||end>=bytes.length||end-start+1>limits.chunkBytes){json(416,{error:'SOURCE_RANGE_INVALID'});return;}res.writeHead(206,{'Content-Type':'application/octet-stream','Content-Range':`bytes ${start}-${end}/${bytes.length}`,'Content-Length':end-start+1,ETag:`"${checksum}"`});res.end(bytes.subarray(start,end+1));return;
  }
  const projectId=String(req.headers['x-project-id']??'');uuid(projectId);if(token.length>512||!equal(token,studioToken)){json(403,{error:'SOURCE_FORBIDDEN'});return;}authorize(req,projectId,'run');
  if(req.method==='POST'&&req.url==='/sources/manifests'){const chunks:Buffer[]=[];let n=0;for await(const chunk of req){n+=chunk.length;if(n>limits.manifestBytes){json(413,{error:'SOURCE_MANIFEST_LIMIT'});return;}chunks.push(Buffer.from(chunk));}const snapshot=JSON.parse(Buffer.concat(chunks).toString()) as ProjectSnapshot;if(snapshot.projectId!==projectId){json(403,{error:'SOURCE_PROJECT_MISMATCH'});return;}await store.begin(snapshot);json(201,{snapshotId:snapshot.snapshotId});return;}
  if(parts[2]==='uploads'&&parts.length===5){uuid(parts[3]);const checksum=parts[4];if(req.method==='HEAD'){const offset=await store.progress(projectId,parts[3],checksum);res.writeHead(200,{'X-Upload-Offset':offset}).end();return;}if(req.method==='PUT'){const raw=String(req.headers['x-upload-offset']??''),chunkHash=String(req.headers['x-upload-chunk-checksum']??'');if(!/^\d+$/.test(raw)||!/^[a-f0-9]{64}$/.test(chunkHash))throw Error('Invalid Source chunk request.');const result=await store.append(projectId,parts[3],checksum,Number(raw),req,chunkHash);res.writeHead(result.complete?201:202,{'X-Upload-Offset':result.offset}).end();return;}}
  if(req.method==='POST'&&parts[2]==='complete'&&parts.length===4){uuid(parts[3]);json(200,projectReference(await store.complete(projectId,parts[3])));return;}
  json(404,{error:'SOURCE_NOT_FOUND'});
 }catch(error){const message=error instanceof Error?error.message:'';json(error instanceof TeamAccessError?403:/busy|capacity/.test(message)?503:/offset conflict|snapshot conflict/.test(message)?409:400,{error:'SOURCE_TRANSFER_REJECTED'});}}
 return{store,grant,revoke,resolve,handle};
}
