import {snapshotHasSecret} from '../src/features/ai/snapshot-content-policy.ts';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {ArtifactUploads} from './artifact-uploads.ts';
import type {StoredArtifact} from './artifact-store.ts';
import type {SnapshotFile} from '../src/features/ai/snapshot.ts';
import {verifyProjectManifest,projectManifestRecord,type ProjectSnapshot} from '../src/features/ai/project-snapshot.ts';
import {projectSnapshotLimits as limits,binaryText} from '../src/features/ai/snapshot-bytes.ts';
import {uuid} from '../src/features/ai/security.ts';
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const digestId=(checksum:string)=>checksum.slice(0,8)+'-'+checksum.slice(8,12)+'-'+checksum.slice(12,16)+'-'+checksum.slice(16,20)+'-'+checksum.slice(20,32);
/** Content addressed within a project. Run-scoped retrieval grants belong to the
 * gateway; a checksum alone is never authorization to fetch Source. */
export class SourceSnapshotStore {
 readonly root:string;private uploads:ArtifactUploads;private publishing=false;
 constructor(root:string){this.root=path.resolve(root);this.uploads=new ArtifactUploads(path.join(this.root,'uploads'),{put:this.putBlob.bind(this)});}
 private async safe(file:string){if(!file.startsWith(this.root+path.sep))throw Error('Source path boundary.');for(let cursor=file;;cursor=path.dirname(cursor)){try{if((await fs.lstat(cursor)).isSymbolicLink())throw Error('Source links forbidden.');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}if(path.dirname(cursor)===cursor)break;}await fs.mkdir(path.dirname(file),{recursive:true});}
 private manifestFile(projectId:string,snapshotId:string){uuid(projectId);uuid(snapshotId);return path.join(this.root,'manifests',projectId,snapshotId+'.json');}
 private blobFile(projectId:string,checksum:string){uuid(projectId);if(!/^[a-f0-9]{64}$/.test(checksum))throw Error('Invalid Source checksum.');return path.join(this.root,'blobs',projectId,checksum);}
 private async atomic(file:string,bytes:Uint8Array){await this.safe(file);const temp=file+'.'+randomUUID()+'.partial';try{const handle=await fs.open(temp,'wx',0o600);try{await handle.writeFile(bytes);await handle.sync();}finally{await handle.close();}await fs.rename(temp,file);}finally{await fs.unlink(temp).catch(e=>{if(e.code!=='ENOENT')throw e;});}}
 private async readBounded(file:string,max:number){await this.safe(file);const handle=await fs.open(file,'r');try{const stat=await handle.stat();if(!stat.isFile()||stat.size>max)throw Error('Source file limit.');const bytes=Buffer.alloc(stat.size+1);let n=0;while(n<bytes.length){const read=await handle.read(bytes,n,bytes.length-n,n);if(!read.bytesRead)break;n+=read.bytesRead;}if(n!==stat.size)throw Error('Source changed while reading.');return bytes.subarray(0,n);}finally{await handle.close();}}
 async manifest(projectId:string,snapshotId:string){const value=JSON.parse((await this.readBounded(this.manifestFile(projectId,snapshotId),limits.manifestBytes)).toString('utf8')) as ProjectSnapshot;await verifyProjectManifest(value);if(value.projectId!==projectId||value.snapshotId!==snapshotId)throw Error('Source manifest identity mismatch.');return value;}
 async begin(snapshot:ProjectSnapshot){await verifyProjectManifest(snapshot);if(snapshot.files.some(f=>f.content!==''))throw Error('Source manifest must exclude bodies.');const file=this.manifestFile(snapshot.projectId,snapshot.snapshotId);try{const prior=await this.manifest(snapshot.projectId,snapshot.snapshotId);if(JSON.stringify(prior)!==JSON.stringify(projectManifestRecord(snapshot)))throw Error('Source snapshot conflict.');return prior;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
  if(this.publishing)throw Error('Source store busy.');this.publishing=true;try{try{const prior=await this.manifest(snapshot.projectId,snapshot.snapshotId);if(JSON.stringify(prior)!==JSON.stringify(projectManifestRecord(snapshot)))throw Error('Source snapshot conflict.');return prior;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}const directory=path.dirname(file);await this.safe(file);if((await fs.readdir(directory)).filter(n=>n.endsWith('.json')).length>=128)throw Error('Source snapshot retention capacity.');await this.atomic(file,Buffer.from(JSON.stringify(projectManifestRecord(snapshot))));}finally{this.publishing=false;}return snapshot;
 }
 private meta(snapshot:ProjectSnapshot,file:SnapshotFile):StoredArtifact {return{id:digestId(file.checksum),runId:snapshot.snapshotId,runStepId:snapshot.snapshotId,projectId:snapshot.projectId,type:'trace',name:file.checksum+'.source',mimeType:'application/zip',size:file.size!,checksum:file.checksum,createdAt:new Date().toISOString(),location:''};}
 private async scopedFile(projectId:string,snapshotId:string,checksum:string){const snapshot=await this.manifest(projectId,snapshotId),file=snapshot.files.find(f=>f.checksum===checksum);if(!file)throw Error('Source file is outside manifest.');if(snapshot.files.some(f=>f.checksum===checksum&&f.size!==file.size))throw Error('Source checksum size conflict.');return{snapshot,file};}
 async blob(projectId:string,checksum:string,size:number){const bytes=await this.readBounded(this.blobFile(projectId,checksum),limits.fileBytes);if(bytes.length!==size||hash(bytes)!==checksum)throw Error('Stored Source integrity failure.');return bytes;}
 private checkContent(snapshot:ProjectSnapshot,checksum:string,bytes:Uint8Array){const raw=binaryText(bytes),decoded=new TextDecoder().decode(bytes),paths=snapshot.files.filter(f=>f.checksum===checksum).map(f=>f.path);if(!paths.length||paths.some(p=>snapshotHasSecret(p,raw)||snapshotHasSecret(p,decoded)))throw Error('Source secret pattern detected.');}
 async progress(projectId:string,snapshotId:string,checksum:string){const {snapshot,file}=await this.scopedFile(projectId,snapshotId,checksum);try{this.checkContent(snapshot,checksum,await this.blob(projectId,checksum,file.size!));return file.size!;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}return this.uploads.progress(this.meta(snapshot,file));}
 async append(projectId:string,snapshotId:string,checksum:string,start:number,body:AsyncIterable<Uint8Array>,chunkChecksum:string){const {snapshot,file}=await this.scopedFile(projectId,snapshotId,checksum);if(file.size===0){if(start!==0||chunkChecksum!==hash(new Uint8Array()))throw Error('Invalid empty Source.');for await(const chunk of body)if(chunk.length)throw Error('Nonempty Source body.');await this.putBlob(this.meta(snapshot,file),(async function*(){})());return{offset:0,complete:true};}
  const bounded=(async function*(){let n=0;for await(const chunk of body){n+=chunk.length;if(n>limits.chunkBytes)throw Error('Source chunk limit.');yield chunk;}})();const result=await this.uploads.append(this.meta(snapshot,file),start,bounded,chunkChecksum);if(result.meta)await this.uploads.finish(result.meta);return{offset:result.offset,complete:!!result.meta};
 }
 private async putBlob(meta:StoredArtifact,body:AsyncIterable<Uint8Array>){const chunks:Buffer[]=[];let size=0;for await(const chunk of body){size+=chunk.length;if(size>limits.fileBytes||size>meta.size)throw Error('Source size exceeded.');chunks.push(Buffer.from(chunk));}const bytes=Buffer.concat(chunks);if(bytes.length!==meta.size||hash(bytes)!==meta.checksum)throw Error('Source checksum mismatch.');this.checkContent(await this.manifest(meta.projectId,meta.runId),meta.checksum,bytes);const file=this.blobFile(meta.projectId,meta.checksum);try{await this.blob(meta.projectId,meta.checksum,meta.size);return meta;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
  if(this.publishing)throw Error('Source store busy.');this.publishing=true;try{let total=0;const base=path.join(this.root,'blobs');await this.safe(file);for(const project of await fs.readdir(base,{withFileTypes:true})){if(!project.isDirectory())throw Error('Invalid Source project directory.');uuid(project.name);const dir=path.join(base,project.name);for(const entry of await fs.readdir(dir)){if(!/^[a-f0-9]{64}(?:\.[0-9a-f-]{36}\.partial)?$/.test(entry))throw Error('Unowned Source store entry.');const candidate=path.join(dir,entry);await this.safe(candidate);total+=(await fs.stat(candidate)).size;}}if(total+bytes.length>512*1024*1024)throw Error('Source store capacity.');await this.atomic(file,bytes);}finally{this.publishing=false;}return meta;
 }
 async complete(projectId:string,snapshotId:string){const snapshot=await this.manifest(projectId,snapshotId);for(const f of snapshot.files)this.checkContent(snapshot,f.checksum,await this.blob(projectId,f.checksum,f.size!));const file=this.manifestFile(projectId,snapshotId)+'.complete';await this.atomic(file,Buffer.from(snapshot.checksum));return snapshot;}
 async completed(projectId:string,snapshotId:string,checksum:string){const snapshot=await this.manifest(projectId,snapshotId),marker=await this.readBounded(this.manifestFile(projectId,snapshotId)+'.complete',64);if(marker.toString()!==checksum||snapshot.checksum!==checksum)throw Error('Source snapshot is not complete.');for(const f of snapshot.files)this.checkContent(snapshot,f.checksum,await this.blob(projectId,f.checksum,f.size!));return snapshot;}
}
