import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {createDecipheriv} from 'node:crypto';
import {STORAGE_VERSION,storageKey} from './storage.ts';import {snapshotBackupFiles,noSnapshotLinks,assertSnapshotReferences} from './snapshot-backup.ts';
import {LocalArtifactStore} from './artifact-store.ts';import type {Job,Artifact} from '../src/features/core/domain.ts';
export interface StorageDiagnosis{ok:boolean;readOnly:true;code:'READY_FOR_OFFLINE_BACKUP'|'DATABASE_MISSING'|'KEY_MISSING'|'KEY_INVALID'|'SCHEMA_NEWER'|'STORAGE_BUSY_OR_INVALID'|'SOURCE_INVALID'|'EVIDENCE_INVALID';schema?:number;units?:number;snapshots?:number;sourceBytes?:number;incompleteSnapshots?:number}
/** No migration, key generation, repair or provider request is made by diagnosis. */
export async function diagnoseStorage(database:string,artifactRoot:string):Promise<StorageDiagnosis>{
 const result:StorageDiagnosis={ok:false,readOnly:true,code:'DATABASE_MISSING'};if(!fs.existsSync(database))return result;
 if(!fs.existsSync(database+'.key'))return{...result,code:'KEY_MISSING'};let key:Buffer|undefined,db:DatabaseSync|undefined;const jobs:Job[]=[],artifacts:Artifact[]=[];
 try{noSnapshotLinks(database);noSnapshotLinks(database+'.key');try{key=storageKey(database,true);}catch{return{...result,code:'KEY_INVALID'};}db=new DatabaseSync(database,{readOnly:true,timeout:100});
  if(db.prepare('PRAGMA integrity_check').get()?.integrity_check!=='ok')throw Error('Integrity');result.schema=Number(db.prepare('PRAGMA user_version').get()?.user_version);if(result.schema!>STORAGE_VERSION)return{...result,code:'SCHEMA_NEWER'};
  let count=0;for(const row of db.prepare('SELECT name,payload FROM units').iterate()){const bytes=Buffer.from(row.payload as Uint8Array);if(bytes.length<28)throw Error('Payload');const cipher=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));cipher.setAAD(Buffer.from('tastestudio-core-unit-v1'));cipher.setAuthTag(bytes.subarray(-16));const value=JSON.parse(Buffer.concat([cipher.update(bytes.subarray(12,-16)),cipher.final()]).toString('utf8'));if(String(row.name).startsWith('core-row:jobs:'))jobs.push(value);if(String(row.name).startsWith('core-row:artifacts:'))artifacts.push(value);if(row.name==='core'){jobs.push(...(value.state?.jobs??[]));artifacts.push(...(value.state?.artifacts??[]));}count++;}result.units=count;
 }catch{return{...result,code:'STORAGE_BUSY_OR_INVALID'};}finally{db?.close();key?.fill(0);}
 try{const evidence=new LocalArtifactStore(artifactRoot);for(const a of artifacts){if(a.deletedAt||!a.location.startsWith('/artifacts/'))continue;const base=path.join(artifactRoot,a.runId,a.id);if(!fs.existsSync(base)||!fs.existsSync(base+'.json'))return{...result,code:'EVIDENCE_INVALID'};const value=await evidence.get(a.runId,a.id);if(value.meta.checksum!==a.checksum||value.meta.size!==a.size)return{...result,code:'EVIDENCE_INVALID'};}}catch{return{...result,code:'EVIDENCE_INVALID'};}
 try{const sources=await snapshotBackupFiles(artifactRoot+'-sources');assertSnapshotReferences(jobs,sources.snapshots);return{...result,ok:true,code:'READY_FOR_OFFLINE_BACKUP',snapshots:sources.snapshots.size,sourceBytes:sources.bytes,incompleteSnapshots:sources.incomplete};}catch{return{...result,code:'SOURCE_INVALID'};}
}
