import {randomUUID} from 'node:crypto';
import type {CoreStore} from './storage.ts';import type {RunHistory} from './run-history.ts';import type {HistoryStore} from './history.ts';import type {CoreService} from '../src/features/core/service.ts';import type {Project} from '../src/features/projects/types/project.ts';import type {FixAttempt} from '../src/features/ai/fix-service.ts';import type {OperationsReport,RunLink} from '../src/features/core/team-operations.ts';import {repository} from '../src/features/issues/security.ts';
export class TeamOperations {
 private memory=new Map<string,RunLink[]>();private store?:CoreStore;private service:CoreService;private records:RunHistory;private history:HistoryStore;private project:(id:string)=>Project|undefined;private now:()=>number;
 constructor(service:CoreService,records:RunHistory,history:HistoryStore,project:(id:string)=>Project|undefined,store?:CoreStore,now=Date.now){this.service=service;this.records=records;this.history=history;this.project=project;this.store=store;this.now=now;}
 links(projectId:string){return structuredClone(this.store?.get<RunLink[]>('operations-links:'+projectId)??this.memory.get(projectId)??[]);}
 link(projectId:string,input:unknown,createdBy?:string){if(!input||typeof input!=='object'||Object.keys(input).some(key=>!['runId','kind','url'].includes(key)))throw Error('Invalid Run link.');const row=input as {runId:string;kind:RunLink['kind'];url:string};if(!['issue','pull-request'].includes(row.kind)||typeof row.url!=='string'||row.url.length>512)throw Error('Invalid Run link.');const project=this.project(projectId);if(!project)throw Error('Run link Project boundary.');const repo=repository(project.repositoryUrl),url=new URL(row.url);const expected='/'+repo+'/'+(row.kind==='issue'?'issues':'pull')+'/';if(url.origin!=='https://github.com'||url.username||url.password||url.search||url.hash||!url.pathname.startsWith(expected)||!/^[1-9]\d{0,8}$/.test(url.pathname.slice(expected.length)))throw Error('Run link repository boundary.');const detail=this.records.request(projectId,'detail',row.runId) as ReturnType<CoreService['snapshot']>,run=detail.runs[0];if(!run||run.id!==row.runId)throw Error('Run link Project boundary.');const links=this.links(projectId),existing=links.find(link=>link.runId===row.runId&&link.url===url.href);if(existing)return existing;if(links.length>=1000)throw Error('Run link limit reached.');const link:RunLink={id:randomUUID(),projectId,runId:run.id,kind:row.kind,url:url.href,revision:run.revision?structuredClone(run.revision):undefined,createdAt:new Date(this.now()).toISOString(),...(createdBy?{createdBy}:{})};const next=[...links,link];this.store?.put('operations-links:'+projectId,next);this.memory.set(projectId,next);return link;}
 report(projectId:string,allowedAgent?:(id:string)=>boolean):OperationsReport {const to=new Date(this.now()).toISOString(),from=new Date(this.now()-7*86400000).toISOString();const stats=this.records.request(projectId,'statistics',{from,to}) as Pick<OperationsReport,'sampleCount'|'total'|'limited'|'passed'|'failed'|'passRate'|'meanElapsedMs'|'days'>;const days=Array.from({length:8},(_,i)=>{const day=new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10);return stats.days.find(d=>d.day===day)??{day,total:0,passed:0,failed:0};});
 const snapshot=this.service.snapshot(projectId,100),entries=this.history.page(projectId,'attempt',{limit:25}).items;const approvals=entries.flatMap(entry=>{const value=this.history.get(projectId,'attempt',entry.id)?.value as FixAttempt|undefined;return value?.approval?[{id:value.id,proposalId:value.proposalId,runId:value.runId,status:value.status,timestamp:value.approval.timestamp,files:[...value.approval.files]}]:[];});return{from,to,...stats,days,agents:snapshot.agents.filter(agent=>!allowedAgent||allowedAgent(agent.id)).map(({id,name,status})=>({id,name,status})),queue:{queued:snapshot.jobs.filter(job=>job.status==='queued').length,active:snapshot.runs.filter(run=>['pending','running'].includes(run.status)).length},agentIssues:snapshot.runs.filter(r=>r.executionReport&&!['PASSED','TEST_FAILED','CANCELLED','TIMEOUT'].includes(r.executionReport.classification)).slice(-100).map(r=>({runId:r.id,agentId:r.agentId,classification:r.executionReport!.classification,timestamp:r.finishedAt??r.createdAt})),approvals,links:this.links(projectId).slice(-100).reverse()};}
}
