import {randomUUID} from 'node:crypto';
import type {CoreStore} from './storage.ts';import type {RunHistory} from './run-history.ts';import type {HistoryStore} from './history.ts';import type {CoreService} from '../src/features/core/service.ts';import type {Project} from '../src/features/projects/types/project.ts';import type {FixAttempt} from '../src/features/ai/fix-service.ts';import type {OperationsReport,RunLink} from '../src/features/core/team-operations.ts';import {repository} from '../src/features/issues/security.ts';
export class TeamOperations {
 private memory=new Map<string,RunLink[]>();private store?:CoreStore;private service:CoreService;private records:RunHistory;private history:HistoryStore;private project:(id:string)=>Project|undefined;private now:()=>number;
 constructor(service:CoreService,records:RunHistory,history:HistoryStore,project:(id:string)=>Project|undefined,store?:CoreStore,now=Date.now){this.service=service;this.records=records;this.history=history;this.project=project;this.store=store;this.now=now;}
 links(projectId:string){return structuredClone(this.store?.get<RunLink[]>('operations-links:'+projectId)??this.memory.get(projectId)??[]);}
 link(projectId:string,input:unknown,createdBy?:string){if(!input||typeof input!=='object'||Object.keys(input).some(key=>!['runId','kind','url'].includes(key)))throw Error('Invalid Run link.');const row=input as {runId:string;kind:RunLink['kind'];url:string};if(!['issue','pull-request'].includes(row.kind)||typeof row.url!=='string'||row.url.length>512)throw Error('Invalid Run link.');const project=this.project(projectId);if(!project)throw Error('Run link Project boundary.');const repo=repository(project.repositoryUrl),url=new URL(row.url);const expected='/'+repo+'/'+(row.kind==='issue'?'issues':'pull')+'/';if(url.origin!=='https://github.com'||url.username||url.password||url.search||url.hash||!url.pathname.startsWith(expected)||!/^[1-9]\d{0,8}$/.test(url.pathname.slice(expected.length)))throw Error('Run link repository boundary.');const detail=this.records.request(projectId,'detail',row.runId) as ReturnType<CoreService['snapshot']>,run=detail.runs[0];if(!run||run.id!==row.runId)throw Error('Run link Project boundary.');const links=this.links(projectId),existing=links.find(link=>link.runId===row.runId&&link.url===url.href);if(existing)return existing;if(links.length>=1000)throw Error('Run link limit reached.');const link:RunLink={id:randomUUID(),projectId,runId:run.id,kind:row.kind,url:url.href,revision:run.revision?structuredClone(run.revision):undefined,createdAt:new Date(this.now()).toISOString(),...(createdBy?{createdBy}:{})};const next=[...links,link];this.store?.put('operations-links:'+projectId,next);this.memory.set(projectId,next);return link;}
 report(projectId:string,allowedAgent?:(id:string)=>boolean):OperationsReport {const to=new Date(this.now()).toISOString(),from=new Date(this.now()-7*86400000).toISOString();type Row={id:string;status:string;createdAt:string;finishedAt:string|null};const rows:Row[]=[];let after:string|undefined,total=0;for(let page=0;page<10;page++){const result=this.records.request(projectId,'page',{limit:100,from,to,...(after?{after}:{})}) as {items:Row[];total:number;next:string|null};rows.push(...result.items);total=result.total;if(!result.next)break;after=result.next;}
 const days=Array.from({length:8},(_,i)=>({day:new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10),total:0,passed:0,failed:0}));let passed=0,failed=0;const elapsed:number[]=[];for(const row of rows){const day=days.find(day=>day.day===row.createdAt.slice(0,10));if(day){day.total++;if(row.status==='passed')day.passed++;if(['failed','timeout'].includes(row.status))day.failed++;}if(row.status==='passed')passed++;if(['failed','timeout'].includes(row.status))failed++;if(row.finishedAt){const value=Date.parse(row.finishedAt)-Date.parse(row.createdAt);if(Number.isFinite(value)&&value>=0)elapsed.push(value);}}
 const snapshot=this.service.snapshot(projectId),entries=this.history.page(projectId,'attempt',{limit:25}).items;const approvals=entries.flatMap(entry=>{const value=this.history.get(projectId,'attempt',entry.id)?.value as FixAttempt|undefined;return value?.approval?[{id:value.id,proposalId:value.proposalId,runId:value.runId,status:value.status,timestamp:value.approval.timestamp,files:[...value.approval.files]}]:[];});return{from,to,sampleCount:rows.length,total,limited:rows.length<total,passed,failed,passRate:passed+failed?passed/(passed+failed):null,meanElapsedMs:elapsed.length?elapsed.reduce((a,b)=>a+b,0)/elapsed.length:null,days,agents:snapshot.agents.filter(agent=>!allowedAgent||allowedAgent(agent.id)).map(({id,name,status})=>({id,name,status})),queue:{queued:snapshot.jobs.filter(job=>job.status==='queued').length,active:snapshot.runs.filter(run=>['pending','running'].includes(run.status)).length},approvals,links:this.links(projectId).slice(-100).reverse()};}
}
