/** Resume from the successful actual Graph fixture; reuse its Source and Agent. */
import fs from 'node:fs';import path from 'node:path';import {spawn,type ChildProcess} from 'node:child_process';import {once} from 'node:events';import {randomUUID,createHash} from 'node:crypto';import assert from 'node:assert/strict';import {WebSocket} from 'ws';
import {startCoreServer} from './server.ts';
import type {GraphOverview} from '../src/features/orchestration/execution.ts';
const root=path.resolve(process.env.GRAPH_CASE!),record=JSON.parse(fs.readFileSync(path.join(root,'RESULT.json'),'utf8'));assert.equal(record.status,'PASS');
const binary=record.agentBinary as string;assert.equal(createHash('sha256').update(fs.readFileSync(binary)).digest('hex'),record.agentBinaryChecksum);
const token=randomUUID(),core=await startCoreServer({port:0,agentToken:token,studioToken:token,storagePath:path.join(root,'core.sqlite'),artifactRoot:path.join(root,'artifacts')});
const project=core.store!.get<[string,{id:string;name:string}][]>('projects')![0][1],baseline=core.service.snapshot(project.id).jobs.length;
const wait=async(predicate:()=>boolean)=>{const end=Date.now()+30000;while(!predicate()){if(Date.now()>end)throw Error('Actual scheduled graph timeout');await new Promise(r=>setTimeout(r,30));}};
const replies=new Map<string,{error?:string;value:unknown}>();let agent:ChildProcess|undefined,ws:WebSocket|undefined,errors='';const checks:string[]=[];
async function rpc<T>(method:string,...args:unknown[]){const requestId=randomUUID();ws!.send(JSON.stringify({type:'rpc',protocolVersion:1,requestId,method,args}));await wait(()=>replies.has(requestId));const r=replies.get(requestId)!;if(r.error)throw Error(r.error);return r.value as T;}
try{
 ws=new WebSocket(`ws://127.0.0.1:${core.port}/studio`);let subscribed=false;ws.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='snapshot')subscribed=true;if(m.type==='reply')replies.set(m.requestId,m);});await once(ws,'open');ws.send(JSON.stringify({type:'subscribe',protocolVersion:1,token,project}));await wait(()=>subscribed);
 const config=path.join(root,'agent.json');fs.writeFileSync(config,JSON.stringify({endpoint:`ws://127.0.0.1:${core.port}/agent`,name:'Actual graph Agent',workspaceRoot:path.join(root,'agent'),heartbeatMs:200,reconnectMaxMs:500,logLevel:'error'}));agent=spawn(binary,['--config',config],{windowsHide:true,env:{...process.env,TASTEDEV_AGENT_TOKEN:token},stdio:['ignore','ignore','pipe']});agent.stderr!.on('data',b=>errors+=b.toString());await wait(()=>core.service.listAgents().some(a=>a.status==='idle'));
 const definition=core.graphExecution.overview(project.id).definition!;assert.equal(definition.source?.checksum,record.source.checksum);const input={name:'Controlled one-shot graph',testName:'Graph root build',enabled:false,trigger:{type:'time',at:new Date(Date.now()+4000).toISOString()},timezone:'UTC',graph:{revision:definition.revision,checksum:definition.checksum,entryNodeId:'build'}};
 const saved=await rpc<ReturnType<typeof core.scheduler.list>>('scheduler','save',input),schedule=saved.schedules.find(s=>s.name===input.name)!;await assert.rejects(rpc('scheduler','run',schedule.id,randomUUID()));assert.equal(core.service.snapshot(project.id).jobs.length,baseline);checks.push('Schedule saved disabled; no automatic grant or execution');
 await rpc('scheduler','enable',schedule.id,true);await wait(()=>core.scheduler.list(project.id).history.some(h=>h.scheduleId===schedule.id&&h.graphExecutionId));const h=core.scheduler.list(project.id).history.find(h=>h.scheduleId===schedule.id)!;await wait(()=>core.graphExecution.overview(project.id).executions.find(e=>e.id===h.graphExecutionId)?.activations.some(a=>a.status==='approval')===true);
 assert.equal(core.service.snapshot(project.id).jobs.length,baseline+2);checks.push('Existing one-time Scheduler started the pinned graph on actual Rust Agent; deployment still waits for approval');
 const e=core.graphExecution.overview(project.id).executions.find(e=>e.id===h.graphExecutionId)!,a=e.activations.find(a=>a.status==='approval')!;await rpc<GraphOverview>('graph','approve',{executionId:e.id,activationId:a.id,revision:e.revision,checksum:e.checksum});await wait(()=>core.service.snapshot(project.id).steps.some(s=>s.name==='wait'&&s.status==='running'));await rpc('graph','cancel',{executionId:e.id});await wait(()=>core.graphExecution.overview(project.id).executions.find(x=>x.id===e.id)?.status==='cancelled');core.scheduler.refresh();assert.equal(core.scheduler.list(project.id).history.find(x=>x.id===h.id)?.status,'cancelled');checks.push('Per-activation approval retained; Agent cancellation and Scheduler history agree');
 const newRuns=core.service.snapshot(project.id).runs.filter(r=>!record.runs.some((old:{id:string})=>old.id===r.id));for(const run of newRuns){assert.equal(run.revision?.snapshotId,record.source.snapshotId);assert.equal(run.revision?.commit,record.source.checksum);}assert.equal(errors,'');checks.push('Previously uploaded Source reused with the same Snapshot checksum; Agent stderr 0');
 fs.writeFileSync(path.join(root,'SCHEDULE-RESULT.json'),JSON.stringify({status:'PASS',checks,schedule,history:core.scheduler.list(project.id).history.filter(x=>x.scheduleId===schedule.id),execution:core.graphExecution.overview(project.id).executions.find(x=>x.id===e.id),runs:newRuns},null,2));console.log(JSON.stringify({status:'PASS',checks}));
}catch(error){fs.writeFileSync(path.join(root,'SCHEDULE-FAILURE.json'),JSON.stringify({error:String(error),checks,errors,scheduler:core.scheduler.list(project.id),graph:core.graphExecution.overview(project.id)},null,2));throw error;}finally{ws?.terminate();if(agent&&agent.exitCode===null){agent.kill();await once(agent,'exit');}await core.close();}
