import { WebSocket, WebSocketServer } from 'ws';
import { spawn, type ChildProcess } from 'node:child_process';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { startCoreServer } from './server.ts';
// 기본 증거 폴더는 이 파일 위치 기준(TASTEDEV/resources). 작업 폴더 기준이면 transport 에서 돌릴 때 sources/resources 가 생겼다.
const evidence=path.resolve(process.env.AGENT_EVIDENCE??path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../../resources/verification/dev-01/tasks/tastedev-studio/step-8-20260930'));
const root=path.join(evidence,'disposable-'+Date.now());fs.mkdirSync(root,{recursive:true});
const token=randomUUID();const core=await startCoreServer({port:0,agentToken:token,studioToken:token,heartbeatTimeoutMs:2500});
const proxy=new WebSocketServer({port:0,host:'127.0.0.1'});await once(proxy,'listening');const addr=proxy.address();if(!addr||typeof addr==='string')throw Error('Invalid proxy address');
let down:WebSocket|undefined;const agentMessages:Record<string,unknown>[]=[];const requests:Record<string,unknown>[]=[];
let suppressAckRun:string|undefined;let droppedAcks=0;let connectionCount=0;
proxy.on('connection',socket=>{connectionCount++;down=socket;const upstream=new WebSocket(`ws://127.0.0.1:${core.port}/agent`);const buffered:string[]=[];socket.on('message',raw=>{const text=raw.toString();const m=JSON.parse(text);if(m.type!=='register')agentMessages.push(m);if(upstream.readyState===WebSocket.OPEN)upstream.send(text);else buffered.push(text);});upstream.on('open',()=>{for(const text of buffered)upstream.send(text);});upstream.on('message',raw=>{const text=raw.toString();const m=JSON.parse(text);if(m.type==='execute')requests.push(m);if(m.type==='ack'&&m.runId===suppressAckRun&&droppedAcks===0){droppedAcks++;return;}if(socket.readyState===WebSocket.OPEN)socket.send(text);});for(const s of [socket,upstream])s.on('error',()=>{});socket.on('close',()=>upstream.terminate());upstream.on('close',()=>socket.terminate());});
const config=path.join(root,'config.json');fs.writeFileSync(config,JSON.stringify({endpoint:`ws://127.0.0.1:${addr.port}/agent`,name:'Actual Rust E2E',workspaceRoot:path.join(root,'workspace'),heartbeatMs:300,reconnectMaxMs:1000,logLevel:'error'}));
const binary=path.resolve(process.env.AGENT_BINARY??'agent/target/release/tastedev-agent.exe');
let child:ChildProcess|undefined;let agentError='';const start=()=>{child=spawn(binary,['--config',config],{env:{...process.env,TASTEDEV_AGENT_TOKEN:token},windowsHide:true,stdio:['ignore','pipe','pipe']});child.stderr?.on('data',d=>agentError+=d.toString());child.on('error',e=>agentError+=e.message);};
const wait=async(fn:()=>boolean,timeout=30000)=>{const until=Date.now()+timeout;while(Date.now()<until){if(fn())return;await new Promise(r=>setTimeout(r,30));}throw Error('Timed out: '+agentError);};
const checks:string[]=[];const studio=new WebSocket(`ws://127.0.0.1:${core.port}/studio`);studio.on('error',()=>{});await once(studio,'open');const replies=new Map<string,Record<string,unknown>>();studio.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='reply')replies.set(m.requestId,m);});
const project={id:'actual-agent-project',name:'Actual Agent E2E',description:'',workspacePath:null,browserFolder:true,repositoryUrl:null,defaultBranch:null,framework:null,runtime:null,packageManager:null,projectType:null,gitEnabled:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastOpenedAt:null};studio.send(JSON.stringify({protocolVersion:1,type:'subscribe',token,project}));
async function rpc(method:string,args:unknown[]){const requestId=randomUUID();studio.send(JSON.stringify({type:'rpc',protocolVersion:1,requestId,method,args}));await wait(()=>replies.has(requestId));const r=replies.get(requestId)!;if(r.error)throw Error(String(r.error));return r.value;}
async function job(name:string,script:string,timeoutMs=5000,executable=process.execPath,env:Record<string,string>={}){await wait(()=>core.service.listAgents().some(a=>a.status==='idle'));const job=await core.service.createJob(project.id,{name,requirements:{runtimes:{node:'>=24'}},payload:{task:name,steps:[{name,executable,args:['-e',script],cwd:'.',timeoutMs,env}]}});await rpc('dispatch',[]);const run=core.service.snapshot(project.id).runs.find(r=>r.jobId===job.id)!;return {job,run};}
async function done(id:string,status:string){await wait(()=>core.service.snapshot(project.id).runs.find(r=>r.id===id)?.status===status);await wait(()=>core.service.listAgents()[0]?.status==='idle');await new Promise(r=>setTimeout(r,80));}
function dead(pid:number){try{process.kill(pid,0);return false;}catch{return true;}}
const descendantScript="const p=require('child_process').spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'});console.log('grandchild:'+p.pid);setInterval(()=>{},1000)";
const treeScript="const cp=require('child_process').spawn(process.execPath,['-e',"+JSON.stringify(descendantScript)+"],{stdio:['ignore','pipe','ignore']});cp.stdout.pipe(process.stdout);console.log('child:'+cp.pid);setInterval(()=>{},1000)";
const grandchildren:number[]=[];
async function childPid(id:string){await wait(()=>core.logs.read([id])[id].some(c=>/grandchild:\d+/.test(c.text)));grandchildren.push(Number(core.logs.read([id])[id].map(c=>c.text).join('').match(/grandchild:(\d+)/)![1]));return Number(core.logs.read([id])[id].map(c=>c.text).join('').match(/child:(\d+)/)![1]);}
try{
 start();await wait(()=>core.service.listAgents()[0]?.status==='idle');const identity=core.service.listAgents()[0].id;assert(core.service.listAgents()[0].capabilities.memoryMiB>0);assert(core.service.listAgents()[0].capabilities.runtimes.node);assert(core.service.listAgents()[0].capabilities.runtimes.git);checks.push('actual binary registered, real hardware/Node/Git capability, idle');
 const success=await job('Success',"console.log('first-live');console.error('stderr-live');if(process.env.TASTEDEV_AGENT_TOKEN)process.exit(9);setTimeout(()=>console.log('finished'),350)");suppressAckRun=success.run.id;const initialConnections=connectionCount;await wait(()=>core.logs.read([success.run.id])[success.run.id].length>0);assert.equal(core.service.snapshot(project.id).runs.find(r=>r.id===success.run.id)!.status,'running');await done(success.run.id,'passed');assert(core.logs.read([success.run.id])[success.run.id].some(c=>c.stream==='stderr'));checks.push('queue/match/assign/accept, live stdout+stderr before completion, secret environment excluded, exit0/passed/idle');
 await wait(()=>agentMessages.filter(m=>m.type==='result'&&m.runId===success.run.id).length>=2);assert.equal(droppedAcks,1);assert.equal(connectionCount,initialConnections);checks.push('lost ACK retried on same socket, duplicate result preserved');
 const large=await job('Bounded masked output',String.raw`process.stdout.write(('prefix:'+process.env.DUMMY_SECRET+'한글\n').repeat(150000))`,20000,process.execPath,{DUMMY_SECRET:'dummy-secret-boundary-12345'});await done(large.run.id,'passed');const largeReport=core.service.snapshot(project.id).runs.find(r=>r.id===large.run.id)!.executionReport!;assert(largeReport.outputSummary!.partial);assert(largeReport.outputSummary!.forwardedBytes<=1048576);assert(!core.logs.read([large.run.id])[large.run.id].some(c=>c.text.includes('dummy-secret-boundary-12345')));checks.push('large UTF8 output bounded, partial evidence declared, Dummy secret masked');
 const failure=await job('Nonzero','process.exit(7)');await done(failure.run.id,'failed');assert.equal(core.service.snapshot(project.id).runs.find(r=>r.id===failure.run.id)!.exitCode,7);checks.push('nonzero exit7 -> failed');
 const invalid=await job('Invalid executable','',5000,'tastedev-missing-binary');await done(invalid.run.id,'failed');checks.push('invalid executable -> failed, Agent recovered');
 const timeout=await job('Timeout tree',treeScript,450);const timeoutPid=await childPid(timeout.run.id);await done(timeout.run.id,'timeout');await wait(()=>dead(timeoutPid));checks.push('timeout terminates child tree, no orphan, idle');
 const cancel=await job('Cancel tree',treeScript,10000);const cancelPid=await childPid(cancel.run.id);await rpc('cancelJob',[cancel.job.id]);await done(cancel.run.id,'cancelled');await wait(()=>dead(cancelPid));checks.push('Studio/Core cancel -> child tree killed, cancelled, idle');
 const replay=requests.find(r=>r.runId===success.run.id)!;down!.send(JSON.stringify(replay));await wait(()=>agentMessages.some(m=>m.type==='rejected'&&m.runId===success.run.id));assert.equal(core.service.snapshot(project.id).runs.filter(r=>r.id===success.run.id).length,1);checks.push('actual Agent rejects duplicate completed Run ID');
 down!.send('{malformed');down!.send(JSON.stringify({type:'execute',protocolVersion:1,runId:'invalid'}));await new Promise(r=>setTimeout(r,100));assert.equal(child!.exitCode,null);checks.push('malformed message does not crash binary');
 const disconnect=await job('Disconnect tree',treeScript,15000);const disconnectPid=await childPid(disconnect.run.id);down!.terminate();await wait(()=>core.service.getAgent(identity)?.status==='offline');await wait(()=>dead(disconnectPid));await done(disconnect.run.id,'cancelled');checks.push('network loss -> offline, tree cleanup, reconnect result reconciliation, idle');
 const shutdown=await job('Agent shutdown tree',treeScript,15000);const shutdownPid=await childPid(shutdown.run.id);child!.kill();await once(child!,'exit');await wait(()=>core.service.getAgent(identity)?.status==='offline');await wait(()=>dead(shutdownPid));start();await wait(()=>core.service.getAgent(identity)?.status==='idle');await wait(()=>core.service.snapshot(project.id).runs.find(r=>r.id===shutdown.run.id)?.status==='failed');assert.equal(core.service.listAgents().length,1);checks.push('abrupt Agent exit kills descendants; restart keeps identity and reconciles interrupted run');
 const before=agentMessages.filter(m=>m.type==='rejected'&&m.runId===success.run.id).length;down!.send(JSON.stringify(replay));await wait(()=>agentMessages.filter(m=>m.type==='rejected'&&m.runId===success.run.id).length>before);checks.push('duplicate prevention persists after Agent restart');
 await wait(()=>grandchildren.every(dead));const outcomes=core.service.snapshot(project.id).runs.map(r=>({id:r.id,status:r.status,report:r.executionReport}));for(const [runId,expected] of [[success.run.id,'PASSED'],[failure.run.id,'TEST_FAILED'],[invalid.run.id,'EXECUTION_ERROR'],[timeout.run.id,'TIMEOUT'],[cancel.run.id,'CANCELLED'],[disconnect.run.id,'CONNECTION_LOST'],[shutdown.run.id,'AGENT_RESTARTED']])assert.equal(outcomes.find(r=>r.id===runId)!.report!.classification,expected);checks.push('actual classifications match outcomes; child and grandchild processes remaining zero');assert.equal(agentError,'');fs.writeFileSync(path.join(evidence,'actual-agent-e2e.json'),JSON.stringify({status:'PASS',binary,workspace:root,checks,outcomes,ownedDescendantProcesses:0,agentErrors:0},null,2));console.log('PASS',checks);
}finally{studio.terminate();child?.kill();for(const socket of proxy.clients)socket.terminate();await new Promise<void>(r=>proxy.close(()=>r()));await core.close();}

