/** Controlled local integration: no production publication or remote deployment. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {startCoreServer} from './server.ts';
import {initialGraph,newNode} from '../src/features/orchestration/domain.ts';
import {buildProjectSnapshot,snapshotBytes} from '../src/features/ai/project-snapshot.ts';
import {uploadProjectSnapshot} from '../src/features/core/source-upload.ts';
import type {GraphOverview} from '../src/features/orchestration/execution.ts';
const evidence=path.resolve(process.env.GRAPH_EVIDENCE!),root=path.join(evidence,'actual-'+Date.now());
fs.mkdirSync(root,{recursive:true});const source=path.join(root,'source'),output=path.join(root,'output');fs.mkdirSync(source);fs.mkdirSync(output);
const agentBinary=path.resolve(process.env.AGENT_BINARY!),hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex'),token=randomUUID();
const project={id:randomUUID(),name:'Actual Node graph verification',description:'',workspacePath:null,browserFolder:true,repositoryUrl:null,defaultBranch:null,framework:null,runtime:null,packageManager:null,projectType:null,gitEnabled:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastOpenedAt:null};
const server=await startCoreServer({port:0,agentToken:token,studioToken:token,storagePath:path.join(root,'core.sqlite'),artifactRoot:path.join(root,'artifacts')});
let agent:ChildProcess|undefined,studio:WebSocket|undefined,agentErrors='';const replies=new Map<string,{value:GraphOverview;error?:string}>(),checks:string[]=[];
const wait=async(predicate:()=>boolean,timeout=45000)=>{const end=Date.now()+timeout;while(!predicate()){if(Date.now()>end)throw Error('Graph actual integration timeout');await new Promise(r=>setTimeout(r,40));}};
async function rpc(action:string,input?:unknown){const requestId=randomUUID();studio!.send(JSON.stringify({type:'rpc',protocolVersion:1,requestId,method:'graph',args:[action,input]}));await wait(()=>replies.has(requestId));const reply=replies.get(requestId)!;if(reply.error)throw Error(reply.error);return reply.value;}
try{
 const shared=path.resolve('../tools/cross-platform-release/Test-ReleaseToolIntegrity.ps1'),config=path.resolve('../tools/cross-platform-release');assert(fs.existsSync(shared));assert(fs.existsSync(agentBinary));
 const artifact='controlled-build-v1\n',artifactHash=hash(Buffer.from(artifact));fs.writeFileSync(path.join(source,'artifact.txt'),artifact);fs.writeFileSync(path.join(source,'.env'),'TOKEN=dummy-never-transferred');
 fs.writeFileSync(path.join(source,'workflow.cjs'),`const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');const [mode,out]=process.argv.slice(2),context=JSON.parse(process.env.TASTEDEV_GRAPH_CONTEXT),digest=b=>crypto.createHash('sha256').update(b).digest('hex'),expected=${JSON.stringify(artifactHash)},file=path.join(out,'artifact.bin'),manifest=path.join(out,'manifest.json'),deployed=path.join(out,'deployed.bin');
 if(mode==='build'){const b=fs.readFileSync('artifact.txt');assert.equal(digest(b),expected);fs.writeFileSync(file,b);fs.writeFileSync(manifest,JSON.stringify({checksum:expected,snapshotId:context.snapshotId,sourceChecksum:context.sourceChecksum,executionId:context.executionId}));}
 else {const m=JSON.parse(fs.readFileSync(manifest,'utf8'));assert.equal(m.snapshotId,context.snapshotId);assert.equal(m.sourceChecksum,context.sourceChecksum);assert.equal(m.executionId,context.executionId);assert.equal(digest(fs.readFileSync(file)),expected);if(mode==='deploy')fs.copyFileSync(file,deployed);else if(mode==='test')assert.equal(digest(fs.readFileSync(deployed)),expected);else if(mode==='fail')assert.fail('Controlled failed test');else if(mode==='wait')setTimeout(()=>{},15000);}
 console.log(mode+' verified '+context.snapshotId);`);
 const task=(mode:string)=>({command:'node',args:['workflow.cjs',mode,output],timeout:30,requirements:{runtimes:{node:'>=24'}}});
 const tasks={build:task('build'),deploy:task('deploy'),test:task('test'),fail:task('fail'),wait:task('wait'),shared:{command:'pwsh.exe',args:['-NoProfile','-NoLogo','-File',shared,'-ToolRoot',config],timeout:60}};
 const sources={'project.yml':JSON.stringify({version:1,project:{name:'Controlled graph',type:'node'}}),'tasks.yml':JSON.stringify(tasks),'tests.yml':JSON.stringify({verification:{task:'test',type:'unit',timeout:30}})};
 const protocolDir=path.join(source,'.tastedev');fs.mkdirSync(protocolDir);for(const [name,content] of Object.entries(sources))fs.writeFileSync(path.join(protocolDir,name),content);
 const files={list:async(dir:string)=>fs.readdirSync(path.join(source,dir),{withFileTypes:true}).map(d=>({name:d.name,path:dir?dir+'/'+d.name:d.name,kind:d.isDirectory()?'directory' as const:'file' as const})),read:async(p:string)=>({content:fs.readFileSync(path.join(source,p),'utf8'),size:fs.statSync(path.join(source,p)).size,modified:0})};
 const built=await buildProjectSnapshot(files,{projectId:project.id,proposalId:randomUUID(),attempt:1,baseRevision:'controlled-working-tree',changedFiles:[]});assert(built.excluded.includes('.env'));
 studio=new WebSocket(`ws://127.0.0.1:${server.port}/studio`);let subscribed=false;studio.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='snapshot')subscribed=true;if(m.type==='reply')replies.set(m.requestId,m);});await once(studio,'open');studio.send(JSON.stringify({type:'subscribe',protocolVersion:1,token,project}));await wait(()=>subscribed);
 const request=(p:string,init:RequestInit)=>fetch(`http://127.0.0.1:${server.port}${p}`,{...init,headers:{...init.headers,Authorization:'Bearer '+token,'X-Project-Id':project.id}});
 const snapshot=await uploadProjectSnapshot(built.snapshot,request);checks.push('Authenticated Source upload; dummy .env excluded');
 const agentConfig=path.join(root,'agent.json');fs.writeFileSync(agentConfig,JSON.stringify({endpoint:`ws://127.0.0.1:${server.port}/agent`,name:'Actual graph Agent',workspaceRoot:path.join(root,'agent'),heartbeatMs:200,reconnectMaxMs:500,logLevel:'error'}));
 agent=spawn(agentBinary,['--config',agentConfig],{windowsHide:true,env:{...process.env,TASTEDEV_AGENT_TOKEN:token},stdio:['ignore','ignore','pipe']});agent.stderr!.on('data',b=>agentErrors+=b.toString());agent.on('error',()=>{agentErrors+='Agent failed to start';});await wait(()=>server.service.listAgents().some(a=>a.status==='idle'));const agentId=server.service.listAgents()[0].id;
 const graph=initialGraph(project.id);graph.nodes.push({...newNode('agent','agent',0),reference:agentId},{...newNode('role','deploy-role',1),role:'deployment'},{...newNode('role','test-role',2),role:'testing'},newNode('approval','review',3),...['build','shared','deploy','test'].map((id,i)=>({...newNode('task',id,i+4),reference:id==='test'?'verification':id,taskType:id==='test'?'test' as const:'task' as const})));
 graph.edges.push({id:'host',from:'current-pc',to:'agent',relation:'hosts'},{id:'deploy-assign',from:'current-pc',to:'deploy-role',relation:'assigns'},{id:'test-assign',from:'current-pc',to:'test-role',relation:'assigns'},...['build','shared','deploy','test'].map(id=>({id:'performs-'+id,from:id==='deploy'?'deploy-role':id==='test'?'test-role':'role-implementation',to:id,relation:'performs' as const})),...['build','shared','review','deploy','test'].slice(0,-1).map((from,i)=>({id:'flow-'+i,from,to:['shared','review','deploy','test'][i],relation:'success' as const})));
 await assert.rejects(rpc('publish',{graph,sources,snapshot:{...snapshot,checksum:'a'.repeat(64),transfer:{...snapshot.transfer,manifestChecksum:'a'.repeat(64)}},expectedRevision:0}));assert.equal(server.service.snapshot(project.id).jobs.length,0);checks.push('Unstored/tampered Source publication rejected');
 const d=(await rpc('publish',{graph,sources,snapshot,expectedRevision:0})).definition!;
 const start=async(id:string)=>{await rpc('start',{revision:d.revision,checksum:d.checksum,entryNodeId:'build',requestId:id});};
 const approval=()=>server.graphExecution.overview(project.id).executions.findLast(e=>e.status==='running')!;
 async function approve(){const e=approval(),a=e.activations.find(a=>a.status==='approval')!;await rpc('approve',{executionId:e.id,activationId:a.id,revision:e.revision,checksum:e.checksum});}
 await start('actual-pass');await wait(()=>approval()?.activations.some(a=>a.status==='approval'));assert(!fs.existsSync(path.join(output,'deployed.bin')));assert.equal(server.service.snapshot(project.id).jobs.length,2);checks.push('Implementation and real shared release tool integrity check ran; deployment blocked before approval');
 // Changing the original working tree cannot alter the frozen Source on later nodes.
 fs.writeFileSync(path.join(source,'artifact.txt'),'changed after publication');await approve();await wait(()=>server.graphExecution.overview(project.id).executions[0].status==='passed');assert.equal(hash(fs.readFileSync(path.join(output,'deployed.bin'))),artifactHash);checks.push('Approved local deployment and actual Rust Agent Test PASS; immutable Source and artifact checksum matched');
 // New publication and approval for a controlled failing Test and independent history.
 graph.nodes.find(n=>n.id==='test')!.reference='fail';graph.nodes.find(n=>n.id==='test')!.taskType='task';const failedD=(await rpc('publish',{graph,sources,snapshot,expectedRevision:1})).definition!;
 await rpc('start',{revision:failedD.revision,checksum:failedD.checksum,entryNodeId:'build',requestId:'actual-fail'});await wait(()=>approval()?.activations.some(a=>a.status==='approval'));await approve();await wait(()=>server.graphExecution.overview(project.id).executions.find(e=>e.id==='actual-fail')?.status==='failed');checks.push('Actual failed Test preserves independent history and failure logs');
 graph.nodes.find(n=>n.id==='test')!.reference='wait';const cancelD=(await rpc('publish',{graph,sources,snapshot,expectedRevision:2})).definition!;
 await rpc('start',{revision:cancelD.revision,checksum:cancelD.checksum,entryNodeId:'build',requestId:'actual-cancel'});await wait(()=>approval()?.activations.some(a=>a.status==='approval'));await approve();await wait(()=>server.service.snapshot(project.id).steps.some(s=>s.name==='wait'&&s.status==='running'));await rpc('cancel',{executionId:'actual-cancel'});await wait(()=>server.graphExecution.overview(project.id).executions.find(e=>e.id==='actual-cancel')?.status==='cancelled');checks.push('Actual Rust Agent cancellation acknowledged with cleanup');
 const state=server.service.snapshot(project.id);for(const run of state.runs){assert.equal(run.revision?.snapshotId,snapshot.snapshotId);assert.equal(run.revision?.commit,snapshot.checksum);const received=path.join(root,'agent','runs',run.id,'source');for(const file of built.snapshot.files)assert.equal(hash(fs.readFileSync(path.join(received,file.path))),hash(snapshotBytes(file)));assert(!fs.existsSync(path.join(received,'.env')));}
 assert.equal(agentErrors,'');checks.push('All actual Runs use the published Snapshot bytes; secret exposure 0; Agent stderr 0');
 fs.writeFileSync(path.join(root,'RESULT.json'),JSON.stringify({status:'PASS',scope:'controlled local E2E; shared tool integrity and local disposable file copy only; release planning, packaging, production publication and remote-device transfer were not performed',agentBinary,agentBinaryChecksum:hash(fs.readFileSync(agentBinary)),agentId,source:snapshot,checks,overview:server.graphExecution.overview(project.id),runs:state.runs,steps:state.steps,logs:server.logs.read(state.runs.map(r=>r.id))},null,2));console.log(JSON.stringify({status:'PASS',root,checks}));
}catch(error){const state=server.service.snapshot(project.id);fs.writeFileSync(path.join(root,'FAILURE.json'),JSON.stringify({error:String(error),agentErrors,checks,overview:server.graphExecution.overview(project.id),runs:state.runs,steps:state.steps,logs:server.logs.read(state.runs.map(r=>r.id))},null,2));throw error;
}finally{studio?.terminate();if(agent&&agent.exitCode===null){agent.kill();await once(agent,'exit');}await server.close();}
