import fs from 'node:fs';
import path from 'node:path';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {WebSocket} from 'ws';
import {startCoreServer} from './server.ts';
import {HistoryStore} from './history.ts';
import {FixService,contentHash,type FixAttempt} from '../src/features/ai/fix-service.ts';
import {buildSnapshot,type WorkspaceSnapshot} from '../src/features/ai/snapshot.ts';
import {planPayload,type TestPlan} from '../src/features/core/test-plan.ts';
import type {AnalysisRecord} from '../src/features/ai/domain.ts';
const evidence=path.resolve(process.env.AGENT_EVIDENCE!);
const resume=process.env.DURABLE_FIX_ROOT;const root=resume?path.resolve(resume):path.join(evidence,'durable-agent-'+Date.now());assert(root.startsWith(evidence+path.sep));const source=path.join(root,'source');fs.mkdirSync(source,{recursive:true});
const baseline='exports.add=(a,b)=>a-b;\n',correct='exports.add=(a,b)=>a+b;\n';
if(!resume){fs.writeFileSync(path.join(source,'service.cjs'),baseline);fs.writeFileSync(path.join(source,'test.cjs'),"const assert=require('node:assert/strict');console.log('test-started');setTimeout(()=>{assert.equal(require('./service.cjs').add(2,3),5)},500);\n");
fs.writeFileSync(path.join(source,'user-note.txt'),'pre-existing user change');fs.writeFileSync(path.join(source,'.env'),'TOKEN=dummy-never-transfer');}
const project={id:randomUUID(),name:'Controlled durable fix fixture',description:'',workspacePath:null,browserFolder:true,repositoryUrl:null,defaultBranch:null,framework:null,runtime:null,packageManager:null,projectType:null,gitEnabled:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastOpenedAt:null};
const token=randomUUID(),options={port:0,agentToken:token,studioToken:token,storagePath:path.join(root,'core.sqlite'),storageKey:Buffer.alloc(32,4),artifactRoot:path.join(root,'artifacts')};
let core=await startCoreServer(options);if(resume){const saved=core.store!.get<[string,typeof project][]>('projects');assert(saved?.length===1);Object.assign(project,saved[0][1]);}options.port=core.port;let history=new HistoryStore(core.store),studio:WebSocket|undefined,agent:ChildProcess|undefined;let errors='';const checks:string[]=[],runs:unknown[]=[];
const wait=async(predicate:()=>boolean)=>{const until=Date.now()+20000;while(Date.now()<until){if(predicate())return;await new Promise(r=>setTimeout(r,30));}throw Error('Durable verification timed out');};
const replies=new Map<string,Record<string,unknown>>();
async function connectStudio(){studio=new WebSocket(`ws://127.0.0.1:${core.port}/studio`);studio.on('error',()=>{});let ready=false;studio.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='reply')replies.set(m.requestId,m);if(m.type==='snapshot')ready=true;});await once(studio,'open');studio.send(JSON.stringify({type:'subscribe',protocolVersion:1,token,project}));await wait(()=>ready);}
async function rpc(method:string,args:unknown[]=[]){const requestId=randomUUID();studio!.send(JSON.stringify({type:'rpc',protocolVersion:1,requestId,method,args}));await wait(()=>replies.has(requestId));const reply=replies.get(requestId)!;if(reply.error)throw Error(String(reply.error));return reply.value as {id:string};}
const files={list:async(dir:string)=>fs.readdirSync(path.join(source,dir),{withFileTypes:true}).map(d=>({name:d.name,path:dir?dir+'/'+d.name:d.name,kind:d.isDirectory()?'directory' as const:'file' as const})),read:async(p:string)=>({path:p,content:fs.readFileSync(path.join(source,p),'utf8'),size:fs.statSync(path.join(source,p)).size,modified:0}),write:async(p:string,value:string,expected:string)=>{assert.equal(fs.readFileSync(path.join(source,p),'utf8'),expected);fs.writeFileSync(path.join(source,p),value);}};
function openFix(){const fix=new FixService(project.id,files);fix.restore(history.list(project.id,'attempt').map(v=>history.get(project.id,'attempt',v.id)!.value as FixAttempt));fix.setPersistence({save:async a=>{await history.put(project.id,'attempt',a.id,history.get(project.id,'attempt',a.id)?.version??0,a);}});return fix;}
function plan(snapshot:WorkspaceSnapshot):TestPlan{return{id:randomUUID(),projectId:project.id,testName:'arithmetic',type:'unit',requirements:{runtimes:{node:'>=24'}},environment:{},timeout:15000,steps:[{name:'Snapshot',stage:'source',executable:'snapshot',args:[],cwd:'.',source:{provider:'snapshot',repository:'snapshot:'+snapshot.snapshotId,revision:snapshot.baseRevision,snapshot},timeoutMs:5000},{name:'Arithmetic',stage:'test',executable:process.execPath,args:['test.cjs'],cwd:'source',timeoutMs:5000},{name:'Cleanup',stage:'cleanup',executable:'internal-stop-services',args:[],cwd:'.',timeoutMs:5000}]};}
async function queue(value:TestPlan,idempotencyKey?:string){await wait(()=>core.service.listAgents().some(a=>a.status==='idle'));const job=await rpc('createJob',[{idempotencyKey,name:'Controlled durable retest',requirements:value.requirements,payload:planPayload(value),maxAttempts:1}]);await rpc('dispatch',[job.id]);return job;}
async function finish(jobId:string){await wait(()=>core.service.snapshot(project.id).runs.some(r=>r.jobId===jobId&&!['pending','running'].includes(r.status)));const snapshot=core.service.snapshot(project.id),run=snapshot.runs.find(r=>r.jobId===jobId)!;runs.push({run,steps:snapshot.steps.filter(s=>s.runId===run.id),logs:core.logs.read([run.id])[run.id]});return run;}
async function verifySource(runId:string,s:WorkspaceSnapshot){const received=path.join(root,'agent','runs',runId,'source');for(const f of s.files)assert.equal(await contentHash(fs.readFileSync(path.join(received,f.path),'utf8')),f.checksum);assert(!fs.existsSync(path.join(received,'.env')));}
try{
 await connectStudio();const config=path.join(root,'agent.json');fs.writeFileSync(config,JSON.stringify({endpoint:`ws://127.0.0.1:${core.port}/agent`,name:'Actual durable Agent',workspaceRoot:path.join(root,'agent'),heartbeatMs:200,reconnectMaxMs:500,logLevel:'error'}));
 agent=spawn(path.resolve(process.env.AGENT_BINARY!),['--config',config],{windowsHide:true,env:{...process.env,TASTEDEV_AGENT_TOKEN:token},stdio:['ignore','ignore','pipe']});agent.stderr!.on('data',data=>errors+=data.toString());agent.on('error',()=>{errors+='Agent start failed';});
 const first=await buildSnapshot(files,{projectId:project.id,proposalId:randomUUID(),attempt:1,baseRevision:'controlled-initial',changedFiles:['service.cjs']});const restoredAttempts=history.list(project.id,'attempt').map(v=>history.get(project.id,'attempt',v.id)!.value as FixAttempt);const initial=resume?core.service.snapshot(project.id).runs.find(r=>r.id===restoredAttempts[0]?.runId)!:await finish((await queue(plan(first.snapshot))).id);assert.equal(initial.status,'failed');checks.push('actual initial arithmetic Test FAIL');
 const record:AnalysisRecord={id:randomUUID(),projectId:project.id,conversationId:randomUUID(),runId:initial.id,model:'controlled synthetic proposal; no actual Provider',createdAt:new Date().toISOString(),context:[],originals:{'service.cjs':baseline},result:{summary:'Controlled arithmetic fix',observedFailure:'2+3 assertion failed',candidates:[],evidence:[],uncertainty:'synthetic verification',relatedFiles:[{path:'service.cjs',start:1,end:1,evidence:'controlled assertion'}],proposal:[{path:'service.cjs',proposed:correct,rationale:'controlled',impact:'controlled',tests:['arithmetic']}]}};
 let fixes=openFix();
 for(const [index,proposed,expected] of [[1,correct,'cancelled'],[2,'exports.add=(a,b)=>a*b;\n','failed'],[3,correct,'passed']] as const){
  const resumed=!!resume&&index===1;const attempt=resumed?fixes.get(restoredAttempts[0].id):await fixes.propose({...record,id:randomUUID(),result:{...record.result,proposal:[{...record.result.proposal[0],proposed}]}});assert.equal(attempt.attempt,index);if(!resumed){await fixes.approve(attempt.id,['service.cjs']);await fixes.apply(attempt.id);}
  const prior=resumed?core.service.snapshot(project.id).jobs.find(j=>j.id===attempt.retestJobId)!.payload.testPlan!:undefined;const snapshot=prior?.steps[0].source?.provider==='snapshot'?prior.steps[0].source.snapshot:(await buildSnapshot(files,{projectId:project.id,proposalId:attempt.proposalId,attempt:attempt.attempt,baseRevision:'controlled-working-tree',changedFiles:['service.cjs']})).snapshot;const value=prior??plan(snapshot);if(!resumed){await fixes.recordSnapshot(attempt.id,snapshot);const approval=await fixes.approveExecution(attempt.id,'remote-test','arithmetic',value);await fixes.beginApprovedRetest(attempt.id,approval.id,value);}const job=await queue(value,resumed?attempt.id+':restart-gate':attempt.id);fixes.setRetestJob(attempt.id,job.id);await fixes.flush();
  if(index===1){await wait(()=>core.service.snapshot(project.id).steps.some(s=>s.name==='Arithmetic'&&s.status==='running'&&core.service.snapshot(project.id).runs.some(r=>r.id===s.runId&&r.jobId===job.id)));const inFlight=core.service.snapshot(project.id).runs.find(r=>r.jobId===job.id)!;studio!.terminate();await core.close();core=await startCoreServer(options);history=new HistoryStore(core.store);await connectStudio();fixes=openFix();const restored=fixes.get(attempt.id);assert.equal(restored.snapshot?.snapshotId,snapshot.snapshotId);assert.equal(restored.approval?.proposalId,attempt.proposalId);assert.equal(restored.retestJobId,job.id);assert.equal(core.service.snapshot(project.id).runs.find(r=>r.id===inFlight.id)?.revision?.snapshotId,snapshot.snapshotId);checks.push('in-flight Core restart preserved approval/attempt/job/run/Snapshot identity');}
  const run=await finish(job.id);assert.equal(run.status,expected);fixes.linkRetest(attempt.id,run.id);fixes.retestResult(attempt.id,expected);await fixes.flush();assert.equal(run.revision?.snapshotId,snapshot.snapshotId);assert.equal(run.revision?.proposalId,attempt.proposalId);assert.equal(run.revision?.attempt,index);await verifySource(run.id,snapshot);await fixes.revert(attempt.id);assert.equal((await files.read('service.cjs')).content,baseline);assert.equal((await files.read('user-note.txt')).content,'pre-existing user change');checks.push(`Attempt ${index}: actual Rust ${expected}, immutable Source verified, exact Revert and user change preserved`);
 }
 fixes=openFix();assert.equal(fixes.history.length,3);await assert.rejects(fixes.propose(record),/RETRY_LIMIT/);checks.push('restored history keeps all attempts and maximum3 retry limit');assert.equal(errors,'');fs.writeFileSync(path.join(evidence,'durable-agent.json'),JSON.stringify({status:'PASS',actualProvider:false,proposalApproval:'controlled synthetic test approval only',actualRustAgent:true,checks,runs,attempts:fixes.history,sourceRestored:true,agentErrors:0},null,2));console.log('PASS',checks);
}finally{studio?.terminate();if(agent&&agent.exitCode===null){agent.kill();await once(agent,'exit');}await core.close();}
