/** Actual TASTEFILES desktop source -> isolated Rust Agent compiler -> approval -> second Agent executable integrity checks; GUI is not launched. No signing, publication or remote deployment. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {startCoreServer} from './server.ts';
import {initialGraph,newNode} from '../src/features/orchestration/domain.ts';
import {buildProjectSnapshot} from '../src/features/ai/project-snapshot.ts';
import {uploadProjectSnapshot} from '../src/features/core/source-upload.ts';
import {parseProtocol} from '../src/features/protocol/parser.ts';
import type {GraphOverview} from '../src/features/orchestration/execution.ts';
const evidence=path.resolve(process.env.GRAPH_EVIDENCE!),root=path.join(evidence,'actual-'+Date.now());fs.mkdirSync(root,{recursive:true});
const workRoot=path.join(path.resolve(process.env.AGENT_WORKSPACE_BASE!),path.basename(root));fs.mkdirSync(workRoot,{recursive:true});
const binary=path.resolve(process.env.AGENT_BINARY!),hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex'),token=randomUUID();assert(fs.existsSync(binary));
const project={id:randomUUID(),name:'Actual artifact transfer verification',description:'',workspacePath:null,browserFolder:true,repositoryUrl:null,defaultBranch:null,framework:null,runtime:null,packageManager:null,projectType:null,gitEnabled:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastOpenedAt:null};
const compilerEnvironment:Record<string,string>=process.env.COMPILER_ENV?JSON.parse(fs.readFileSync(process.env.COMPILER_ENV,'utf8')):{};assert(Object.keys(compilerEnvironment).every(k=>['LIB','LIBPATH','INCLUDE','PATH'].includes(k)));
const unexpected:string[]=[],children:ChildProcess[]=[],errors:string[]=[],checks:string[]=[];
const server=await startCoreServer({port:0,agentToken:token,studioToken:token,storagePath:path.join(root,'core.sqlite'),artifactRoot:path.join(root,'artifacts'),buildArtifactRuntime:true,runtimeEvent:(level,event)=>{if(level==='error')unexpected.push(event);}});
let studio:WebSocket|undefined;const replies=new Map<string,{value:GraphOverview;error?:string}>();
async function wait(predicate:()=>boolean,timeout=900000){const deadline=Date.now()+timeout;while(!predicate()){if(Date.now()>deadline)throw Error('Actual artifact flow timeout');await new Promise(r=>setTimeout(r,25));}}
async function rpc(action:string,input?:unknown){const requestId=randomUUID();studio!.send(JSON.stringify({type:'rpc',protocolVersion:1,requestId,method:'graph',args:[action,input]}));await wait(()=>replies.has(requestId));const reply=replies.get(requestId)!;if(reply.error)throw Error(reply.error);return reply.value;}
try{
 const product=path.resolve(process.env.TASTEFILES_SOURCE!);assert(fs.existsSync(path.join(product,'Cargo.lock')));
 const expectedInputs=JSON.parse(fs.readFileSync(process.env.SOURCE_PREFLIGHT!,'utf8')).sourceInputs as Record<string,string>;
 expectedInputs['THIRD_PARTY.md']=hash(fs.readFileSync(path.join(product,'THIRD_PARTY.md')));
 const assetInputs=JSON.parse(fs.readFileSync(process.env.ASSET_PREFLIGHT!,'utf8')).files as {path:string;checksum:string}[];for(const asset of assetInputs)expectedInputs[asset.path]=asset.checksum;
 for(const [file,checksum] of Object.entries(expectedInputs))assert.equal(hash(fs.readFileSync(path.join(product,file))),checksum,'Source changed since reviewed preflight: '+file);
 const cacheRoot=process.env.DESKTOP_BUILD_CACHE?path.resolve(process.env.DESKTOP_BUILD_CACHE):null;
 if(cacheRoot){assert(cacheRoot.startsWith(path.resolve(process.env.AGENT_WORKSPACE_BASE!)+path.sep));assert(cacheRoot.endsWith(path.sep+'source'+path.sep+'target'));const previous=path.dirname(cacheRoot);for(const [file,checksum] of Object.entries(expectedInputs)){if(file==='THIRD_PARTY.md')continue;assert.equal(hash(fs.readFileSync(path.join(previous,file))),checksum,'Cache source mismatch: '+file);}fs.writeFileSync(path.join(root,'CACHE-PRECONDITIONS.json'),JSON.stringify({cacheRoot,sourceInputsChecked:Object.keys(expectedInputs).length-1,addedInput:'THIRD_PARTY.md',contract:'Same Cargo.lock/toolchain/SDK/options; compiler cache only, Cargo fingerprints decide reuse; no existing desktop output'},null,2));}
 const compile=`const fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');const cache=${JSON.stringify(cacheRoot)};if(cache){const root=path.resolve(cache);function check(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(fs.lstatSync(p).isSymbolicLink())throw Error('Cache link rejected');if(item.isDirectory())check(p);}}check(root);fs.cpSync(root,path.resolve('target'),{recursive:true,preserveTimestamps:true,errorOnExist:true,force:false});}const result=spawnSync('cargo',['build','--locked','--offline','--release','--package','tastefiles-gui','--bin','tastefiles'],{stdio:'inherit',env:process.env});if(result.error)throw result.error;process.exit(result.status??1);`;
 const harness=`const fs=require('node:fs'),assert=require('node:assert/strict');const bytes=fs.readFileSync('received/tastefiles.exe');assert.equal(bytes.subarray(0,2).toString(),'MZ');const offset=bytes.readUInt32LE(0x3c);assert(offset>0&&offset+24<bytes.length);assert.equal(bytes.subarray(offset,offset+4).toString('hex'),'50450000');assert.equal(bytes.readUInt16LE(offset+4),0x8664);console.log('Actual TASTEFILES desktop Windows x64 executable structure verified; no GUI launch');`;
 const files={readBytes:async(p:string)=>new Uint8Array(fs.readFileSync(path.join(product,p))),list:async(dir:string='')=>fs.readdirSync(path.join(product,dir),{withFileTypes:true}).flatMap<{name:string;path:string;kind:'file'|'directory'}>(d=>{const p=(dir?dir+'/':'')+d.name;if(d.isDirectory()&&['crates','tools','.cargo','resources'].includes(p.split('/')[0]))return[{name:d.name,path:p,kind:'directory' as const}];if(d.isFile()&&Object.hasOwn(expectedInputs,p))return[{name:d.name,path:p,kind:'file' as const}];return[];}),read:async(p:string)=>({content:fs.readFileSync(path.join(product,p),'utf8'),size:fs.statSync(path.join(product,p)).size,modified:0})};
 const built=await buildProjectSnapshot(files,{projectId:project.id,proposalId:randomUUID(),attempt:1,baseRevision:'reviewed-working-tree',changedFiles:[]});assert(built.snapshot.files.some(f=>f.path==='crates/tastefiles-gui/src/main.rs'));for(const asset of assetInputs)assert(built.snapshot.files.some(f=>f.path===asset.path&&f.checksum===asset.checksum),'Required asset missing');
 // Add only the controlled test harness, then reconstruct a checked byte-preserving Snapshot.
 const source=path.join(root,'source');fs.mkdirSync(source);for(const f of built.snapshot.files){const target=path.join(source,f.path);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,f.encoding==='base64'?Buffer.from(f.content,'base64'):Buffer.from(f.content));}fs.writeFileSync(path.join(source,'workflow.cjs'),harness);fs.writeFileSync(path.join(source,'desktop-build.cjs'),compile);
 const staged={readBytes:async(p:string)=>new Uint8Array(fs.readFileSync(path.join(source,p))),list:async(dir:string='')=>fs.readdirSync(path.join(source,dir),{withFileTypes:true}).map(d=>({name:d.name,path:(dir?dir+'/':'')+d.name,kind:d.isDirectory()?'directory' as const:'file' as const})),read:async(p:string)=>({content:fs.readFileSync(path.join(source,p),'utf8'),size:fs.statSync(path.join(source,p)).size,modified:0})};
 built.snapshot=(await buildProjectSnapshot(staged,{projectId:project.id,proposalId:randomUUID(),attempt:1,baseRevision:'reviewed-working-tree',changedFiles:[]})).snapshot;
 studio=new WebSocket(`ws://127.0.0.1:${server.port}/studio`);let subscribed=false;studio.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.type==='snapshot')subscribed=true;if(m.type==='reply')replies.set(m.requestId,m);});await once(studio,'open');studio.send(JSON.stringify({type:'subscribe',protocolVersion:1,token,project}));await wait(()=>subscribed);
 const snapshot=await uploadProjectSnapshot(built.snapshot,(p,init)=>fetch(`http://127.0.0.1:${server.port}${p}`,{...init,headers:{...init.headers,Authorization:'Bearer '+token,'X-Project-Id':project.id}}));
 for(const name of ['Producer','Consumer']){const config=path.join(root,name+'.json');fs.writeFileSync(config,JSON.stringify({endpoint:`ws://127.0.0.1:${server.port}/agent`,name,workspaceRoot:path.join(workRoot,name),heartbeatMs:200,reconnectMaxMs:500,logLevel:'error'}));const child=spawn(binary,['--config',config],{windowsHide:true,env:{...process.env,...compilerEnvironment,PATH:path.dirname(process.env.CARGO_BINARY!)+path.delimiter+(compilerEnvironment.PATH??process.env.PATH),TASTEDEV_AGENT_TOKEN:token},stdio:['ignore','ignore','pipe']});children.push(child);child.stderr!.on('data',b=>errors.push(b.toString()));child.on('error',()=>errors.push('Agent failed to start'));}
 await wait(()=>server.service.listAgents().filter(a=>a.status==='idle').length===2);const agents=server.service.listAgents();for(const a of agents)assert.equal(a.capabilities.buildArtifacts,2);
 const producer=agents.find(a=>a.name==='Producer')!,consumer=agents.find(a=>a.name==='Consumer')!;assert.notEqual(producer.id,consumer.id);
 const graph=initialGraph(project.id);graph.nodes.push(newNode('device','consumer-pc',0),{...newNode('agent','producer-agent',1),reference:producer.id},{...newNode('agent','consumer-agent',2),reference:consumer.id},{...newNode('role','consumer-role',3),role:'deployment'},{...newNode('task','build-node',4),reference:'build'},newNode('approval','review',5),{...newNode('task','consumer-node',6),reference:'verify'});
 graph.edges.push({id:'producer-host',from:'current-pc',to:'producer-agent',relation:'hosts'},{id:'consumer-host',from:'consumer-pc',to:'consumer-agent',relation:'hosts'},{id:'consumer-role',from:'consumer-pc',to:'consumer-role',relation:'assigns'},{id:'produce',from:'role-implementation',to:'build-node',relation:'performs'},{id:'consume',from:'consumer-role',to:'consumer-node',relation:'performs'},{id:'built',from:'build-node',to:'review',relation:'success'},{id:'reviewed',from:'review',to:'consumer-node',relation:'success'});
 const sources=()=>({'project.yml':JSON.stringify({version:1,project:{name:'Actual TASTEFILES desktop qualification',type:'desktop'}}),'tasks.yml':JSON.stringify({build:{command:'node',args:['desktop-build.cjs'],env:Object.fromEntries(Object.entries(compilerEnvironment).filter(([key])=>key!=='PATH')),requirements:{os:'windows',architecture:'x86_64',runtimes:{node:'>=24',rust:'>=1.98.1'}},timeout:900,artifacts:{outputs:[{name:'desktop',path:'target/release/tastefiles.exe',executable:true}]}},verify:{command:'node',args:['workflow.cjs'],timeout:60,requirements:{runtimes:{node:'>=24'}},artifacts:{inputs:[{fromTask:'build',name:'desktop',path:'received/tastefiles.exe',executable:true}]}}})});
 const protocol=parseProtocol(sources());assert.equal(protocol.status,'Valid','Verifier Protocol preflight failed');
 async function execute(mode:string,revision:number){
  const definition=(await rpc('publish',{graph,sources:sources(),snapshot,expectedRevision:revision})).definition!;
  await rpc('start',{revision:definition.revision,checksum:definition.checksum,entryNodeId:'build-node',requestId:randomUUID()});
  const executionId=server.graphExecution.overview(project.id).executions.at(-1)!.id;
  const current=()=>server.graphExecution.overview(project.id).executions.find(e=>e.id===executionId)!;
  await wait(()=>current().activations.some(a=>a.status==='approval')||current().status==='failed');assert.notEqual(current().status,'failed');
  assert(!current().activations.some(a=>a.nodeId==='consumer-node'));checks.push(mode+': consumer blocked until approval');
  const approval=current().activations.find(a=>a.status==='approval')!;await rpc('approve',{executionId,activationId:approval.id,revision:definition.revision,checksum:definition.checksum});
  await wait(()=>['passed','failed'].includes(current().status));assert.equal(current().status,mode==='fail'?'failed':'passed');
  const made=current().activations.find(a=>a.nodeId==='build-node')!,used=current().activations.find(a=>a.nodeId==='consumer-node')!;const state=server.service.snapshot(project.id),madeRun=state.runs.find(r=>r.id===made.runId)!,usedRun=state.runs.find(r=>r.id===used.runId)!;
  assert.equal(madeRun.agentId,producer.id);assert.equal(usedRun.agentId,consumer.id);const checksum=hash(fs.readFileSync(path.join(workRoot,'Producer','runs',madeRun.id,'source/target/release/tastefiles.exe')));const receipts=made.artifactReceipts!;assert.equal(receipts.length,1);assert.equal(receipts[0].outputs[0].checksum,checksum);assert.equal(receipts[0].outputs[0].version,2);assert.equal(receipts[0].outputs[0].executable,true);assert.equal(receipts[0].outputs[0].producerRunId,madeRun.id);assert.equal(receipts[0].outputs[0].snapshotId,snapshot.snapshotId);assert(!('token' in receipts[0].outputs[0]));checks.push(mode+': persisted Core output receipt matched actual bytes and producer Run');
  const installation=used.artifactInstallations![0];assert.equal(installation.consumerRunId,usedRun.id);assert.equal(installation.agentId,consumer.id);assert.equal(installation.inputs[0].artifact.producerRunId,madeRun.id);assert.equal(installation.inputs[0].artifact.checksum,checksum);assert.equal(installation.inputs[0].path,'received/tastefiles.exe');checks.push(mode+': consumer installation receipt retained independently of test result');
  const output=fs.readFileSync(path.join(workRoot,'Producer','runs',madeRun.id,'source/target/release/tastefiles.exe')),received=fs.readFileSync(path.join(workRoot,'Consumer','runs',usedRun.id,'source/received/tastefiles.exe'));assert.equal(hash(output),checksum);assert.deepEqual(received,output);assert(!fs.existsSync(path.join(workRoot,'Consumer','runs',usedRun.id,'source/.env')));
  assert(!fs.existsSync(path.join(workRoot,'Consumer','runs',usedRun.id,'source/target/release/tastefiles.exe')));assert(!fs.existsSync(path.join(workRoot,'Producer','runs',madeRun.id,'source/received/tastefiles.exe')));
  assert.equal(madeRun.revision?.snapshotId,snapshot.snapshotId);assert.equal(usedRun.revision?.snapshotId,snapshot.snapshotId);checks.push(mode+': actual two Rust Agent workspaces, Core HTTP checksum bytes and immutable Snapshot matched');return definition.revision;
 }
 await execute('verify',0);assert.equal(errors.length,0);assert.equal(unexpected.length,0);
 fs.writeFileSync(path.join(root,'RESULT.json'),JSON.stringify({status:'PASS',scope:'actual local Core/two Rust Agents; controlled explicit approval and actual read-only product source; actual offline desktop build and consumer executable integrity; GUI not launched; no remote deployment',workRoot,binary,binaryChecksum:hash(fs.readFileSync(binary)),checks,snapshotId:snapshot.snapshotId,sourceChecksum:snapshot.checksum,overview:server.graphExecution.overview(project.id),runs:server.service.snapshot(project.id).runs,unexpected,agentErrors:errors},null,2));console.log(JSON.stringify({status:'PASS',root,checks}));
}catch(error){fs.writeFileSync(path.join(root,'FAILURE.json'),JSON.stringify({error:String(error),unexpected,agentErrors:errors,checks,overview:server.graphExecution.overview(project.id),runs:server.service.snapshot(project.id).runs,steps:server.service.snapshot(project.id).steps,logs:server.logs.read(server.service.snapshot(project.id).runs.map(r=>r.id))},null,2));throw error;
}finally{studio?.terminate();for(const child of children)if(child.exitCode===null){child.kill();await once(child,'exit');}await server.close();}
