import type {Project} from '../projects/types/project.ts';
import type {CoreSnapshot} from '../core/domain.ts';
import type {AnalysisRecord} from '../ai/domain.ts';
import type {FixAttempt} from '../ai/fix-service.ts';
import {IssueError,type IssueCandidate} from './domain.ts';
import {repository,safeText,fields} from './security.ts';
export interface CandidateInput {runId:string;analysis?:AnalysisRecord;fixAttempt?:FixAttempt}
export function buildCandidate(project:Project,snapshot:CoreSnapshot,input:CandidateInput,logs:string[],secrets:string[]=[]):IssueCandidate{
 const run=snapshot.runs.find(r=>r.id===input.runId&&r.projectId===project.id);if(!run||!['failed','timeout','passed','cancelled'].includes(run.status))throw new IssueError('boundary');
 const job=snapshot.jobs.find(j=>j.id===run.jobId&&j.projectId===project.id);if(!job)throw new IssueError('boundary');const analysis=input.analysis,fix=input.fixAttempt;if(analysis&&(analysis.projectId!==project.id||analysis.runId!==run.id)||fix&&(fix.projectId!==project.id||![fix.runId,fix.retestRunId].includes(run.id)))throw new IssueError('boundary');
 const step=snapshot.steps.find(s=>s.id===run.primaryFailureStepId&&s.runId===run.id)??snapshot.steps.find(s=>s.runId===run.id&&['failed','timeout'].includes(s.status));const artifacts=snapshot.artifacts.filter(a=>a.runId===run.id);const test=job.payload.testPlan?.testName??job.name;const summary=run.result?.summary??`${test}: ${run.status}`;const source=fix?(run.id===fix.retestRunId?'retest':fix.status==='passed'?'fix-record':'fix-attempt'):analysis?'analysis':job.payload.testPlan?'failed-test':'failed-run';const sections:string[]=[];const add=(name:string,text:string|undefined)=>{if(text)sections.push(`## ${name}\n\n${safeText(text,secrets)}`);};
 add('Summary',summary);add('Failure',run.status==='passed'?undefined:`${run.status}; exit ${run.exitCode??'not reported'}\n${step?.failureReason??''}`);add('Steps / Reproduction',`Run the saved Protocol ${job.payload.testPlan?'Test':'Task'}: ${test}.\nTask references: ${job.payload.steps.map(s=>s.taskReference??s.name).join(', ')}`);add('Expected Result','The selected validation test passes.');add('Actual Result',`${run.status}; exit ${run.exitCode??'not reported'}`);const agent=snapshot.agents.find(a=>a.id===run.agentId);add('Environment',agent?`${agent.name}; ${agent.platform}/${agent.architecture}`:`Agent reference: ${run.agentId}`);
 const revision=run.revision?run.revision.snapshotId?`Snapshot ${run.revision.snapshotId}\nBase revision: ${run.revision.branch}\nManifest checksum: ${run.revision.commit}\nProposal: ${run.revision.proposalId}\nAttempt: ${run.revision.attempt}`:`Repository: ${run.revision.repository}\nRevision: ${run.revision.branch}\nCommit: ${run.revision.commit}`:undefined;add('Revision',revision);add('Failed Step',step?`${step.name}; ${step.status}; exit ${step.exitCode??'not reported'}`:undefined);add('Relevant Logs',logs.join('').slice(-8000));add('Evidence',artifacts.length?artifacts.map(a=>`${a.type}: tastedev:artifact/${a.id} (internal reference; not publicly accessible)`).join('\n'):undefined);
 const related=analysis?.result.relatedFiles.map(f=>`${f.path}:${f.start}-${f.end}`)??[];add('Related Source',related.join('\n'));add('AI Analysis',analysis?`${analysis.result.summary}\n${analysis.result.candidates.map(c=>`Candidate: ${c.cause}\nUncertainty: ${c.uncertainty}`).join('\n')}\n${analysis.result.uncertainty}`:undefined);add('Fix Attempt',fix?`Attempt ${fix.attempt}: ${fix.status}\nProposal: ${fix.proposalId}\nRetest: ${fix.retestRunId??'not run'}\nValidation: ${(fix.validation??[]).map(v=>`${v.name}: ${v.status}`).join(', ')}`:undefined);add('TASTEDEV Run Reference',`tastedev:run/${run.id} (internal reference; not publicly accessible)`);
 let repo:string|null=null;try{repo=repository(project.repositoryUrl);}catch{}const now=new Date().toISOString(),editable=fields(`[${run.status.toUpperCase()}] ${test}`,sections.join('\n\n'),[],secrets);return{id:crypto.randomUUID(),projectId:project.id,repository:repo,...editable,status:'draft',source,createdAt:now,updatedAt:now,version:1,summary:safeText(summary,secrets),runId:run.id,...(step?{runStepId:step.id}:{}),testName:safeText(test,secrets),...(revision?{revision:safeText(revision,secrets)}:{}),...(analysis?{analysisId:analysis.id}:{}),...(fix?{fixAttemptId:fix.id,fixStatus:fix.status}:{}),artifactIds:artifacts.map(a=>a.id),relatedFiles:related.map(f=>safeText(f,secrets)),duplicates:[]};
}
