import {IssueError,type IssueCandidate,type IssueProvider,type ExternalIssue} from './domain.ts';
import {fields,externalURL} from './security.ts';
import {contentHash} from '../ai/fix-service.ts';
const identity=(c:IssueCandidate)=>JSON.stringify([c.projectId,c.repository,c.version,c.title,c.body,c.labels]);
export const requestMarker=(id:string)=>`<!-- tastedev-issue:${id} -->`;
const words=(s:string)=>new Set(s.toLowerCase().match(/[a-z0-9_-]{3,}/g)??[]);
export function similarity(candidate:IssueCandidate,issue:ExternalIssue){const a=words(candidate.title+' '+candidate.testName+' '+candidate.summary),b=words(issue.title+' '+issue.body);let shared=0;for(const w of a)if(b.has(w))shared++;return shared/Math.max(1,a.size);}
export interface IssuePersistence {load():IssueCandidate[];save(candidates:IssueCandidate[]):void}
export class IssueService {
 private candidates=new Map<string,IssueCandidate>();private busy=new Set<string>();private searchedAt=new Map<string,number>();
 readonly provider:IssueProvider;readonly secrets:string[];
 private persistence?:IssuePersistence;private committed:IssueCandidate[]=[];
 constructor(provider:IssueProvider,secrets:string[]=[],persistence?:IssuePersistence){this.provider=provider;this.secrets=secrets;this.persistence=persistence;const saved=persistence?.load()??[];this.candidates=new Map(saved.map(c=>{if(c.status==='creating'){c.status='failed';c.uncertain=true;c.error='create-uncertain';}return[c.id,c];}));this.checkpoint();}
 private checkpoint(){const next=structuredClone([...this.candidates.values()]);try{this.persistence?.save(next);}catch(e){this.candidates=new Map(this.committed.map(c=>[c.id,structuredClone(c)]));throw e;}this.committed=next;}
 add(c:IssueCandidate){if(this.candidates.size>=200)throw new IssueError('validation');this.candidates.set(c.id,structuredClone(c));this.checkpoint();return this.get(c.projectId,c.id);}
 private own(projectId:string,id:string){const c=this.candidates.get(id);if(!c||c.projectId!==projectId)throw new IssueError('boundary');return c;}
 get(projectId:string,id:string){return structuredClone(this.own(projectId,id));}
 list(projectId:string){return structuredClone([...this.candidates.values()].filter(c=>c.projectId===projectId));}
 private touch(c:IssueCandidate){c.updatedAt=new Date().toISOString();this.checkpoint();}
 edit(projectId:string,id:string,version:number,input:{title:string;body:string;labels:string[]}){const c=this.own(projectId,id);if(this.busy.has(id)||c.uncertain||['linked','dismissed','creating'].includes(c.status))throw new IssueError('busy');if(c.version!==version)throw new IssueError('stale');Object.assign(c,fields(input.title,input.body,input.labels,this.secrets));c.version++;c.status='reviewing';delete c.approval;delete c.searchVersion;delete c.error;this.touch(c);return this.get(projectId,id);}
 dismiss(projectId:string,id:string,reason=''){const c=this.own(projectId,id);if(this.busy.has(id)||c.uncertain||['linked','creating'].includes(c.status))throw new IssueError('busy');c.status='dismissed';c.dismissReason=fields('reason',reason,[],this.secrets).body;delete c.approval;this.touch(c);return this.get(projectId,id);}
 private async operation<T>(c:IssueCandidate,work:()=>Promise<T>){if(this.busy.has(c.id))throw new IssueError('busy');this.busy.add(c.id);try{return await work();}catch(e){const safe=e instanceof IssueError?e:new IssueError('unavailable');c.error=safe.code;if(!['linked','dismissed'].includes(c.status))c.status='failed';throw safe;}finally{this.busy.delete(c.id);this.touch(c);}}
 async search(projectId:string,id:string){const c=this.own(projectId,id);if(c.uncertain||['linked','dismissed','creating'].includes(c.status))throw new IssueError('busy');if(!c.repository)throw new IssueError('repository');const last=this.searchedAt.get(id)??0;if(Date.now()-last<5000&&c.searchVersion===c.version)return this.get(projectId,id);await this.operation(c,async()=>{this.searchedAt.set(id,Date.now());await this.provider.identify(c.repository!);const terms=[c.title,c.testName,c.summary,c.relatedFiles.join(' ')].map(t=>[...words(t)].slice(0,5).join(' ')).filter(Boolean);const found=await this.provider.search(c.repository!,terms);c.duplicates=found.map(issue=>({issue:this.valid(c,issue),score:similarity(c,issue),reasons:['Shared title/test/error/component terms; user review required.']})).sort((a,b)=>b.score-a.score).slice(0,20);c.searchVersion=c.version;c.status=c.duplicates.length?'duplicate':'reviewing';delete c.error;});return this.get(projectId,id);}
 private valid(c:IssueCandidate,i:ExternalIssue){if(i.provider!==this.provider.name||i.repository!==c.repository)throw new IssueError('boundary');externalURL(i.url,c.repository!,i.number);return structuredClone(i);}
 async approve(projectId:string,id:string,version:number,repo:string){const c=this.own(projectId,id);if(this.busy.has(id)||c.uncertain||!['reviewing','duplicate'].includes(c.status)||c.searchVersion!==c.version||version!==c.version||repo!==c.repository)throw new IssueError('stale');c.approval={version,repository:repo,hash:await contentHash(identity(c)),timestamp:new Date().toISOString()};c.status='approved';this.touch(c);return this.get(projectId,id);}
 async create(projectId:string,id:string){const c=this.own(projectId,id);if(c.status==='linked')return this.get(projectId,id);if(c.uncertain)throw new IssueError('create-uncertain');await this.operation(c,async()=>{if(c.status==='linked')return;if(c.status!=='approved'||!c.approval||c.approval.hash!==await contentHash(identity(c))||c.approval.repository!==c.repository)throw new IssueError('approval');const checked=fields(c.title,c.body,c.labels,this.secrets);if(JSON.stringify(checked)!==JSON.stringify({title:c.title,body:c.body,labels:c.labels}))throw new IssueError('stale');c.status='creating';this.touch(c);try{const issue=await this.provider.create(c.repository!,{...checked,body:checked.body+'\n\n'+requestMarker(c.id)});c.externalIssue=this.valid(c,issue);c.status='linked';delete c.error;}catch(e){if(!(e instanceof IssueError)||['timeout','create-uncertain','unavailable'].includes(e.code)){c.uncertain=true;throw new IssueError('create-uncertain');}throw e;}});return this.get(projectId,id);}
 async reconcile(projectId:string,id:string){const c=this.own(projectId,id);if(!c.uncertain||!c.repository)throw new IssueError('validation');await this.operation(c,async()=>{const found=(await this.provider.reconcile(c.repository!,c.id)).filter(i=>i.body.includes(requestMarker(c.id)));if(found.length!==1)throw new IssueError('create-uncertain');c.externalIssue=this.valid(c,found[0]);c.status='linked';c.uncertain=false;delete c.error;});return this.get(projectId,id);}
 async link(projectId:string,id:string,number:number){const c=this.own(projectId,id);if(c.uncertain||!c.repository||c.searchVersion!==c.version||!['reviewing','duplicate'].includes(c.status)||!c.duplicates.some(d=>d.issue.number===number))throw new IssueError('validation');await this.operation(c,async()=>{c.externalIssue=this.valid(c,await this.provider.get(c.repository!,number));c.status='linked';delete c.approval;});return this.get(projectId,id);}
}

