export type CollaborationOperation='create-branch'|'switch-branch'|'fetch'|'pull'|'push'|'commit'|'resolve-conflict'|'stage-hunk';
export interface GitHunk{id:number;path:string;header:string;patch:string}
export interface CollaborationPreview {approvalId:string;operation:CollaborationOperation;branch:string;remote:string|null;head:string;files:string[];message:string|null;patch?:string|null;expiresInSeconds:number}
export interface CollaborationOverview {remotes:string[];branch:string|null;head?:string|null;divergence:{ahead:number;behind:number}|null}
export interface ConflictReview {path:string;base:string;ours:string;theirs:string}
export interface CollaborationState {overview:CollaborationOverview|null;preview:CollaborationPreview|null;busy:boolean;error:string;notice:string;conflict:ConflictReview|null;compareURL:string;hunks:GitHunk[]}
export type CollaborationInvoke=<T>(request:Record<string,unknown>)=>Promise<T>;
const errors:Record<string,string>={'git-dirty':'Commit or preserve disk changes before switching branches or pulling.','git-conflict':'Repository state changed after review. Prepare a new approval.','git-approval':'This approval expired or was already used. Review the operation again.','git-branch':'Choose a valid branch. Pull and push must target the current branch.','git-remote':'Choose a configured remote. GitHub review supports public GitHub remote URLs without credentials.','conflict':'Resolve conflicts before committing.','git':'Git did not complete. Refresh repository and remote state before retrying.','git-limit':'Git timed out or output exceeded the limit. Refresh before retrying.'};
export class CollaborationService {
 readonly workspaceId:string;private invoke:CollaborationInvoke;private dirty:()=>boolean;private refresh:()=>Promise<unknown>;private state:CollaborationState={overview:null,preview:null,busy:false,error:'',notice:'',conflict:null,compareURL:'',hunks:[]};private listeners=new Set<()=>void>();private disposed=false;
 constructor(workspaceId:string,invoke:CollaborationInvoke,dirty:()=>boolean,refresh:()=>Promise<unknown>){this.workspaceId=workspaceId;this.invoke=invoke;this.dirty=dirty;this.refresh=refresh;}
 snapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 private publish(patch:Partial<CollaborationState>){if(this.disposed)return;this.state={...this.state,...patch};this.listeners.forEach(fn=>fn());}
 private request<T>(action:string,values:Record<string,unknown>={}){return this.invoke<T>({action,workspaceId:this.workspaceId,...values});}
 private async operation(fn:()=>Promise<void>){if(this.state.busy||this.disposed)return false;this.publish({busy:true,error:'',notice:''});try{await fn();return true;}catch(error){const code=typeof error==='object'&&error&&'code'in error?String(error.code):'';this.publish({error:errors[code]??(error instanceof Error?error.message:'Git operation failed. Refresh before retrying.')});return false;}finally{this.publish({busy:false});}}
 overview=()=>this.operation(async()=>{this.publish({overview:await this.request<CollaborationOverview>('overview')});});
 prepare=(operation:CollaborationOperation,values:{branch?:string;remote?:string;message?:string;path?:string;hunk?:number}={})=>this.operation(async()=>{if(this.state.preview)throw new Error('Approve or cancel the current Git review first.');if(this.dirty()&&['create-branch','switch-branch','pull','commit','resolve-conflict','stage-hunk'].includes(operation))throw new Error('Save all edited files before changing Git source.');const proposal={workspaceId:this.workspaceId,operation,...values};const preview=await this.request<CollaborationPreview>('prepare',{proposal});if(this.disposed){await this.request('cancel',{approvalId:preview.approvalId});return;}this.publish({preview,compareURL:''});});
 approve=()=>this.operation(async()=>{const preview=this.state.preview;if(!preview)return;if(this.dirty()&&['create-branch','switch-branch','pull','commit','resolve-conflict','stage-hunk'].includes(preview.operation))throw new Error('Save all edited files before changing Git source.');this.publish({preview:null});await this.request('apply',{approvalId:preview.approvalId});this.publish({notice:'Git operation completed.',hunks:[]});try{await this.refresh();this.publish({overview:await this.request<CollaborationOverview>('overview')});}catch{this.publish({notice:'Git operation completed. Refresh repository state before another operation.'});}});
 hunks=(path:string)=>this.operation(async()=>{if(this.state.preview)throw new Error('Approve or cancel the current Git review first.');this.publish({hunks:[]});this.publish({hunks:await this.request<GitHunk[]>('hunks',{path})});});
 cancel=()=>this.operation(async()=>{const preview=this.state.preview;if(preview)await this.request('cancel',{approvalId:preview.approvalId});this.publish({preview:null});});
 conflict=(path:string)=>this.operation(async()=>{this.publish({conflict:await this.request<ConflictReview>('conflict',{path})});});
 compare=(remote:string,base:string,head:string)=>this.operation(async()=>{const value=await this.request<{url:string}>('compare',{remote,base,head});const url=new URL(value.url);if(url.origin!=='https://github.com'||url.username||url.password)throw new Error('Invalid GitHub review URL.');this.publish({compareURL:url.href});});
 dispose(){this.disposed=true;const preview=this.state.preview;if(preview)void this.request('cancel',{approvalId:preview.approvalId}).catch(()=>{});this.listeners.clear();}
}
