'use client';
import { CustomSelect } from '@/components/ui/custom-select';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {nativeBridge} from '../runtime/native-hosts';
import {useFiles} from '../editor/session';
import {useUpdateProtection} from '../update/views';
import {useGit} from './context';
import {CollaborationService} from './collaboration';
import {PullRequestView} from './pull-request-view';
import {useI18n} from '@/i18n/react';
export function useCollaboration(){const files=useFiles(),git=useGit();const [service]=useState(()=>new CollaborationService(git.service.scope.workspaceId??'',async <T,>(request:Record<string,unknown>)=>{if(request.action!=='apply')return nativeBridge.invoke<T>('git_collaboration',{request});let value:T|undefined,fault:unknown;const ok=await files.run('Git operation…',async()=>{try{value=await nativeBridge.invoke<T>('git_collaboration',{request});}catch(error){fault=error;throw error;}});if(!ok)throw fault??new Error('Git operation failed. Review file feedback.');return value as T;},()=>files.documents.snapshot().dirtyEditors.length>0,async()=>{await git.service.refresh();files.refresh();for(const doc of files.documents.snapshot().openEditors)if(!files.documents.snapshot().dirtyEditors.includes(doc.id)){try{await files.documents.reload(doc.id);}catch{files.setNotice('Git source changed. Reopen deleted or renamed files from Explorer.');}}}));const state=useSyncExternalStore(service.subscribe,service.snapshot,service.snapshot);useUpdateProtection(()=>service.snapshot().busy);const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;queueMicrotask(()=>{if(!mounted.current)service.dispose();});};},[service]);useEffect(()=>{if(git.service.host.capabilities.git&&git.state.repository)void service.overview();},[service,git.service,git.state.repository]);return{service,state};}
export function CollaborationPanel({value}:{value:ReturnType<typeof useCollaboration>}){const {service,state}=value,{state:git,service:gitService}=useGit(),files=useFiles(),{t}=useI18n();const [branch,setBranch]=useState(''),[remote,setRemote]=useState('origin'),[base,setBase]=useState('main');const disabled=state.busy||!!state.preview||!git.fresh||!git.repository;return <section className="git-view" aria-label={t('Git collaboration')}><h3>{t('Git collaboration')}</h3><p>{state.overview?.branch}{state.overview?.divergence&&` · ↑${state.overview.divergence.ahead} ↓${state.overview.divergence.behind}`}</p><label>{t('Branch name')}<input value={branch} onChange={e=>setBranch(e.target.value)} disabled={disabled}/></label><button className="fs-button" disabled={disabled||!branch} onClick={()=>void service.prepare('create-branch',{branch})}>{t('Create branch')}</button><label>{t('Switch branch')}<CustomSelect disabled={disabled} value={state.overview?.branch??''} onChange={e=>void service.prepare('switch-branch',{branch:e.target.value})}><option value="">—</option>{git.branches.filter(b=>!b.remote).map(b=><option key={b.name} value={b.name}>{b.name}</option>)}</CustomSelect></label><label>{t('Remote')}<CustomSelect disabled={disabled} value={remote} onChange={e=>setRemote(e.target.value)}><option value="">—</option>{state.overview?.remotes.map(name=><option key={name} value={name}>{name}</option>)}</CustomSelect></label>{(['fetch','pull','push'] as const).map(operation=><button className="fs-button" key={operation} disabled={disabled||!remote||!state.overview?.branch} onClick={()=>void service.prepare(operation,{remote,branch:state.overview!.branch!})}>{t(operation)}</button>)}<p>{t('Pull only accepts fast-forward updates. Push never forces remote history.')}</p>
 {state.preview&&<section role="dialog" aria-label={t('Review Git operation')} aria-modal="false"><h4>{t('Review Git operation')}</h4><dl><dt>{t('Operation')}</dt><dd>{t(state.preview.operation==='stage-hunk'?'Stage this change block':state.preview.operation)}</dd><dt>{t('Branch')}</dt><dd>{state.preview.branch}</dd><dt>{t('Remote')}</dt><dd>{state.preview.remote??'—'}</dd><dt>HEAD</dt><dd><code>{state.preview.head}</code></dd><dt>{t('Commit message')}</dt><dd>{state.preview.message??'—'}</dd></dl>{state.preview.patch&&<pre className="git-conflict-source">{state.preview.patch}</pre>}<ul>{state.preview.files.map(file=><li key={file}>{file}</li>)}</ul><p>{t('Approval expires in 60 seconds. Changed repository state requires a new review.')}</p><button className="fs-button" disabled={state.busy} onClick={()=>void service.approve()}>{t('Approve Git operation')}</button><button className="fs-button" disabled={state.busy} onClick={()=>void service.cancel()}>{t('Cancel')}</button></section>}
 {git.files.filter(file=>file.workingTree==='modified'&&file.index!=='conflicted').map(file=><button className="fs-button" key={file.path} disabled={disabled} onClick={()=>void service.hunks(file.path)}>{t('Review change blocks')}: {file.path}</button>)}{state.hunks.map(hunk=><details key={hunk.id}><summary>{hunk.path} · {hunk.header}</summary><pre className="git-conflict-source">{hunk.patch}</pre><button className="fs-button" disabled={disabled||files.editor.dirtyEditors.length>0} onClick={()=>void service.prepare('stage-hunk',{path:hunk.path,hunk:hunk.id})}>{t('Stage this change block')}</button></details>)}
 {git.files.filter(file=>file.index==='conflicted'||file.workingTree==='conflicted').map(file=><button key={file.path} className="fs-button" disabled={state.busy} onClick={()=>void service.conflict(file.path)}>{t('Review conflict')}: {file.path}</button>)}{state.conflict&&<details open><summary>{state.conflict.path}</summary>{(['base','ours','theirs'] as const).map(side=><section key={side}><h4>{t(side)}</h4><pre className="git-conflict-source">{state.conflict![side]}</pre></section>)}{(['ours','theirs'] as const).map(side=><button className="fs-button" key={side} disabled={state.busy||!!state.preview} onClick={()=>void (async()=>{try{const review=state.conflict!;const existing=files.documents.snapshot().openEditors.find(d=>d.path===review.path);if(existing&&existing.content!==existing.savedContent)throw Error('Save all edited files before changing Git source.');await files.documents.open(review.path);const doc=files.documents.snapshot().openEditors.find(d=>d.path===review.path)!;if(doc.content!==doc.savedContent)throw Error('Save all edited files before changing Git source.');files.documents.edit(doc.id,review[side]);gitService.closeDiff();files.setNotice('Conflict resolution is unsaved. Review and save it before marking resolved.');}catch(error){files.setNotice(error instanceof Error?error.message:'Conflict editor could not open.');}})()}>{t(side==='ours'?'Use ours in editor':'Use theirs in editor')}</button>)}<button className="fs-button" onClick={()=>void files.documents.open(state.conflict!.path)}>{t('Open file to resolve')}</button><button className="fs-button" disabled={state.busy||!!state.preview} onClick={()=>void service.prepare('resolve-conflict',{path:state.conflict!.path})}>{t('Mark conflict resolved')}</button><p>{t('Edit and save the resolution, then stage it explicitly. Conflict review never overwrites source.')}</p></details>}
 <label>{t('PR base branch')}<input disabled={disabled} value={base} onChange={e=>setBase(e.target.value)}/></label><button className="fs-button" disabled={disabled||!remote||!base||!state.overview?.branch} onClick={()=>void service.compare(remote,base,state.overview!.branch!)}>{t('Prepare GitHub review')}</button>{state.compareURL&&<a href={state.compareURL} target="_blank" rel="noopener noreferrer">{t('Review and create PR on GitHub')}</a>}<p>{t('GitHub opens the comparison for your review. Studio does not create a PR automatically.')}</p><PullRequestView service={service} overview={state.overview} base={base} remote={remote}/>{state.busy&&<p role="status">{t('Working…')}</p>}{state.error&&<p role="alert">{t(state.error)}</p>}{state.notice&&<p role="status">{t(state.notice)}</p>}</section>}
