import {IssueError} from '../issues/domain.ts';
import {repository,fields} from '../issues/security.ts';
import {contentHash} from '../ai/fix-service.ts';
export interface PullRequest {number:number;url:string;title:string;state:string;sha:string;base:string;head:string;body:string}
export interface PullChecks {sha:string;state:string;checks:{name:string;status:string;conclusion:string|null}[];truncated:boolean}
export interface PullProvider {head(repo:string,branch:string):Promise<string>;list(repo:string,base:string,head:string):Promise<PullRequest[]>;create(repo:string,fields:{title:string;body:string;base:string;head:string}):Promise<PullRequest>;get(repo:string,number:number):Promise<PullRequest>;checks(repo:string,sha:string):Promise<PullChecks>}
export interface PullDraft {id:string;projectId:string;repository:string;base:string;head:string;sha:string;title:string;body:string;status:'reviewing'|'creating'|'linked'|'cancelled'|'failed'|'uncertain';createdAt:string;approval?:{hash:string;timestamp:string};pull?:PullRequest;error?:string}
export interface PullPersistence {load():PullDraft[];save(value:PullDraft[]):void}
export function pullBranch(value:unknown){if(typeof value!=='string'||!/^[A-Za-z0-9_][A-Za-z0-9_./-]{0,199}$/.test(value)||value.includes('..')||value.endsWith('/')||value.endsWith('.')||value.includes('//')||value.split('/').some(p=>p.endsWith('.lock')))throw new IssueError('validation');return value;}
export function pullURL(value:unknown,repo:string,number:number){const url=new URL(String(value));if(url.origin!=='https://github.com'||url.username||url.password||url.search||url.hash||url.pathname.toLowerCase()!==`/${repository(repo)}/pull/${number}`)throw new IssueError('boundary');return url.href;}
const marker=(id:string)=>`<!-- tastestudio-pr:${id} -->`;
const identity=(draft:PullDraft)=>JSON.stringify([draft.id,draft.projectId,draft.repository,draft.base,draft.head,draft.sha,draft.title,draft.body]);
export class PullRequestService {
 private drafts=new Map<string,PullDraft>();private busy=new Set<string>();private committed:PullDraft[]=[];
 readonly provider:PullProvider;readonly secrets:string[];readonly persistence?:PullPersistence;
 constructor(provider:PullProvider,secrets:string[]=[],persistence?:PullPersistence){this.provider=provider;this.secrets=secrets;this.persistence=persistence;for(const row of persistence?.load()??[]){const draft=structuredClone(row);if(draft.status==='creating')draft.status='uncertain';this.drafts.set(draft.id,draft);}this.checkpoint();}
 private checkpoint(){const value=structuredClone([...this.drafts.values()]);try{this.persistence?.save(value);}catch(error){this.drafts=new Map(this.committed.map(row=>[row.id,structuredClone(row)]));throw error;}this.committed=value;}
 private own(projectId:string,repo:string,id:string){const draft=this.drafts.get(id);if(!draft||draft.projectId!==projectId||draft.repository!==repository(repo))throw new IssueError('boundary');return draft;}
 list(projectId:string){return structuredClone([...this.drafts.values()].filter(row=>row.projectId===projectId));}
 async build(projectId:string,repo:string,input:{base:string;head:string;title:string;body:string;sha?:string}){repo=repository(repo);if(this.drafts.size>=100)throw new IssueError('validation');const base=pullBranch(input.base),head=pullBranch(input.head),safe=fields(input.title,input.body,[],this.secrets);if(base===head)throw new IssueError('validation');const sha=await this.provider.head(repo,head);if(input.sha&&input.sha!==sha)throw new IssueError('stale');const draft:PullDraft={id:crypto.randomUUID(),projectId,repository:repo,base,head,sha,title:safe.title,body:safe.body,status:'reviewing',createdAt:new Date().toISOString()};this.drafts.set(draft.id,draft);this.checkpoint();return structuredClone(draft);}
 cancel(projectId:string,repo:string,id:string){const draft=this.own(projectId,repo,id);if(this.busy.has(id)||['creating','uncertain','linked'].includes(draft.status))throw new IssueError('busy');draft.status='cancelled';delete draft.approval;this.checkpoint();return structuredClone(draft);}
 private valid(draft:PullDraft,pull:PullRequest){pullURL(pull.url,draft.repository,pull.number);if(pull.head!==draft.head||pull.base!==draft.base)throw new IssueError('boundary');return structuredClone(pull);}
 async approveAndCreate(projectId:string,repo:string,id:string){const draft=this.own(projectId,repo,id);if(this.busy.has(id)||draft.status!=='reviewing')throw new IssueError('approval');this.busy.add(id);try{const masked=fields(draft.title,draft.body,[],this.secrets);if(masked.title!==draft.title||masked.body!==draft.body)throw new IssueError('stale');if(await this.provider.head(draft.repository,draft.head)!==draft.sha)throw new IssueError('stale');const matches=await this.provider.list(draft.repository,draft.base,draft.head);const existing=matches.find(pull=>pull.state==='open');if(existing){draft.pull=this.valid(draft,existing);draft.status='linked';this.checkpoint();return structuredClone(draft);}draft.approval={hash:await contentHash(identity(draft)),timestamp:new Date().toISOString()};draft.status='creating';this.checkpoint();try{const pull=await this.provider.create(draft.repository,{title:draft.title,body:draft.body+'\n\n'+marker(id),base:draft.base,head:draft.head});draft.pull=this.valid(draft,pull);draft.status='linked';this.checkpoint();return structuredClone(draft);}catch(error){const active=this.drafts.get(id)??draft;active.status=error instanceof IssueError&&['authentication','permission','validation','repository','rate-limit'].includes(error.code)?'failed':'uncertain';active.error=error instanceof IssueError?error.code:'create-uncertain';this.checkpoint();throw new IssueError(active.status==='uncertain'?'create-uncertain':active.error as 'permission');}}finally{this.busy.delete(id);}}
 async reconcile(projectId:string,repo:string,id:string){const draft=this.own(projectId,repo,id);if(this.busy.has(id)||draft.status!=='uncertain')throw new IssueError('busy');this.busy.add(id);try{const matches=(await this.provider.list(draft.repository,draft.base,draft.head)).filter(pull=>pull.body.includes(marker(id)));if(matches.length!==1)throw new IssueError('create-uncertain');draft.pull=this.valid(draft,matches[0]);draft.status='linked';delete draft.error;this.checkpoint();return structuredClone(draft);}finally{this.busy.delete(id);}}
 async status(projectId:string,repo:string,id:string){const draft=this.own(projectId,repo,id);if(this.busy.has(id)||!draft.pull)throw new IssueError('validation');this.busy.add(id);try{const pull=this.valid(draft,await this.provider.get(draft.repository,draft.pull.number)),checks=await this.provider.checks(draft.repository,pull.sha);if(checks.sha!==pull.sha)throw new IssueError('boundary');draft.pull=pull;this.checkpoint();return {draft:structuredClone(draft),checks};}finally{this.busy.delete(id);}}
}
