'use client';
import { useI18n, I18nText } from '@/i18n/react';
import dynamic from 'next/dynamic';
import { useState } from 'react';
import { GitBranch, RefreshCw, Plus, Minus, X, GitCommitHorizontal } from 'lucide-react';
import { useGit } from './context';
import { useFiles } from '../editor/session';
import { FileEditorArea } from '../editor/editor-area';
import { gitDesktopRequired, type GitFileStatus, type DiffSide, type GitDiff } from './contracts';
import { isConflict, statusLetters, type GitState } from './service';
const DiffEditor = dynamic(() => import('./diff-editor').then(m => m.GitDiffEditor), { ssr: false, loading: () => <p className="fs-empty" role="status">{<I18nText text="Loading diff editor…" />}</p> });
export interface GitActions { refresh(): Promise<boolean>; selectDiff(path: string, side: DiffSide): Promise<boolean>; changeIndex(kind: 'stage' | 'unstage', path?: string): Promise<boolean>; commit(message: string): Promise<boolean> }
export function SourceControlPanel({ state, available, actions, dirty }: { state: GitState; available: boolean; actions: GitActions; dirty: boolean }) {
  const { t } = useI18n();

  const [message, setMessage] = useState('');
  const ready = available && state.fresh && state.phase === 'ready' && !state.busy;
  const conflicts = state.files.filter(isConflict), changes = state.files.filter(f => f.workingTree && !isConflict(f)), staged = state.files.filter(f => f.index && !isConflict(f));
  const commit = async () => { if (await actions.commit(message)) setMessage(''); };
  const group = (title: string, files: GitFileStatus[], side: DiffSide, conflict = false) => <section className="git-group" aria-label={t(title)}><div className="git-group-heading"><h3>{t(title)}</h3><span>{available && state.fresh ? files.length : '—'}</span>{!conflict && <button aria-label={side === 'working' ? t("Stage All") : t("Unstage All")} title={side === 'working' ? t("Stage All") : t("Unstage All")} disabled={!ready || !files.length || !!conflicts.length} onClick={() => void actions.changeIndex(side === 'working' ? 'stage' : 'unstage')}>{side === 'working' ? <Plus size={14} /> : <Minus size={14} />}</button>}</div>{files.map(file => { const kind = conflict ? 'conflicted' : (side === 'working' ? file.workingTree : file.index)!; return <div className="git-file" key={file.path}><button className="git-file-path" disabled={!ready} title={`${file.originalPath ? file.originalPath + ' → ' : ''}${file.path}`} aria-label={`View ${side} diff: ${file.path}, ${kind}`} onClick={() => void actions.selectDiff(file.path, side)}><span className={`git-badge git-${kind}`} aria-hidden="true">{statusLetters[kind]}</span><span>{file.path}</span></button>{!conflict && <button aria-label={`${side === 'working' ? 'Stage' : 'Unstage'} ${file.path}`} disabled={!ready} onClick={() => void actions.changeIndex(side === 'working' ? 'stage' : 'unstage', file.path)}>{side === 'working' ? <Plus size={14} /> : <Minus size={14} />}</button>}</div>; })}{available && state.fresh && !files.length && <p className="git-muted">{t("No")} {t(title)}.</p>}</section>;
  return <div className="git-view"><div className="git-heading"><h3>{t("Repository")}</h3><button aria-label={t("Refresh Git")} title={t("Refresh Git")} disabled={!!state.busy} onClick={() => void actions.refresh()}><RefreshCw size={15} /></button></div><div className="git-repository"><GitBranch size={17} /><div><strong>{available ? state.repository ? state.repository.detached ? t("Detached HEAD") : state.repository.currentBranch ?? t("Unborn branch") : t("Repository not detected") : t("Desktop runtime required")}</strong>{state.repository && <small title={state.repository.root}>{state.repository.root}</small>}</div></div>{!available && <p className="git-runtime">{t(gitDesktopRequired)}</p>}{state.phase === 'not-repository' && <p role="status">{t("This folder is not a Git repository.")}</p>}{state.busy && <p role="status">{t(state.busy || "")}</p>}{state.error && available && <p className="git-error" role="alert">{t(state.error || "")}</p>}{state.notice && <p role="status">{t(state.notice || "")}</p>}{dirty && <p className="git-dirty-note">{t("Save the file to update Git changes. Git compares saved disk content; unsaved edits are preserved.")}</p>}{state.repository && !state.fresh && <p className="git-dirty-note">{t("Status is out of date. Refresh before changing Git data.")}</p>}{group('Conflicts', conflicts, 'working', true)}{group('Changes', changes, 'working')}{group('Staged Changes', staged, 'staged')}<section className="git-group"><h3>{t("Commit")}</h3><label htmlFor="git-commit-message">{t("Commit message")}</label><textarea id="git-commit-message" value={message} onChange={e => setMessage(e.target.value)} maxLength={4096} disabled={!available || !!state.busy} placeholder={t("Describe your staged changes")} rows={3} /><button className="fs-button git-commit" disabled={!ready || !staged.length || !!conflicts.length || !message.trim()} onClick={() => void commit()}><GitCommitHorizontal size={14} />{t("Commit staged changes")}</button><p className="git-muted">{available ? t("Only staged changes are committed.") : t("Commit becomes available in the desktop runtime.")}</p></section><section className="git-group"><h3>{t("History")}</h3>{state.history.map(c => <article className="git-history" key={c.hash}><strong title={c.message}>{c.message}</strong><code>{c.shortHash}</code><span>{c.author}</span><time dateTime={c.date}>{c.date.slice(0, 10)}</time></article>)}{!state.history.length && <p className="git-muted">{available && state.fresh ? t("No commits yet.") : t("History is unavailable.")}</p>}{state.history.length === 50 && <p className="git-muted">{t("Showing the latest 50 commits.")}</p>}</section><p className="git-capability">{t("Git capability:")} {available ? t("Available") : t("Unavailable")}</p></div>;
}
export function SourceControlView() { const { service, state } = useGit(); const { editor } = useFiles(); return <SourceControlPanel key={service.scope.projectId} state={state} available={service.host.capabilities.git} actions={service} dirty={editor.dirtyEditors.length > 0} />; }
export function GitStatus() {
  const { t } = useI18n();
 const { state, service } = useGit(); return <span>{t("Git:")} {!service.host.capabilities.git ? t("Desktop runtime required") : state.repository ? state.repository.detached ? t("Detached HEAD") : state.repository.currentBranch ?? t("Unborn branch") : t("No repository")}</span>; }
export function DiffView({ diff, close, dirty }: { diff: GitDiff; close(): void; dirty: boolean }) {
  const { t } = useI18n();
 return <section className="git-diff-view" aria-label={t("Git diff")}><header><div><strong>{t("Git diff ·")} {diff.side === 'staged' ? t("HEAD → Index") : t("Index → Working tree")}</strong><span title={diff.path}>{diff.path}</span></div><button aria-label={t("Close diff")} onClick={close}><X size={16} /></button></header><p className="git-diff-caption">{t("Original ↔ Modified · Read only · Saved repository content")}{dirty ? t(" · Unsaved editor changes are not included.") : ''}</p><DiffEditor key={`${diff.side}:${diff.path}`} diff={diff} /></section>; }
export function GitEditorArea() { const { state, service } = useGit(); const { editor } = useFiles(); return <div className="git-editor-stack"><div className="git-normal-editor" hidden={!!state.diff}><FileEditorArea /></div>{state.diff && <DiffView diff={state.diff} close={service.closeDiff} dirty={editor.dirtyEditors.length > 0} />}</div>; }
