/** Controlled localhost verification; no Provider, repository or user source writes. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {WebSocket} from 'ws';
import {startCoreServer} from '../transport/server.ts';
import {teamTokenHash,type TeamConfiguration} from '../transport/team-access.ts';
const root=path.resolve('../../../resources/verification/dev-01/tasks/tastedev-studio/advancement-6/actual-agents',randomUUID());fs.mkdirSync(root,{recursive:true});
const binary=path.resolve('target/release-gate/release/tastedev-agent.exe'),hash=createHash('sha256').update(fs.readFileSync(binary)).digest('hex');assert.equal(hash,'f3a5e73d399ef82fc40455e732dcb3e02f7062a8c2501f4cb0845e1c5fd753f7');
const token=(id:string)=>'Dummy-team-actual-'+id+'-20261001';
const projects=[randomUUID(),randomUUID()],agentIds=[randomUUID(),randomUUID()];
const team:TeamConfiguration={users:[{id:'owner',role:'Owner',projects},{id:'alice',role:'Developer',projects:[projects[0]]},{id:'bob',role:'Developer',projects:[projects[1]]},{id:'viewer',role:'Viewer',projects:[projects[0]]}],sessions:['owner','alice','bob','viewer'].map(userId=>({id:'session-'+userId,userId,tokenHash:teamTokenHash(token(userId)),expiresAt:'2099-01-01T00:00:00Z'})),projects:projects.map((id,i)=>({id,agentGroups:['group-'+i],maxQueued:3,maxActive:1})),agents:agentIds.map((id,i)=>({id,tokenHash:teamTokenHash(token(id)),groups:['group-'+i],labels:{purpose:'controlled-verification'}})),maxQueuedPerUser:2,maxActivePerUser:1};
const options={port:0,accessMode:'team' as const,team,agentToken:token('internal-agent'),studioToken:token('internal-studio'),storagePath:path.join(root,'core.sqlite'),storageKey:Buffer.alloc(32,17),artifactRoot:path.join(root,'artifacts')};
let core=await startCoreServer(options);const sockets:WebSocket[]=[],children:ChildProcess[]=[];const results:Record<string,unknown>={status:'IN_PROGRESS',root,binaryHash:hash,providerCalls:0,projects,agentIds,workload:{users:2,projects:2,agents:2,queuedPerUser:2,maxActivePerProject:1},checks:[]};
const checks=results.checks as string[];
async function wait(check:()=>boolean,limit=20000){const end=Date.now()+limit;while(!check()){if(Date.now()>end)throw Error('Controlled verification deadline exceeded');await new Promise(r=>setTimeout(r,20));}}
async function connect(user:string,p:string){const socket=new WebSocket(`ws://127.0.0.1:${core.port}/studio`);sockets.push(socket);const messages:Record<string,unknown>[]=[];socket.on('message',raw=>messages.push(JSON.parse(raw.toString())));await new Promise<void>((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject);});socket.send(JSON.stringify({protocolVersion:1,type:'subscribe',token:token(user),project:{id:p,name:'Controlled '+p}}));await wait(()=>messages.some(m=>m.type==='snapshot'||m.type==='error'));return{socket,messages};}
async function rpc(client:Awaited<ReturnType<typeof connect>>,method:string,args:unknown[]){const requestId=randomUUID();client.socket.send(JSON.stringify({protocolVersion:1,type:'rpc',requestId,method,args}));await wait(()=>client.messages.some(m=>m.requestId===requestId));const response=client.messages.find(m=>m.requestId===requestId)!;return response;}
function startAgent(i:number){const workspaceRoot=path.join(root,'agent-'+i);fs.mkdirSync(workspaceRoot,{recursive:true});fs.writeFileSync(path.join(workspaceRoot,'agent-id.json'),agentIds[i]);const file=path.join(root,'agent-'+i+'.json');fs.writeFileSync(file,JSON.stringify({endpoint:`ws://127.0.0.1:${core.port}/agent`,name:'Actual Team Agent '+i,workspaceRoot,heartbeatMs:200,reconnectMaxMs:500,logLevel:'error'}));const child=spawn(binary,['--config',file],{windowsHide:true,env:{...process.env,TASTEDEV_AGENT_TOKEN:token(agentIds[i])},stdio:['ignore','ignore','pipe']});children.push(child);child.stderr?.on('data',chunk=>fs.appendFileSync(path.join(root,'agent-'+i+'.log'),chunk));child.on('error',error=>fs.appendFileSync(path.join(root,'agent-'+i+'.log'),error.message));return child;}
try{
 const owner=await connect('owner',projects[0]);await connect('owner',projects[1]);const alice=await connect('alice',projects[0]),bob=await connect('bob',projects[1]),viewer=await connect('viewer',projects[0]);
 for(let i=0;i<2;i++)startAgent(i);await wait(()=>projects.every(p=>core.service.snapshot(p).agents.some(a=>a.status==='idle')));checks.push('Actual release Rust Agents connected with separate configured identities');
 const denied=await connect('alice',projects[1]);assert.equal(denied.messages[0].error,'TEAM_FORBIDDEN');assert.match(String((await rpc(viewer,'createJob',[{}])).error),/TEAM_FORBIDDEN/);checks.push('Cross-project subscribe and Viewer execution blocked');
 for(let i=0;i<2;i++){const snapshot=core.service.snapshot(projects[i]);assert.deepEqual(snapshot.agents.map(a=>a.id),[agentIds[i]]);}
 checks.push('Agent and event visibility isolated by project groups');
 const jobs:string[]=[];
 for(const [i,client] of [alice,bob].entries())for(let n=0;n<2;n++){const response=await rpc(client,'createJob',[{idempotencyKey:`team-${i}-${n}`,name:`controlled-${i}-${n}`,requirements:{platform:'windows'},payload:{task:'controlled-pass',steps:[{name:'controlled-pass',executable:process.execPath,args:['-e',"setTimeout(()=>{console.log('controlled PASS');process.exit(0)},300)"],cwd:'.',timeoutMs:5000}]}}]);assert.equal(response.error,undefined);jobs.push((response.value as {id:string}).id);}
 const flood=await rpc(alice,'createJob',[{name:'quota-overflow',requirements:{},payload:{task:'overflow',steps:[{name:'overflow',executable:process.execPath,args:['-v'],cwd:'.'}]}}]);assert.match(String(flood.error),/QUEUE_LIMIT/);checks.push('Per-user bounded queue rejects third pending job');
 await rpc(alice,'dispatch',[]);await rpc(bob,'dispatch',[]);
 await wait(()=>projects.every(p=>core.service.snapshot(p).runs.filter(r=>r.status==='passed').length===2));
 const runs=projects.flatMap(p=>core.service.snapshot(p).runs);assert.equal(runs.length,4);for(const [i,p]of projects.entries()){const selected=runs.filter(r=>r.projectId===p);assert.ok(selected.every(r=>r.agentId===agentIds[i]));const ordered=selected.sort((a,b)=>String(a.startedAt).localeCompare(String(b.startedAt)));assert.ok(Date.parse(ordered[1].startedAt!)>=Date.parse(ordered[0].finishedAt!));}results.runs=runs;checks.push('Four real command runs PASS, correct group routing, active cap 1 and both projects progress');
 const next=structuredClone(team);next.users.find(u=>u.id==='alice')!.role='Viewer';assert.equal((await rpc(owner,'team',['update',next])).error,undefined);assert.match(String((await rpc(alice,'createJob',[{}])).error),/TEAM_FORBIDDEN/);checks.push('Live role downgrade blocks previously connected Developer');
 for(const s of sockets)s.terminate();await core.close();await wait(()=>children.every(c=>c.exitCode!==null||c.signalCode!==null),3000).catch(()=>{});for(const c of children)if(c.exitCode===null&&c.signalCode===null)c.kill();await wait(()=>children.every(c=>c.exitCode!==null||c.signalCode!==null));
 core=await startCoreServer(options);const restored=await connect('alice',projects[0]);assert.equal((restored.messages.find(m=>m.type==='snapshot')!.access as {role:string}).role,'Viewer');assert.equal(core.service.snapshot(projects[0]).runs.filter(r=>r.status==='passed').length,2);const restoredOwner=await connect('owner',projects[0]);const audit=await rpc(restoredOwner,'team',['audit']);assert.equal(audit.error,undefined);assert.ok(JSON.stringify(audit.value).includes('denied'));checks.push('Restart preserves current role, execution history and authorization audit');
 results.status='PASS';
}catch(error){results.status='FAIL';results.error=error instanceof Error?error.message:'Verification failed';process.exitCode=1;}
finally{for(const s of sockets)s.terminate();await core.close();for(const c of children)if(c.exitCode===null&&c.signalCode===null)c.kill();await wait(()=>children.every(c=>c.exitCode!==null||c.signalCode!==null)).catch(()=>{results.cleanup='FAILED';process.exitCode=1;});results.ownedOrphanProcesses=children.filter(c=>c.exitCode===null&&c.signalCode===null).length;results.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(root,'RESULT.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({status:results.status,root,checks:checks.length,ownedOrphanProcesses:results.ownedOrphanProcesses}));}
